const CONFIG={deepDepthWorker:'x',deepInferenceIntervalMs:1000};const BUILD={version:'30.20.0'};const state={deepDepthWorker:null,deepWorkerModelId:null,deepDisabled:false,deepLivePending:null,deepLastRequestAt:0,deepCalls:0,denseManager:{},denseDepthWorker:{},slam:{metricLocked:true}};const $=()=>null;const log={info(){}};const modelForWorker=()=>({});const selectedDeepModel=()=>({id:'x',label:'x'});const updateDeepModelUi=()=>{};const captureDepthTestFrame=async()=>({rgba:new Uint8ClampedArray(4),width:1,height:1});const workerRequest=async()=>({type:'deep-test-result',rawDepth:new Float32Array(4),rawWidth:2,rawHeight:2,ms:1,provider:'webgpu'});const drawDepth=()=>{};
function deepWorkerConfig(){return {};}
function ensureDeepWorker(){if(state.deepDepthWorker)return state.deepDepthWorker;const worker=new Worker(`${CONFIG.deepDepthWorker}?v=${BUILD.version}`,{type:'module'});state.deepDepthWorker=worker;state.deepWorkerModelId=null;worker.postMessage({type:'init',config:deepWorkerConfig()});return worker;}
function heatColor(t){return t;}
async function testDeepModel(){const button=$('testDeepBtn');if(button)button.disabled=true;updateDeepModelUi('x');try{const frame=await captureDepthTestFrame(),worker=ensureDeepWorker(),jobId=`test-${Date.now()}`,result=await workerRequest(worker,{type:'test',jobId,model:modelForWorker(),...frame},()=>true,90000);drawDepth($('deepTestPreview'),result.rawDepth,result.rawWidth,result.rawHeight);updateDeepModelUi(`ok`,'ok');log.info('deep-model-test',{});}finally{if(button)button.disabled=false;}}
async function chooseDeepModel(file){return file;}
function scan(r,frame,K){if(r.newKeyframe&&r.trackingValid)queueDenseKeyframe(r.newKeyframe,frame,K);}
async function queueDenseKeyframe(kf,frame,K){if(!state.denseManager||!state.denseDepthWorker)return;state.denseManager.add?.(kf,frame,K,{metricLocked:!!state.slam?.metricLocked});requestLiveDepth(kf,frame);await scheduleDenseWork();}
function requestLiveDepth(kf,frame){const worker=state.deepDepthWorker,now=performance.now();if(state.deepDisabled||!worker||state.deepLivePending||now-state.deepLastRequestAt<(CONFIG.deepInferenceIntervalMs||1000))return;state.deepLastRequestAt=now;state.deepCalls++;state.deepLivePending={refId:kf.id,at:now};const rgba=new Uint8ClampedArray(frame.rgba);worker.postMessage({type:'infer',jobId:`live-${kf.id}`,refId:kf.id,model:modelForWorker(),rgba,width:frame.width,height:frame.height},[rgba.buffer]);if($('mvsState'))$('mvsState').textContent=`AI locale ${state.deepCalls} · inferenza 1 fps · Alva continua`;log.info('deep-live-request',{refId:kf.id,calls:state.deepCalls,width:frame.width,height:frame.height});}
async function scheduleDenseWork(){}
