import {qRotate,pixelRay} from './diagnostic_math.js?v=30.51.0';

export class DiagnosticViewer{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scene={frames:[],landmarks:[],deepPoints:[],triangulatedPoints:[]};this.yaw=-.75;this.pitch=-.45;this.zoom=1;this.center=[0,0,0];this.radius=1;this.options={cameras:true,landmarks:true,deep:true,optimized:false};this.drag=null;this.bind();this.resize();}
  bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{c.setPointerCapture?.(e.pointerId);this.drag={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch};});c.addEventListener('pointermove',e=>{if(!this.drag)return;this.yaw=this.drag.yaw+(e.clientX-this.drag.x)*.008;this.pitch=Math.max(-1.52,Math.min(1.52,this.drag.pitch+(e.clientY-this.drag.y)*.008));this.draw();});c.addEventListener('pointerup',()=>this.drag=null);c.addEventListener('pointercancel',()=>this.drag=null);c.addEventListener('wheel',e=>{e.preventDefault();this.zoom*=Math.exp(-e.deltaY*.001);this.zoom=Math.max(.08,Math.min(20,this.zoom));this.draw();},{passive:false});globalThis.addEventListener?.('resize',()=>{this.resize();this.draw();},{passive:true});}
  resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(2,globalThis.devicePixelRatio||1),w=Math.max(320,Math.round(r.width*dpr)),h=Math.max(220,Math.round((r.height||r.width*.6)*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}}
  setScene({graph,report}){const frames=(graph?.frames||[]).filter(f=>f?.posePrior?.p?.length),landmarks=(graph?.landmarkFactors||[]).filter(l=>l?.point?.length).map(l=>({p:l.point,q:l.probability||.4})),deepPoints=report?.visuals?.deepPoints||[],triangulatedPoints=(report?.visuals?.triangulatedPoints||[]).map(p=>({p}));this.scene={frames,landmarks,deepPoints,triangulatedPoints};this.fit();}
  setOptions(patch){Object.assign(this.options,patch);this.draw();}
  preset(name){if(name==='top'){this.yaw=0;this.pitch=-Math.PI/2+.001;}else if(name==='front'){this.yaw=0;this.pitch=0;}else if(name==='side'){this.yaw=Math.PI/2;this.pitch=0;}this.draw();}
  fit(){const pts=[];for(const f of this.scene.frames){pts.push(f.posePrior.p);if(this.options.optimized&&f.poseEstimate?.p)pts.push(f.poseEstimate.p);}for(const l of this.scene.landmarks.slice(0,12000))pts.push(l.p);for(const d of this.scene.deepPoints.slice(0,16000))pts.push(d.p);if(!pts.length){this.center=[0,0,0];this.radius=1;this.zoom=1;return this.draw();}const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const p of pts)for(let k=0;k<3;k++){if(Number.isFinite(p[k])){lo[k]=Math.min(lo[k],p[k]);hi[k]=Math.max(hi[k],p[k]);}}this.center=lo.map((x,k)=>Number.isFinite(x)&&Number.isFinite(hi[k])?(x+hi[k])*.5:0);this.radius=Math.max(.05,...lo.map((x,k)=>Number.isFinite(x)&&Number.isFinite(hi[k])?hi[k]-x:0));this.zoom=1;this.draw();}
  project(p){let x=p[0]-this.center[0],y=p[1]-this.center[1],z=p[2]-this.center[2];const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),x1=cy*x-sy*z,z1=sy*x+cy*z,cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),y1=cp*y-sp*z1,z2=sp*y+cp*z1,s=Math.min(this.canvas.width,this.canvas.height)*.78/Math.max(.05,this.radius)*this.zoom;return {x:this.canvas.width*.5+x1*s,y:this.canvas.height*.5-y1*s,z:z2};}
  draw(){this.resize();const g=this.ctx,W=this.canvas.width,H=this.canvas.height;g.clearRect(0,0,W,H);g.fillStyle='#050b10';g.fillRect(0,0,W,H);this.drawGrid();if(this.options.deep)this.drawDeep();if(this.options.landmarks)this.drawLandmarks();if(this.options.cameras)this.drawCameras();this.drawAxes();}
  drawGrid(){const g=this.ctx,s=this.radius||1;g.strokeStyle='#173044';g.lineWidth=1;g.globalAlpha=.5;for(let i=-5;i<=5;i++){this.line([this.center[0]-s,this.center[1],this.center[2]+i*s/5],[this.center[0]+s,this.center[1],this.center[2]+i*s/5]);this.line([this.center[0]+i*s/5,this.center[1],this.center[2]-s],[this.center[0]+i*s/5,this.center[1],this.center[2]+s]);}g.globalAlpha=1;}
  drawLandmarks(){const g=this.ctx,pts=[...this.scene.landmarks.slice(0,9000).map(x=>({p:x.p,type:'landmark'})),...this.scene.triangulatedPoints.slice(0,4000).map(x=>({p:x.p,type:'tri'}))].map(x=>({...x,s:this.project(x.p)})).sort((a,b)=>a.s.z-b.s.z);for(const x of pts){g.fillStyle=x.type==='tri'?'#ffd277':'#8cd9ff';g.globalAlpha=x.type==='tri'?.5:.72;g.fillRect(x.s.x-1,x.s.y-1,2.2,2.2);}g.globalAlpha=1;}
  drawDeep(){const g=this.ctx,pts=this.scene.deepPoints.slice(0,18000).map(x=>({...x,s:this.project(x.p)})).sort((a,b)=>a.s.z-b.s.z);for(const x of pts){g.fillStyle=frameColor(x.frameIndex||0,.78);g.fillRect(x.s.x-.8,x.s.y-.8,1.6,1.6);}}
  drawCameras(){const g=this.ctx;for(let i=0;i<this.scene.frames.length;i++){const f=this.scene.frames[i],pose=this.options.optimized&&f.poseEstimate?.p?f.poseEstimate:f.posePrior,K=f.K;if(!pose||!K)continue;const c=pose.p,scale=Math.max(.025,this.radius*.025),corners=[[0,0],[K.width,0],[K.width,K.height],[0,K.height]].map(([u,v])=>{const r=qRotate(pose.q,pixelRay(K,u,v));return [c[0]+r[0]*scale*5,c[1]+r[1]*scale*5,c[2]+r[2]*scale*5];});g.strokeStyle=frameColor(i,.85);g.lineWidth=1.3;for(const p of corners)this.line(c,p);for(let j=0;j<4;j++)this.line(corners[j],corners[(j+1)%4]);const s=this.project(c);g.fillStyle=frameColor(i,1);g.beginPath();g.arc(s.x,s.y,2.6,0,Math.PI*2);g.fill();}}
  drawAxes(){const s=Math.max(.06,this.radius*.12),o=this.center;this.ctx.lineWidth=2;this.ctx.strokeStyle='#ff7d86';this.line(o,[o[0]+s,o[1],o[2]]);this.ctx.strokeStyle='#76e6a6';this.line(o,[o[0],o[1]+s,o[2]]);this.ctx.strokeStyle='#69d7ff';this.line(o,[o[0],o[1],o[2]+s]);}
  line(a,b){const A=this.project(a),B=this.project(b),g=this.ctx;g.beginPath();g.moveTo(A.x,A.y);g.lineTo(B.x,B.y);g.stroke();}
}
function frameColor(i,a=1){const h=(i*67)%360;return `hsla(${h},82%,68%,${a})`;}
