import {coverCrop,intrinsicsForCrop,analysisPixelToSource} from '../camera.js?v=30.51.0';
import {ProbabilisticJointOptimizer} from '../probabilistic/joint_optimizer.js?v=30.51.0';
import {pixelRay,qRotate,poseInverse,projectPoint,triangulateRays,clamp,DEG,finite,median,quantile,mean,norm,sub,poseRotationAngle,validPose,validK,epipolarPlaneResidual,sampleDeepFactor,bestDepthFit,fitDepthMode,predictDepth,pointFromPixelDepth} from './diagnostic_math.js?v=30.51.0';

const STATUS_RANK={ok:0,skip:0,warn:1,fail:2,blocked:3};
const stage=(index,name,status,metrics={},reasons=[],actions=[],extra={})=>({index,name,status,metrics,reasons,actions,...extra});
const clone=x=>{try{return structuredClone(x);}catch{return JSON.parse(JSON.stringify(x));}};

export async function runGeometryDiagnostics(source,{full=false,onProgress=null,maxEdges=28,maxMatchesPerEdge=90,maxDeepFrames=8}={}){
  const graph=source?.graph||source?.snapshot?.factorGraph||{},frames=Array.isArray(graph.frames)?graph.frames:[],frameMap=new Map(frames.map(f=>[String(f.frameId),f])),edges=(graph.edgeFactors||[]).filter(e=>frameMap.has(String(e.aId))&&frameMap.has(String(e.bId))),landmarks=graph.landmarkFactors||[],deep=graph.deepFactors||[],deepMap=new Map(deep.map(d=>[String(d.frameId),d])),stages=[],visuals={deepPoints:[],triangulatedPoints:[]};
  const progress=(i,msg)=>onProgress?.({index:i,total:full?12:11,message:msg});

  progress(0,'Contratto dati');stages.push(testFrameContract(graph,frames,edges,landmarks,deep,frameMap));
  progress(1,'Camera e intrinseche');stages.push(testCameraGeometry(graph,frames));
  progress(2,'Pose Alva');stages.push(testPoseSanity(frames));
  progress(3,'Convenzione pose');const convention=testPoseConvention(frames,edges,frameMap,{maxEdges,maxMatchesPerEdge});stages.push(convention);
  progress(4,'Epipolare RGB');const epi=testRgbEpipolar(edges,frameMap,{maxEdges,maxMatchesPerEdge});stages.push(epi);
  progress(5,'Triangolazione');const tri=testTriangulation(edges,frameMap,{maxEdges,maxMatchesPerEdge});stages.push(tri.stage);visuals.triangulatedPoints=tri.points;
  progress(6,'Reproiezione landmark');stages.push(testLandmarkReprojection(landmarks,frameMap));
  progress(7,'Binding Deep');stages.push(testDeepIntegrity(deep,frameMap));
  progress(8,'Deep ↔ geometria sparsa');const depthFit=testDepthTransfer(landmarks,frameMap,deepMap);stages.push(depthFit.stage);
  progress(9,'Stabilità Deep tra frame');const depthStability=testDepthStability(depthFit);stages.push(depthStability);
  progress(10,'Consistenza Deep cross-view');const cross=testDeepCrossView(edges,frameMap,deepMap,depthFit,{maxEdges:Math.min(maxEdges,16),maxFrames:maxDeepFrames});stages.push(cross.stage);visuals.deepPoints=cross.deepPoints;
  if(full){progress(11,'Ablation optimizer');stages.push(await testOptimizerAblation(graph));}

  const firstFailure=stages.find(s=>s.status==='fail'||s.status==='warn')||null;
  const report={format:'ROOMSCAN-GEOMETRY-DIAGNOSTICS-1',version:'30.51-test-1',createdAt:Date.now(),source:{kind:source?.kind||null,name:source?.name||null,build:source?.build||null,sessionId:source?.session?.id||null},mode:full?'full':'quick',summary:{frames:frames.length,edges:edges.length,landmarks:landmarks.length,deepFrames:deep.length,firstFailure:firstFailure?{index:firstFailure.index,name:firstFailure.name,status:firstFailure.status,reasons:firstFailure.reasons}:null},stages,visuals:{deepPoints:visuals.deepPoints.slice(0,18000),triangulatedPoints:visuals.triangulatedPoints.slice(0,6000)}};
  progress(full?12:11,'Completato');return report;
}

function testFrameContract(graph,frames,edges,landmarks,deep,frameMap){
  let badPose=0,badK=0,badId=0,duplicate=0,badPhoto=0;const ids=new Set();for(const f of frames){const id=String(f?.frameId||'');if(!id)badId++;if(ids.has(id))duplicate++;ids.add(id);if(!validPose(f?.posePrior))badPose++;if(!validK(f?.K))badK++;if(f?.photo&&(!(f.photo.width>1&&f.photo.height>1)||!f.photo.gray?.length))badPhoto++;}
  let brokenEdges=0,badMeasurements=0;for(const e of graph.edgeFactors||[])if(!frameMap.has(String(e.aId))||!frameMap.has(String(e.bId)))brokenEdges++;for(const l of landmarks)for(const m of l.measurements||[])if(!frameMap.has(String(m.frameId))||!finite(m.u)||!finite(m.v))badMeasurements++;
  let orphanDeep=0,badDeepShape=0;for(const d of deep){if(!frameMap.has(String(d.frameId)))orphanDeep++;if(!(d.cols>1&&d.rows>1&&d.raw?.length===d.cols*d.rows))badDeepShape++;}
  const reasons=[],actions=[];let status='ok';if(frames.length<2){status='fail';reasons.push('Meno di due frame persistiti.');actions.push('Salvare/esportare una scansione con almeno due keyframe validi.');}if(badPose||badK||badId||duplicate){status='fail';reasons.push(`Contratto frame rotto: pose=${badPose}, K=${badK}, id mancanti=${badId}, duplicati=${duplicate}.`);actions.push('Correggere il binding frameId/K/pose prima di qualunque ricostruzione.');}if(brokenEdges||badMeasurements||orphanDeep||badDeepShape){status=status==='fail'?'fail':'warn';reasons.push(`Riferimenti non coerenti: edge=${brokenEdges}, measurement=${badMeasurements}, Deep orphan=${orphanDeep}, Deep shape=${badDeepShape}.`);}
  if(badPhoto){status=status==='fail'?'fail':'warn';reasons.push(`${badPhoto} frame hanno thumbnail fotografica incompleta.`);}
  return stage(0,'Frame identity / data contract',status,{frames:frames.length,validEdges:edges.length,landmarks:landmarks.length,deepFrames:deep.length,badPose,badK,badId,duplicate,badPhoto,brokenEdges,badMeasurements,orphanDeep,badDeepShape},reasons,actions);
}

function testCameraGeometry(graph,frames){
  const rows=[],devFx=[],devFy=[],devCx=[],devCy=[],centerRayDeg=[];for(const f of frames){if(!validK(f.K))continue;const K=f.K,W=K.width,H=K.height,fovX=2*Math.atan(W/(2*K.fx))/DEG,fovY=2*Math.atan(H/(2*K.fy))/DEG,r=pixelRay(K,K.cx,K.cy),a=Math.acos(clamp(r[2],-1,1))/DEG;centerRayDeg.push(a);const d=f.intrinsicsDeviation||{};if(finite(d.fxRel))devFx.push(d.fxRel);if(finite(d.fyRel))devFy.push(d.fyRel);if(finite(d.cxPx))devCx.push(d.cxPx);if(finite(d.cyPx))devCy.push(d.cyPx);rows.push({frameId:String(f.frameId),fx:K.fx,fy:K.fy,cx:K.cx,cy:K.cy,width:W,height:H,fovXDeg:fovX,fovYDeg:fovY});}
  // Verify the actual crop helper used by production code with an exact round trip.
  const g=coverCrop(1920,1080,320,480),src=analysisPixelToSource(g,123.25,277.75),u=(src.x-g.sx)*g.targetWidth/g.sw,v=(src.y-g.sy)*g.targetHeight/g.sh,roundTripPx=Math.hypot(u-123.25,v-277.75),syntheticK=intrinsicsForCrop({fxN:.72,fyN:1.28,cxN:.5,cyN:.5},g);
  const fovXs=rows.map(r=>r.fovXDeg),fovYs=rows.map(r=>r.fovYDeg),fxRel=quantile(devFx,.95),fyRel=quantile(devFy,.95),cPx=Math.max(quantile(devCx,.95)||0,quantile(devCy,.95)||0),reasons=[],actions=[];let status='ok';
  const strange=rows.filter(r=>!(r.fovXDeg>25&&r.fovXDeg<130&&r.fovYDeg>25&&r.fovYDeg<130)||r.cx<-.15*r.width||r.cx>1.15*r.width||r.cy<-.15*r.height||r.cy>1.15*r.height).length;if(strange){status='fail';reasons.push(`${strange} frame hanno FOV/principal point geometricamente sospetti.`);actions.push('Controllare intrinsicsForCrop e quale raster riceve K.');}
  if((fxRel||0)>.03||(fyRel||0)>.03||cPx>5){status=status==='fail'?'fail':'warn';reasons.push('K osservata varia rispetto al camera model bloccato più del previsto.');actions.push('Verificare crop/resize e intrinseche normalizzate del sensore.');}
  if(roundTripPx>1e-8){status='fail';reasons.push('Il round-trip sintetico analysis↔source del crop non è identico.');}
  return stage(1,'Camera intrinsics / pixel → ray',status,{cameraModel:graph.cameraModel||null,framesChecked:rows.length,fovXMedianDeg:median(fovXs),fovYMedianDeg:median(fovYs),fovXRange:[quantile(fovXs,.05),quantile(fovXs,.95)],fovYRange:[quantile(fovYs,.05),quantile(fovYs,.95)],centerRayMedianDeg:median(centerRayDeg),intrinsicsDeviationP95:{fxRel,fyRel,cPx},cropHelperRoundTripPx:roundTripPx,syntheticCrop:g,syntheticCroppedK:syntheticK,exactPerFrameCropPersisted:frames.some(f=>!!f.geometry)},reasons,actions,{notes:frames.some(f=>!!f.geometry)?[]:['Il factor graph non conserva normalmente geometry/mediaTime: il crop reale del singolo frame non è retro-auditabile da un R30 storico.']});
}

function testPoseSanity(frames){
  const valid=frames.filter(f=>validPose(f.posePrior)).slice().sort((a,b)=>(a.at||0)-(b.at||0)),steps=[],angles=[],qErr=[];for(const f of valid)qErr.push(Math.abs(norm(f.posePrior.q)-1));for(let i=1;i<valid.length;i++){steps.push(norm(sub(valid[i].posePrior.p,valid[i-1].posePrior.p)));angles.push(poseRotationAngle(valid[i-1].posePrior,valid[i].posePrior)/DEG);}
  const medT=median(steps)||0,p95T=quantile(steps,.95)||0,medR=median(angles)||0,p95R=quantile(angles,.95)||0,jumps=steps.filter(x=>x>Math.max(.25,medT*8)).length+angles.filter(x=>x>Math.max(35,medR*8)).length,reasons=[],actions=[];let status='ok';if(valid.length<2){status='fail';reasons.push('Pose valide insufficienti.');}if((quantile(qErr,.99)||0)>1e-3){status='fail';reasons.push('Quaternion non normalizzati.');}if(jumps>Math.max(2,steps.length*.08)){status='warn';reasons.push(`Molti salti di posa robustamente anomali (${jumps}).`);actions.push('Ispezionare i frame attorno ai salti prima di usare Deep/TSDF.');}
  const xs=valid.map(f=>f.posePrior.p[0]),ys=valid.map(f=>f.posePrior.p[1]),zs=valid.map(f=>f.posePrior.p[2]);return stage(2,'Alva pose sanity / trajectory',status,{validPoses:valid.length,translationStepMedian:medT,translationStepP95:p95T,rotationStepMedianDeg:medR,rotationStepP95Deg:p95R,quaternionNormErrorP99:quantile(qErr,.99),robustJumpFlags:jumps,trajectoryExtent:[range(xs),range(ys),range(zs)]},reasons,actions);
}

function testPoseConvention(frames,edges,frameMap,{maxEdges,maxMatchesPerEdge}){
  const current=[],inverse=[];let used=0;for(const e of chooseEdges(edges,maxEdges)){const A=frameMap.get(String(e.aId)),B=frameMap.get(String(e.bId));for(const m of sampleMatches(e.matches,maxMatchesPerEdge)){const a=epipolarPlaneResidual(A,B,m),b=epipolarPlaneResidual(A,B,m,{inversePoses:true});if(a&&b){current.push(a.px);inverse.push(b.px);used++;}}}
  if(used<12)return stage(3,'Pose convention T_wc vs inverse','skip',{matchesUsed:used},['Poche corrispondenze RGB per discriminare la convenzione.'],['Acquisire overlap fotografico con parallasse.']);
  const c=median(current),iv=median(inverse),ratio=iv/Math.max(.05,c),reasons=[],actions=[];let status='ok';if(iv+.75<c*.55){status='fail';reasons.push(`L’interpretazione inversa delle pose spiega molto meglio l’epipolare (${iv.toFixed(2)} px vs ${c.toFixed(2)} px).`);actions.push('Controllare T_wc/T_cw e la conversione Alva→Room CV prima dell’optimizer.');}else if(c>5&&iv<c*.8){status='warn';reasons.push('La convenzione inversa migliora sensibilmente i residui, ma non in modo conclusivo.');}
  return stage(3,'Pose convention T_wc vs inverse',status,{matchesUsed:used,currentMedianPx:c,currentP90Px:quantile(current,.9),inverseMedianPx:iv,inverseP90Px:quantile(inverse,.9),inverseOverCurrent:ratio},reasons,actions);
}

function testRgbEpipolar(edges,frameMap,{maxEdges,maxMatchesPerEdge}){
  const px=[],perEdge=[];for(const e of chooseEdges(edges,maxEdges)){const A=frameMap.get(String(e.aId)),B=frameMap.get(String(e.bId)),r=[];for(const m of sampleMatches(e.matches,maxMatchesPerEdge)){const x=epipolarPlaneResidual(A,B,m);if(x){px.push(x.px);r.push(x.px);}}if(r.length)perEdge.push({aId:String(e.aId),bId:String(e.bId),n:r.length,medianPx:median(r),p90Px:quantile(r,.9)});}
  if(px.length<12)return stage(4,'RGB epipolar consistency','skip',{matchesUsed:px.length,edges:perEdge.length},['Scaffold fotografico insufficiente per un test epipolare robusto.']);
  const med=median(px),p90=quantile(px,.9),inlier3=px.filter(x=>x<3).length/px.length,reasons=[],actions=[];let status='ok';if(med>7||inlier3<.25){status='fail';reasons.push(`Residuo epipolare alto: mediana ${med.toFixed(2)} px, inlier<3px ${(100*inlier3).toFixed(0)}%.`);actions.push('Il problema è a monte di Deep: verificare K, pose, convenzione e corrispondenze RGB.');}else if(med>3.2||p90>8){status='warn';reasons.push(`Scaffold RGB rumoroso: mediana ${med.toFixed(2)} px, P90 ${p90.toFixed(2)} px.`);}
  return stage(4,'RGB epipolar consistency',status,{matchesUsed:px.length,edgesTested:perEdge.length,medianPx:med,p90Px:p90,inlier3px:inlier3,inlier5px:px.filter(x=>x<5).length/px.length,worstEdges:perEdge.sort((a,b)=>b.medianPx-a.medianPx).slice(0,8)},reasons,actions);
}

function testTriangulation(edges,frameMap,{maxEdges,maxMatchesPerEdge}){
  let attempts=0,positive=0;const gapRatio=[],angles=[],reproj=[],points=[];for(const e of chooseEdges(edges,maxEdges)){const A=frameMap.get(String(e.aId)),B=frameMap.get(String(e.bId));if(!A||!B)continue;const baseline=norm(sub(A.posePrior.p,B.posePrior.p));if(baseline<1e-6)continue;for(const m of sampleMatches(e.matches,maxMatchesPerEdge)){attempts++;const t=triangulateRays({pose:A.posePrior,K:A.K,u:+m.aU,v:+m.aV},{pose:B.posePrior,K:B.K,u:+m.bU,v:+m.bV},{minAngleRad:.15*DEG,maxGapM:Infinity});if(!t?.ok)continue;angles.push(t.angle/DEG);gapRatio.push(t.gap/baseline);if(t.depthA>0&&t.depthB>0)positive++;else continue;const qa=projectPoint(A.posePrior,A.K,t.p),qb=projectPoint(B.posePrior,B.K,t.p);if(qa&&qb)reproj.push(.5*(Math.hypot(qa.u-m.aU,qa.v-m.aV)+Math.hypot(qb.u-m.bU,qb.v-m.bV)));if(points.length<6000&&t.gap/baseline<.12)points.push(t.p);}}
  if(attempts<10)return {stage:stage(5,'RGB triangulation','skip',{attempts},['Nessun insieme di match sufficiente.']),points};const valid=positive/Math.max(1,attempts),g=median(gapRatio),a=median(angles),rp=median(reproj),reasons=[],actions=[];let status='ok';if(valid<.35||g>.18){status='fail';reasons.push(`I raggi RGB non si incontrano in modo coerente: depth positive ${(100*valid).toFixed(0)}%, gap/baseline mediano ${fmt(g)}.`);actions.push('Non usare l’optimizer denso finché triangolazione e pose non sono coerenti.');}else if(valid<.65||g>.08||a<.45){status='warn';reasons.push('Triangolazione debole o con poca parallasse.');}
  return {stage:stage(5,'RGB triangulation',status,{attempts,positiveDepthFraction:valid,medianParallaxDeg:a,p10ParallaxDeg:quantile(angles,.1),medianRayGapOverBaseline:g,p90RayGapOverBaseline:quantile(gapRatio,.9),medianPairReprojectionPx:rp,visualizedPoints:points.length},reasons,actions),points};
}

function testLandmarkReprojection(landmarks,frameMap){
  const prior=[],estimate=[];let obs=0,behind=0;for(const l of landmarks){if(!l?.point?.length)continue;for(const m of l.measurements||[]){const f=frameMap.get(String(m.frameId));if(!f)continue;obs++;const a=projectPoint(f.posePrior,f.K,l.point);if(a)prior.push(Math.hypot(a.u-m.u,a.v-m.v));else behind++;const pe=f.poseEstimate||f.posePrior,b=projectPoint(pe,f.K,l.point);if(b)estimate.push(Math.hypot(b.u-m.u,b.v-m.v));}}
  if(prior.length<12)return stage(6,'Sparse landmark reprojection','skip',{observations:obs,projectable:prior.length},['Landmark sparsi insufficienti.']);const med=median(prior),est=median(estimate),reasons=[],actions=[];let status='ok';if(med>8){status='fail';reasons.push(`I landmark salvati non reproiettano sulle misure RGB (mediana ${med.toFixed(2)} px).`);actions.push('Isolare prima scaffold/associazioni; Deep non può correggere questo errore.');}else if(med>3.5){status='warn';reasons.push(`Reproiezione sparsa mediocre (${med.toFixed(2)} px).`);}return stage(6,'Sparse landmark reprojection',status,{landmarks:landmarks.length,observations:obs,projectable:prior.length,behindCamera:behind,posePriorMedianPx:med,posePriorP90Px:quantile(prior,.9),poseEstimateMedianPx:est,poseEstimateP90Px:quantile(estimate,.9),estimateImprovementPx:Number.isFinite(est)?med-est:null},reasons,actions);
}

function testDeepIntegrity(deep,frameMap){if(!deep.length)return stage(7,'Deep frame binding / RAW integrity','skip',{deepFrames:0},['Nessuna depth persistita nel factor graph.']);let orphan=0,badShape=0,lowFinite=0,suspicious=0;const ranges=[];for(const d of deep){if(!frameMap.has(String(d.frameId)))orphan++;if(!(d.cols>1&&d.rows>1&&d.raw?.length===d.cols*d.rows)){badShape++;continue;}const vals=Array.from(d.raw).filter(Number.isFinite),fraction=vals.length/d.raw.length;if(fraction<.9)lowFinite++;if(d.quality?.suspicious)suspicious++;ranges.push({frameId:String(d.frameId),finiteFraction:fraction,p03:quantile(vals,.03),median:median(vals),p97:quantile(vals,.97),span:(quantile(vals,.97)||0)-(quantile(vals,.03)||0)});}
  const reasons=[],actions=[];let status='ok';if(orphan||badShape){status='fail';reasons.push(`Deep non legata correttamente: orphan=${orphan}, shape errata=${badShape}.`);actions.push('Correggere frameId/resize prima di calibrare la depth.');}else if(lowFinite||suspicious>deep.length*.35){status='warn';reasons.push('Una quota rilevante di depth RAW è sospetta o non finita.');}
  return stage(7,'Deep frame binding / RAW integrity',status,{deepFrames:deep.length,orphan,badShape,lowFinite,suspicious,rawRanges:ranges.slice(0,12)},reasons,actions);
}

function testDepthTransfer(landmarks,frameMap,deepMap){
  const pairs=[],byFrame=new Map();for(const l of landmarks){if(!l?.point?.length)continue;for(const m of l.measurements||[]){const id=String(m.frameId),f=frameMap.get(id),d=deepMap.get(id);if(!f||!d)continue;const p=projectPoint(f.posePrior,f.K,l.point);if(!p||!(p.z>.04))continue;const raw=sampleDeepFactor(d,f,+m.u,+m.v);if(!finite(raw))continue;const row={frameId:id,raw,z:p.z,u:+m.u,v:+m.v,landmarkId:String(l.id||'')};pairs.push(row);let a=byFrame.get(id);if(!a)byFrame.set(id,a=[]);a.push(row);}}
  if(pairs.length<16)return {stage:stage(8,'Deep ↔ sparse RGB geometry transfer','skip',{anchorPairs:pairs.length,frames:byFrame.size},['Pochi landmark con Deep sullo stesso frame.'],['Servono overlap/parallasse RGB prima di giudicare la funzione Deep.']),pairs,byFrame,globalFit:null,frameFits:new Map()};
  const candidates=['direct','inverse-raw','inverse-depth'].map(mode=>fitDepthMode(pairs,mode)).filter(Boolean).sort((a,b)=>a.score-b.score),best=candidates[0]||null,frameFits=new Map();if(best)for(const [id,rows] of byFrame){const f=fitDepthMode(rows,best.mode);if(f)frameFits.set(id,f);}
  const reasons=[],actions=[];let status='ok';if(!best||best.medianRelative>.55){status='fail';reasons.push(`Nessuna funzione semplice Deep→depth spiega gli anchor RGB${best?` (errore relativo mediano ${(100*best.medianRelative).toFixed(0)}%)`:''}.`);actions.push('Controllare registrazione RGB/Deep, semantica raw e qualità delle pose prima dell’optimizer.');}else if(best.medianRelative>.28||best.p90Relative>.65){status='warn';reasons.push(`Calibrazione Deep debole: errore relativo mediano ${(100*best.medianRelative).toFixed(0)}%.`);}
  return {stage:stage(8,'Deep ↔ sparse RGB geometry transfer',status,{anchorPairs:pairs.length,frames:byFrame.size,bestFit:best,candidates,perFrameFits:[...frameFits].map(([frameId,f])=>({frameId,...f})).slice(0,30)},reasons,actions),pairs,byFrame,globalFit:best,frameFits};
}

function testDepthStability(depthFit){const mode=depthFit.globalFit?.mode,fits=[...depthFit.frameFits.entries()].filter(([,f])=>f.n>=5);if(!mode||fits.length<3)return stage(9,'Deep transfer stability across frames','skip',{mode:mode||null,framesWithFit:fits.length},['Non ci sono abbastanza frame calibrabili separatamente.']);const a=fits.map(([,f])=>f.a),scaleMed=median(a.map(Math.abs))||1,aSpread=median(a.map(x=>Math.abs(x-median(a))))/scaleMed,err=fits.map(([,f])=>f.medianRelative),bad=err.filter(x=>x>.45).length,reasons=[],actions=[];let status='ok';if(aSpread>.55||bad>fits.length*.45){status='fail';reasons.push('La funzione Deep cambia troppo tra i frame: una calibrazione globale rigida è poco plausibile.');actions.push('Usare correzioni per-frame regolarizzate e confidence multivista, non una sola transfer function libera.');}else if(aSpread>.25||median(err)>.25){status='warn';reasons.push('Scala/transfer Deep mostra deriva frame-to-frame significativa.');}
  return stage(9,'Deep transfer stability across frames',status,{mode,framesWithFit:fits.length,coefficientA:fits.map(([frameId,f])=>({frameId,a:f.a,b:f.b,n:f.n,medianRelative:f.medianRelative})).slice(0,40),robustRelativeSpreadA:aSpread,medianFrameRelativeError:median(err),p90FrameRelativeError:quantile(err,.9),badFrameFraction:bad/fits.length},reasons,actions);
}

function testDeepCrossView(edges,frameMap,deepMap,depthFit,{maxEdges,maxFrames}){
  const fitFor=id=>depthFit.frameFits.get(String(id))||depthFit.globalFit;if(!depthFit.globalFit)return {stage:stage(10,'Deep cross-view consistency','skip',{},['Manca una transfer Deep diagnosticamente osservabile.']),deepPoints:[]};
  const chosenFrames=chooseDeepFrames(frameMap,deepMap,depthFit.frameFits,maxFrames),deepPoints=[];for(let fi=0;fi<chosenFrames.length;fi++){const f=chosenFrames[fi],d=deepMap.get(String(f.frameId)),fit=fitFor(f.frameId);if(!d||!fit)continue;const stride=Math.max(1,Math.ceil(Math.sqrt((d.cols*d.rows)/450)));for(let y=0;y<d.rows;y+=stride)for(let x=0;x<d.cols;x+=stride){const raw=Number(d.raw[y*d.cols+x]),z=predictDepth(fit,raw);if(!(z>.08&&z<30))continue;const u=x/(d.cols-1)*(f.K.width-1),v=y/(d.rows-1)*(f.K.height-1),p=pointFromPixelDepth(f,u,v,z,f.posePrior);if(p)deepPoints.push({p,frameId:String(f.frameId),frameIndex:fi});}}
  const residual=[],pairRows=[];for(const e of chooseEdges(edges,maxEdges)){const A=frameMap.get(String(e.aId)),B=frameMap.get(String(e.bId)),da=deepMap.get(String(e.aId)),db=deepMap.get(String(e.bId)),fa=fitFor(e.aId),fb=fitFor(e.bId);if(!A||!B||!da||!db||!fa||!fb)continue;const vals=[];const sx=Math.max(1,Math.floor(da.cols/10)),sy=Math.max(1,Math.floor(da.rows/14));for(let y=0;y<da.rows;y+=sy)for(let x=0;x<da.cols;x+=sx){const raw=Number(da.raw[y*da.cols+x]),za=predictDepth(fa,raw);if(!(za>.08&&za<30))continue;const u=x/(da.cols-1)*(A.K.width-1),v=y/(da.rows-1)*(A.K.height-1),P=pointFromPixelDepth(A,u,v,za,A.posePrior),q=P?projectPoint(B.posePrior,B.K,P):null;if(!q||q.u<0||q.v<0||q.u>=B.K.width||q.v>=B.K.height||q.z<.08)continue;const rb=sampleDeepFactor(db,B,q.u,q.v),zb=predictDepth(fb,rb);if(!(zb>.08&&zb<30))continue;const r=Math.abs(zb-q.z)/Math.max(.08,q.z);if(r<4){residual.push(r);vals.push(r);}}if(vals.length>=5)pairRows.push({aId:String(e.aId),bId:String(e.bId),n:vals.length,medianRelative:median(vals),p90Relative:quantile(vals,.9)});}
  if(residual.length<20)return {stage:stage(10,'Deep cross-view consistency','skip',{comparisons:residual.length,deepCloudPoints:deepPoints.length},['Poca sovrapposizione Deep proiettabile tra viste.']),deepPoints};const med=median(residual),p90=quantile(residual,.9),reasons=[],actions=[];let status='ok';if(med>.5){status='fail';reasons.push(`Le depth calibrate non sono compatibili tra viste: residuo relativo mediano ${(100*med).toFixed(0)}%.`);actions.push('Non fondere le cloud; identificare frame/pixel Deep incoerenti tramite supporto cross-view.');}else if(med>.25||p90>.75){status='warn';reasons.push(`Consistenza Deep cross-view debole: mediana ${(100*med).toFixed(0)}%.`);}
  return {stage:stage(10,'Deep cross-view consistency',status,{comparisons:residual.length,medianRelative:med,p90Relative:p90,inlier20pct:residual.filter(x=>x<.2).length/residual.length,deepCloudPoints:deepPoints.length,worstPairs:pairRows.sort((a,b)=>b.medianRelative-a.medianRelative).slice(0,8)},reasons,actions),deepPoints};
}

async function testOptimizerAblation(graph){
  if((graph.frames?.length||0)<2||(graph.landmarkFactors?.length||0)<4)return stage(11,'Optimizer ablation (read-only)','skip',{},['Scaffold insufficiente per istanziare l’optimizer.']);
  const configs=[['RGB',{alva:false,deep:false}],['RGB+Alva',{alva:true,deep:false}],['RGB+Deep',{alva:false,deep:true}],['ALL',{alva:true,deep:true}]],rows=[];for(const [name,c] of configs){try{const g=clone(graph);if(!c.alva)g.alvaFactors=[];if(!c.deep){g.deepFactors=[];g.mvsFactors=[];}const opt=new ProbabilisticJointOptimizer(g,{maxLandmarks:Math.min(5000,g.landmarkFactors?.length||5000),maxObsPerFrame:220,rgbWarmupIterations:0,depthFeedbackEvery:1,localWindowSize:18,localWindowOverlap:5}),before=opt.computeStats();opt.step(3,{bootstrap:false,allowDepth:c.deep});const after=opt.computeStats();rows.push({name,before:compactOpt(before),after:compactOpt(after),delta:{robustReprojectionPx:after.reprojectionRobustRmse-before.reprojectionRobustRmse,poseShiftMean:after.poseShiftMean-before.poseShiftMean,deepRelativeError:finite(after.deepRelativeError)&&finite(before.deepRelativeError)?after.deepRelativeError-before.deepRelativeError:null}});}catch(err){rows.push({name,error:err?.message||String(err)});}}
  const good=rows.filter(r=>r.after),all=good.find(r=>r.name==='ALL'),rgb=good.find(r=>r.name==='RGB'),reasons=[],actions=[];let status=good.length?'ok':'fail';if(all&&rgb&&finite(all.after.reprojectionRobustRmse)&&finite(rgb.after.reprojectionRobustRmse)&&all.after.reprojectionRobustRmse>rgb.after.reprojectionRobustRmse*1.45+.5){status='warn';reasons.push('L’inclusione di Alva/Deep peggiora nettamente la reproiezione rispetto al solve RGB-only.');actions.push('Usare l’ablation per identificare quale famiglia di fattori trascina la soluzione fuori dal basin RGB.');}if(rows.some(r=>r.error)){status=status==='fail'?'fail':'warn';reasons.push('Almeno una configurazione dell’ablation ha generato errore.');}
  return stage(11,'Optimizer ablation (read-only)',status,{runs:rows},reasons,actions,{notes:['Esegue 3 step su copie del graph; non persiste né modifica la sessione.']});
}

function chooseEdges(edges,n){if(edges.length<=n)return edges;const sorted=edges.slice().sort((a,b)=>(b.matches?.length||0)-(a.matches?.length||0)),out=[];for(let i=0;i<n;i++)out.push(sorted[Math.floor(i*(sorted.length-1)/Math.max(1,n-1))]);return [...new Set(out)];}
function sampleMatches(matches,n){const a=(matches||[]).filter(m=>[m.aU,m.aV,m.bU,m.bV].every(finite));if(a.length<=n)return a;const out=[];for(let i=0;i<n;i++)out.push(a[Math.floor(i*(a.length-1)/Math.max(1,n-1))]);return out;}
function range(a){const b=a.filter(Number.isFinite);return b.length?Math.max(...b)-Math.min(...b):0;}
function fmt(x){return Number.isFinite(x)?x.toFixed(3):'n/a';}
function compactOpt(s){return {iterations:s.iterations,reprojectionRobustRmse:s.reprojectionRobustRmse,reprojectionMedianPx:s.reprojectionMedianPx,reprojectionP90Px:s.reprojectionP90Px,reprojectionInlierFraction4px:s.reprojectionInlierFraction4px,poseShiftMean:s.poseShiftMean,poseRotationShiftMeanRad:s.poseRotationShiftMeanRad,deepRelativeError:s.deepRelativeError,rgbActiveFraction:s.rgbActiveFraction,rgbRejectedFraction:s.rgbRejectedFraction,feedbackPhase:s.feedbackPhase};}
function chooseDeepFrames(frameMap,deepMap,frameFits,maxFrames){const rows=[...deepMap.keys()].map(id=>frameMap.get(id)).filter(Boolean).sort((a,b)=>(a.at||0)-(b.at||0));if(rows.length<=maxFrames)return rows;const fitted=rows.filter(f=>frameFits.has(String(f.frameId))),src=fitted.length>=Math.min(3,maxFrames)?fitted:rows,out=[];for(let i=0;i<Math.min(maxFrames,src.length);i++)out.push(src[Math.floor(i*(src.length-1)/Math.max(1,Math.min(maxFrames,src.length)-1))]);return [...new Set(out)];}
