import {openDiagnosticDatabase,listDiagnosticSessions,loadDiagnosticSession,loadDiagnosticR30} from './data_loader.js?v=30.51.0';
import {runGeometryDiagnostics} from './diagnostic_runner.js?v=30.51.0';
import {DiagnosticViewer} from './diagnostic_viewer.js?v=30.51.0';
import {downloadBlob} from '../formats.js?v=30.51.0';

const $=id=>document.getElementById(id),state={db:null,sessions:[],source:null,report:null,viewer:null};
boot();

async function boot(){state.viewer=new DiagnosticViewer($('sceneCanvas'));bind();await refreshSessions();}
function bind(){
  $('refreshSessionsBtn').addEventListener('click',()=>guard(refreshSessions));$('loadSessionBtn').addEventListener('click',()=>guard(()=>loadSelected(false)));$('loadLatestBtn').addEventListener('click',()=>guard(()=>loadSelected(true)));$('r30File').addEventListener('change',e=>guard(async()=>{const f=e.target.files?.[0];if(f)await setSource(await loadDiagnosticR30(f));e.target.value='';}));
  $('runQuickBtn').addEventListener('click',()=>guard(()=>run(false)));$('runFullBtn').addEventListener('click',()=>guard(()=>run(true)));$('exportBtn').addEventListener('click',exportReport);$('copyBtn').addEventListener('click',()=>navigator.clipboard?.writeText(summaryText()).catch(()=>{}));
  $('showCameras').addEventListener('change',e=>state.viewer.setOptions({cameras:e.target.checked}));$('showLandmarks').addEventListener('change',e=>state.viewer.setOptions({landmarks:e.target.checked}));$('showDeep').addEventListener('change',e=>state.viewer.setOptions({deep:e.target.checked}));$('showOptimized').addEventListener('change',e=>state.viewer.setOptions({optimized:e.target.checked}));$('fitViewBtn').addEventListener('click',()=>state.viewer.fit());$('topViewBtn').addEventListener('click',()=>state.viewer.preset('top'));$('frontViewBtn').addEventListener('click',()=>state.viewer.preset('front'));$('sideViewBtn').addEventListener('click',()=>state.viewer.preset('side'));
  $('frameSelect').addEventListener('change',renderFrameInspector);$('edgeSelect').addEventListener('change',renderMatchInspector);
}
async function guard(fn){try{return await fn();}catch(err){console.error(err);$('runState').textContent='errore';$('datasetSummary').textContent=err?.message||String(err);}}
async function refreshSessions(){if(!state.db)state.db=await openDiagnosticDatabase();state.sessions=await listDiagnosticSessions(state.db);const s=$('sessionSelect');s.innerHTML='<option value="">Sessioni locali…</option>';for(const x of state.sessions){const o=document.createElement('option');o.value=x.session.id;o.textContent=`${new Date(x.session.updatedAt||x.session.createdAt).toLocaleString()} · ${x.session.id} · ${x.snapshot.factorGraph.frames.length}F`;s.appendChild(o);}if(state.sessions.length)s.value=state.sessions[0].session.id;$('datasetSummary').textContent=state.sessions.length?`${state.sessions.length} sessioni con factor graph disponibili nello storage locale.`:'Nessuna sessione V30 con factor graph trovata su questa origin.';}
async function loadSelected(latest){if(!state.db)await refreshSessions();const id=latest?state.sessions[0]?.session?.id:$('sessionSelect').value;if(!id)throw new Error('Nessuna sessione selezionata.');await setSource(await loadDiagnosticSession(state.db,id));}
async function setSource(src){state.source=src;state.report=null;const g=src.graph,$badge=$('sourceBadge');$badge.textContent=src.kind==='r30'?`R30 · ${src.fileName||src.name}`:`IndexedDB · ${src.session?.id||''}`;$('datasetSummary').textContent=`${g.frames?.length||0} frame · ${g.edgeFactors?.length||0} photo edge · ${g.landmarkFactors?.length||0} landmark · ${g.deepFactors?.length||0} depth frame · build ${buildLabel(src.build)}`;$('runQuickBtn').disabled=false;$('runFullBtn').disabled=false;$('exportBtn').disabled=true;$('copyBtn').disabled=true;$('stageList').textContent='';$('rawJson').textContent='';$('firstFailure').className='firstFailure neutral';$('firstFailure').innerHTML='<b>FIRST FAILURE</b><span>Dataset caricato. Esegui un test.</span>';populateInspectors();renderFrameInspector();renderMatchInspector();state.viewer.setScene({graph:g,report:null});updateViewerStats();}
async function run(full){if(!state.source)return;$('runQuickBtn').disabled=true;$('runFullBtn').disabled=true;$('runState').textContent=full?'test completo…':'test rapido…';$('progressBar').style.width='2%';state.report=await runGeometryDiagnostics(state.source,{full,onProgress:p=>{$('runState').textContent=p.message;$('progressBar').style.width=`${Math.min(100,100*p.index/Math.max(1,p.total))}%`;awaitFrame();}});$('progressBar').style.width='100%';$('runState').textContent='completato';$('runQuickBtn').disabled=false;$('runFullBtn').disabled=false;$('exportBtn').disabled=false;$('copyBtn').disabled=false;renderReport();state.viewer.setScene({graph:state.source.graph,report:state.report});updateViewerStats();setTimeout(()=>$('progressBar').style.width='0%',700);}
function renderReport(){const r=state.report,first=r.summary.firstFailure,box=$('firstFailure');if(first){box.className=`firstFailure ${first.status}`;box.innerHTML=`<b>FIRST FAILURE</b><span><strong>T${first.index} · ${esc(first.name)}</strong><br>${esc(first.reasons?.[0]||'Anomalia rilevata')}</span>`;}else{box.className='firstFailure ok';box.innerHTML='<b>FIRST FAILURE</b><span>Nessun blocker evidente nei dati disponibili.</span>';}
  const list=$('stageList');list.textContent='';for(const s of r.stages){const el=document.createElement('div');el.className=`stage ${s.status}`;const head=document.createElement('div');head.className='stageHead';head.innerHTML=`<span class="stageIndex">T${s.index}</span><strong>${esc(s.name)}</strong><span class="badge">${s.status.toUpperCase()}</span>`;const body=document.createElement('div');body.className='stageBody';const why=[...(s.reasons||[]),...(s.notes||[])];body.innerHTML=`<p>${why.length?why.map(esc).join(' '):'Nessuna anomalia strutturale rilevata.'}</p>${s.actions?.length?`<p><strong>Intervento:</strong> ${s.actions.map(esc).join(' ')}</p>`:''}<pre>${esc(JSON.stringify(s.metrics||{},null,2))}</pre>`;head.addEventListener('click',()=>el.classList.toggle('open'));el.append(head,body);list.appendChild(el);}if(r.stages[0])list.firstElementChild?.classList.add('open');$('rawJson').textContent=JSON.stringify(r,null,2);}
function populateInspectors(){const frames=state.source.graph.frames||[],fs=$('frameSelect');fs.innerHTML='';frames.forEach((f,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`${i} · ${f.frameId}`;fs.appendChild(o);});const es=$('edgeSelect');es.innerHTML='';(state.source.graph.edgeFactors||[]).forEach((e,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`${i} · ${e.aId} → ${e.bId} · ${e.matches?.length||0} match`;es.appendChild(o);});}
function renderFrameInspector(){if(!state.source)return;const frames=state.source.graph.frames||[],i=Number($('frameSelect').value)||0,f=frames[i];if(!f)return;drawRgb($('rgbCanvas'),f.photo||f);const d=(state.source.graph.deepFactors||[]).find(x=>String(x.frameId)===String(f.frameId));drawDepth($('deepCanvas'),d);$('frameMeta').textContent=JSON.stringify({frameId:f.frameId,at:f.at,K:f.K,KObserved:f.KObserved,intrinsicsDeviation:f.intrinsicsDeviation,posePrior:f.posePrior,poseEstimate:f.poseEstimate,poseCov:f.poseCov,trackingMode:f.trackingMode,photo:{width:f.photo?.width,height:f.photo?.height,features:f.photo?.features?.length},features:f.features?.length},null,2);$('deepMeta').textContent=d?JSON.stringify({frameId:d.frameId,cols:d.cols,rows:d.rows,calibration:d.calibration,quality:d.quality},null,2):'Nessuna Deep associata a questo frame.';}
function renderMatchInspector(){if(!state.source)return;const edges=state.source.graph.edgeFactors||[],e=edges[Number($('edgeSelect').value)||0],canvas=$('matchCanvas'),g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);g.fillStyle='#050b10';g.fillRect(0,0,canvas.width,canvas.height);if(!e)return;const map=new Map((state.source.graph.frames||[]).map(f=>[String(f.frameId),f])),A=map.get(String(e.aId)),B=map.get(String(e.bId));if(!A||!B)return;const left={x:0,y:0,w:canvas.width/2,h:canvas.height},right={x:canvas.width/2,y:0,w:canvas.width/2,h:canvas.height};drawRgbRect(g,A.photo||A,left);drawRgbRect(g,B.photo||B,right);const m=(e.matches||[]).slice(0,100);g.lineWidth=1;for(let k=0;k<m.length;k++){const x=m[k],a=mapPixelToRect(A,x.aU,x.aV,left),b=mapPixelToRect(B,x.bU,x.bV,right);g.strokeStyle=`hsla(${(k*53)%360},85%,70%,.52)`;g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();}}
function mapPixelToRect(f,u,v,r){const W=f.K?.width||f.width||1,H=f.K?.height||f.height||1;return {x:r.x+u/W*r.w,y:r.y+v/H*r.h};}
function drawRgb(canvas,f){const g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);g.fillStyle='#050b10';g.fillRect(0,0,canvas.width,canvas.height);drawRgbRect(g,f,{x:0,y:0,w:canvas.width,h:canvas.height});}
function drawRgbRect(g,f,r){const w=f?.width|0,h=f?.height|0,rgb=f?.rgb||null,gray=f?.gray||null;if(w<1||h<1||(!rgb?.length&&!gray?.length))return;const tiny=document.createElement('canvas');tiny.width=w;tiny.height=h;const t=tiny.getContext('2d'),im=t.createImageData(w,h);for(let i=0;i<w*h;i++){const j=i*4;if(rgb?.length>=w*h*3){im.data[j]=rgb[i*3];im.data[j+1]=rgb[i*3+1];im.data[j+2]=rgb[i*3+2];}else{const q=gray[i]||0;im.data[j]=im.data[j+1]=im.data[j+2]=q;}im.data[j+3]=255;}t.putImageData(im,0,0);g.drawImage(tiny,r.x,r.y,r.w,r.h);}
function drawDepth(canvas,d){const g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);g.fillStyle='#050b10';g.fillRect(0,0,canvas.width,canvas.height);if(!d?.raw?.length)return;const vals=Array.from(d.raw).filter(Number.isFinite).sort((a,b)=>a-b),lo=vals[Math.floor(vals.length*.03)],hi=vals[Math.floor(vals.length*.97)],tiny=document.createElement('canvas');tiny.width=d.cols;tiny.height=d.rows;const t=tiny.getContext('2d'),im=t.createImageData(d.cols,d.rows);for(let i=0;i<d.raw.length;i++){const x=Math.max(0,Math.min(1,(d.raw[i]-lo)/Math.max(1e-9,hi-lo))),j=i*4;im.data[j]=Math.round(255*x);im.data[j+1]=Math.round(255*(1-Math.abs(2*x-1)));im.data[j+2]=Math.round(255*(1-x));im.data[j+3]=255;}t.putImageData(im,0,0);g.imageSmoothingEnabled=true;g.drawImage(tiny,0,0,canvas.width,canvas.height);}
function exportReport(){if(!state.report)return;downloadBlob(new Blob([JSON.stringify(state.report,null,2)],{type:'application/json'}),`room-test-geometry-${Date.now()}.json`);}
function summaryText(){const r=state.report;if(!r)return '';return [`Room Test ${r.version}`,`Source: ${r.source.name||r.source.kind}`,`Frames: ${r.summary.frames}, edges: ${r.summary.edges}, landmarks: ${r.summary.landmarks}, Deep: ${r.summary.deepFrames}`,r.summary.firstFailure?`FIRST FAILURE: T${r.summary.firstFailure.index} ${r.summary.firstFailure.name} (${r.summary.firstFailure.status}) — ${r.summary.firstFailure.reasons?.join(' ')}`:'FIRST FAILURE: none',...r.stages.map(s=>`T${s.index} ${s.name}: ${s.status.toUpperCase()}${s.reasons?.length?' — '+s.reasons.join(' '):''}`)].join('\n');}
function updateViewerStats(){if(!state.source)return;const r=state.report;$('viewerStats').textContent=`${state.source.graph.frames?.length||0} camere · ${state.source.graph.landmarkFactors?.length||0} landmark${r?` · ${r.visuals.deepPoints?.length||0} Deep pts`:''}`;}
function buildLabel(b){return typeof b==='string'?b:(b?.id||b?.version||'n/a');}function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function awaitFrame(){return new Promise(r=>requestAnimationFrame(r));}
