/* Room Scanner Diagnostic Recorder v1.0 — 2026-08-15
 * Version-agnostic, injected before the application's ES module by the
 * diagnostic Service Worker. It does not change Room Scanner algorithms.
 * It records chronology, browser/runtime state and bounded visual probes.
 */
(function(){
'use strict';
if (globalThis.RoomScannerDiagnostics?.version) return;
const VERSION='rsdiag-2026-08-15.1';
const START_PERF=performance.now();
const SESSION_ID=new URL(location.href).searchParams.get('rsdiag')||sessionStorage.getItem('roomScannerDiagSessionId')||('diag-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8));
try{sessionStorage.setItem('roomScannerDiagSessionId',SESSION_ID);localStorage.setItem('roomScannerDiagSessionId',SESSION_ID)}catch{}
const encoder=new TextEncoder();
const mem=[]; const queue=[]; const categoryCounts={}; const errors=[]; const videoProbes=[]; const uiProbes=[]; const glContexts=[];
let dbPromise=null, flushTimer=null, dropped=0, exportBusy=false, lastInternalState=null;
const MAX_MEM=9000, MAX_STRING=1600, MAX_ARRAY=40, MAX_DEPTH=4;

function iso(){return new Date().toISOString()}
function finite(v){return typeof v==='number'&&Number.isFinite(v)?v:null}
function sanitize(v,depth=0,seen=new WeakSet()){
  if(v==null||typeof v==='boolean'||typeof v==='number') return Number.isNaN(v)?'NaN':v;
  if(typeof v==='string') return v.length>MAX_STRING?v.slice(0,MAX_STRING)+'…':v;
  if(typeof v==='bigint') return String(v)+'n';
  if(typeof v==='function') return `[Function ${v.name||'anonymous'}]`;
  if(v instanceof Error) return {name:v.name,message:v.message,stack:String(v.stack||'').slice(0,6000),cause:depth<2?sanitize(v.cause,depth+1,seen):undefined};
  if(v instanceof Event) return {type:v.type,timeStamp:finite(v.timeStamp),target:sanitize(v.target,depth+1,seen)};
  if(v instanceof Node) return {node:v.nodeName,id:v.id||'',className:typeof v.className==='string'?v.className:'',text:(v.textContent||'').trim().slice(0,280)};
  if(ArrayBuffer.isView(v)){
    const n=v.length??v.byteLength??0, sample=[]; if(typeof v.length==='number'){const step=Math.max(1,Math.floor(v.length/12));for(let i=0;i<v.length&&sample.length<12;i+=step)sample.push(finite(Number(v[i]))??String(v[i]))}
    return {typedArray:v.constructor?.name||'View',length:n,byteLength:v.byteLength,sample};
  }
  if(v instanceof ArrayBuffer) return {arrayBuffer:true,byteLength:v.byteLength};
  if(v instanceof Blob) return {blob:true,type:v.type,size:v.size};
  if(depth>=MAX_DEPTH) return `[${v?.constructor?.name||typeof v}]`;
  if(typeof v==='object'){
    if(seen.has(v)) return '[Circular]'; seen.add(v);
    if(Array.isArray(v)) return v.slice(0,MAX_ARRAY).map(x=>sanitize(x,depth+1,seen)).concat(v.length>MAX_ARRAY?[`… ${v.length-MAX_ARRAY} more`]:[]);
    const out={}; let n=0;
    for(const k of Object.keys(v)){if(n++>=60){out.__truncated__=true;break}try{out[k]=sanitize(v[k],depth+1,seen)}catch(e){out[k]=`[unreadable: ${e.message}]`}}
    return out;
  }
  try{return String(v)}catch{return '[unserializable]'}
}
function event(category,data={},level='info'){
  const e={sessionId:SESSION_ID,seq:(event.seq=(event.seq||0)+1),t_iso:iso(),t_ms:+(performance.now()-START_PERF).toFixed(3),category,level,data:sanitize(data)};
  categoryCounts[category]=(categoryCounts[category]||0)+1;
  if(level==='error'||category.includes('error')||category.includes('fail')) errors.push(e);
  mem.push(e); if(mem.length>MAX_MEM){mem.shift();dropped++}
  queue.push(e); scheduleFlush(); updateBadge(); return e;
}
function scheduleFlush(){if(flushTimer)return;flushTimer=setTimeout(()=>{flushTimer=null;flush().catch(()=>{})},350)}
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{try{const r=indexedDB.open('room_scanner_diagnostics_v1',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('events')){const s=db.createObjectStore('events',{keyPath:'id',autoIncrement:true});s.createIndex('sessionId','sessionId',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}});return dbPromise}
async function flush(){if(!queue.length)return;const batch=queue.splice(0,queue.length);try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('events','readwrite'),st=tx.objectStore('events');for(const e of batch)st.add(e);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}catch(e){queue.unshift(...batch.slice(-1200));if(!mem.some(x=>x.category==='diag.idb.error'))mem.push({sessionId:SESSION_ID,seq:0,t_iso:iso(),t_ms:0,category:'diag.idb.error',level:'error',data:{message:e.message}})}}
async function storedEvents(){await flush();try{const db=await openDB();return await new Promise((resolve,reject)=>{const tx=db.transaction('events','readonly'),idx=tx.objectStore('events').index('sessionId'),r=idx.getAll(IDBKeyRange.only(SESSION_ID));r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}catch{return mem.slice()}}

function summarizeArgs(args){return Array.from(args||[]).slice(0,8).map(a=>sanitize(a,0))}
function appLog(args){event('app.log',{args:summarizeArgs(args)})}
function checkpoint(label,data){event('checkpoint',{label,data}); flash(`Checkpoint: ${label}`)}

// Console first: the app's own log() calls console.log, so this captures even
// module-private messages before the internal bridge is ready.
for(const name of ['log','info','warn','error','debug']){
  const orig=console[name]?.bind(console); if(!orig)continue;
  console[name]=(...args)=>{try{event('console.'+name,{args:summarizeArgs(args)},name==='error'?'error':name==='warn'?'warn':'info')}catch{} return orig(...args)};
}
addEventListener('error',e=>event('window.error',{message:e.message,filename:e.filename,lineno:e.lineno,colno:e.colno,error:e.error},'error'),true);
addEventListener('unhandledrejection',e=>event('window.unhandledrejection',{reason:e.reason},'error'));
addEventListener('securitypolicyviolation',e=>event('security.csp',{blockedURI:e.blockedURI,violatedDirective:e.violatedDirective,effectiveDirective:e.effectiveDirective,sourceFile:e.sourceFile,lineNumber:e.lineNumber},'error'));
for(const n of ['visibilitychange','pageshow','pagehide','freeze','resume','online','offline','orientationchange','resize']) addEventListener(n,e=>event('lifecycle.'+n,{visibility:document.visibilityState,online:navigator.onLine,inner:[innerWidth,innerHeight],orientation:screen.orientation?.type||null,event:e}),{capture:true,passive:true});

// Fetch/XHR: model/wasm/worker request timing and HTTP/cache headers.
const nativeFetch=globalThis.fetch?.bind(globalThis);
if(nativeFetch) globalThis.fetch=async function(input,init){const url=typeof input==='string'?input:input?.url||String(input),method=init?.method||input?.method||'GET',t=performance.now();event('network.fetch.start',{url,method,cache:init?.cache||input?.cache||null,mode:init?.mode||input?.mode||null});try{const r=await nativeFetch(input,init);event('network.fetch.end',{url:r.url||url,method,status:r.status,ok:r.ok,type:r.type,duration_ms:performance.now()-t,contentType:r.headers.get('content-type'),contentLength:r.headers.get('content-length'),cacheControl:r.headers.get('cache-control'),etag:r.headers.get('etag')},r.ok?'info':'warn');return r}catch(e){event('network.fetch.error',{url,method,duration_ms:performance.now()-t,error:e},'error');throw e}};
try{
 const XO=XMLHttpRequest.prototype.open, XS=XMLHttpRequest.prototype.send;
 XMLHttpRequest.prototype.open=function(method,url,...rest){this.__rsd={method,url:String(url),t:0};return XO.call(this,method,url,...rest)};
 XMLHttpRequest.prototype.send=function(body){if(this.__rsd){this.__rsd.t=performance.now();event('network.xhr.start',{...this.__rsd,body:sanitize(body)})}this.addEventListener('loadend',()=>{const d=this.__rsd||{};event('network.xhr.end',{method:d.method,url:d.url,status:this.status,duration_ms:d.t?performance.now()-d.t:null,responseType:this.responseType})},{once:true});return XS.call(this,body)};
}catch(e){event('diag.patch.xhr.error',{error:e},'warn')}

// Workers: log model-worker lifecycle and bounded message shapes.
try{const NativeWorker=globalThis.Worker;if(NativeWorker){globalThis.Worker=function(url,opts){const w=new NativeWorker(url,opts);const wid='w'+Math.random().toString(36).slice(2,8);event('worker.create',{wid,url:String(url),opts});const post=w.postMessage.bind(w);w.postMessage=(msg,transfer)=>{event('worker.postMessage',{wid,msg:sanitize(msg),transferCount:transfer?.length||0});return post(msg,transfer)};w.addEventListener('message',e=>event('worker.message',{wid,data:sanitize(e.data)}));w.addEventListener('error',e=>event('worker.error',{wid,message:e.message,filename:e.filename,lineno:e.lineno,colno:e.colno},'error'));w.addEventListener('messageerror',e=>event('worker.messageerror',{wid,data:sanitize(e.data)},'error'));return w};globalThis.Worker.prototype=NativeWorker.prototype}}
catch(e){event('diag.patch.worker.error',{error:e},'warn')}

// Media permissions and camera settings.
try{const md=navigator.mediaDevices;if(md?.getUserMedia){const gum=md.getUserMedia.bind(md);md.getUserMedia=async c=>{const t=performance.now();event('media.getUserMedia.start',{constraints:c});try{const st=await gum(c);event('media.getUserMedia.end',{duration_ms:performance.now()-t,tracks:st.getTracks().map(tr=>({kind:tr.kind,label:tr.label,enabled:tr.enabled,muted:tr.muted,readyState:tr.readyState,settings:tr.getSettings?.(),constraints:tr.getConstraints?.(),capabilities:tr.getCapabilities?.()}))});for(const tr of st.getTracks()){for(const n of ['mute','unmute','ended'])tr.addEventListener(n,()=>event('media.track.'+n,{kind:tr.kind,label:tr.label,readyState:tr.readyState,muted:tr.muted,settings:tr.getSettings?.()}))}return st}catch(e){event('media.getUserMedia.error',{constraints:c,duration_ms:performance.now()-t,error:e},'error');throw e}}}}
catch(e){event('diag.patch.media.error',{error:e},'warn')}

// WebXR lifecycle. Keep requestAnimationFrame itself untouched to avoid changing timing.
try{if(navigator.xr){const xr=navigator.xr;if(typeof xr.isSessionSupported==='function'){const f=xr.isSessionSupported.bind(xr);xr.isSessionSupported=async mode=>{const t=performance.now();try{const ok=await f(mode);event('xr.isSessionSupported',{mode,ok,duration_ms:performance.now()-t});return ok}catch(e){event('xr.isSessionSupported.error',{mode,error:e},'error');throw e}}}if(typeof xr.requestSession==='function'){const f=xr.requestSession.bind(xr);xr.requestSession=async(mode,opts)=>{const t=performance.now();event('xr.requestSession.start',{mode,opts});try{const s=await f(mode,opts);event('xr.requestSession.end',{mode,duration_ms:performance.now()-t,visibilityState:s.visibilityState,renderState:s.renderState,enabledFeatures:s.enabledFeatures?Array.from(s.enabledFeatures):null});for(const n of ['end','visibilitychange','inputsourceschange','select','selectstart','selectend'])s.addEventListener(n,e=>event('xr.session.'+n,{visibilityState:s.visibilityState,inputSources:s.inputSources?.length,event:e}));const end=s.end.bind(s);s.end=async()=>{event('xr.session.end.called',{});try{const r=await end();event('xr.session.end.resolved',{});return r}catch(e){event('xr.session.end.error',{error:e},'error');throw e}};if(s.requestReferenceSpace){const rr=s.requestReferenceSpace.bind(s);s.requestReferenceSpace=async type=>{const tt=performance.now();try{const r=await rr(type);event('xr.referenceSpace',{type,duration_ms:performance.now()-tt});return r}catch(e){event('xr.referenceSpace.error',{type,error:e},'error');throw e}}}return s}catch(e){event('xr.requestSession.error',{mode,opts,duration_ms:performance.now()-t,error:e},'error');throw e}}}}}
catch(e){event('diag.patch.xr.error',{error:e},'warn')}

// WebGL creation/loss and GPU identity.
try{const nativeGetContext=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,attrs){const c=nativeGetContext.call(this,type,attrs);if(c&&/^webgl2?$/.test(String(type))&&!this.__rsdGlId){const id='gl'+(glContexts.length+1);this.__rsdGlId=id;let info={id,type,attrs,canvas:{id:this.id||'',width:this.width,height:this.height}};try{const ext=c.getExtension('WEBGL_debug_renderer_info');info.vendor=ext?c.getParameter(ext.UNMASKED_VENDOR_WEBGL):c.getParameter(c.VENDOR);info.renderer=ext?c.getParameter(ext.UNMASKED_RENDERER_WEBGL):c.getParameter(c.RENDERER);info.version=c.getParameter(c.VERSION);info.shadingLanguage=c.getParameter(c.SHADING_LANGUAGE_VERSION);info.maxTextureSize=c.getParameter(c.MAX_TEXTURE_SIZE);info.maxRenderbufferSize=c.getParameter(c.MAX_RENDERBUFFER_SIZE)}catch(e){info.infoError=e.message}glContexts.push(info);event('webgl.context.create',info);this.addEventListener('webglcontextlost',e=>{event('webgl.context.lost',{id,statusMessage:e.statusMessage},'error')},false);this.addEventListener('webglcontextrestored',()=>event('webgl.context.restored',{id}),false)}return c}}
catch(e){event('diag.patch.webgl.error',{error:e},'warn')}

// Service Worker messages include requests that happen before app-level fetch hooks.
try{navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.__rsdiag)event('sw.'+(e.data.type||'message'),e.data.payload||e.data)})}catch{}

function elementState(el){if(!el)return null;const cs=getComputedStyle(el),r=el.getBoundingClientRect();return {tag:el.tagName,id:el.id,className:el.className,hidden:!!el.hidden,display:cs.display,visibility:cs.visibility,opacity:cs.opacity,zIndex:cs.zIndex,pointerEvents:cs.pointerEvents,rect:{x:+r.x.toFixed(1),y:+r.y.toFixed(1),w:+r.width.toFixed(1),h:+r.height.toFixed(1)},text:(el.textContent||'').trim().replace(/\s+/g,' ').slice(0,420)} }
function domSnapshot(){
 const ids=['preview','xrHost','landing','hud','scanPreviewWrap','scanPreviewLabel','scanPreviewPercent','scanPreviewDetail','objectSeedUI','objectSeedMask','objectFreezeFrame','seedMeta','seedHint','semanticStatus','aiMiniProgress','processingOverlay','processingTitle','processingDetail','finalView','finalCanvas','finalSummary','finalMenu','debug'];
 const out={body:{className:document.body?.className||'',workflow:document.body?.dataset?.workflowStage||null},elements:{}};for(const id of ids)out.elements[id]=elementState(document.getElementById(id));out.canvases=[...document.querySelectorAll('canvas')].map(c=>({...elementState(c),buffer:[c.width,c.height],glId:c.__rsdGlId||null}));out.videos=[...document.querySelectorAll('video')].map(v=>({...elementState(v),readyState:v.readyState,networkState:v.networkState,paused:v.paused,ended:v.ended,currentTime:finite(v.currentTime),videoWidth:v.videoWidth,videoHeight:v.videoHeight,srcObject:!!v.srcObject,tracks:v.srcObject?.getTracks?.().map(t=>({kind:t.kind,readyState:t.readyState,muted:t.muted,enabled:t.enabled,settings:t.getSettings?.()}))||[]}));return out
}
function videoProbe(){const v=document.getElementById('preview')||document.querySelector('video');if(!v)return null;const row={t_ms:+(performance.now()-START_PERF).toFixed(1),readyState:v.readyState,paused:v.paused,currentTime:finite(v.currentTime),videoWidth:v.videoWidth,videoHeight:v.videoHeight,hasStream:!!v.srcObject};try{if(v.videoWidth&&v.videoHeight&&v.readyState>=2){const c=document.createElement('canvas');c.width=48;c.height=27;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let n=0,sum=0,sum2=0,mn=255,mx=0,nonzero=0;for(let i=0;i<d.length;i+=4){const y=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];sum+=y;sum2+=y*y;mn=Math.min(mn,y);mx=Math.max(mx,y);if(y>3)nonzero++;n++}const mean=sum/n;row.lumaMean=+mean.toFixed(2);row.lumaStd=+Math.sqrt(Math.max(0,sum2/n-mean*mean)).toFixed(2);row.lumaMin=+mn.toFixed(2);row.lumaMax=+mx.toFixed(2);row.nonBlackFraction=+(nonzero/n).toFixed(4)}}catch(e){row.probeError=e.message}videoProbes.push(row);if(videoProbes.length>2400)videoProbes.shift();return row}
function internalState(){try{const s=globalThis.__RS_DIAG_BRIDGE__?.snapshot?.();if(s)lastInternalState=s;return s||lastInternalState}catch(e){event('bridge.snapshot.error',{error:e},'warn');return lastInternalState}}

let lastDomHash='';
setInterval(()=>{try{const d=domSnapshot(),sig=JSON.stringify({body:d.body,e:Object.fromEntries(Object.entries(d.elements).map(([k,v])=>[k,v&&{c:v.className,d:v.display,v:v.visibility,o:v.opacity,r:v.rect,t:v.text}]))});if(sig!==lastDomHash){lastDomHash=sig;uiProbes.push({t_ms:+(performance.now()-START_PERF).toFixed(1),snapshot:d});if(uiProbes.length>900)uiProbes.shift();event('ui.changed',d)}const vp=videoProbe();if(vp)event('preview.probe',vp);const st=internalState();if(st)event('app.state.sample',st)}catch(e){event('diag.sampler.error',{error:e},'warn')}},1000);

try{const mo=new MutationObserver(ms=>{const rows=[];for(const m of ms.slice(0,80)){const t=m.target;if(t.closest?.('[data-rsdiag-ui]'))continue;rows.push({type:m.type,target:sanitize(t),attributeName:m.attributeName,oldValue:m.oldValue,added:m.addedNodes?.length||0,removed:m.removedNodes?.length||0})}if(rows.length)event('dom.mutation',{mutations:rows})});addEventListener('DOMContentLoaded',()=>{mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeOldValue:true,attributeFilter:['class','style','hidden','disabled','aria-expanded']});event('dom.ready',domSnapshot())},{once:true})}catch(e){event('diag.mutation.error',{error:e},'warn')}

try{const po=new PerformanceObserver(list=>{for(const x of list.getEntries())event('performance.'+x.entryType,{name:x.name,startTime:x.startTime,duration:x.duration,initiatorType:x.initiatorType,transferSize:x.transferSize,encodedBodySize:x.encodedBodySize,decodedBodySize:x.decodedBodySize})});po.observe({entryTypes:['longtask','resource','navigation','measure']})}catch(e){event('diag.performanceObserver.error',{error:e},'warn')}

async function cacheSnapshot(){const out={controller:navigator.serviceWorker?.controller?{scriptURL:navigator.serviceWorker.controller.scriptURL,state:navigator.serviceWorker.controller.state}:null,registrations:[],caches:[]};try{for(const r of await navigator.serviceWorker?.getRegistrations?.()||[])out.registrations.push({scope:r.scope,active:r.active?.scriptURL||null,waiting:r.waiting?.scriptURL||null,installing:r.installing?.scriptURL||null})}catch(e){out.registrationError=e.message}try{for(const k of await caches.keys()){const c=await caches.open(k),req=await c.keys();out.caches.push({name:k,count:req.length,urls:req.slice(0,160).map(x=>x.url)})}}catch(e){out.cacheError=e.message}return out}
function environment(){return {diagnosticVersion:VERSION,sessionId:SESSION_ID,startedAt:new Date(Date.now()-performance.now()+START_PERF).toISOString(),exportedAt:iso(),url:location.href,referrer:document.referrer,userAgent:navigator.userAgent,platform:navigator.platform,languages:navigator.languages,hardwareConcurrency:navigator.hardwareConcurrency||null,deviceMemoryGB:navigator.deviceMemory||null,connection:navigator.connection?sanitize(navigator.connection):null,secureContext:isSecureContext,crossOriginIsolated,cookieEnabled:navigator.cookieEnabled,screen:{width:screen.width,height:screen.height,availWidth:screen.availWidth,availHeight:screen.availHeight,dpr:devicePixelRatio,orientation:screen.orientation?.type||null},viewport:{innerWidth,innerHeight},webgpu:!!navigator.gpu,webxr:!!navigator.xr,mediaDevices:!!navigator.mediaDevices,visibility:document.visibilityState,memory:performance.memory?sanitize(performance.memory):null}}

function u16(v){return Uint8Array.of(v&255,(v>>>8)&255)} function u32(v){return Uint8Array.of(v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255)}
const crcTable=(()=>{const a=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;a[n]=c>>>0}return a})();
function crc32(a){let c=0xffffffff;for(const b of a)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function concat(parts){const n=parts.reduce((a,b)=>a+b.length,0),o=new Uint8Array(n);let p=0;for(const b of parts){o.set(b,p);p+=b.length}return o}
async function bytes(v){if(v instanceof Uint8Array)return v;if(v instanceof ArrayBuffer)return new Uint8Array(v);if(v instanceof Blob)return new Uint8Array(await v.arrayBuffer());return encoder.encode(String(v))}
async function makeZip(entries){const locals=[],central=[];let off=0,count=0;for(const ent of entries){if(ent.data==null)continue;const name=encoder.encode(ent.name.replace(/^\/+/,'')),data=await bytes(ent.data),crc=crc32(data),lh=concat([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]),ch=concat([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),name]);locals.push(lh,data);central.push(ch);off+=lh.length+data.length;count++}const cd=concat(central),end=concat([u32(0x06054b50),u16(0),u16(0),u16(count),u16(count),u32(cd.length),u32(off),u16(0)]);return new Blob([...locals,cd,end],{type:'application/zip'})}
function csv(rows){if(!rows?.length)return '';const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))],q=v=>'"'+String(v??'').replaceAll('"','""')+'"';return keys.join(',')+'\n'+rows.map(r=>keys.map(k=>q(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(',')).join('\n')+'\n'}
async function canvasPng(canvas){try{return await new Promise(resolve=>canvas.toBlob(b=>resolve(b),'image/png'))}catch{return null}}
async function videoPng(v){try{if(!v?.videoWidth||!v?.videoHeight)return null;const max=1280,sc=Math.min(1,max/v.videoWidth),c=document.createElement('canvas');c.width=Math.max(1,Math.round(v.videoWidth*sc));c.height=Math.max(1,Math.round(v.videoHeight*sc));c.getContext('2d',{alpha:false}).drawImage(v,0,0,c.width,c.height);return await canvasPng(c)}catch{return null}}
async function screenshots(){const out=[];const v=document.getElementById('preview')||document.querySelector('video'),p=await videoPng(v);if(p)out.push({name:'images/preview_current.png',data:p});for(const [name,sel] of [['seed_mask','#objectSeedMask'],['freeze_frame','#objectFreezeCanvas'],['xr_canvas','#xrHost canvas'],['final_canvas','#finalCanvas canvas']]){const c=document.querySelector(sel);if(c){const b=await canvasPng(c);if(b?.size)out.push({name:`images/${name}.png`,data:b})}}return out}
async function runSelfTest(){const b=globalThis.__RS_DIAG_BRIDGE__;if(!b?.selfTest){event('selftest.unavailable',{bridge:!!b},'error');flash('SELF TEST non disponibile');return null}flash('SELF TEST avviato…');const r=await b.selfTest();flash('SELF TEST completato');return r}
async function exportZip(){if(exportBusy)return;exportBusy=true;updateBadge('EXPORT…');try{checkpoint('EXPORT_DIAGNOSTICS');const ev=await storedEvents(),internal=internalState(),dom=domSnapshot(),cache=await cacheSnapshot(),resources=performance.getEntriesByType('resource').map(x=>sanitize(x)),shots=await screenshots();const manifest={format:'room-scanner-capillary-diagnostic-v1',...environment(),eventCount:ev.length,memoryRingCount:mem.length,droppedMemoryEvents:dropped,categoryCounts,errors:errors.length,bridgeAvailable:!!globalThis.__RS_DIAG_BRIDGE__,bridgeVersion:globalThis.__RS_DIAG_BRIDGE__?.version||null,notes:['No microphone PCM is included.','Images folder contains only current diagnostic screenshots captured when ZIP export is pressed.','timeline.jsonl is the primary chronological evidence.','service_worker_cache.json confirms which worker/cache actually controlled the run.']};const readme=`ROOM SCANNER CAPILLARY DIAGNOSTIC\nSession: ${SESSION_ID}\nBuild visible to bridge: ${internal?.appBuild||'unknown'}\n\nReproduce the problem before pressing ZIP LOG. The archive contains chronological browser/app/model/WebXR/WebGL diagnostics. No raw microphone audio is included. Current visual screenshots are included only at export time.\n`;const entries=[{name:'README.txt',data:readme},{name:'diagnostic_manifest.json',data:JSON.stringify(manifest,null,2)},{name:'app_internal_state.json',data:JSON.stringify(internal,null,2)},{name:'dom_snapshot.json',data:JSON.stringify(dom,null,2)},{name:'service_worker_cache.json',data:JSON.stringify(cache,null,2)},{name:'webgl_contexts.json',data:JSON.stringify(glContexts,null,2)},{name:'performance_resources.json',data:JSON.stringify(resources,null,2)},{name:'timeline.jsonl',data:ev.map(x=>JSON.stringify(x)).join('\n')+'\n'},{name:'errors.jsonl',data:errors.map(x=>JSON.stringify(x)).join('\n')+'\n'},{name:'preview_probe.csv',data:csv(videoProbes)},{name:'ui_timeline.jsonl',data:uiProbes.map(x=>JSON.stringify(x)).join('\n')+'\n'},...shots];const z=await makeZip(entries),a=document.createElement('a'),u=URL.createObjectURL(z);a.href=u;a.download=`room_scanner_CAPILLARY_${SESSION_ID}_${new Date().toISOString().replaceAll(':','-')}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000);event('diag.export.complete',{bytes:z.size,entries:entries.length})}catch(e){event('diag.export.error',{error:e},'error');alert('Export diagnostica fallito: '+e.message)}finally{exportBusy=false;updateBadge()}}

function flash(text){const n=document.getElementById('rsdiagToast');if(!n)return;n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1600)}
function updateBadge(text){const b=document.getElementById('rsdiagCount');if(b)b.textContent=text||`${event.seq||0} ev · ${errors.length} err`}
async function exitDiagnostics(){try{event('diag.exit',{});await flush();for(const r of await navigator.serviceWorker?.getRegistrations?.()||[]){const u=r.active?.scriptURL||r.waiting?.scriptURL||r.installing?.scriptURL||'';if(u.includes('room_scanner_diag_sw.js'))await r.unregister()}location.replace('./room_scanner_v9.html?cb='+Date.now())}catch(e){event('diag.exit.error',{error:e},'error')}}
function installUI(){if(document.getElementById('rsdiagPanel'))return;const css=document.createElement('style');css.dataset.rsdiagUi='1';css.textContent=`#rsdiagPanel{position:fixed;right:8px;bottom:max(8px,env(safe-area-inset-bottom));z-index:2147483647;display:flex;gap:5px;align-items:center;padding:6px;border-radius:12px;background:rgba(5,9,16,.92);border:1px solid rgba(99,220,255,.65);box-shadow:0 6px 25px rgba(0,0,0,.45);font:700 10px/1.1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#eafaff;pointer-events:auto}#rsdiagPanel button{min-width:0!important;padding:7px 8px!important;font:800 10px/1 ui-monospace,SFMono-Regular,Menlo,monospace!important;border-radius:8px!important;background:#143048!important;color:#eafaff!important;border:1px solid rgba(255,255,255,.18)!important}#rsdiagCount{white-space:nowrap;color:#7df2ac}#rsdiagToast{position:fixed;left:50%;bottom:70px;z-index:2147483647;transform:translateX(-50%) translateY(12px);opacity:0;padding:8px 11px;border-radius:10px;background:#07131f;color:#eafaff;border:1px solid rgba(99,220,255,.45);font:700 11px ui-monospace;transition:.15s;pointer-events:none}#rsdiagToast.show{opacity:1;transform:translateX(-50%) translateY(0)}`;document.head.appendChild(css);const p=document.createElement('div');p.id='rsdiagPanel';p.dataset.rsdiagUi='1';p.innerHTML='<span id="rsdiagCount">0 ev</span><button id="rsdiagTest" type="button">SELF TEST</button><button id="rsdiagMark" type="button">MARK</button><button id="rsdiagZip" type="button">ZIP LOG</button><button id="rsdiagExit" type="button">EXIT</button>';document.body.appendChild(p);const t=document.createElement('div');t.id='rsdiagToast';t.dataset.rsdiagUi='1';document.body.appendChild(t);document.getElementById('rsdiagTest').onclick=()=>runSelfTest().catch(e=>event('selftest.ui.error',{error:e},'error'));document.getElementById('rsdiagMark').onclick=()=>checkpoint(prompt('Nome checkpoint diagnostico:','problema_visibile')||'manual');document.getElementById('rsdiagZip').onclick=exportZip;document.getElementById('rsdiagExit').onclick=exitDiagnostics;updateBadge();event('diag.ui.installed',{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installUI,{once:true});else installUI();

const api={version:VERSION,sessionId:SESSION_ID,event,appLog,checkpoint,runSelfTest,exportZip,sanitize,domSnapshot,internalState};
globalThis.RoomScannerDiagnostics=api;
event('diag.start',environment());
})();
