import {coverCrop,intrinsicsForCrop} from '../camera.js';
import {refinePosePnP} from '../metric/pnp_pose.js';

/**
 * Short-lived visual metric bootstrap.
 *
 * This module does NOT track the room. It only re-observes >=3 calibrated
 * metric pins for a few seconds, refines the metric camera pose with PnP and
 * pairs those poses with the concurrently running AlvaAR world tracker. Once
 * the Alva->metric Sim(3) transform is locked, this bridge is discarded.
 */
function previewViewportSize(){const vv=globalThis.visualViewport,doc=globalThis.document?.documentElement;return {width:Math.max(1,Math.round(vv?.width||globalThis.innerWidth||doc?.clientWidth||1)),height:Math.max(1,Math.round(vv?.height||globalThis.innerHeight||doc?.clientHeight||1))};}
function fitPreviewViewport(video){if(!video)return {width:0,height:0};const {width,height}=previewViewportSize(),host=video.parentElement;if(host){host.style.setProperty('padding','0','important');host.style.setProperty('overflow','hidden','important');host.style.setProperty('width',width+'px','important');host.style.setProperty('height',height+'px','important');host.style.setProperty('min-height',height+'px','important');host.style.setProperty('max-height',height+'px','important');}for(const [k,v] of Object.entries({position:'absolute',left:'0',top:'0',right:'auto',bottom:'auto',width:width+'px',height:height+'px','min-width':'0','min-height':'0','max-width':'none','max-height':'none','object-fit':'cover','object-position':'center center',display:'block','z-index':'0'}))video.style.setProperty(k,v,'important');return {width,height};}
function waitForVideoGeometry(video,timeoutMs=1600){if(!video)return Promise.resolve(false);if(video.readyState>=2&&video.videoWidth>0&&video.videoHeight>0)return Promise.resolve(true);return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);video.removeEventListener('loadedmetadata',onReady);video.removeEventListener('canplay',onReady);resolve(v);},onReady=()=>finish(video.videoWidth>0&&video.videoHeight>0),timer=setTimeout(()=>finish(false),timeoutMs);video.addEventListener('loadedmetadata',onReady,{once:true});video.addEventListener('canplay',onReady,{once:true});});}

export class MetricBridge extends EventTarget{
  constructor({video,calibration,log=null,analysisWidth=320,analysisHeight=480,frontend=null,trackingFps=12}={}){
    super();this.video=video;this.calibration=calibration;this.log=log;this.w=Math.max(160,analysisWidth|0);this.h=Math.max(240,analysisHeight|0);this.frontend=frontend;this.trackingFps=trackingFps;
    this.canvas=document.createElement('canvas');this.canvas.width=this.w;this.canvas.height=this.h;this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});this.running=false;this.cancelled=false;this.timer=0;this.trackTimer=0;this.result=null;this.stream=null;this.latestAlva=null;this.lastMetricPose=clonePose(calibration?.commonView?.pose||calibration?.pose||null);this.geometry=null;this.K=null;
    this._resizeHandler=()=>fitPreviewViewport(this.video);this._lastGeometryCheck=0;this._groups=groupAnchors(calibration);
  }
  setFrontend(frontend){this.frontend=frontend;if(this.running&&!this.trackTimer)this._trackLoop();return this;}
  async start(){
    if(!this.video)throw new Error('bridge video missing');if(!this.calibration?.anchors?.length)throw new Error('calibration missing');this.cancelled=false;fitPreviewViewport(this.video);globalThis.addEventListener?.('resize',this._resizeHandler,{passive:true});globalThis.visualViewport?.addEventListener?.('resize',this._resizeHandler,{passive:true});
    if(!this.video.srcObject){const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:60}}});if(this.cancelled){for(const t of stream.getTracks?.()||[])try{t.stop()}catch{};return this;}this.stream=stream;this.video.srcObject=stream;try{await this.video.play();}catch(err){this.stop();throw new Error(`Impossibile avviare anteprima camera: ${err?.message||err}`);}}
    if(this.cancelled)return this;await waitForVideoGeometry(this.video);const viewport=fitPreviewViewport(this.video);this._updateGeometry();this.running=true;this._loop();if(this.frontend)this._trackLoop();const videoRect=this.video?.getBoundingClientRect?.();this.log?.info('metric-bridge-camera-ready',{analysis:[this.w,this.h],groups:this._groups.length,viewport,videoIntrinsic:[this.video.videoWidth||0,this.video.videoHeight||0],videoRect:videoRect?{width:videoRect.width,height:videoRect.height}:null,K:this.K});return this;
  }
  pause(){this.running=false;clearTimeout(this.timer);clearTimeout(this.trackTimer);this.timer=0;this.trackTimer=0;}
  resume(){if(this.cancelled||this.running)return;this.running=true;this._loop();if(this.frontend)this._trackLoop();}
  takeStream(){this.pause();const stream=this.stream;this.stream=null;if(this.video)this.video.srcObject=null;globalThis.removeEventListener?.('resize',this._resizeHandler);globalThis.visualViewport?.removeEventListener?.('resize',this._resizeHandler);return stream;}
  async restoreStream(stream){if(!stream)return;this.cancelled=false;this.stream=stream;if(this.video){fitPreviewViewport(this.video);this.video.srcObject=stream;try{await this.video.play();}catch{}await waitForVideoGeometry(this.video);this._updateGeometry();fitPreviewViewport(this.video);globalThis.addEventListener?.('resize',this._resizeHandler,{passive:true});globalThis.visualViewport?.addEventListener?.('resize',this._resizeHandler,{passive:true});}}
  stop(){this.cancelled=true;this.pause();for(const t of this.stream?.getTracks?.()||[])try{t.stop()}catch{}if(this.stream&&this.video)this.video.srcObject=null;globalThis.removeEventListener?.('resize',this._resizeHandler);globalThis.visualViewport?.removeEventListener?.('resize',this._resizeHandler);this.stream=null;}
  _updateGeometry(){const vw=this.video?.videoWidth||this.w,vh=this.video?.videoHeight||this.h;this.geometry=coverCrop(vw,vh,this.w,this.h);const common=this.calibration.commonView||{};this.K=intrinsicsForCrop(common.intrinsicsNorm||this.calibration.intrinsicsNorm,this.geometry,{fallbackFovDeg:62});}
  _capture(){if(!this.video||this.video.readyState<2)return null;this._updateGeometry();const g=this.geometry;this.ctx.drawImage(this.video,g.sx,g.sy,g.sw,g.sh,0,0,this.w,this.h);const image=this.ctx.getImageData(0,0,this.w,this.h),gray=new Uint8Array(this.w*this.h),d=image.data;for(let i=0,j=0;i<d.length;i+=4,j++)gray[j]=(d[i]*77+d[i+1]*150+d[i+2]*29)>>8;return {at:performance.now(),width:this.w,height:this.h,imageData:image,rgba:image.data,gray,geometry:g};}
  _trackLoop(){if(!this.running||!this.frontend)return;const started=performance.now();try{const frame=this._capture();if(frame){const tr=this.frontend.trackPose(frame);this.latestAlva={...tr,at:frame.at};this.dispatchEvent(new CustomEvent('alva',{detail:this.latestAlva}));}}catch(err){this.log?.warn('metric-bridge-alva',{message:err.message,stack:err.stack||null});}const elapsed=performance.now()-started,period=1000/Math.max(2,this.trackingFps);this.trackTimer=setTimeout(()=>this._trackLoop(),Math.max(4,period-elapsed));}
  _loop(){if(!this.running)return;const started=performance.now();if(started-this._lastGeometryCheck>1000){this._lastGeometryCheck=started;const vp=fitPreviewViewport(this.video),rect=this.video?.getBoundingClientRect?.();if(rect&&rect.height<vp.height*.72)this.log?.warn('metric-preview-layout',{viewport:vp,rect:{width:rect.width,height:rect.height},intrinsic:[this.video.videoWidth||0,this.video.videoHeight||0]});}
    try{const r=this.evaluate();r.computeMs=performance.now()-started;this.dispatchEvent(new CustomEvent('update',{detail:r}));if(r.locked&&!this.result){this.result=r;this.dispatchEvent(new CustomEvent('locked',{detail:r}));}}catch(err){this.log?.warn('metric-bridge-evaluate',{message:err.message,stack:err.stack||null});}
    this.timer=setTimeout(()=>this._loop(),220);
  }
  evaluate(){
    const frame=this._capture();if(!frame)return {locked:false,found:0,inliers:0,rmse:null,matches:[]};const matches=[];for(const g of this._groups){const expected=fullUvToAnalysis(g.uv,frame.geometry);const m=findGroup(frame.gray,this.w,this.h,{...g,analysisUv:expected});if(m)matches.push(m);}
    const inliers=matches.filter(m=>m.score>=.38&&m.shiftN<=.15);const observations=inliers.map(m=>{const g=this._groups.find(x=>x.id===m.id);return g?.world?{world:g.world,u:m.uv[0]*this.w,v:m.uv[1]*this.h,id:m.id}:null;}).filter(Boolean);
    const common=this.calibration.commonView||{},initial=this.lastMetricPose||common.pose||this.calibration.pose||null;let pnp={ok:false,pose:initial,rmsePx:Infinity,inliers:0,reason:'not-enough-correspondences'};
    if(initial&&observations.length>=3)pnp=refinePosePnP({initialPose:initial,K:this.K,observations,maxIterations:10,huberPx:9});
    const locked=!!pnp.ok&&pnp.inliers>=3&&pnp.rmsePx<=10;if(locked)this.lastMetricPose=clonePose(pnp.pose);const rmse=Number.isFinite(pnp.rmsePx)?pnp.rmsePx/Math.max(this.w,this.h):null;
    return {at:frame.at,locked,found:matches.length,inliers:observations.length,rmse,reprojectionPx:Number.isFinite(pnp.rmsePx)?pnp.rmsePx:null,pose:locked?clonePose(pnp.pose):null,intrinsicsNorm:common.intrinsicsNorm||this.calibration.intrinsicsNorm||null,cameraSize:common.cameraSize||this.calibration.cameraSize||null,K:{...this.K},unit:'m',method:'short-lived-pin-pnp-bootstrap-v30.17.0',matches,pnpReason:pnp.reason||null,alvaAt:this.latestAlva?.at||null};
  }
}

function groupAnchors(cal){const map=new Map(),objects=new Map((cal?.objects||[]).map(o=>[o.id,o]));for(const a of cal?.anchors||[]){if(!a?.objectId||!Array.isArray(a.uv)||!a.patch||!Array.isArray(a.p))continue;if(!map.has(a.objectId))map.set(a.objectId,[]);map.get(a.objectId).push(a);}return [...map].map(([id,as])=>{const common=[],observed=[],roi=[];const push=(dst,patch,size,source)=>{if(!patch?.length)return;const n=size||Math.round(Math.sqrt(patch.length));if(n<4||patch.length<n*n)return;dst.push({patch:Uint8Array.from(patch),size:n,source});};for(const a of as){push(common,a.patch,a.patchSize,'common');for(const o of a.observations||[])push(observed,o.patch,o.patchSize,'anchor-observation');}for(const v of objects.get(id)?.roiViews||[])for(const sc of v.scales||[])push(roi,sc.patch,sc.patchSize||Math.round(Math.sqrt(sc.patch?.length||0)),'roi-atlas');const templates=[...common.slice(-2),...observed.slice(-2),...roi.slice(-4)].slice(0,8),world=average3(as.map(a=>a.p));return {id,uv:[as.reduce((s,a)=>s+a.uv[0],0)/as.length,as.reduce((s,a)=>s+a.uv[1],0)/as.length],world,templates};}).filter(g=>g.templates.length&&g.world);}
function fullUvToAnalysis(uv,g){const x=uv[0]*g.sourceWidth,y=uv[1]*g.sourceHeight;return [(x-g.sx)/g.sw,(y-g.sy)/g.sh];}
function findGroup(gray,w,h,g){let best=null,comparisons=0;const maxComparisons=520;for(const t of g.templates){const size=t.size;if(size<4||t.patch.length<size*size)continue;const cx=Math.round(g.analysisUv[0]*w),cy=Math.round(g.analysisUv[1]*h),range=Math.max(10,Math.round(Math.min(w,h)*.105)),step=Math.max(3,Math.floor(size/3));for(let y=cy-range;y<=cy+range;y+=step)for(let x=cx-range;x<=cx+range;x+=step){if(++comparisons>maxComparisons)return best;const patch=sample(gray,w,h,x,y,size);if(!patch)continue;const score=zncc(t.patch,patch);if(!best||score>best.score){const uv=[x/w,y/h],shiftN=Math.hypot(uv[0]-g.analysisUv[0],uv[1]-g.analysisUv[1]);best={id:g.id,score,uv,expectedUv:g.analysisUv,shiftN,source:t.source};}}}return best;}
function sample(g,w,h,cx,cy,n){const half=n>>1,x0=cx-half,y0=cy-half;if(x0<0||y0<0||x0+n>=w||y0+n>=h)return null;const out=new Uint8Array(n*n);for(let y=0;y<n;y++)for(let x=0;x<n;x++)out[y*n+x]=g[(y0+y)*w+x0+x];return out;}
function zncc(a,b){if(a.length!==b.length||!a.length)return -1;let ma=0,mb=0;for(let i=0;i<a.length;i++){ma+=a[i];mb+=b[i]}ma/=a.length;mb/=b.length;let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return n/(Math.sqrt(da*db)+1e-9);}
function average3(ps){if(!ps.length)return null;const s=[0,0,0];for(const p of ps)for(let i=0;i<3;i++)s[i]+=Number(p[i]);return s.map(v=>v/ps.length);}
function clonePose(p){return p?.p&&p?.q?{p:p.p.slice(0,3).map(Number),q:p.q.slice(0,4).map(Number)}:null;}
