import {BUILD,CONFIG} from './config.js';
import {DiagnosticLog,downloadBlob,installGlobalDiagnostics} from './logger.js';
import {V30Database} from './storage/db.js';
import {CameraSource} from './camera.js';
import {ImuTracker} from './imu.js';
import {WasmVisionFrontend} from './slam/wasm_frontend.js';
import {SlamEngine} from './slam/slam_engine.js';
import {GaussianRenderer} from './gaussian/renderer.js';
import {downloadPly,makeR30,parsePly,parseR30} from './formats.js';
import {runSelfTests} from './self_test.js';

const $=id=>document.getElementById(id),log=new DiagnosticLog();installGlobalDiagnostics(log);window.__roomscanV30Log=log;
let db=null,session=null,camera=null,imu=null,frontend=null,slam=null,gWorker=null,dWorker=null,renderer=null,currentSnapshot=null,scanRaf=0,lastAnalysisAt=0,scanning=false,deepEnabled=CONFIG.deepOnlineDefault,deepBusy=false,deepQueue=[],pendingDepth=new Map(),lastKeyframe=null,lastWorkerStats={count:0,totalObs:0},imuArchive=[],analysisErrorState={message:null,count:0,lastLogAt:0},sessionEpoch=0,lastSnapshotPersistAt=0,recoveredKeyframes=[],importedEntries=[],deferredDeep=false,deferredQueue=[],deferredDone=0,deferredTotal=0;

function setStatus(text,kind=''){const el=$('homeStatus');el.textContent=text;el.dataset.kind=kind;}
function showScreen(id){for(const s of document.querySelectorAll('.screen'))s.classList.toggle('active',s.id===id);log.info('screen',{id});}
function updateDiagPanel(){const out=$('diagLive');if(out)out.textContent=log.events.slice(-8).map(e=>`${new Date(e.time).toLocaleTimeString()} ${e.level.toUpperCase()} ${e.type}${e.data?.message?`: ${e.data.message}`:''}`).join('\n')||'Nessun evento.';}
log.subscribe(updateDiagPanel);log.subscribe(ev=>{if(db&&session)db.put('events',{id:`${session.id}:${String(ev.seq).padStart(8,'0')}`,sessionId:session.id,...ev}).catch(()=>{});});
function diagnosticsExtra(){return {build:BUILD,session,scan:{scanning,deepEnabled,deepBusy,deepQueue:deepQueue.length,deferredDeep,deferredDone,deferredTotal,gaussians:lastWorkerStats,slam:slam?.diagnostics?.()||null},capabilities:{mediaDevices:!!navigator.mediaDevices?.getUserMedia,indexedDB:!!indexedDB,webAssembly:typeof WebAssembly==='object',webGL2:!!document.createElement('canvas').getContext('webgl2'),webGPU:'gpu' in navigator,serviceWorker:'serviceWorker' in navigator}};}

async function bootstrap(){
  log.info('bootstrap-start',{build:BUILD.id});$('buildBadge').textContent=`V${BUILD.version} · STANDALONE WASM SLAM + GAUSSIANS`;$('buildFoot').textContent=BUILD.id;
  $('cameraHeight').addEventListener('input',e=>{$('heightLabel').textContent=`${Number(e.target.value).toFixed(2)} m`;});$('startBtn').addEventListener('click',startScan);$('finishBtn').addEventListener('click',finishScan);$('pinBtn').addEventListener('click',pinMarkpoint);$('pauseDeepBtn').addEventListener('click',toggleDeep);
  $('backHomeBtn').addEventListener('click',()=>showScreen('home'));$('orbitBtn').addEventListener('click',()=>renderer?.setMode('orbit'));$('panBtn').addEventListener('click',()=>renderer?.setMode('pan'));$('fitBtn').addEventListener('click',()=>renderer?.fit());$('splatSize').addEventListener('input',e=>{if(renderer){renderer.pointScale=Number(e.target.value);renderer.requestRender();}});
  $('loadPlyBtn').addEventListener('click',()=>$('filePly').click());$('filePly').addEventListener('change',loadPly);$('loadR30Btn').addEventListener('click',()=>$('fileR30').click());$('fileR30').addEventListener('change',loadR30);$('savedSessions').addEventListener('click',e=>{const b=e.target.closest('button[data-session-id]');if(b)void openSavedSession(b.dataset.sessionId);});
  $('exportPlyBtn').addEventListener('click',()=>{if(currentSnapshot)downloadPly(currentSnapshot,`roomscan-${session?.id||'loaded'}-gaussians.ply`);});$('processDeepBtn').addEventListener('click',startDeferredDeep);$('exportDiagBtn').addEventListener('click',()=>log.download(diagnosticsExtra()));$('diagDownloadBtn').addEventListener('click',()=>log.download(diagnosticsExtra()));$('diagCopyBtn').addEventListener('click',copyDiagnostics);$('selfTestBtn').addEventListener('click',runUiSelfTest);$('exportR30Btn').addEventListener('click',exportR30);$('resumeBtn').addEventListener('click',startScan);$('pauseDeepBtn').textContent=deepEnabled?'Deep live ON':'Deep live OFF';
  try{db=await new V30Database().open();log.info('indexeddb-ready');await refreshSavedSessions();}catch(err){log.error('indexeddb-open-failed',{message:err.message,stack:err.stack});setStatus(`IndexedDB non disponibile: ${err.message}`,'warn');}
  if('serviceWorker' in navigator)navigator.serviceWorker.register(CONFIG.serviceWorker).then(r=>log.info('service-worker-ready',{scope:r.scope})).catch(e=>log.warn('service-worker-failed',{message:e.message}));
  const missing=[];for(const path of ['js/app.js','js/slam/math.js',CONFIG.wasmCore,CONFIG.gaussianWorker,CONFIG.depthWorker])try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)missing.push(`${path} (${r.status})`);}catch(e){missing.push(`${path} (${e.message})`);}if(missing.length){log.error('preflight-assets-missing',{missing});setStatus(`Installazione incompleta: ${missing.join(', ')}`,'error');}else setStatus('Pronto. Premi “Avvia scansione”.','ok');
  document.documentElement.dataset.v30Ready='1';if(window.__ROOMSCAN_PREBOOT)window.__ROOMSCAN_PREBOOT.ready=true;log.info('bootstrap-complete',{missing});updateDiagPanel();
}

function resetCaptureRuntime(){sessionEpoch++;cancelAnimationFrame(scanRaf);gWorker?.terminate();dWorker?.terminate();gWorker=dWorker=null;camera?.stop();imu?.stop();camera=imu=frontend=slam=null;scanning=false;deepBusy=false;deepQueue=[];pendingDepth.clear();deferredDeep=false;deferredQueue=[];deferredDone=deferredTotal=0;lastKeyframe=null;lastAnalysisAt=0;analysisErrorState={message:null,count:0,lastLogAt:0};currentSnapshot=null;lastWorkerStats={count:0,totalObs:0};imuArchive=[];recoveredKeyframes=[];importedEntries=[];lastSnapshotPersistAt=0;}
async function startScan(){
  if(scanning)return;const btn=$('startBtn');btn.disabled=true;setStatus('Inizializzazione camera e SLAM…');
  try{resetCaptureRuntime();frontend=new WasmVisionFrontend(CONFIG.wasmCore);await frontend.init();slam=new SlamEngine(frontend,{cameraHeightM:Number($('cameraHeight').value),fovDeg:CONFIG.cameraFovDeg,keyframeIntervalMs:CONFIG.keyframeIntervalMs,minMetricConfidence:CONFIG.minimumMetricConfidence,relativeReferenceDepthL:CONFIG.relativeReferenceDepthL});imu=new ImuTracker();if(!session||session.status!=='capturing')session=db?await db.createSession({cameraHeightM:Number($('cameraHeight').value),status:'starting'}):{id:`volatile-${crypto.randomUUID()}`,createdAt:Date.now(),status:'starting',counts:{}};log.setSession(session.id);const epoch=sessionEpoch;setupWorkers(epoch);camera=new CameraSource($('camera'),{analysisWidth:CONFIG.analysisWidth,analysisHeight:CONFIG.analysisHeight});const camInfo=await camera.start();log.info('camera-started',camInfo);log.info('analysis-frame-config',{source:[camInfo.width,camInfo.height],analysis:[camInfo.analysis?.width,camInfo.analysis?.height],wasmLimits:frontend.limits});imu.start().then(ok=>log.info('imu-start',{ok,permission:imu.permission}));scanning=true;showScreen('scan');$('slamState').textContent='TRACK';$('deepState').textContent=deepEnabled?'Deep live avvio…':'Deep differito';session=await persistSession({status:'capturing',camera:camInfo});scanRaf=requestAnimationFrame(scanLoop);
  }catch(err){log.error('scan-start-failed',{message:err.message,stack:err.stack});await persistSession({status:'failed',error:err.message});setStatus(`Avvio fallito: ${err.message}`,'error');resetCaptureRuntime();showScreen('home');}finally{btn.disabled=false;}
}
function gaussianWorkerConfig(){return {voxel:CONFIG.gaussianVoxelM,maxGaussians:CONFIG.gaussianMaxLive,maxSnapshot:CONFIG.gaussianSnapshot,minDepth:CONFIG.gaussianMinDepthL,maxDepth:CONFIG.gaussianMaxDepthL};}
function setupWorkers(epoch){
  gWorker=new Worker(CONFIG.gaussianWorker);gWorker.onmessage=e=>{if(epoch===sessionEpoch)onGaussianMessage(e);};gWorker.onerror=e=>log.error('gaussian-worker-error',{message:e.message,filename:e.filename,line:e.lineno});gWorker.postMessage({type:'init',config:gaussianWorkerConfig()});
  if(deepEnabled)startDepthWorker(epoch);
}
function startDepthWorker(epoch){if(dWorker)return;dWorker=new Worker(CONFIG.depthWorker,{type:'module'});dWorker.onmessage=e=>{if(epoch===sessionEpoch)onDepthMessage(e);};dWorker.onerror=e=>{if(epoch!==sessionEpoch)return;deepBusy=false;pendingDepth.clear();deferredDeep=false;log.error('depth-worker-runtime-error',{message:e.message,filename:e.filename,line:e.lineno});$('deepState').textContent='Deep errore';};dWorker.postMessage({type:'init',config:{transformersRemote:CONFIG.transformersRemote,modelId:CONFIG.depthModelId}});}
function scanLoop(now){if(!scanning)return;if(now-lastAnalysisAt>=1000/CONFIG.analysisFps){lastAnalysisAt=now;try{const frame=camera.analysisFrame(now);if(frame){const analysis=slam.processAnalysis(frame,{motionScore:imu?.motionScore?.()||0});if(analysisErrorState.count){log.info('analysis-recovered',{previousMessage:analysisErrorState.message,suppressed:Math.max(0,analysisErrorState.count-1),frame:[frame.width,frame.height]});analysisErrorState={message:null,count:0,lastLogAt:0};}updateTrackingHud(analysis);drawMiniMap(analysis);if(analysis.keyframeDue)void captureKeyframe(analysis);}}catch(err){const msg=err?.message||String(err);analysisErrorState.count++;if(analysisErrorState.message!==msg||now-analysisErrorState.lastLogAt>3000){log.error('analysis-frame-failed',{message:msg,stack:err.stack,repeated:analysisErrorState.count,analysisSize:camera?.lastAnalysisSize,wasmLimits:frontend?.limits});analysisErrorState.message=msg;analysisErrorState.lastLogAt=now;}$('slamState').textContent='TRACK ERR';}}if(imu?.samples?.length>=180)void flushImu();scanRaf=requestAnimationFrame(scanLoop);}
function updateTrackingHud(a){$('statFeat').textContent=a.quality.features;$('statMatch').textContent=a.quality.matches;$('statLandmarks').textContent=slam.landmarks.size;$('statKf').textContent=slam.keyframes.length;const cal=slam.mapCalibration||slam.metricCalibration;$('metricState').textContent=cal?.relative?'scala L':cal?`scala ${Math.round((cal.confidence||0)*100)}%`:'scala attesa';const good=a.quality.matches>20;$('slamState').textContent=good?'TRACK':'CERCA';$('coach').textContent=good?'Cammina lentamente. Copri pavimento, pareti, soffitto e oggetti da più angoli.':'Punta verso zone con texture/contrasto e muovi lentamente il telefono.';}
function drawMiniMap(a){const c=$('miniMap'),dpr=Math.min(2,devicePixelRatio||1),w=c.clientWidth||innerWidth,h=c.clientHeight||innerHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle='rgba(30,255,180,.75)';const sx=w/a.K.width,sy=h/a.K.height;for(let i=0;i<a.features.count;i+=Math.max(1,Math.floor(a.features.count/220))){x.beginPath();x.arc(a.features.xs[i]*sx,a.features.ys[i]*sy,1.6,0,Math.PI*2);x.fill();}x.strokeStyle='rgba(255,255,255,.65)';x.beginPath();x.moveTo(w/2-8,h/2);x.lineTo(w/2+8,h/2);x.moveTo(w/2,h/2-8);x.lineTo(w/2,h/2+8);x.stroke();}
async function captureKeyframe(analysis){if(!scanning||slam.keyframes.length>=CONFIG.maxKeyframes||lastKeyframe&&performance.now()-lastKeyframe<CONFIG.keyframeIntervalMs*.75)return;lastKeyframe=performance.now();try{const f=await camera.keyframe();if(!scanning)return;const kf=slam.createKeyframeSnapshot(analysis,f);log.info('keyframe-captured',{id:kf.id,seq:kf.seq,size:f.blob.size});await persistKeyframe(kf);$('statKf').textContent=slam.keyframes.length;if(deepEnabled&&kf.seq%CONFIG.deepEveryNthKeyframe===0)queueDepth(kf);}catch(err){log.warn('keyframe-failed',{message:err.message,stack:err.stack});}}
async function persistKeyframe(kf){if(!db||!session)return;try{await db.put('keyframes',{id:`${session.id}:${kf.id}`,sessionId:session.id,...kf});session=await persistSession({counts:{...(session.counts||{}),keyframes:slam.keyframes.length,gaussians:lastWorkerStats.count||0}});}catch(err){log.error('keyframe-persist-failed',{message:err.message,stack:err.stack});}}
function queueDepth(kf){if(!scanning||!deepEnabled)return;if(deepQueue.length>=CONFIG.deepQueueMax){log.warn('deep-queue-drop',{kf:kf.id,queued:deepQueue.length});return;}deepQueue.push(kf);void pumpDepth();}
async function pumpDepth(){if(deepBusy||!deepEnabled||!scanning||!deepQueue.length||!dWorker)return;deepBusy=true;const kf=deepQueue.shift(),requestId=crypto.randomUUID();pendingDepth.set(requestId,kf);$('deepState').textContent=`Deep ${deepQueue.length+1}`;try{const jpeg=await kf.blob.arrayBuffer();if(!scanning||!dWorker){deepBusy=false;pendingDepth.delete(requestId);return;}dWorker.postMessage({type:'infer',requestId,frameId:kf.id,jpeg},[jpeg]);}catch(err){deepBusy=false;pendingDepth.delete(requestId);log.error('deep-submit-failed',{message:err.message});void pumpDepth();}}
function onDepthMessage(e){const m=e.data||{};if(m.type==='ready'){log.info('depth-worker-ready',{deferred:deferredDeep});$('deepState').textContent=deferredDeep?'Deep post pronto':'Deep live pronto';if(deferredDeep)void pumpDeferredDepth();return;}if(m.type==='diag'){log.push(m.level||'info',m.event||'depth-diag',{message:m.message});return;}if(m.type==='error'){deepBusy=false;const kf=pendingDepth.get(m.requestId);pendingDepth.delete(m.requestId);log.error('depth-inference-failed',{kf:kf?.id,provider:m.provider,message:m.message,stack:m.stack,deferred:deferredDeep});$('deepState').textContent='Deep errore';if(deferredDeep)void pumpDeferredDepth();else void pumpDepth();return;}if(m.type!=='depth')return;deepBusy=false;const kf=pendingDepth.get(m.requestId);pendingDepth.delete(m.requestId);if(!kf)return;if(deferredDeep){void integrateDeferredDepth(kf,m);return;}if(!scanning||!deepEnabled){void pumpDepth();return;}void integrateDepthResult(kf,m,()=>pumpDepth());}
async function integrateDepthResult(kf,m,next){try{const depth=new Float32Array(m.depth),rgb=new Uint8Array(m.rgb),integrated=slam.integrateDepth(kf,{depth,width:m.width,height:m.height});if(integrated.mappingAllowed&&gWorker){const cal=integrated.calibration,K={fx:kf.K.fx*m.width/kf.analysisWidth,fy:kf.K.fy*m.height/kf.analysisHeight,cx:m.width*.5,cy:m.height*.5,width:m.width,height:m.height};gWorker.postMessage({type:'integrate',frameId:kf.id,width:m.width,height:m.height,depth:depth.buffer,rgb:rgb.buffer,K,pose:kf.pose,calibration:cal,targetPoints:6500},[depth.buffer,rgb.buffer]);$('deepState').textContent=integrated.relative?`Deep ${m.provider} · scala L`:`Deep ${m.provider}`;}else $('deepState').textContent='Deep: profondità non valida';log.info('depth-integrated',{kf:kf.id,provider:m.provider,calibration:integrated.calibration,landmarksAdded:integrated.landmarksAdded,mappingAllowed:integrated.mappingAllowed,relative:integrated.relative,deferred:deferredDeep});}catch(err){log.error('depth-integration-failed',{message:err.message,stack:err.stack});}finally{next?.();}}
function onGaussianMessage(e){const m=e.data||{};if(m.type==='ready'){log.info('gaussian-worker-ready',m.config);return;}if(m.type==='error'){log.error('gaussian-worker-message-error',{message:m.message,stack:m.stack});return;}if(m.type==='snapshot'||m.type==='export'){currentSnapshot={data:new Float32Array(m.data),stride:m.stride||16,count:m.count||0};lastWorkerStats={count:m.count||0,totalObs:m.totalObs||0};$('statGs').textContent=lastWorkerStats.count;if(m.type==='snapshot')void persistSnapshot(false);if(document.getElementById('review').classList.contains('active'))renderer?.setData(currentSnapshot);}}
function setDeferredButton(busy=false){const b=$('processDeepBtn'),count=slam?.keyframes?.length||recoveredKeyframes.length;b.disabled=busy||!count;b.textContent=busy?`Deep post ${deferredDone}/${deferredTotal}`:'Elabora Deep dopo la scansione';}
function restoreDeferredEngine(){if(slam?.keyframes?.length)return slam;if(!recoveredKeyframes.length)return null;const stored=session?.slam?.metricCalibration,trustStored=stored?.confidence>=.45&&stored.source!=='carry';slam=new SlamEngine(null,{cameraHeightM:session?.cameraHeightM||Number($('cameraHeight').value),fovDeg:CONFIG.cameraFovDeg,keyframeIntervalMs:CONFIG.keyframeIntervalMs,minMetricConfidence:CONFIG.minimumMetricConfidence,relativeReferenceDepthL:CONFIG.relativeReferenceDepthL});slam.keyframes=recoveredKeyframes;slam.pose=session?.slam?.pose||slam.pose;slam.markpoints=session?.slam?.markpoints||[];slam.metricCalibration=trustStored?stored:null;log.info('deferred-engine-restored',{keyframes:slam.keyframes.length,storedCalibrationTrusted:trustStored});return slam;}
async function startDeferredDeep(){if(scanning||deferredDeep)return;const engine=restoreDeferredEngine();if(!engine?.keyframes?.length){setStatus('Questa sessione non contiene keyframe elaborabili; il RAW .r30 resta esportabile.','warn');return;}const all=engine.keyframes,limit=CONFIG.deferredDeepMaxKeyframes,step=Math.max(1,Math.ceil(all.length/limit));deferredQueue=all.filter((_,i)=>i%step===0);deferredTotal=deferredQueue.length;deferredDone=0;deferredDeep=true;deepBusy=false;pendingDepth.clear();currentSnapshot=null;lastWorkerStats={count:0,totalObs:0};const epoch=++sessionEpoch;gWorker?.terminate();dWorker?.terminate();gWorker=new Worker(CONFIG.gaussianWorker);gWorker.onmessage=e=>{if(epoch===sessionEpoch)onGaussianMessage(e);};gWorker.onerror=e=>log.error('gaussian-worker-error',{message:e.message,filename:e.filename,line:e.lineno});gWorker.postMessage({type:'init',config:gaussianWorkerConfig()});startDepthWorker(epoch);setDeferredButton(true);$('deepState').textContent='Deep post: carico modello…';$('reviewStats').textContent=`Deep post avviato: 0/${deferredTotal} keyframe. La scansione era già stata salvata.`;log.info('deferred-deep-started',{keyframes:deferredTotal,sourceKeyframes:all.length});}
async function pumpDeferredDepth(){if(!deferredDeep||deepBusy)return;if(!deferredQueue.length){await finishDeferredDeep();return;}if(!dWorker)return;deepBusy=true;const kf=deferredQueue.shift(),requestId=crypto.randomUUID();pendingDepth.set(requestId,kf);try{const jpeg=await kf.blob.arrayBuffer();if(!deferredDeep||!dWorker){deepBusy=false;pendingDepth.delete(requestId);return;}dWorker.postMessage({type:'infer',requestId,frameId:kf.id,jpeg},[jpeg]);}catch(e){deepBusy=false;pendingDepth.delete(requestId);log.error('deferred-deep-submit-failed',{message:e.message,kf:kf.id});void pumpDeferredDepth();}}
async function integrateDeferredDepth(kf,m){await integrateDepthResult(kf,m);deferredDone++;$('reviewStats').textContent=`Deep post ${deferredDone}/${deferredTotal} · ${lastWorkerStats.count||0} Gaussian`;setDeferredButton(true);void pumpDeferredDepth();}
async function finishDeferredDeep(){if(!deferredDeep)return;deferredDeep=false;setDeferredButton(true);try{await requestGaussianExport();await persistSnapshot(true);session=await persistSession({status:'completed',deepProcessedAt:Date.now(),counts:{...(session.counts||{}),keyframes:slam?.keyframes.length||0,gaussians:currentSnapshot?.count||0,imu:imuArchive.length},slam:slam?.diagnostics?.()||null});log.info('deferred-deep-complete',{keyframes:deferredDone,gaussians:currentSnapshot?.count||0});}catch(e){log.error('deferred-deep-finish-failed',{message:e.message,stack:e.stack});}finally{dWorker?.terminate();gWorker?.terminate();dWorker=gWorker=null;setDeferredButton(false);showReview();await refreshSavedSessions();}}
async function persistSnapshot(force){if(!db||!session||!currentSnapshot?.data)return;if(!force&&Date.now()-lastSnapshotPersistAt<CONFIG.snapshotPersistIntervalMs)return;lastSnapshotPersistAt=Date.now();try{const d=currentSnapshot.data;await db.put('snapshots',{id:session.id,sessionId:session.id,updatedAt:Date.now(),stride:currentSnapshot.stride,count:currentSnapshot.count,data:d.buffer.slice(d.byteOffset,d.byteOffset+d.byteLength)});}catch(e){log.warn('snapshot-persist-failed',{message:e.message});}}
function pinMarkpoint(){const r=slam?.pinCenter?.()||{ok:false,reason:'slam-not-ready'};if(r.ok){log.info('markpoint-created',r.mark);void persistSession({slam:slam.diagnostics(),markpointsUpdatedAt:Date.now()});$('coach').textContent=r.metric?`Repere metrico salvato (${r.mark.views} viste).`:'Repere visivo salvato: la profondità verrà associata durante l’elaborazione Deep.';}else{log.warn('markpoint-rejected',r);$('coach').textContent=`Repere non valido: ${r.reason}. Inquadra un dettaglio ad alto contrasto.`;}}
function toggleDeep(){deepEnabled=!deepEnabled;if(!deepEnabled){deepQueue=[];stopDepthPipeline();}else if(scanning){startDepthWorker(sessionEpoch);void pumpDepth();}$('pauseDeepBtn').textContent=deepEnabled?'Deep live ON':'Deep live OFF';$('deepState').textContent=deepEnabled?'Deep live attivo':'Deep differito';log.info('deep-toggle',{enabled:deepEnabled});}
async function flushImu(){const samples=imu?.drain?.()||[];if(!samples.length)return;imuArchive.push(...samples);if(imuArchive.length>30000)imuArchive.splice(0,5000);if(db&&session)try{await db.put('imu',{id:`${session.id}:${Date.now()}:${crypto.randomUUID()}`,sessionId:session.id,samples});}catch(e){log.warn('imu-persist-failed',{message:e.message});}}
function stopDepthPipeline(){deepQueue=[];pendingDepth.clear();deepBusy=false;dWorker?.terminate();dWorker=null;}
async function finishScan(){if(!scanning)return;$('finishBtn').disabled=true;log.info('finish-requested');try{scanning=false;cancelAnimationFrame(scanRaf);await flushImu();camera?.stop();imu?.stop();stopDepthPipeline();await requestGaussianExport();await persistSnapshot(true);session=await persistSession({status:'completed',counts:{...(session.counts||{}),keyframes:slam?.keyframes.length||0,gaussians:currentSnapshot?.count||0,imu:imuArchive.length},slam:slam?.diagnostics?.()||null});gWorker?.terminate();gWorker=null;await refreshSavedSessions();showReview();}catch(err){log.error('finish-failed',{message:err.message,stack:err.stack});showReview();}finally{$('finishBtn').disabled=false;}}
function requestGaussianExport(){return new Promise(resolve=>{const worker=gWorker;if(!worker)return resolve();let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(timer);worker.removeEventListener('message',handler);resolve();},timer=setTimeout(()=>{log.warn('gaussian-export-timeout');finish();},4000),handler=e=>{if(e.data?.type==='export')finish();};worker.addEventListener('message',handler);worker.postMessage({type:'export'});});}
function showReview(){showScreen('review');try{if(!renderer)renderer=new GaussianRenderer($('viewer'));if(currentSnapshot)renderer.setData(currentSnapshot);renderer.requestRender();$('reviewStats').textContent=`${currentSnapshot?.count||0} Gaussian · ${slam?.keyframes.length||recoveredKeyframes.length||0} keyframe · ${slam?.landmarks.size||0} landmark · ${slam?.markpoints.length||0} repere`;setDeferredButton(deferredDeep);}catch(e){log.error('review-renderer-failed',{message:e.message,stack:e.stack});$('reviewStats').textContent=`${currentSnapshot?.count||0} Gaussian disponibili, ma la preview GPU non è utilizzabile.`;}}
async function persistSession(patch){if(!session)return null;Object.assign(session,patch,{updatedAt:Date.now()});if(db)try{session=await db.updateSession(session.id,patch);}catch(e){log.warn('session-persist-failed',{message:e.message});}return session;}
async function refreshSavedSessions(){if(!db)return;const sessions=(await db.getAll('sessions')).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,8),el=$('savedSessions');el.replaceChildren();if(!sessions.length){el.innerHTML='<span class="muted">Nessuna sessione V30 salvata.</span>';return;}for(const s of sessions){const row=document.createElement('div'),info=document.createElement('span'),id=document.createElement('b'),meta=document.createElement('small'),counts=document.createElement('span'),open=document.createElement('button');row.className='savedRow';id.textContent=s.id.slice(0,12);meta.textContent=`${new Date(s.updatedAt).toLocaleString()} · ${s.status||'?'}`;info.append(id,meta);counts.textContent=`${s.counts?.keyframes||0} KF · ${s.counts?.gaussians||0} GS`;open.textContent='Apri';open.dataset.sessionId=s.id;row.append(info,counts,open);el.append(row);}}
async function openSavedSession(id){if(!db)return;try{const b=await db.loadSessionBundle(id);if(!b.session)throw new Error('sessione non trovata');session={...b.session,status:'loaded'};recoveredKeyframes=b.keyframes.map(k=>({...k,id:k.kfId||k.id?.split(':').at(-1)}));imuArchive=b.imu.flatMap(x=>x.samples||[]);importedEntries=[];if(b.snapshot?.data){const a=b.snapshot.data instanceof ArrayBuffer?b.snapshot.data:b.snapshot.data.buffer;currentSnapshot={data:new Float32Array(a),stride:b.snapshot.stride||16,count:b.snapshot.count||0};}else currentSnapshot=null;log.setSession(session.id);log.info('saved-session-opened',{id,keyframes:recoveredKeyframes.length,gaussians:currentSnapshot?.count||0});showReview();}catch(err){log.error('saved-session-open-failed',{id,message:err.message});setStatus(`Impossibile aprire la sessione: ${err.message}`,'error');}}
async function loadPly(e){const file=e.target.files?.[0];if(!file)return;try{resetCaptureRuntime();const snap=await parsePly(file);session={id:`ply-${file.name}`,status:'loaded',counts:{gaussians:snap.count}};currentSnapshot=snap;log.setSession(session.id);log.info('ply-loaded',{name:file.name,count:snap.count,size:file.size});showReview();}catch(err){log.error('ply-load-failed',{message:err.message});setStatus(`PLY non valido: ${err.message}`,'error');}finally{e.target.value='';}}
async function loadR30(e){const file=e.target.files?.[0];if(!file)return;try{resetCaptureRuntime();const r=await parseR30(file);session={...(r.meta.session||r.meta),id:r.meta.id||r.meta.session?.id||`r30-${file.name}`,status:'loaded'};currentSnapshot=r.gaussians;recoveredKeyframes=r.keyframes;imuArchive=r.imu;importedEntries=Object.entries(r.entries).filter(([name])=>name!=='map/gaussians.f32'&&(r.keyframes.length?!name.startsWith('keyframes/'):true)).map(([name,blob])=>({name,blob}));log.setSession(session.id);log.info('r30-loaded',{name:file.name,entries:Object.keys(r.entries).length,keyframes:r.keyframes.length,gaussians:r.gaussians?.count||0});showReview();}catch(err){log.error('r30-load-failed',{message:err.message});setStatus(`R30 non valido: ${err.message}`,'error');}finally{e.target.value='';}}
async function exportR30(){if(!session)return;try{const keyframes=slam?.keyframes?.length?slam.keyframes:recoveredKeyframes,blob=makeR30({manifest:{id:session.id,build:BUILD,session,slam:slam?.diagnostics?.()||session.slam||null},keyframes,gaussians:currentSnapshot,imu:imuArchive,extraEntries:importedEntries});downloadBlob(blob,`roomscan-${session.id}.r30`);log.info('r30-exported',{bytes:blob.size,keyframes:keyframes.length});}catch(e){log.error('r30-export-failed',{message:e.message,stack:e.stack});setStatus(`Export R30 fallito: ${e.message}`,'error');}}
async function copyDiagnostics(){try{await navigator.clipboard.writeText(JSON.stringify(log.snapshot(diagnosticsExtra()),null,2));log.info('diagnostics-copied');}catch(e){log.warn('diagnostics-copy-failed',{message:e.message});}}
async function runUiSelfTest(){const b=$('selfTestBtn');b.disabled=true;b.textContent='Test…';$('selfTestSummary').textContent='Self-test in corso…';try{const r=await runSelfTests(log);$('selfTestSummary').textContent=r.tests.map(t=>`${t.ok?'PASS':'FAIL'} ${t.name}${t.ok?'':`: ${t.error}`}`).join(' · ');}finally{b.textContent='Esegui self-test';b.disabled=false;}}
window.addEventListener('pagehide',()=>{if(scanning){void flushImu();void persistSnapshot(true);void persistSession({status:'interrupted',interruptedAt:Date.now()});}});
bootstrap().catch(err=>{log.error('bootstrap-fatal',{message:err.message,stack:err.stack});setStatus(`BOOTSTRAP FATAL: ${err.message}`,'error');document.documentElement.dataset.bootstrap='failed';});
