import {BUILD,CONFIG} from './config.js';
import {DiagnosticLog,downloadBlob,installGlobalDiagnostics} from './logger.js';
import {V30Database} from './storage/db.js';
import {CameraSource} from './camera.js';
import {WasmVisionFrontend} from './slam/wasm_frontend.js';
import {SlamEngine} from './slam/slam_engine.js';
import {qAngle} from './slam/math.js';
import {XRMetricCalibrator} from './xr/xr_calibration.js';
import {bridgeMetricPose} from './xr/metric_bridge.js';
import {GaussianRenderer} from './gaussian/renderer.js';
import {downloadPly,makeR30,parsePly,parseR30} from './formats.js';
import {runSelfTests} from './self_test.js';

const $=id=>document.getElementById(id),log=new DiagnosticLog();installGlobalDiagnostics(log);window.__roomscanV30Log=log;
let db=null,session=null,camera=null,frontend=null,slam=null,calibrator=null,calibration=null,gWorker=null,mvsWorker=null,renderer=null,currentSnapshot=null,scanRaf=0,bridgeRaf=0,lastAnalysisAt=0,scanning=false,lastKeyframeAt=0,lastWorkerStats={count:0,totalObs:0},analysisErrorState={message:null,count:0,lastLogAt:0},mvsBusy=false,mvsQueue=[],mvsStats={pairs:0,points:0,triangles:0,rejected:0},meshChunks=[];

function setStatus(text,kind=''){const el=$('homeStatus');if(el){el.textContent=text;el.dataset.kind=kind;}}
function showScreen(id){for(const s of document.querySelectorAll('.screen'))s.classList.toggle('active',s.id===id);log.info('screen',{id});}
function updateDiagPanel(){const out=$('diagLive');if(!out)return;out.textContent=log.events.slice(-10).map(e=>`${new Date(e.time).toLocaleTimeString()} ${e.level.toUpperCase()} ${e.type}${e.data?.message?`: ${e.data.message}`:''}`).join('\n')||'Nessun evento.';}
log.subscribe(updateDiagPanel);log.subscribe(ev=>{if(db&&session)db.put('events',{id:`${session.id}:${String(ev.seq).padStart(8,'0')}`,sessionId:session.id,...ev}).catch(()=>{});});
function diagnosticsExtra(){return {build:BUILD,session,calibration:calibration?{createdAt:calibration.createdAt,anchors:calibration.anchors?.length,quality:calibration.quality,cameraSize:calibration.cameraSize}:null,scan:{scanning,gaussians:lastWorkerStats,mvs:mvsStats,mvsQueue:mvsQueue.length,mvsBusy,meshChunks:meshChunks.length,slam:slam?.diagnostics?.()||null},capabilities:{mediaDevices:!!navigator.mediaDevices?.getUserMedia,indexedDB:!!indexedDB,webAssembly:typeof WebAssembly==='object',webGL2:!!document.createElement('canvas').getContext('webgl2'),webXR:!!navigator.xr,serviceWorker:'serviceWorker' in navigator}};}

async function bootstrap(){
  log.info('bootstrap-start',{build:BUILD.id});$('buildBadge').textContent=`V${BUILD.version} · WEBXR METRIC → CAMERA SLAM + GS`;$('buildFoot').textContent=BUILD.id;
  bindUi();loadCalibration();
  try{db=await new V30Database().open();log.info('indexeddb-ready');await refreshSavedSessions();}catch(err){log.error('indexeddb-open-failed',{message:err.message,stack:err.stack});setStatus(`IndexedDB non disponibile: ${err.message}`,'warn');}
  await registerServiceWorker();
  const assets=['js/app.js','js/slam/math.js','js/xr/xr_calibration.js','js/xr/metric_bridge.js',CONFIG.wasmCore,CONFIG.gaussianWorker,CONFIG.mvsWorker,'styles.css','build_info.json'],missing=[];
  for(const path of assets){try{const r=await fetch(`${path}?preflight=${Date.now()}`,{cache:'no-store'});if(!r.ok)missing.push(`${path} (${r.status})`);}catch(e){missing.push(`${path} (${e.message})`);}}
  if(missing.length){log.error('preflight-assets-missing',{missing});setStatus(`Installazione incompleta: ${missing.join(', ')}`,'error');}else setStatus(calibration?'Calibrazione presente. Puoi avviare la scansione camera-only.':'Pronto. Esegui prima la calibrazione WebXR.','ok');
  await checkPublishedBuild();document.documentElement.dataset.v30Ready='1';if(window.__ROOMSCAN_PREBOOT)window.__ROOMSCAN_PREBOOT.ready=true;log.info('bootstrap-complete',{missing,calibration:!!calibration});updateDiagPanel();
}
function bindUi(){
  $('calibrateBtn').addEventListener('click',startCalibration);$('clearCalibrationBtn').addEventListener('click',clearCalibration);$('calibFinishBtn').addEventListener('click',finishCalibration);$('calibCancelBtn').addEventListener('click',cancelCalibration);
  $('startBtn').addEventListener('click',startScan);$('bridgeRetryBtn').addEventListener('click',()=>startBridgeLoop(true));$('bridgeCancelBtn').addEventListener('click',cancelScanStart);$('finishBtn').addEventListener('click',finishScan);$('pinBtn').addEventListener('click',pinMarkpoint);
  $('backHomeBtn').addEventListener('click',()=>showScreen('home'));$('orbitBtn').addEventListener('click',()=>renderer?.setMode('orbit'));$('panBtn').addEventListener('click',()=>renderer?.setMode('pan'));$('fitBtn').addEventListener('click',()=>renderer?.fit());$('splatSize').addEventListener('input',e=>{if(renderer){renderer.pointScale=Number(e.target.value);renderer.requestRender();}});
  $('loadPlyBtn').addEventListener('click',()=>$('filePly').click());$('filePly').addEventListener('change',loadPly);$('loadR30Btn').addEventListener('click',()=>$('fileR30').click());$('fileR30').addEventListener('change',loadR30);
  $('exportPlyBtn').addEventListener('click',()=>{if(currentSnapshot)downloadPly(currentSnapshot,`roomscan-${session?.id||'loaded'}-gaussians.ply`);});$('exportR30Btn').addEventListener('click',exportR30);$('exportDiagBtn').addEventListener('click',()=>log.download(diagnosticsExtra()));$('diagDownloadBtn').addEventListener('click',()=>log.download(diagnosticsExtra()));$('diagCopyBtn').addEventListener('click',copyDiagnostics);$('selfTestBtn').addEventListener('click',runUiSelfTest);$('forceUpdateBtn').addEventListener('click',forceUpdate);$('diagForceUpdateBtn').addEventListener('click',forceUpdate);$('resumeBtn').addEventListener('click',()=>{showScreen('home');setStatus('Pronto per una nuova scansione.','ok');});
}
function loadCalibration(){try{const raw=localStorage.getItem(CONFIG.calibrationStorageKey);calibration=raw?JSON.parse(raw):null;if(calibration?.format!=='ROOMSCAN-V30-XR-CALIBRATION-1')calibration=null;}catch{calibration=null;}updateCalibrationHome();}
function updateCalibrationHome(){const n=calibration?.anchors?.length||0,q=calibration?.quality;$('calibSummary').textContent=calibration?`Calibrata: ${n} riferimenti · span ${(q?.span||0).toFixed(2)} m · verticale ${(q?.vertical||0).toFixed(2)} m`:'Calibrazione non presente.';$('startBtn').disabled=!calibration;}
function clearCalibration(){localStorage.removeItem(CONFIG.calibrationStorageKey);calibration=null;updateCalibrationHome();log.info('xr-calibration-cleared');setStatus('Calibrazione azzerata.','ok');}

async function startCalibration(){
  $('calibrateBtn').disabled=true;showScreen('calibration');$('calibCoach').textContent='Muovi lentamente il telefono inquadrando pavimento e due pareti con dettagli fermi.';
  try{calibrator=new XRMetricCalibrator({overlayRoot:$('calibration'),config:CONFIG,log});calibrator.addEventListener('progress',e=>updateCalibrationProgress(e.detail));calibrator.addEventListener('ended',()=>log.info('xr-calibration-session-ended'));await calibrator.start();}
  catch(err){log.error('xr-calibration-start-failed',{message:err.message,stack:err.stack});setStatus(`Calibrazione WebXR fallita: ${err.message}`,'error');showScreen('home');}
  finally{$('calibrateBtn').disabled=false;}
}
function updateCalibrationProgress(q){$('calibAnchors').textContent=`${q.count}/${q.target}`;$('calibSpan').textContent=`${q.span.toFixed(2)} m`;$('calibVertical').textContent=`${q.vertical.toFixed(2)} m`;$('calibBar').style.width=`${Math.min(100,q.count/q.target*100)}%`;$('calibFinishBtn').disabled=!q.ready;$('calibCoach').textContent=q.ready?'Calibrazione sufficiente. Puoi confermare.':'Cerca più parallasse: includi pavimento e parti alte delle pareti, mantenendo in vista dettagli fermi.';}
async function finishCalibration(){const b=$('calibFinishBtn');b.disabled=true;try{calibration=await calibrator.finish();localStorage.setItem(CONFIG.calibrationStorageKey,JSON.stringify(calibration));log.info('xr-calibration-saved',{anchors:calibration.anchors.length,quality:calibration.quality});updateCalibrationHome();showScreen('home');setStatus('Calibrazione metrica salvata. Ora puoi avviare la scansione.','ok');}catch(err){log.warn('xr-calibration-not-ready',{message:err.message});$('calibCoach').textContent=err.message;}finally{b.disabled=false;calibrator=null;}}
async function cancelCalibration(){try{await calibrator?.stop();}catch{}calibrator=null;showScreen('home');setStatus('Calibrazione annullata.','warn');}

async function startScan(){
  if(!calibration){setStatus('Serve prima una calibrazione WebXR.','warn');return;}const b=$('startBtn');b.disabled=true;setStatus('Inizializzazione WASM, camera e worker…');
  try{frontend=new WasmVisionFrontend(CONFIG.wasmCore);await frontend.init();slam=new SlamEngine(frontend,{fovDeg:CONFIG.cameraFovDeg,keyframeIntervalMs:CONFIG.keyframeIntervalMs,intrinsicsNorm:calibration.intrinsicsNorm});session=db?await db.createSession({status:'starting',calibrationCreatedAt:calibration.createdAt}):{id:`volatile-${crypto.randomUUID()}`,createdAt:Date.now(),status:'starting',counts:{}};log.setSession(session.id);setupWorkers();camera=new CameraSource($('bridgeCamera'),{analysisWidth:CONFIG.analysisWidth,analysisHeight:CONFIG.analysisHeight});const camInfo=await camera.start();log.info('camera-started',camInfo);log.info('analysis-frame-config',{source:[camInfo.width,camInfo.height],analysis:[camInfo.analysis?.width,camInfo.analysis?.height],wasmLimits:frontend.limits,intrinsicsNorm:calibration.intrinsicsNorm});showScreen('bridge');session=await persistSession({status:'metric-bridge',camera:camInfo,calibration:{createdAt:calibration.createdAt,anchors:calibration.anchors.length,quality:calibration.quality}});startBridgeLoop(true);}catch(err){log.error('scan-start-failed',{message:err.message,stack:err.stack});cleanupCapture();showScreen('home');setStatus(`Avvio fallito: ${err.message}`,'error');}finally{b.disabled=false;}}
function setupWorkers(){gWorker?.terminate();mvsWorker?.terminate();gWorker=new Worker(CONFIG.gaussianWorker);gWorker.onmessage=onGaussianMessage;gWorker.onerror=e=>log.error('gaussian-worker-error',{message:e.message,filename:e.filename,line:e.lineno});gWorker.postMessage({type:'init',config:{voxel:CONFIG.gaussianVoxelM,maxGaussians:CONFIG.gaussianMaxLive,maxSnapshot:CONFIG.gaussianSnapshot}});mvsWorker=new Worker(CONFIG.mvsWorker);mvsWorker.onmessage=onMvsMessage;mvsWorker.onerror=e=>{mvsBusy=false;log.error('mvs-worker-error',{message:e.message,filename:e.filename,line:e.lineno});pumpMvs();};mvsWorker.postMessage({type:'init',config:{near:CONFIG.mvsNearM,far:CONFIG.mvsFarM,depthSteps:CONFIG.mvsDepthSteps,gridStep:CONFIG.mvsGridStep,maxPoints:CONFIG.mvsMaxPoints}});}
function startBridgeLoop(reset=false){if(reset){cancelAnimationFrame(bridgeRaf);$('bridgeCoach').textContent='Ripunta la vista finale della calibrazione. Cerco i template metrici…';}let last=0,attempts=0;const loop=now=>{if(!camera||scanning)return;if(now-last>160){last=now;try{const frame=camera.analysisFrame(now);if(frame){const analysis=slam.processAnalysis(frame),r=bridgeMetricPose({calibration,frame,analysis,frontend});attempts++;$('bridgeFound').textContent=r.found?.length||0;$('bridgeInliers').textContent=r.inliers||0;$('bridgeRmse').textContent=Number.isFinite(r.rmse)?`${r.rmse.toFixed(2)} px`:'—';drawBridge(r,frame);if(r.ok){log.info('metric-bridge-success',{attempts,found:r.found.length,inliers:r.inliers,rmse:r.rmse,bindings:r.bindings.length});const seed=slam.seedMetricFromWebXR({pose:r.pose,analysis,bindings:r.bindings,rmse:r.rmse,inliers:r.inliers,calibrationId:calibration.createdAt});seedCalibrationGaussians(r.bindings,r.pose,frame);handoffCameraToScan();scanning=true;lastAnalysisAt=0;showScreen('scan');session&&persistSession({status:'capturing',metricBridge:{inliers:r.inliers,rmse:r.rmse,bindings:r.bindings.length}});scanRaf=requestAnimationFrame(scanLoop);return;}if(attempts%8===0)log.info('metric-bridge-progress',{attempts,found:r.found?.length||0,inliers:r.inliers||0,rmse:r.rmse,reason:r.reason});$('bridgeCoach').textContent=r.reason==='few-visual-anchors'?'Non riconosco abbastanza riferimenti: torna più vicino alla vista usata in WebXR.':'Riferimenti trovati ma posa non ancora stabile. Mantieni il telefono fermo un istante.';}}catch(err){log.warn('metric-bridge-attempt-failed',{message:err.message});}}bridgeRaf=requestAnimationFrame(loop);};bridgeRaf=requestAnimationFrame(loop);}
function drawBridge(r,frame){const c=$('bridgeMap'),dpr=Math.min(2,devicePixelRatio||1),w=c.clientWidth||innerWidth,h=c.clientHeight||innerHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);const sx=w/frame.width,sy=h/frame.height;x.fillStyle='rgba(102,240,189,.9)';for(const f of r.found||[]){x.beginPath();x.arc(f.u*sx,f.v*sy,5,0,Math.PI*2);x.fill();}x.strokeStyle='rgba(255,255,255,.8)';x.strokeRect(w/2-12,h/2-12,24,24);}
function seedCalibrationGaussians(bindings,pose,frame){const rgb=camera.analysisRgb();if(!rgb||!bindings?.length)return;const out=new Float32Array(bindings.length*10);for(let i=0;i<bindings.length;i++){const b=bindings[i],o=i*10,p=b.anchor.p,dx=pose.p[0]-p[0],dy=pose.p[1]-p[1],dz=pose.p[2]-p[2],dn=Math.hypot(dx,dy,dz)||1,ix=Math.max(0,Math.min(frame.width-1,Math.round(b.u))),iy=Math.max(0,Math.min(frame.height-1,Math.round(b.v))),ci=(iy*frame.width+ix)*3;out[o]=p[0];out[o+1]=p[1];out[o+2]=p[2];out[o+3]=dx/dn;out[o+4]=dy/dn;out[o+5]=dz/dn;out[o+6]=rgb[ci];out[o+7]=rgb[ci+1];out[o+8]=rgb[ci+2];out[o+9]=1;}gWorker.postMessage({type:'integratePoints',frameId:'webxr-seed',stride:10,points:out.buffer},[out.buffer]);}
function handoffCameraToScan(){const v=$('camera');v.srcObject=camera.stream;v.play().catch(()=>{});camera.video=v;log.info('camera-handoff-to-slam');}
function cancelScanStart(){cancelAnimationFrame(bridgeRaf);cleanupCapture();session&&persistSession({status:'cancelled-before-scan'});showScreen('home');setStatus('Avvio scansione annullato.','warn');}

function scanLoop(now){if(!scanning)return;if(now-lastAnalysisAt>=1000/CONFIG.analysisFps){lastAnalysisAt=now;try{const frame=camera.analysisFrame(now);if(frame){const analysis=slam.processAnalysis(frame);if(analysisErrorState.count){log.info('analysis-recovered',{previousMessage:analysisErrorState.message,suppressed:Math.max(0,analysisErrorState.count-1),frame:[frame.width,frame.height]});analysisErrorState={message:null,count:0,lastLogAt:0};}updateTrackingHud(analysis);drawMiniMap(analysis);if(analysis.keyframeDue)void captureKeyframe(analysis,frame);}}catch(err){const msg=err?.message||String(err);analysisErrorState.count++;const changed=analysisErrorState.message!==msg,due=now-analysisErrorState.lastLogAt>3000;if(changed||due){log.error('analysis-frame-failed',{message:msg,stack:err.stack,repeated:analysisErrorState.count,analysisSize:camera?.lastAnalysisSize,wasmLimits:frontend?.limits});analysisErrorState.message=msg;analysisErrorState.lastLogAt=now;}$('slamState').textContent='TRACK ERR';}}scanRaf=requestAnimationFrame(scanLoop);}
function updateTrackingHud(a){$('statFeat').textContent=a.quality.features;$('statMatch').textContent=a.quality.matches;$('statLandmarks').textContent=slam.landmarks.size;$('statKf').textContent=slam.keyframes.length;$('metricState').textContent=slam.metricCalibration?`metrico ${Math.round((slam.metricCalibration.confidence||0)*100)}%`:'scala persa';const good=a.quality.inliers>=8||a.quality.matches>24;$('slamState').textContent=good?'TRACK':'CERCA';$('mvsState').textContent=mvsBusy?`MVS ${mvsQueue.length+1}`:`MVS ${mvsStats.pairs}`;$('coach').textContent=good?'Cammina lentamente e crea parallasse. Guarda pavimento, pareti, soffitto e oggetti da più lati.':'Tracking debole: torna verso dettagli già visti e muovi più lentamente.';}
function drawMiniMap(a){const c=$('miniMap'),dpr=Math.min(2,devicePixelRatio||1),w=c.clientWidth||innerWidth,h=c.clientHeight||innerHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle='rgba(30,255,180,.75)';const sx=w/a.K.width,sy=h/a.K.height;for(let i=0;i<a.features.count;i+=Math.max(1,Math.floor(a.features.count/260))){x.beginPath();x.arc(a.features.xs[i]*sx,a.features.ys[i]*sy,1.5,0,Math.PI*2);x.fill();}x.strokeStyle='rgba(255,255,255,.65)';x.beginPath();x.moveTo(w/2-8,h/2);x.lineTo(w/2+8,h/2);x.moveTo(w/2,h/2-8);x.lineTo(w/2,h/2+8);x.stroke();}

async function captureKeyframe(analysis,frame){if(!scanning||slam.keyframes.length>=CONFIG.maxKeyframes)return;if(performance.now()-lastKeyframeAt<CONFIG.keyframeIntervalMs*.72)return;lastKeyframeAt=performance.now();try{const rgb=camera.analysisRgb();if(!rgb)return;const f=await camera.keyframe(),kf=slam.createKeyframeSnapshot(analysis,f,{analysisGray:frame.gray,analysisRgb:rgb});log.info('keyframe-captured',{id:kf.id,seq:kf.seq,size:f.blob.size,pose:kf.pose});await persistKeyframe(kf);integrateSparseLandmarks(kf);scheduleMvs(kf);$('statKf').textContent=slam.keyframes.length;}catch(err){log.warn('keyframe-failed',{message:err.message,stack:err.stack});}}
function integrateSparseLandmarks(kf){const rows=[];for(let i=0;i<kf.trackIds.length;i++){const lm=slam.landmarks.get(kf.trackIds[i]);if(!lm)continue;const x=Math.round(kf.featureX[i]),y=Math.round(kf.featureY[i]);if(x<0||y<0||x>=kf.analysisWidth||y>=kf.analysisHeight)continue;const ci=(y*kf.analysisWidth+x)*3,p=lm.p,dx=kf.pose.p[0]-p[0],dy=kf.pose.p[1]-p[1],dz=kf.pose.p[2]-p[2],n=Math.hypot(dx,dy,dz)||1;rows.push(p[0],p[1],p[2],dx/n,dy/n,dz/n,kf.analysisRgb[ci]||128,kf.analysisRgb[ci+1]||128,kf.analysisRgb[ci+2]||128,Math.min(1,.35+(lm.views||1)*.1));if(rows.length>=12000)break;}if(rows.length){const out=Float32Array.from(rows);gWorker.postMessage({type:'integratePoints',frameId:`sparse:${kf.id}`,stride:10,points:out.buffer},[out.buffer]);}}
function scheduleMvs(kf){if(kf.seq<1||kf.seq%CONFIG.mvsEveryNthKeyframe!==0||!kf.analysisGray||!kf.analysisRgb)return;let ref=null;for(let i=slam.keyframes.length-2;i>=0;i--){const c=slam.keyframes[i],b=Math.hypot(kf.pose.p[0]-c.pose.p[0],kf.pose.p[1]-c.pose.p[1],kf.pose.p[2]-c.pose.p[2]),a=qAngle(kf.pose.q,c.pose.q);if(b>=CONFIG.mvsMinBaselineM&&b<=CONFIG.mvsMaxBaselineM&&a<=CONFIG.mvsMaxAngleRad&&c.analysisGray&&c.analysisRgb){ref=c;break;}}if(!ref)return;const job={pairId:`${ref.id}:${kf.id}`,ref,cur:kf};if(mvsQueue.length>=3){mvsQueue.shift();mvsStats.rejected++;log.warn('mvs-queue-drop',{queued:mvsQueue.length});}mvsQueue.push(job);pumpMvs();}
function pumpMvs(){if(mvsBusy||!mvsQueue.length||!mvsWorker)return;const j=mvsQueue.shift();mvsBusy=true;const pack=k=>({id:k.id,width:k.analysisWidth,height:k.analysisHeight,K:k.K,pose:k.pose,gray:k.analysisGray.slice().buffer,rgb:k.analysisRgb.slice().buffer});const ref=pack(j.ref),cur=pack(j.cur);mvsWorker.postMessage({type:'pair',pairId:j.pairId,ref,cur,config:{near:CONFIG.mvsNearM,far:CONFIG.mvsFarM,depthSteps:CONFIG.mvsDepthSteps,gridStep:CONFIG.mvsGridStep,maxPoints:CONFIG.mvsMaxPoints}},[ref.gray,ref.rgb,cur.gray,cur.rgb]);$('mvsState').textContent=`MVS ${mvsQueue.length+1}`;}
function onMvsMessage(e){const m=e.data||{};if(m.type==='ready'){log.info('mvs-worker-ready',m.config);return;}if(m.type==='error'){mvsBusy=false;log.error('mvs-pair-error',{pairId:m.pairId,message:m.message,stack:m.stack});pumpMvs();return;}if(m.type==='result'){mvsBusy=false;mvsStats.pairs++;mvsStats.points+=m.pointCount||0;mvsStats.triangles+=m.triangleCount||0;$('statTri').textContent=mvsStats.triangles;log.info('mvs-pair-complete',{pairId:m.pairId,points:m.pointCount,triangles:m.triangleCount,stats:m.stats});if(m.pointCount){gWorker.postMessage({type:'integratePoints',frameId:`mvs:${m.pairId}`,stride:m.stride||10,points:m.points},[m.points]);if(m.triangleCount){meshChunks.push({pairId:m.pairId,vertices:new Float32Array(m.meshVertices),indices:new Uint32Array(m.meshIndices)});while(meshChunks.reduce((s,c)=>s+c.indices.length/3,0)>160000)meshChunks.shift();}}pumpMvs();}}
function onGaussianMessage(e){const m=e.data||{};if(m.type==='ready'){log.info('gaussian-worker-ready',m.config);return;}if(m.type==='error'){log.error('gaussian-worker-message-error',{message:m.message,stack:m.stack});return;}if(m.type==='snapshot'||m.type==='export'){currentSnapshot={data:new Float32Array(m.data),stride:m.stride||16,count:m.count||0};lastWorkerStats={count:m.count||0,totalObs:m.totalObs||0};$('statGs').textContent=lastWorkerStats.count;if($('review').classList.contains('active')){ensureRenderer();renderer.setData(currentSnapshot);}}}
function pinMarkpoint(){const r=slam?.pinCenter?.()||{ok:false,reason:'slam-not-ready'};if(r.ok){log.info('markpoint-created',r.mark);$('coach').textContent=`Repere metrico salvato (${r.mark.views} viste).`;}else{log.warn('markpoint-rejected',r);$('coach').textContent=`Repere non valido: ${r.reason}. Ripunta un dettaglio già triangolato.`;}}

async function finishScan(){if(!scanning)return;$('finishBtn').disabled=true;log.info('finish-requested');try{scanning=false;cancelAnimationFrame(scanRaf);camera?.stop();await drainMvs(2200);await requestGaussianExport();session=await persistSession({status:'completed',counts:{...(session.counts||{}),keyframes:slam?.keyframes.length||0,gaussians:currentSnapshot?.count||0,triangles:mvsStats.triangles},slam:slam?.diagnostics?.()||null,mvs:mvsStats});showReview();}catch(err){log.error('finish-failed',{message:err.message,stack:err.stack});showReview();}finally{$('finishBtn').disabled=false;}}
async function drainMvs(timeoutMs){const t=performance.now();while((mvsBusy||mvsQueue.length)&&performance.now()-t<timeoutMs)await new Promise(r=>setTimeout(r,60));}
function requestGaussianExport(){return new Promise(resolve=>{if(!gWorker)return resolve();const timer=setTimeout(resolve,1600),handler=e=>{if(e.data?.type==='export'){clearTimeout(timer);gWorker.removeEventListener('message',handler);resolve();}};gWorker.addEventListener('message',handler);gWorker.postMessage({type:'export'});});}
function cleanupCapture(){scanning=false;cancelAnimationFrame(scanRaf);cancelAnimationFrame(bridgeRaf);camera?.stop();gWorker?.terminate();mvsWorker?.terminate();camera=null;gWorker=null;mvsWorker=null;}
function ensureRenderer(){if(!renderer)renderer=new GaussianRenderer($('viewer'));}
function showReview(){showScreen('review');ensureRenderer();if(currentSnapshot)renderer.setData(currentSnapshot);$('reviewStats').innerHTML=`<b>${currentSnapshot?.count||0}</b> Gaussian · <b>${slam?.keyframes.length||0}</b> keyframe · <b>${slam?.landmarks.size||0}</b> landmark · <b>${mvsStats.triangles}</b> triangoli MVS · <b>${slam?.markpoints.length||0}</b> repere`;renderer.requestRender();}

async function persistKeyframe(kf){if(!db||!session)return;try{await db.put('keyframes',{id:`${session.id}:${kf.id}`,sessionId:session.id,kfId:kf.id,seq:kf.seq,t:kf.t,pose:kf.pose,K:kf.K,analysisWidth:kf.analysisWidth,analysisHeight:kf.analysisHeight,imageWidth:kf.imageWidth,imageHeight:kf.imageHeight,trackIds:kf.trackIds,featureX:kf.featureX,featureY:kf.featureY,featureScore:kf.featureScore,descriptorBytes:kf.descriptorBytes,blob:kf.blob});session=await persistSession({counts:{...(session.counts||{}),keyframes:slam.keyframes.length,gaussians:lastWorkerStats.count||0,triangles:mvsStats.triangles}});}catch(err){log.error('keyframe-persist-failed',{message:err.message,stack:err.stack});}}
async function persistSession(patch){if(!session)return null;Object.assign(session,patch,{updatedAt:Date.now()});if(db)try{session=await db.updateSession(session.id,patch);}catch(e){log.warn('session-persist-failed',{message:e.message});}return session;}
async function refreshSavedSessions(){const sessions=(await db.getAll('sessions')).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,8),el=$('savedSessions');if(!sessions.length){el.innerHTML='<span class="muted">Nessuna sessione V30 salvata.</span>';return;}el.innerHTML=sessions.map(s=>`<div class="savedRow"><span><b>${s.id.slice(0,12)}</b><small>${new Date(s.updatedAt).toLocaleString()} · ${s.status||'?'}</small></span><span>${s.counts?.keyframes||0} KF · ${s.counts?.gaussians||0} GS</span></div>`).join('');}
async function loadPly(e){const file=e.target.files?.[0];if(!file)return;try{const snap=await parsePly(file);session={id:`ply-${file.name}`,status:'loaded',counts:{gaussians:snap.count}};currentSnapshot=snap;log.setSession(session.id);log.info('ply-loaded',{name:file.name,count:snap.count,size:file.size});showReview();}catch(err){log.error('ply-load-failed',{message:err.message});setStatus(`PLY non valido: ${err.message}`,'error');}finally{e.target.value='';}}
async function loadR30(e){const file=e.target.files?.[0];if(!file)return;try{const r=await parseR30(file);session={id:r.meta.id||`r30-${file.name}`,status:'loaded',...r.meta};currentSnapshot=r.gaussians;log.setSession(session.id);log.info('r30-loaded',{name:file.name,entries:Object.keys(r.entries).length,gaussians:r.gaussians?.count||0});showReview();}catch(err){log.error('r30-load-failed',{message:err.message});setStatus(`R30 non valido: ${err.message}`,'error');}finally{e.target.value='';}}
async function exportR30(){if(!session)return;const blob=makeR30({manifest:{id:session.id,build:BUILD,session,slam:slam?.diagnostics?.()||null,calibration,mvs:mvsStats,mesh:{chunks:meshChunks.length,triangles:mvsStats.triangles}},keyframes:slam?.keyframes||[],gaussians:currentSnapshot});downloadBlob(blob,`roomscan-${session.id}.r30`);log.info('r30-exported',{bytes:blob.size});}
async function copyDiagnostics(){try{await navigator.clipboard.writeText(JSON.stringify(log.snapshot(diagnosticsExtra()),null,2));log.info('diagnostics-copied');}catch(e){log.warn('diagnostics-copy-failed',{message:e.message});}}
async function runUiSelfTest(){const b=$('selfTestBtn');b.disabled=true;b.textContent='Test…';$('selfTestSummary').textContent='Self-test in corso…';const r=await runSelfTests(log);$('selfTestSummary').textContent=r.tests.map(t=>`${t.ok?'PASS':'FAIL'} ${t.name}${t.ok?'':`: ${t.error}`}`).join(' · ');b.textContent='Esegui self-test';b.disabled=false;}

async function registerServiceWorker(){if(!('serviceWorker' in navigator))return;try{navigator.serviceWorker.addEventListener('controllerchange',()=>{const last=Number(sessionStorage.getItem('roomscan-v30-controller-reload')||0);if(Date.now()-last<10000)return;sessionStorage.setItem('roomscan-v30-controller-reload',String(Date.now()));log.info('service-worker-controller-changed',{action:'reload'});const u=new URL(location.href);u.searchParams.set('sw-update',Date.now());location.replace(u.href);});const reg=await navigator.serviceWorker.register(CONFIG.serviceWorker,{updateViaCache:'none'});await reg.update().catch(()=>{});log.info('service-worker-ready',{scope:reg.scope,updateViaCache:'none',waiting:!!reg.waiting,installing:!!reg.installing});if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});}catch(e){log.warn('service-worker-failed',{message:e.message});}}
async function checkPublishedBuild(){try{const r=await fetch(`${CONFIG.buildInfo}?t=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)return;const remote=await r.json();if(remote.id&&remote.id!==BUILD.id){$('updateBanner').hidden=false;$('updateText').textContent=`Pagina: ${BUILD.id} · pubblicato: ${remote.id}. Premi Aggiorna ora.`;log.warn('build-mismatch',{page:BUILD.id,remote:remote.id});}}catch(e){log.warn('build-check-failed',{message:e.message});}}
async function forceUpdate(){log.info('force-update-requested');try{const regs=await navigator.serviceWorker?.getRegistrations?.()||[];for(const r of regs)if(r.scope.includes('/v30/'))await r.unregister();const keys=await caches.keys();for(const k of keys)if(k.startsWith('room-scanner-v30'))await caches.delete(k);sessionStorage.setItem('roomscan-v30-force-refresh',String(Date.now()));const u=new URL(location.href);u.searchParams.set('roomscan-refresh',Date.now());location.replace(u.href);}catch(err){log.error('force-update-failed',{message:err.message,stack:err.stack});location.reload();}}

bootstrap().catch(err=>{log.error('bootstrap-fatal',{message:err.message,stack:err.stack});setStatus(`BOOTSTRAP FATAL: ${err.message}`,'error');document.documentElement.dataset.bootstrap='failed';});
