/* V30 standalone camera source. Portrait and landscape frames are always fitted
 * inside the WASM analysis rectangle while preserving aspect ratio. */
export function fitAnalysisSize(srcW,srcH,{maxWidth=320,maxHeight=480,maxPixels=640*480}={}){
  if(!(srcW>0&&srcH>0))return {width:0,height:0,scale:0};let s=Math.min(1,maxWidth/srcW,maxHeight/srcH,Math.sqrt(maxPixels/(srcW*srcH)));const width=Math.max(32,Math.floor(srcW*s)),height=Math.max(24,Math.floor(srcH*s));return {width,height,scale:Math.min(width/srcW,height/srcH)};
}
export class CameraSource{
  constructor(video,{analysisWidth=320,analysisHeight=480}={}){this.video=video;this.analysisWidth=analysisWidth;this.analysisHeight=analysisHeight;this.stream=null;this.canvas=document.createElement('canvas');this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});this.fullCanvas=document.createElement('canvas');this.fullCtx=this.fullCanvas.getContext('2d',{willReadFrequently:true});this.lastAnalysisSize=null;this.lastRgba=null;}
  async start(){this.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});this.video.srcObject=this.stream;await this.video.play();await new Promise(resolve=>{if(this.video.videoWidth)return resolve();this.video.addEventListener('loadedmetadata',resolve,{once:true});});return {width:this.video.videoWidth,height:this.video.videoHeight,analysis:fitAnalysisSize(this.video.videoWidth,this.video.videoHeight,{maxWidth:this.analysisWidth,maxHeight:this.analysisHeight}),settings:this.stream.getVideoTracks()[0]?.getSettings?.()||{}};}
  analysisFrame(timestamp=performance.now()){const vw=this.video.videoWidth,vh=this.video.videoHeight;if(!vw||!vh)return null;const size=fitAnalysisSize(vw,vh,{maxWidth:this.analysisWidth,maxHeight:this.analysisHeight}),w=size.width,h=size.height;if(!w||!h)return null;this.lastAnalysisSize=size;if(this.canvas.width!==w)this.canvas.width=w;if(this.canvas.height!==h)this.canvas.height=h;this.ctx.drawImage(this.video,0,0,w,h);const rgba=this.ctx.getImageData(0,0,w,h).data;this.lastRgba=new Uint8ClampedArray(rgba);const gray=new Uint8Array(w*h);for(let i=0,j=0;i<rgba.length;i+=4,j++)gray[j]=(rgba[i]*77+rgba[i+1]*150+rgba[i+2]*29)>>8;return {gray,width:w,height:h,timestamp,sourceWidth:vw,sourceHeight:vh,scale:size.scale};}
  analysisRgb(){if(!this.lastRgba)return null;const n=this.lastRgba.length/4,out=new Uint8Array(n*3);for(let i=0,j=0;i<this.lastRgba.length;i+=4,j+=3){out[j]=this.lastRgba[i];out[j+1]=this.lastRgba[i+1];out[j+2]=this.lastRgba[i+2];}return out;}
  async keyframe({quality=.84,maxWidth=960}={}){const vw=this.video.videoWidth,vh=this.video.videoHeight;if(!vw||!vh)throw new Error('camera frame unavailable');const scale=Math.min(1,maxWidth/vw),w=Math.max(1,Math.round(vw*scale)),h=Math.max(1,Math.round(vh*scale));this.fullCanvas.width=w;this.fullCanvas.height=h;this.fullCtx.drawImage(this.video,0,0,w,h);const image=this.fullCtx.getImageData(0,0,w,h);const blob=await new Promise((resolve,reject)=>this.fullCanvas.toBlob(b=>b?resolve(b):reject(new Error('JPEG encode failed')),'image/jpeg',quality));return {blob,image,width:w,height:h,timestamp:performance.now()};}
  stop(){for(const t of this.stream?.getTracks?.()||[])t.stop();this.video.srcObject=null;this.stream=null;this.lastRgba=null;}
}
