import {downloadBlob} from './logger.js';

const MAX_PLY_VERTICES=1_000_000,MAX_R30_JSON=4*1024*1024;
const clamp01=v=>Math.max(0,Math.min(1,v));

export function gaussianSnapshotToPly(snapshot){
  const a=snapshot?.data instanceof Float32Array?snapshot.data:new Float32Array(snapshot?.data||0),stride=snapshot?.stride||16,n=Math.min(Math.floor(a.length/stride),MAX_PLY_VERTICES);
  const header=`ply\nformat binary_little_endian 1.0\ncomment Room Scanner V30 Gaussian RGB\nelement vertex ${n}\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nproperty float scale_x\nproperty float scale_y\nproperty float scale_z\nproperty float opacity\nend_header\n`;
  const hb=new TextEncoder().encode(header),row=31,buf=new ArrayBuffer(hb.length+n*row),u8=new Uint8Array(buf);u8.set(hb);const dv=new DataView(buf);let o=hb.length;
  for(let i=0;i<n;i++){const s=i*stride;for(let k=0;k<3;k++){dv.setFloat32(o,a[s+k],true);o+=4;}u8[o++]=Math.round(clamp01(a[s+9])*255);u8[o++]=Math.round(clamp01(a[s+10])*255);u8[o++]=Math.round(clamp01(a[s+11])*255);for(let k=3;k<6;k++){dv.setFloat32(o,a[s+k],true);o+=4;}dv.setFloat32(o,Number.isFinite(a[s+12])?a[s+12]:.5,true);o+=4;}
  return new Blob([buf],{type:'application/octet-stream'});
}
export function downloadPly(snapshot,name='roomscan-v30-gaussians.ply'){downloadBlob(gaussianSnapshotToPly(snapshot),name);}
export function meshToPly(mesh){const p=mesh?.positions instanceof Float32Array?mesh.positions:new Float32Array(mesh?.positions||0),c=mesh?.colors instanceof Float32Array?mesh.colors:new Float32Array(mesh?.colors||0),f=mesh?.indices instanceof Uint32Array?mesh.indices:new Uint32Array(mesh?.indices||0),n=Math.floor(p.length/3),tri=Math.floor(f.length/3),header=`ply\nformat binary_little_endian 1.0\ncomment Room Scanner V30 confidence mesh\nelement vertex ${n}\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nelement face ${tri}\nproperty list uchar uint vertex_indices\nend_header\n`,hb=new TextEncoder().encode(header),buf=new ArrayBuffer(hb.length+n*15+tri*13),u8=new Uint8Array(buf),dv=new DataView(buf);u8.set(hb);let o=hb.length;for(let i=0;i<n;i++){const j=i*3;for(let k=0;k<3;k++){dv.setFloat32(o,p[j+k],true);o+=4;}u8[o++]=Math.round(clamp01(c[j]??.8)*255);u8[o++]=Math.round(clamp01(c[j+1]??.8)*255);u8[o++]=Math.round(clamp01(c[j+2]??.8)*255);}for(let i=0;i<tri;i++){u8[o++]=3;for(let k=0;k<3;k++){dv.setUint32(o,f[i*3+k],true);o+=4;}}return new Blob([buf],{type:'application/octet-stream'});}
export function downloadMeshPly(mesh,name='roomscan-v30-mesh.ply'){downloadBlob(meshToPly(mesh),name);}

function headerEnd(bytes){const marker=new TextEncoder().encode('end_header');for(let i=0;i<=bytes.length-marker.length;i++){let ok=true;for(let j=0;j<marker.length;j++)if(bytes[i+j]!==marker[j]){ok=false;break;}if(ok){let end=i+marker.length;if(bytes[end]===13)end++;if(bytes[end]===10)end++;return end;}}return -1;}
const typeInfo={char:[1,'getInt8'],int8:[1,'getInt8'],uchar:[1,'getUint8'],uint8:[1,'getUint8'],short:[2,'getInt16'],int16:[2,'getInt16'],ushort:[2,'getUint16'],uint16:[2,'getUint16'],int:[4,'getInt32'],int32:[4,'getInt32'],uint:[4,'getUint32'],uint32:[4,'getUint32'],float:[4,'getFloat32'],float32:[4,'getFloat32'],double:[8,'getFloat64'],float64:[8,'getFloat64']};
function vertexProperties(header){const lines=header.split(/\r?\n/);let inVertex=false,props=[];for(const line of lines){const e=/^element\s+(\S+)\s+(\d+)/.exec(line);if(e){if(inVertex)break;inVertex=e[1]==='vertex';continue;}if(inVertex){const p=/^property\s+(\S+)\s+(\S+)/.exec(line);if(p){if(!typeInfo[p[1]])throw new Error(`Unsupported PLY property type ${p[1]}`);props.push({type:p[1],name:p[2]});}}}return props;}
function snapshotRow(out,s,val){out[s]=Number.isFinite(val.x)?val.x:0;out[s+1]=Number.isFinite(val.y)?val.y:0;out[s+2]=Number.isFinite(val.z)?val.z:0;out[s+3]=Number.isFinite(val.scale_x)?val.scale_x:.02;out[s+4]=Number.isFinite(val.scale_y)?val.scale_y:.02;out[s+5]=Number.isFinite(val.scale_z)?val.scale_z:.02;out[s+6]=0;out[s+7]=1;out[s+8]=0;out[s+9]=clamp01((val.red??180)/255);out[s+10]=clamp01((val.green??180)/255);out[s+11]=clamp01((val.blue??180)/255);out[s+12]=Number.isFinite(val.opacity)?val.opacity:.65;out[s+13]=1;out[s+14]=1;}

export async function parsePly(file){
  const buf=await file.arrayBuffer(),u8=new Uint8Array(buf),base=headerEnd(u8);if(base<0)throw new Error('PLY header missing');const header=new TextDecoder().decode(u8.subarray(0,base)),count=Number((/element\s+vertex\s+(\d+)/.exec(header)||[])[1]);if(!Number.isSafeInteger(count)||count<1)throw new Error('PLY vertex count missing');if(count>MAX_PLY_VERTICES)throw new Error(`PLY has too many vertices (max ${MAX_PLY_VERTICES})`);const props=vertexProperties(header);if(!props.length)throw new Error('PLY vertex properties missing');
  if(/format\s+ascii/.test(header)){const body=new TextDecoder().decode(u8.subarray(base));const lines=body.split(/\r?\n/).filter(Boolean);if(lines.length<count)throw new Error('Truncated ASCII PLY');const out=new Float32Array(count*16);for(let i=0;i<count;i++){const vals=lines[i].trim().split(/\s+/).map(Number),val=Object.fromEntries(props.map((p,j)=>[p.name,vals[j]]));snapshotRow(out,i*16,val);}return {data:out,stride:16,count};}
  if(!/format\s+binary_little_endian/.test(header))throw new Error('Only ASCII or binary little-endian PLY supported');let row=0;for(const p of props)row+=typeInfo[p.type][0];if(base+count*row>buf.byteLength)throw new Error('Truncated binary PLY');const dv=new DataView(buf),out=new Float32Array(count*16);for(let i=0;i<count;i++){let o=base+i*row;const val={};for(const p of props){const [size,getter]=typeInfo[p.type];val[p.name]=size===1?dv[getter](o):dv[getter](o,true);o+=size;}snapshotRow(out,i*16,val);}return {data:out,stride:16,count};
}

function serializableKeyframe(k){return {id:k.id,seq:k.seq,t:k.t,pose:k.pose,K:k.K,analysisWidth:k.analysisWidth,analysisHeight:k.analysisHeight,imageWidth:k.imageWidth,imageHeight:k.imageHeight,trackIds:k.trackIds,featureX:k.featureX,featureY:k.featureY,featureScore:k.featureScore,descriptorBytes:k.descriptorBytes,depthCalibration:k.depthCalibration};}
function safeEntryName(name){return typeof name==='string'&&name.length>0&&name.length<240&&!name.startsWith('/')&&!name.includes('..');}
export function makeR30({manifest,keyframes=[],gaussians=null,mesh=null,imu=[],extraEntries=[]}){
  const entries=[],names=new Set();const add=(name,blob)=>{if(!safeEntryName(name)||!blob||names.has(name))return;names.add(name);entries.push({name,blob});};
  for(const e of extraEntries)add(e.name,e.blob);for(const k of keyframes){if(k.blob)add(`keyframes/${k.id}.jpg`,k.blob);if(k.descriptors instanceof Uint8Array)add(`keyframes/${k.id}.desc`,new Blob([k.descriptors],{type:'application/octet-stream'}));}
  const index=keyframes.map(serializableKeyframe);if(index.length)add('keyframes/index.json',new Blob([JSON.stringify(index)],{type:'application/json'}));if(imu.length)add('imu/samples.json',new Blob([JSON.stringify(imu)],{type:'application/json'}));
  if(gaussians?.data){const d=gaussians.data,bytes=d.buffer.slice(d.byteOffset,d.byteOffset+d.byteLength);add('map/gaussians.f32',new Blob([bytes],{type:'application/octet-stream'}));}if(mesh?.positions){for(const [name,data] of [['map/mesh_positions.f32',mesh.positions],['map/mesh_colors.f32',mesh.colors],['map/mesh_confidence.f32',mesh.confidence],['map/mesh_indices.u32',mesh.indices]])if(data){const bytes=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength);add(name,new Blob([bytes],{type:'application/octet-stream'}));}}
  const meta={...manifest,imu:imu.length?undefined:imu,imuEntry:imu.length?'imu/samples.json':undefined,gaussianStride:gaussians?.stride||16,gaussianCount:gaussians?.count||0,meshVertexCount:mesh?.vertexCount||0,meshTriangleCount:mesh?.triangleCount||0,meshSealed:!!mesh?.sealed,entries:[]};let offset=0;for(const e of entries){meta.entries.push({name:e.name,offset,length:e.blob.size,type:e.blob.type});offset+=e.blob.size;}const json=new TextEncoder().encode(JSON.stringify(meta));if(json.length>MAX_R30_JSON)throw new Error('R30 metadata too large');const head=new ArrayBuffer(12),dv=new DataView(head);['R','3','0','1'].forEach((c,i)=>dv.setUint8(i,c.charCodeAt(0)));dv.setUint32(4,json.length,true);dv.setUint32(8,entries.length,true);return new Blob([head,json,...entries.map(e=>e.blob)],{type:'application/octet-stream'});
}
export async function parseR30(file){
  const buf=await file.arrayBuffer(),dv=new DataView(buf);if(buf.byteLength<12||String.fromCharCode(...new Uint8Array(buf,0,4))!=='R301')throw new Error('Not a Room Scanner V30 .r30 file');const jsonLen=dv.getUint32(4,true),entryCount=dv.getUint32(8,true),jsonStart=12,jsonEnd=jsonStart+jsonLen;if(jsonLen>MAX_R30_JSON||jsonEnd>buf.byteLength)throw new Error('Corrupt R30 metadata length');const meta=JSON.parse(new TextDecoder().decode(new Uint8Array(buf,jsonStart,jsonLen)));if(!Array.isArray(meta.entries)||meta.entries.length!==entryCount)throw new Error('Corrupt R30 entry index');let o=jsonEnd;const entries={};for(const e of meta.entries){if(!safeEntryName(e.name)||!Number.isSafeInteger(e.length)||e.length<0||o+e.length>buf.byteLength)throw new Error('Corrupt R30 entry');entries[e.name]=new Blob([buf.slice(o,o+e.length)],{type:e.type||'application/octet-stream'});o+=e.length;}if(o!==buf.byteLength)throw new Error('Unexpected trailing R30 data');let gaussians=null;const gb=entries['map/gaussians.f32'];if(gb){const ab=await gb.arrayBuffer();if(ab.byteLength%4)throw new Error('Invalid Gaussian binary payload');const data=new Float32Array(ab),stride=meta.gaussianStride||16;if(!Number.isSafeInteger(stride)||stride<13||data.length%stride)throw new Error('Invalid Gaussian stride');gaussians={data,stride,count:data.length/stride};}let mesh=null;const mp=entries['map/mesh_positions.f32'],mi=entries['map/mesh_indices.u32'];if(mp&&mi){const [p,c,q,f]=await Promise.all([mp.arrayBuffer(),entries['map/mesh_colors.f32']?.arrayBuffer(),entries['map/mesh_confidence.f32']?.arrayBuffer(),mi.arrayBuffer()]);if(p.byteLength%12||f.byteLength%12)throw new Error('Invalid mesh binary payload');mesh={positions:new Float32Array(p),colors:c?new Float32Array(c):new Float32Array(p.byteLength/4),confidence:q?new Float32Array(q):new Float32Array(p.byteLength/12),indices:new Uint32Array(f),vertexCount:p.byteLength/12,triangleCount:f.byteLength/12,sealed:!!meta.meshSealed};}let keyframes=[];const ib=entries['keyframes/index.json'];if(ib){try{const index=JSON.parse(await ib.text());if(!Array.isArray(index))throw new Error('invalid keyframe index');keyframes=index.map(k=>({...k,blob:entries[`keyframes/${k.id}.jpg`]||null,descriptors:null}));for(const k of keyframes){const d=entries[`keyframes/${k.id}.desc`];if(d)k.descriptors=new Uint8Array(await d.arrayBuffer());}}catch(e){throw new Error(`Invalid R30 keyframe index: ${e.message}`);}}let imu=Array.isArray(meta.imu)?meta.imu:[];if(meta.imuEntry){const b=entries[meta.imuEntry];if(!b)throw new Error('Missing R30 IMU entry');try{imu=JSON.parse(await b.text());if(!Array.isArray(imu))throw new Error('not an array');}catch(e){throw new Error(`Invalid R30 IMU entry: ${e.message}`);}}return {meta,entries,gaussians,mesh,keyframes,imu};
}
