#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8'),m=html.match(/<script type="module">([\s\S]*?)<\/script>/);if(!m)throw new Error('module missing');
class Ctx{clearRect(){}fillRect(){}strokeRect(){}beginPath(){}moveTo(){}lineTo(){}closePath(){}fill(){}stroke(){}putImageData(){}drawImage(){}createImageData(w,h){return{data:new Uint8ClampedArray(w*h*4)}}getImageData(x,y,w,h){return{data:new Uint8ClampedArray(w*h*4)}}}
class El{constructor(id=''){this.id=id;this.style={setProperty(){}};this.className='';this._classes=new Set(['reviewModal','sceneModal','processModal','hud','arCanvas','coverageCanvas','coverageLegend'].includes(id)?['hidden']:[]);this.classList={contains:x=>this._classes.has(x),add:x=>this._classes.add(x),remove:x=>this._classes.delete(x),toggle:(x,f)=>{if(f===undefined)f=!this._classes.has(x);f?this._classes.add(x):this._classes.delete(x)}};this.innerHTML='';this.textContent='';this.dataset={};this.checked=true;this.value=id==='processQuality'?'balanced':'';this.files=[];this.disabled=false;this.width=800;this.height=600}addEventListener(){}appendChild(){}setPointerCapture(){}click(){}getContext(){return new Ctx}getBoundingClientRect(){return{left:0,top:0,width:800,height:600}}toDataURL(){return'data:image/jpeg;base64,AA=='}}
const els=new Map(),docEl=new El('html');docEl.requestFullscreen=async()=>true;const document={documentElement:docEl,body:new El('body'),fullscreenElement:null,getElementById:id=>{if(!els.has(id))els.set(id,new El(id));return els.get(id)},querySelectorAll:()=>[],createElement:()=>new El(),addEventListener(){},permissionsPolicy:null,featurePolicy:null};
const context={console,document,window:{addEventListener(){},devicePixelRatio:1,innerHeight:600,isSecureContext:true,visualViewport:{offsetTop:0,height:600,addEventListener(){}}},location:{protocol:'https:'},navigator:{},performance:{now:()=>1000},setTimeout,clearTimeout,requestAnimationFrame:fn=>{fn();return 1},requestIdleCallback:fn=>{fn();return 1},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),alert(){},ImageData:class{constructor(data,w,h){this.data=data;this.width=w;this.height=h}},Image:class{},devicePixelRatio:1,globalThis:null};context.globalThis=context;vm.createContext(context);vm.runInContext(m[1],context,{filename:'v1215.js'});const H=context.__ROOM_SCANNER_V12_1_5__;if(!H)throw new Error('hook missing');
let fail=0;const ok=(c,msg,d='')=>{if(c)console.log('PASS',msg,d);else{console.error('FAIL',msg,d);fail++}},close=(a,b,t=.03)=>Math.abs(a-b)<=t;
const P=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],W=[...P],k={id:1,projection:P,worldFromView:W,worldToView:W,poseInfo:{p:[0,0,0]},deep:null};
function mkWall(id,a,b,h=2.5){const dx=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dx,dz),n=[-dz/L,0,dx/L],poly=[[a[0],0,a[1]],[b[0],0,b[1]],[b[0],h,b[1]],[a[0],h,a[1]]];return{id,kind:'parete',polygon:poly,center:[(a[0]+b[0])/2,h/2,(a[1]+b[1])/2],normal:n,area:L*h,confidence:.92,evidence:['WebXR depth plane'],frames:[1,2,3],source:'xr-depth-plane',admissionSupport:true}}
function mkFloor(poly){return{id:'FLOOR',kind:'pavimento',polygon:poly.map(p=>[p[0],0,p[1]]),center:[0,0,0],normal:[0,1,0],area:16,confidence:.96,evidence:['XR plane'],frames:[1,2],source:'native-plane',admissionSupport:true}}
const wall={id:'W1',kind:'parete',polygon:[[-2,-1,-2],[2,-1,-2],[2,2,-2],[-2,2,-2]],center:[0,.5,-2],normal:[0,0,1],area:12,confidence:.96,evidence:['XR plane'],frames:[1,2],source:'native-plane',admissionSupport:true};H.state.surfaces=[wall];H.state.roomShell=null;H.state.structuralModel=null;
let t=H.structuralTargetForRay(k,.5,.5,2.12);ok(t&&close(t.d,2,.03)&&t.surface.id==='W1','stesso raggio associa Deep alla parete globale XR',t?`d=${t.d}`:'null');
let sem=H.semanticAssignmentForVertex(k,{u:.5,v:.5,d:2.12,p:[0,0,-2.12],confidence:.6},{ok:true,strongConflict:false,score:.7,evidence:[],direct:false,raySupport:0,mv:{support:0,conflict:0}});ok(sem.kind==='structure'&&sem.surface.id==='W1','Deep vicino al muro diventa struttura, non foglio libero');
sem=H.semanticAssignmentForVertex(k,{u:.5,v:.5,d:1.0,p:[0,0,-1],confidence:.7},{ok:true,strongConflict:false,score:.8,evidence:[],direct:true,raySupport:.5,mv:{support:1,conflict:0}});ok(sem.kind==='residual','oggetto davanti alla parete resta residuo interno invece di essere schiacciato sul muro');
// Three slightly rotated Deep sheets: global normal must remain locked and only offset/extent may refine.
H.state.frames=[{poseInfo:{p:[0,1,0]}},{poseInfo:{p:[.3,1,.1]}},{poseInfo:{p:[-.3,1,.1]}}];const obs=[];for(let f=1;f<=3;f++)for(let ix=-4;ix<=4;ix++)for(let iy=0;iy<3;iy++){const x=ix*.18,y=.2+iy*.55,z=-2+(f-2)*.018+x*(f-2)*.025;obs.push({surfaceId:'W1',kind:'parete',rawP:[x,y,z],targetP:[x,y,-2],frameId:f,u:.5,v:.5,color:[120,140,160],confidence:.8})}const refined=H.refinePersistentStructure([wall],obs)[0];ok(refined&&Math.abs(refined.normal[0])<1e-9&&Math.abs(refined.normal[2]-1)<1e-9&&refined.refinement?.normalLocked,'tre fogli ruotati raffinano UNA parete con normale bloccata');ok(Math.abs(refined.refinement.offsetM)<=H.CFG.semanticPlaneOffsetMax+.001,'correzione offset Deep limitata',`${(refined.refinement.offsetM*1000).toFixed(1)}mm`);
// An interior vertical plane (e.g. cabinet face) must not replace the farther room boundary wall.
const rect=[[-2,-2],[2,-2],[2,2],[-2,2]],cab=mkWall('CAB',[1,-.75],[1,.75],2.25);H.state.frames=[{poseInfo:{p:[0,1,0]}},{poseInfo:{p:[.25,1,.15]}},{poseInfo:{p:[-.2,1,-.15]}}];H.state.surfaces=[mkFloor(rect),mkWall('S',rect[0],rect[1]),mkWall('E',rect[1],rect[2]),mkWall('N',rect[2],rect[3]),mkWall('W',rect[3],rect[0]),cab];const boundaryModel=H.buildStructuralModel();ok(boundaryModel&&boundaryModel.wallLines.length===4&&!boundaryModel.wallLines.some(l=>(l.memberIds||[]).includes('CAB')),'piano verticale interno non sostituisce la frontiera stanza',boundaryModel?`walls=${boundaryModel.wallLines.length}`:'null');ok(cab.roomBoundary===false,'faccia verticale interna marcata non-boundary e non usata come target strutturale');ok(H.nearestStructuralDistance([1,1,0])>H.CFG.semanticObjectSurfaceClearance,'faccia interna esclusa dalla distanza strutturale e disponibile alla popolazione oggetti');
ok(H.classifySurface([0,1,0],[0,1.65,0],null,'horizontal',2.4)==='superficie orizzontale','piano orizzontale interno sopra 1.45 m non diventa automaticamente soffitto');
ok(H.classifySurface([0,1,0],[0,2.55,0],null,'horizontal',3.5)==='soffitto','piano orizzontale alto/esteso sopra la camera puo diventare soffitto');
ok(H.classifySurface([0,1,0],[0,2.55,0],'desk','horizontal',4)==='superficie orizzontale','semantic label desk impedisce falsa classificazione soffitto');
// Inferred shell can be confirmed only with persistent multi-view Deep support.
H.state.roomShell={footprint:[[-2,-2],[2,-2],[2,2],[-2,2]],floorY:0,ceilY:2.5,parts:[{kind:'pavimento',observed:true,confidence:.9},{kind:'soffitto',observed:false,confidence:.4},{kind:'parete',observed:false,confidence:.3,lineId:null},{kind:'parete',observed:true,confidence:.8,lineId:'E'},{kind:'parete',observed:true,confidence:.8,lineId:'N'},{kind:'parete',observed:true,confidence:.8,lineId:'W'}]};const shellObs=[];for(let f=1;f<=3;f++)for(let x=-1.5;x<=1.5;x+=.3)for(let y=.2;y<=2.2;y+=.5)shellObs.push({surfaceId:'ROOM_WALL_1',kind:'parete',rawP:[x,y,-2+.01*(f-2)],targetP:[x,y,-2],frameId:f,color:[100,110,120],confidence:.7});const promoted=H.promotePersistentShellFaces([],shellObs);ok(promoted.length===1&&promoted[0].frames.length===3&&!promoted[0].admissionSupport,'chiusura inferita diventa candidato Deep solo dopo 3 viste persistenti');
// Persistent residual cluster becomes internal object; structural-near points are removed.
H.state.structuralModel={floorY:0,ceilY:2.5,footprint:[[-2,-2],[2,-2],[2,2],[-2,2]]};H.state.surfaces=[wall,{id:'F',kind:'pavimento',polygon:[[-2,0,-2],[2,0,-2],[2,0,2],[-2,0,2]],center:[0,0,0],normal:[0,1,0],area:16,confidence:.95,evidence:['XR plane'],frames:[1],source:'native-plane',admissionSupport:true}];H.state.deepResidualSurfels=new Map();let q=0;for(let x=-.28;x<=.28;x+=.14)for(let y=.42;y<=.84;y+=.14)for(let z=-.28;z<=.28;z+=.14)H.state.deepResidualSurfels.set(`r${q++}`,{p:[x,y,z],color:[180,120,70],confidence:.8,frames:[1,2,3]});for(let x=-.4;x<=.4;x+=.14)H.state.deepResidualSurfels.set(`w${q++}`,{p:[x,1,-1.97],color:[50,50,50],confidence:.9,frames:[1,2,3]});H.state.nativeSurfels=new Map();H.state.objects=[];H.state.objectOverrides=new Map();const objects=H.buildPersistentObjects();ok(objects.length>=1&&objects[0].frames.length>=2,'residuo popolato/persistente diventa oggetto interno',`objects=${objects.length}`);ok(objects.every(o=>o.center[2]>-1.5),'punti aderenti alla parete non vengono trasformati in oggetti');
// Removed objects stay recoverable in Review but are excluded from active object-id/export cells.
if(objects.length){const sig=objects[0].signature,probe=objects[0].points[0].p;H.state.objectOverrides.set(sig,'removed');H.buildPersistentObjects();ok(H.state.removedObjectCells.size>0&&H.objectIdForPoint(probe)===0,'oggetto rimosso resta separato dalla mappa attiva');H.state.objectOverrides.set(sig,'candidate');H.buildPersistentObjects();ok(H.objectIdForPoint(probe)>0,'oggetto rimosso puo essere riaggiunto senza ricostruire Deep')}
const mesh=H.semanticBoxMesh([0,0,0],[1,1,1]);const E=new Map();for(let i=0;i<mesh.indices.length;i+=3)for(const [a,b] of [[mesh.indices[i],mesh.indices[i+1]],[mesh.indices[i+1],mesh.indices[i+2]],[mesh.indices[i+2],mesh.indices[i]]]){const key=a<b?`${a},${b}`:`${b},${a}`;E.set(key,(E.get(key)||0)+1)}ok([...E.values()].every(n=>n===2),'mesh coarse oggetto è chiusa/manifold');
// Existing parser/memory regressions.
const ply=`ply\nformat ascii 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nend_header\n0 0 0\n1 0 0\n0 1 0\n`,pm=H.parsePlyAscii(ply,'a.ply');ok(pm.vertices.length===3,'parser PLY invariato');const src=Float32Array.from([.2,.7,1.1,2.3,4]),packed=H.packFloatU16(src),round=H.unpackFloatU16(packed);ok(round.length===src.length&&Math.max(...src.map((v,i)=>Math.abs(v-round[i])))<1e-3,'quantizzazione Deep invariata');
if(fail)process.exit(1);console.log('\nTutti i test runtime/semantici V12.1.5 sono passati.');
