#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8');
const script=(html.match(/<script type="module">([\s\S]*?)<\/script>/)||[])[1]||'';
let fail=0;const ok=(c,m,d='')=>{if(c)console.log('PASS',m,d);else{console.error('FAIL',m,d);fail++}};
ok(/V12\.1\.5/.test(html)&&/1215-persistent-structure-deep-projection-20260817/.test(html),'build V12.1.5 esplicita');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]),idSet=new Set(ids);ok(ids.length===idSet.size,'ID HTML univoci');
const refs=[...script.matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]),missing=[...new Set(refs.filter(x=>!idSet.has(x)))];ok(!missing.length,'tutti i riferimenti $() hanno elemento DOM',missing.join(','));
ok(!/navigator\.mediaDevices|getUserMedia\s*\(|ImageCapture\s*\(/.test(script),'nessuna seconda camera/API MediaStream');
ok((script.match(/navigator\.xr\.requestSession\s*\(/g)||[]).length===1,'una sola requestSession XR');
ok(/requiredFeatures:\['local-floor','dom-overlay','camera-access'\]/.test(script),'camera raw resta nella stessa sessione XR');
ok(/id="processModel"/.test(html)&&/id="processQuality"/.test(html)&&/id="processFill"/.test(html),'batch transazionale e qualità presenti');
ok(/id="processDeepCount"/.test(html)&&/id="processFuseCount"/.test(html),'progress foto Deep/fuse presente');
ok(/id="reviewModal"[\s\S]*?<div class="modalFooter">[\s\S]*id="rebuildReview"[\s\S]*data-close="reviewModal"/.test(html),'Ricalcola e Chiudi restano in basso');
ok(/id="sceneModal"[\s\S]*?<div class="modalFooter">[\s\S]*data-close="sceneModal"/.test(html),'Chiudi Scena resta in basso');
ok(/id="layObjects"/.test(html)&&/id="objectsReview"/.test(html),'layer e revisione oggetti persistenti presenti');
ok(/structuralTargetForRay/.test(script)&&/semanticAssignmentForVertex/.test(script),'assegnazione Deep per raggio a superfici globali presente');
ok(/optimizerSemantic:1\.65/.test(script)&&/semanticTarget/.test(script),'ottimizzatore Deep usa target strutturale globale');
ok(/normalLocked:true/.test(script)&&/projectPointToSurface/.test(script),'Deep strutturale blocca la normale globale e viene riproiettato');
ok(/deepResidualSurfels:new Map/.test(script)&&/deepResidualTriangles:\[\]/.test(script),'residuo non strutturale separato dalla struttura');
ok(/Deep persistent residual >=3 views/.test(script)&&/semanticNewWallFrames:3/.test(script),'nuova parete Deep richiede persistenza multi-vista');
ok(/admissionSupport:false/.test(script),'pareti nate da Deep non diventano autorità per ammettere altro Deep');
ok(/selectBoundaryWallLines/.test(script)&&/INTERIOR_VERTICAL_PLANES_EXCLUDED/.test(script),'selezione top-down esclude piani verticali interni dalla frontiera stanza');
ok(/distanceToRoomBoundaryXZ/.test(script)&&/semanticNewWallBoundaryGate:\.48/.test(script),'nuove pareti Deep persistenti devono restare vicine alla frontiera stanza nota');
ok(/cameraHeightEstimate/.test(script)&&/area>1\.35/.test(script),'soffitto geometrico richiede quota rispetto alla camera e area, non soglia fissa 1.45m');
ok(/buildPersistentObjects/.test(script)&&/semanticObjectVoxel/.test(script),'clustering leggero del residuo in oggetti presente');
ok(/objectOverrides/.test(script)&&/data-object-hide/.test(script)&&/data-object-remove/.test(script),'oggetti possono essere nascosti/rimossi/ripristinati');
ok(/property ushort object_id/.test(script)&&/\[3,S\.deepResidualSurfels\]/.test(script),'PLY esporta residuo e object_id');
ok(/removedObjectCells/.test(script)&&/filter\(s=>!S\.removedObjectCells/.test(script),'PLY esclude celle degli oggetti rimossi');
ok(/if\(o\.status==='removed'\|\|!o\.mesh\)continue/.test(script),'OBJ esclude rimossi ma non confonde Nascondi con Rimuovi');
ok(/for\(const o of S\.objects\).*o\.mesh/s.test(script),'OBJ esporta oggetti interni attivi');
ok(/room-scanner-v12\.1\.5-raw/.test(script)&&/deepResidualSurfels/.test(script)&&/objectOverrides/.test(script),'RAW V12.1.5 conserva semantica/residuo');
ok(/quantizeDeepInMemory/.test(script)&&/frameHotRGBA/.test(script),'compattazione memoria V12.1.4 preservata');
ok(/class RayEvidenceVolume/.test(script)&&/rayMaxVoxels/.test(script)&&/prune\(target=/.test(script),'budget TSDF/pruning preservati');
const ps=script.indexOf('async function processModel'),initialShell=script.indexOf('buildRoomShell(false);for(let i=0;i<frames.length',ps),fusion=script.indexOf("await rebuildDeep('V12.1.5 semantic batch'",ps),ready=script.indexOf('S.modelReady=true',ps);ok(initialShell>ps&&fusion>initialShell&&ready>fusion,'shell XR iniziale precede Deep e commit finale segue la fusione semantica');
const fusionBody=(script.match(/async function rebuildDeep\([\s\S]*?\nfunction scheduleRevalidation/)||[])[0]||'';ok(/semanticAssignmentForVertex/.test(fusionBody)&&/refinePersistentStructure/.test(fusionBody)&&/buildPersistentObjects/.test(fusionBody),'rebuildDeep esegue struttura → raffinamento → oggetti');
ok(!/projectDeepToStructure\(V\[i\]\.p/.test(fusionBody),'fusione non usa più il vecchio projection gate punto-per-punto come percorso principale');
const directEvents=[...script.matchAll(/\$\('([^']+)'\)\.addEventListener\('([^']+)'/g)].map(m=>`${m[1]}:${m[2]}`),dup=directEvents.filter((x,i)=>directEvents.indexOf(x)!==i);ok(!dup.length,'nessun listener diretto duplicato',dup.join(','));
if(fail)process.exit(1);console.log('\nTutti i test statici V12.1.5 sono passati.');
