#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8'),m=html.match(/<script type="module">([\s\S]*?)<\/script>/);if(!m)throw new Error('module missing');
class Ctx{clearRect(){}fillRect(){}strokeRect(){}beginPath(){}moveTo(){}lineTo(){}closePath(){}fill(){}stroke(){}putImageData(){}drawImage(){}createImageData(w,h){return{data:new Uint8ClampedArray(w*h*4)}}getImageData(x,y,w,h){return{data:new Uint8ClampedArray(w*h*4)}}}
class El{constructor(id=''){this.id=id;this.style={setProperty(){}};this.className='';this._classes=new Set(['reviewModal','sceneModal','processModal','hud','arCanvas','coverageCanvas','coverageLegend'].includes(id)?['hidden']:[]);this.classList={contains:x=>this._classes.has(x),add:x=>this._classes.add(x),remove:x=>this._classes.delete(x),toggle:(x,f)=>{if(f===undefined)f=!this._classes.has(x);f?this._classes.add(x):this._classes.delete(x)}};this.innerHTML='';this.textContent='';this.dataset={};this.checked=true;this.value=id==='processQuality'?'balanced':'';this.files=[];this.disabled=false;this.width=800;this.height=600}addEventListener(){}appendChild(){}setPointerCapture(){}click(){}getContext(){return new Ctx}getBoundingClientRect(){return{left:0,top:0,width:800,height:600}}toDataURL(){return'data:image/jpeg;base64,AA=='}}
const els=new Map(),docEl=new El('html');docEl.requestFullscreen=async()=>true;const document={documentElement:docEl,body:new El('body'),fullscreenElement:null,getElementById:id=>{if(!els.has(id))els.set(id,new El(id));return els.get(id)},querySelectorAll:()=>[],createElement:()=>new El(),addEventListener(){},permissionsPolicy:null,featurePolicy:null};
let now=1000;const context={console,document,window:{addEventListener(){},devicePixelRatio:1,innerHeight:600,isSecureContext:true,visualViewport:{offsetTop:0,height:600,addEventListener(){}}},location:{protocol:'https:'},navigator:{},performance:{now:()=>now},setTimeout,clearTimeout,requestAnimationFrame:fn=>{fn();return 1},requestIdleCallback:fn=>{fn();return 1},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),alert(){},ImageData:class{constructor(data,w,h){this.data=data;this.width=w;this.height=h}},Image:class{},devicePixelRatio:1,globalThis:null};context.globalThis=context;vm.createContext(context);vm.runInContext(m[1],context,{filename:'v1214.js'});const H=context.__ROOM_SCANNER_V12_1_4__;if(!H)throw new Error('hook missing');
let fail=0;const ok=(c,msg,d='')=>{if(c)console.log('PASS',msg,d);else{console.error('FAIL',msg,d);fail++}};
const ply=`ply\nformat ascii 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n0 0 0 255 0 0\n1 0 0 0 255 0\n0 1 0 0 0 255\n`,pm=H.parsePlyAscii(ply,'a.ply');ok(pm.vertices.length===3&&pm.colors[1][1]===255,'parser PLY ASCII mantiene RGB');
const obj=`v 0 0 0 1 0 0\nv 1 0 0 0 1 0\nv 0 1 0 0 0 1\nf 1 2 3\n`,om=H.parseObj(obj,'a.obj');ok(om.vertices.length===3&&om.indices.length===3&&om.colors[0][0]===255,'parser OBJ mantiene mesh + vertex colors');
const a=new Map(),b=new Map();a.set('a',{p:[0,0,0],color:[200,0,0],confidence:.9});b.set('b',{p:[.01,0,0],color:[0,0,200],confidence:.7});const cp=H.compactSurfelArray([[1,a],[2,b]],.055);ok(cp.length===1&&cp[0].source===1,'compattazione export fonde voxel sovrapposti con priorità XR');
const wall=(id,x,cx=0)=>({id,kind:'parete',polygon:[[cx-1,0,x],[cx+1,0,x],[cx+1,2.5,x],[cx-1,2.5,x]],center:[cx,1.25,x],normal:[0,0,1],area:5,confidence:.9,evidence:['XR plane'],frames:[],source:id==='xr'?'native-plane':'deep-plane',admissionSupport:id==='xr'});let merged=H.optimizeStructuralSurfaces([wall('xr',0),wall('d',.04)]);ok(merged.length===1&&merged[0].mergedCount===2&&merged[0].admissionSupport,'ottimizzazione coplanare pesa XR e fonde supporti vicini');merged=H.optimizeStructuralSurfaces([wall('a',0,-5),wall('b',.03,5)]);ok(merged.length===2,'pareti coplanari ma lontane non vengono unite attraverso zone ignote');
const vol=new H.RayEvidenceVolume(.1,.2,80);for(let i=0;i<120;i++)vol.integrateSample([i*.11,0,0],.8,.08,'Deep');const before=vol.map.size,removed=vol.prune(35);ok(before<=80&&removed>0&&vol.map.size<=35,'TSDF non cresce oltre budget e il pruning libera celle',`before=${before} after=${vol.map.size}`);
const src=Float32Array.from([.2,.7,1.1,2.3,4.0]),packed=H.packFloatU16(src),round=H.unpackFloatU16(packed);ok(round.length===src.length&&Math.max(...src.map((v,i)=>Math.abs(v-round[i])))<1e-3,'packing Deep uint16 conserva la mappa entro errore sub-mm relativo al range');
const fast=H.qualityProfile('fast'),high=H.qualityProfile('high');ok(fast.optimizerIters<high.optimizerIters&&fast.meshMaxVertices<high.meshMaxVertices&&fast.sourceLongEdge<high.sourceLongEdge,'profili qualità riducono costo in modo coerente');
const L=[[0,0],[3,0],[3,1],[1,1],[1,3],[0,3]],tri=H.triangulatePolygon2D(L);ok(tri.length===12,'ear clipping mantiene footprint concavo a L');
if(fail)process.exit(1);console.log('\nTutti i test runtime V12.1.4 sono passati.');
