const fs=require('fs'),assert=require('assert');
const h=fs.readFileSync('room_scanner_v12.html','utf8');
assert(h.includes('V14.1.0')); assert(h.includes('Room Cells AutoSurvey'));
assert.strictEqual((h.match(/requestSession\s*\(/g)||[]).length,1,'one requestSession');
for(const bad of ['getUserMedia','ImageCapture','setInterval','RayEvidenceVolume','mesh-detection']) assert(!h.includes(bad),`forbidden ${bad}`);
for(const s of ['autoSurveyTick','buildParallaxTargets','spatialViewId','Termina intera scansione','La sessione WebXR RESTA attiva','viewCluster','deepMaxFrames']) assert(h.includes(s),`missing ${s}`);
assert(!h.includes('metricSessionEnded'));
const ns=h.match(/function newStationFromPortal\(\)\{[^}]+\}/s)?.[0]||''; assert(!ns.includes('.end('),'new room must not close XR');
function body(name){const i=h.indexOf(`function ${name}(`);assert(i>=0,name);let b=h.indexOf('{',i),d=0;for(let j=b;j<h.length;j++){if(h[j]==='{')d++;else if(h[j]==='}'&&!--d)return h.slice(b+1,j)}return ''} const pm=body('processModel'); assert(pm.includes('Termina intera scansione'),'Deep guard'); assert(h.includes('k.deep=null'),'discard Deep maps');
const ids=[...h.matchAll(/id="([^"]+)"/g)].map(m=>m[1]); assert.strictEqual(new Set(ids).size,ids.length,'unique DOM ids');
const fn=[...h.matchAll(/\b(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]); assert.strictEqual(new Set(fn).size,fn.length,'unique functions');
console.log('static ok', {ids:ids.length,functions:fn.length});
