#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8');
const script=(html.match(/<script type="module">([\s\S]*?)<\/script>/)||[])[1]||'';
let fail=0;const ok=(c,m,d='')=>{if(c)console.log('PASS',m,d);else{console.error('FAIL',m,d);fail++}};
ok(/V12\.2\.4/.test(html)&&/1224-multiview-corner-anchors-closed-shell-20260817/.test(html),'build V12.2.4 esplicita');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]),set=new Set(ids);ok(ids.length===set.size,'ID HTML univoci');
const refs=[...script.matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]),missing=[...new Set(refs.filter(x=>!set.has(x)))];ok(!missing.length,'tutti i riferimenti DOM esistono',missing.join(','));
ok(!/navigator\.mediaDevices|getUserMedia\s*\(|ImageCapture\s*\(/.test(script),'nessuna seconda camera');
ok((script.match(/navigator\.xr\.requestSession\s*\(/g)||[]).length===1,'una sola requestSession XR');
ok(/requiredFeatures:\['local-floor','dom-overlay','camera-access'\]/.test(script),'raw camera nella stessa sessione XR');
ok(/function shouldCapture\(info,manual\)\{[^}]*return !!manual/.test(script),'nessun keyframe RGB automatico');
ok(/id="guidedPrimary"/.test(html)&&/Aggiungi spigolo \+ foto/.test(html),'tracciamento guidato spigolo + foto presente');
ok(/function updateGuidedAimAndOverlay\(view\)/.test(script)&&/G\.currentAim=floorPhase\?guidedFloorAim\(view\):null/.test(script),'loop XR aggiorna il puntatore metrico e può abilitare Aggiungi spigolo');
ok(/id="planCanvas"/.test(html)&&/Pianta metrica verificabile/.test(html),'verifica top-down metrica presente');
ok(/id="layTextures"/.test(html)&&/id="isoScene"/.test(html),'viewer espone texture pareti e reset isometrico');
ok(/id="objectSelect"/.test(html)&&/id="objectRemoveSelected"/.test(html)&&/id="bareRoom"/.test(html),'gestore oggetti con tendina, rimozione e stanza nuda presente');
ok(/id="layObjectBoxes"/.test(html)&&/function semanticOrientedBox/.test(script)&&/RGB point cloud \+ OBB/.test(script),'oggetti rappresentati come OBB orientato + point cloud RGB');
ok(/semanticObjectPointMax:900/.test(script)&&/cellKeys/.test(script),'geometria oggetti limitata in memoria ma appartenenza voxel completa conservata');
ok(/function projectScenePoint\([^)]*\)\{[^}]*vdot\(d,cam\.right\)[^}]*vdot\(d,cam\.up\)/.test(script)&&!/vdot\(d,cam\.right\)\/z/.test(script),'viewer 3D ortografico: nessuna divisione prospettica per z');
ok(/function guidedWallViewMetricsMatrices/.test(script)&&/wallGuideGreenAngleDeg/.test(script)&&/wallGuideYellowAngleDeg/.test(script),'guida posa parete rosso-giallo-verde presente');
ok(/wallGuideBadge/.test(html)&&/rgba\(55,220,125/.test(script)&&/rgba\(255,70,85/.test(script),'overlay AR semitrasparente verde/giallo/rosso presente');
ok(/function guidedWallHit/.test(script)&&/confirmed wall render/.test(script),'render analitico della parete confermata usato per il fit');
ok(/function guidedRansacMode/.test(script)&&/guided RANSAC shell\+XR/.test(script),'fit robusto Deep relativo→metrico presente');
ok(/d<hit\.d-CFG\.guidedObjectGap/.test(script),'punti Deep davanti alla parete diventano residuo/oggetto');
ok(/optical\.push/.test(script)&&/optical-or-opening/.test(script),'punti dietro il guscio diventano aperture/superfici ottiche, non geometria libera');
ok(/p:hit\.p/.test(script),'punti strutturali vengono proiettati sulla parete nota, non conservati come foglio libero');
ok(/function summarizeGuidedWallFeatures/.test(script)&&/wallAnomalyMinFrames/.test(script),'anomalie parete richiedono persistenza multi-vista');
ok(/function buildGuidedWallTextures/.test(script)&&/objects masked; optical\/opening RGB preserved/.test(script),'texture atlas per parete maschera oggetti e conserva RGB di aperture/specchi');
ok(/texture-only score/.test(script)&&/captureRole==='wall'/.test(script),'foto parete resta utilizzabile come RGB texture-only se Deep è debole');
ok(/wallDiagnosticVoxel/.test(script)&&/Deep wall evidence/.test(script),'Deep strutturale globale resta diagnostico e compattato');
ok(/function estimateGuidedCeiling/.test(script)&&/Deep ceiling cluster \+ wall upper envelope/.test(script),'stima soffitto multi-foto presente');
ok(/buildGuidedRoomShell/.test(script)&&/multi-view corner-ray anchors \+ persistent WebXR surfel refinement \+ constrained Deep ceiling/.test(script),'ROOM_SHELL deriva dal perimetro utente');
ok(/if\(!S\.guided\.enabled&&a\.gx%CFG\.rayGridStride/.test(script),'TSDF live disabilitata nel workflow guidato');
ok(/guidedSpatial=\['xr-refine','wall-capture'\]\.includes\(S\.guided\.phase\)/.test(script)&&/allowNativePrimitives/.test(script),'plane/mesh WebXR attive solo nelle fasi guidate di raffinamento/copertura');
ok(/m2:\[0,0,0\]/.test(script)&&/function surfelSigma/.test(script)&&/function surfelPersistence/.test(script),'surfel XR conservano statistiche gaussiane leggere senza seconda cloud');
ok(/function analyzeWallEvidenceFromNative/.test(script)&&/wallRefineBin/.test(script)&&/lineIntersectionNormal2/.test(script),'raffinamento robusto del footprint da persistenza XR presente');
ok(/function rebuildWallPhotoCoverage/.test(script)&&/function rebuildWallDeepCoverage/.test(script)&&/id="wallCoverageReview"/.test(html),'coverage XR/foto/Deep per parete presente');
ok(/persistent XR gaussian/.test(script)&&/gaussianAnchorsForFrame/.test(script),'Deep usa anchor XR persistenti oltre alla depth della stessa vista');
ok(/id="processDeepCount"/.test(html)&&/id="processFuseCount"/.test(html),'barra batch foto Deep/applicate preservata');
ok(/id="reviewModal"[\s\S]*?<div class="modalFooter">[\s\S]*id="rebuildReview"[\s\S]*data-close="reviewModal"/.test(html),'Ricalcola/Chiudi in basso');

ok(/function solveCornerAnchor/.test(script)&&/cornerAnchorMinViews/.test(script)&&/cornerRaySeparationDeg/.test(script),'spigoli 3D ancorati da raggi multi-vista invece di overwrite');
ok(/cornerCeilingSamples/.test(script)&&/multi-view ceiling-corner rays/.test(script),'raccordi parete-soffitto contribuiscono alla quota del soffitto');
ok(/id="guidedExtra"/.test(html)&&/Aggiungi vista dello spigolo/.test(script),'workflow fase 2 guida osservazioni ripetute e mantiene correzione manuale');
ok(/function buildSnappedXrModel/.test(script)&&/WebXR structural snapped/.test(script),'surfel RGB strutturali vengono schiacciati sulle superfici della shell');
ok(/function drawRoomCaps/.test(script)&&/drawRoomCaps\(ctx,cam,w,h\)/.test(script),'preview evidenzia esplicitamente pavimento e soffitto della shell chiusa');
ok(/wallPhotoFinishMin/.test(script)&&/Completa \$\{missingWalls\.length\} pareti/.test(script),'acquisizione foto richiede coverage per parete, non una sola foto simbolica');

ok(/source: 1=XR_structural 2=Deep_structural 3=Deep_residual 4=XR\+Deep_object/.test(script)&&/const objectMap=new Map\(\)/.test(script),'PLY preserva esplicitamente la cloud oggetti XR+Deep oltre alla shell snapped');
ok(/room-scanner-v12\.2\.4-raw/.test(script)&&/2\\\.\[0-4\]/.test(script),'RAW V12.2.4 esportabile e import retrocompatibile');

const events=[...script.matchAll(/\$\('([^']+)'\)\.addEventListener\('([^']+)'/g)].map(m=>`${m[1]}:${m[2]}`),dup=events.filter((x,i)=>events.indexOf(x)!==i);ok(!dup.length,'nessun listener diretto duplicato',dup.join(','));
if(fail)process.exit(1);console.log('\nTutti i test statici V12.2.4 sono passati.');
