#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8');
const script=(html.match(/<script type="module">([\s\S]*?)<\/script>/)||[])[1]||'';
let fail=0;const ok=(c,m,d='')=>{if(c)console.log('PASS',m,d);else{console.error('FAIL',m,d);fail++}};
ok(/V12\.1\.4/.test(html)&&/1214-audit-batch-memory-20260817/.test(html),'build V12.1.4 esplicita');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]),idSet=new Set(ids);ok(ids.length===idSet.size,'ID HTML univoci');
const refs=[...script.matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]),missing=[...new Set(refs.filter(x=>!idSet.has(x)))];ok(!missing.length,'tutti i riferimenti $() hanno elemento DOM',missing.join(','));
ok(!/navigator\.mediaDevices|getUserMedia\s*\(|ImageCapture\s*\(/.test(script),'nessuna seconda camera/API MediaStream nel codice');
ok((script.match(/navigator\.xr\.requestSession\s*\(/g)||[]).length===1,'una sola requestSession XR nel codice');
ok(/requiredFeatures:\['local-floor','dom-overlay','camera-access'\]/.test(script),'camera-access resta required nella stessa sessione XR');
ok(/optionalFeatures:\['depth-sensing','plane-detection','mesh-detection'\]/.test(script),'depth/plane/mesh restano opportunistiche');
ok(/id="processModel"/.test(html)&&/id="processQuality"/.test(html)&&/id="processFill"/.test(html),'batch UI con qualità e progress bar presente');
ok(/id="processDeepCount"/.test(html)&&/id="processFuseCount"/.test(html)&&/id="processWeakCount"/.test(html),'progress distingue foto Deep, fuse e deboli');
ok(/id="processFaster"/.test(html)&&/Riduci qualità e riavvia/.test(html),'downgrade qualità disponibile durante batch');
ok(!/id="rebuildAll"/.test(html)&&!/\$\('rebuildAll'\)/.test(script),'nessun bottone/listener rebuildAll duplicato o fantasma');
const sceneHead=(html.match(/id="sceneModal"[\s\S]*?<div class="modalHead">([\s\S]*?)<\/div>/)||[])[1]||'',reviewHead=(html.match(/id="reviewModal"[\s\S]*?<div class="modalHead">([\s\S]*?)<\/div>/)||[])[1]||'';
ok(!/<button/.test(sceneHead)&&!/<button/.test(reviewHead),'header Scena/Revisione senza pulsanti che coprono la toolbar');
ok(/id="reviewModal"[\s\S]*?<div class="modalFooter">[\s\S]*id="rebuildReview"[\s\S]*data-close="reviewModal"/.test(html),'Ricalcola e Chiudi sono nel footer Revisione');
ok(/id="sceneModal"[\s\S]*?<div class="modalFooter">[\s\S]*data-close="sceneModal"/.test(html),'Chiudi è nel footer Scena');
const keyframeBody=(script.match(/function keyframeFromView\([\s\S]*?\nfunction queueDepth/)||[])[0]||'';ok(!/queueDepth\(k\)/.test(keyframeBody),'acquisizione non avvia automaticamente inferenza Deep pesante');
ok(!/for\(const k of S\.frames\)if\(!k\.deep.*queueDepth/.test(script),'boot modello non lancia automaticamente tutte le foto');
ok(/workerRequest\(S\.worker,'infer'/.test(script)&&!/workerRequest\('infer'/.test(script),'infer Deep usa sempre worker attivo esplicito');
ok(/class RayEvidenceVolume/.test(script)&&/prune\(target=/.test(script)&&/rayDeepMaxVoxels/.test(script),'TSDF ha budget separato e pruning esplicito');
ok(/nativeMaxSurfels:90000/.test(script)&&/deepMaxSurfels:65000/.test(script),'surfels hanno limiti di memoria');
ok(/tuneMemoryBudget/.test(script)&&/navigator\.deviceMemory/.test(script),'budget memoria adattivo sui dispositivi low-memory');
ok(/autoFrameSoftCap:140/.test(script)&&/AUTO_KEYFRAME_SOFT_CAP/.test(script),'keyframe automatici hanno soft-cap senza bloccare le foto manuali');
ok(/quantizeDeepInMemory/.test(script)&&/qdata/.test(script),'mappe Deep fredde quantizzate a 16 bit in RAM');
ok(/anchors:null/.test(script)&&/k\.xrDepthGrid/.test(script),'anchor XR duplicati non persistono nei nuovi keyframe');
ok(/readCameraRGBA\(view,false\)/.test(script),'color painting XR riusa il buffer camera senza copia continua');
ok(/planeUpdateMs:420/.test(script)&&/meshUpdateMs:700/.test(script),'plane/mesh WebXR sono throttled');
ok(/lastChangedTime/.test(script),'mesh/plane invariati possono essere saltati');
ok(/for\(const plane of \[\.\.\.S\.planes\.keys\(\)\]\)if\(!live\.has\(plane\)\)/.test(script)&&/for\(const mesh of \[\.\.\.S\.meshes\.keys\(\)\]\)if\(!live\.has\(mesh\)\)/.test(script),'primitive WebXR non piu rilevate vengono rimosse dalle mappe attive');
ok(/jpegDataUrl/.test(script)&&/evictColdRGBA/.test(script)&&/frameHotRGBA/.test(script),'foto persistono compresse e RGBA freddi vengono rilasciati');
ok(/room-scanner-v12\.1\.4-raw/.test(script)&&/u16-linear/.test(script),'RAW V12.1.4 comprime le mappe Deep in uint16');
ok(/importMaxBytes/.test(script)&&/importMaxVertices/.test(script)&&/importMaxTriangles/.test(script),'import PLY/OBJ/RAW ha limiti di sicurezza');
ok(/importMaxModels:4/.test(script)&&/importMaxTotalVertices:500000/.test(script)&&/importMaxTotalTriangles:900000/.test(script),'import multipli hanno budget aggregato');
ok(/const esc=v=>/.test(script)&&/esc\(m\.name\)/.test(script)&&/esc\(k\.reason\)/.test(script),'campi provenienti da RAW/file importati sono escapati prima di innerHTML');
ok(/serviceWorker\.register/.test(script)&&/updateViaCache:'none'/.test(script),'service worker viene aggiornato senza cache del bootstrap');
ok(/renderReview\(force=false\).*classList\.contains\('hidden'\)/s.test(script),'Review evita generazione miniature quando chiusa');
ok(/rafPending/.test(script),'viewer coalesca requestAnimationFrame');
const ps=script.indexOf('async function processModel'),pc=script.indexOf('S.modelReady=true',ps),fusion=script.indexOf("await rebuildDeep('V12.1.4 batch'",ps),shell=script.indexOf('buildRoomShell(false)',fusion);ok(ps>=0&&fusion>ps&&shell>fusion&&pc>shell,'modello finale diventa ready solo dopo Deep fusion + ROOM_SHELL');
const directEvents=[...script.matchAll(/\$\('([^']+)'\)\.addEventListener\('([^']+)'/g)].map(m=>`${m[1]}:${m[2]}`),dupEvt=directEvents.filter((x,i)=>directEvents.indexOf(x)!==i);ok(!dupEvt.length,'nessun listener diretto duplicato',dupEvt.join(','));
if(fail)process.exit(1);console.log('\nTutti i test statici V12.1.4 sono passati.');
