#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'..','room_scanner_v12.html'),'utf8'),m=html.match(/<script type="module">([\s\S]*?)<\/script>/);if(!m)throw new Error('module missing');
class Ctx{clearRect(){}fillRect(){}strokeRect(){}beginPath(){}moveTo(){}lineTo(){}closePath(){}fill(){}stroke(){}arc(){}fillText(){}putImageData(){}drawImage(){}save(){}restore(){}clip(){}transform(){}createImageData(w,h){return{data:new Uint8ClampedArray(w*h*4)}}getImageData(x,y,w,h){return{data:new Uint8ClampedArray(w*h*4)}}}
class El{constructor(id=''){this.id=id;this.style={setProperty(){}};this.className='';this._classes=new Set(['reviewModal','sceneModal','processModal','hud','arCanvas','coverageCanvas','coverageLegend','planModal'].includes(id)?['hidden']:[]);this.classList={contains:x=>this._classes.has(x),add:x=>this._classes.add(x),remove:x=>this._classes.delete(x),toggle:(x,f)=>{if(f===undefined)f=!this._classes.has(x);f?this._classes.add(x):this._classes.delete(x)}};this.innerHTML='';this.textContent='';this.dataset={};this.checked=true;this.value=id==='processQuality'?'balanced':'';this.files=[];this.disabled=false;this.width=800;this.height=600;this.src=''}addEventListener(){}appendChild(){}setPointerCapture(){}click(){}getContext(){return new Ctx}getBoundingClientRect(){return{left:0,top:0,width:800,height:600}}toDataURL(){return'data:image/jpeg;base64,AA=='}}
const els=new Map(),docEl=new El('html');docEl.requestFullscreen=async()=>true;const document={documentElement:docEl,body:new El('body'),fullscreenElement:null,getElementById:id=>{if(!els.has(id))els.set(id,new El(id));return els.get(id)},querySelectorAll:()=>[],createElement:()=>new El(),addEventListener(){},permissionsPolicy:null,featurePolicy:null};
const context={console,document,window:{addEventListener(){},devicePixelRatio:1,innerHeight:600,isSecureContext:true,visualViewport:{offsetTop:0,height:600,addEventListener(){}}},location:{protocol:'https:'},navigator:{},performance:{now:()=>1000},setTimeout,clearTimeout,requestAnimationFrame:fn=>{fn();return 1},requestIdleCallback:fn=>{fn();return 1},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),alert(){},ImageData:class{constructor(data,w,h){this.data=data;this.width=w;this.height=h}},Image:class{},devicePixelRatio:1,globalThis:null};context.globalThis=context;vm.createContext(context);vm.runInContext(m[1],context,{filename:'v1223.js'});const H=context.__ROOM_SCANNER_V12_2_3__;if(!H)throw new Error('hook missing');
let fail=0;const ok=(c,msg,d='')=>{if(c)console.log('PASS',msg,d);else{console.error('FAIL',msg,d);fail++}},close=(a,b,t=.05)=>Math.abs(a-b)<=t;
// Regression V12.2.1: onXRFrame called a missing aim helper, leaving currentAim null and the corner button disabled forever.
H.state.guided.phase='floor-trace';H.state.guided.floorPoints=[];H.state.xrFrames=1;const c=Math.SQRT1_2,downView={projectionMatrix:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],transform:{matrix:[1,0,0,0,0,c,-c,0,0,c,c,0,0,1.5,0,1],inverse:{matrix:[1,0,0,0,0,c,c,0,0,-c,c,0,0,-1.0606601718,-1.0606601718,1]}}};H.updateGuidedAimAndOverlay(downView);ok(!!H.state.guided.currentAim,'puntatore pavimento metrico aggiornato nel loop XR',H.state.guided.currentAim?H.state.guided.currentAim.p.map(x=>x.toFixed(2)).join(','):'null');ok(document.getElementById('guidedPrimary').disabled===false,'Aggiungi spigolo si abilita quando il reticolo interseca il pavimento');
H.state.guided.floorPoints=[[-2,0,-2],[2,0,-2],[2,0,2],[-2,0,2]].map((p,i)=>({id:`C${i+1}`,p,createdAt:'x',frameId:null,revisions:0}));H.state.guided.closed=true;H.state.guided.confirmed=true;H.state.guided.wallPhotoCounts=[1,1,1,1];
let v=H.guidedPolygonValid();ok(v.ok,'rettangolo guidato valido');const walls=H.guidedWallDescriptors();ok(walls.length===4&&close(walls[0].length,4,.001),'quattro pareti metriche dal perimetro');
const P=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],W=[...P],k={id:1,projection:P,worldFromView:W,worldToView:W,poseInfo:{p:[0,1,0]},captureRole:'corner',wallIndex:null,deep:null,xrDepthGrid:null,quality:{score:.9}};
const guide=H.guidedWallViewMetricsMatrices(P,W,W,walls[0],2.65);ok(guide&&guide.frontal>.99&&guide.angle<2,'guida parete riconosce una vista frontale');
// Orthographic projection: moving a point deeper along the view direction must not change its image scale.
H.state.viewer.target=[0,0,0];H.state.viewer.distance=5;const orthoCam={pos:[0,0,5],target:[0,0,0],f:[0,0,-1],right:[1,0,0],up:[0,1,0]},oa=H.projectScenePoint([1,.4,0],orthoCam,800,600),ob=H.projectScenePoint([1,.4,-2],orthoCam,800,600);ok(Number.isFinite(oa.x)&&close(oa.x,ob.x,1e-9)&&close(oa.y,ob.y,1e-9),'proiezione ortografica invariata lungo la profondità della vista',`A=${oa.x.toFixed(2)},${oa.y.toFixed(2)} B=${ob.x.toFixed(2)},${ob.y.toFixed(2)}`);
const hit=H.guidedWallHit(k,.5,.5,null);ok(hit&&close(hit.d,2,.02)&&hit.wall.index===0,'ray centrale colpisce la parete confermata a 2 m',hit?`d=${hit.d}`:'none');
const samples=[];for(let i=0;i<90;i++){const d=1.4+(i%30)*.045,r=(d-.35)/1.55;samples.push({u:(i%10)/10+.03,v:(i%9)/9+.03,d,r,weight:1})}for(let i=0;i<35;i++)samples.push({u:.1+(i%5)*.03,v:.1+(i%7)*.025,d:.7+(i%11)*.071,r:.2+((i*7)%29)*.103,weight:1});const fit=H.guidedRegression(samples);ok(fit&&fit.med<.05&&close(fit.m,1.55,.12),'RANSAC recupera scale/shift con outlier',fit?`m=${fit.m.toFixed(2)} med=${fit.med.toFixed(3)}`:'none');
const shell=H.buildGuidedRoomShell(2.65,false,true);ok(shell&&shell.watertight&&close(shell.area,16,.01)&&close(shell.height,2.65,.01),'ROOM_SHELL esatta dal perimetro confermato',shell?`area=${shell.area} h=${shell.height}`:'none');
const E=new Map();for(let i=0;i<shell.indices.length;i+=3)for(const [a,b] of [[shell.indices[i],shell.indices[i+1]],[shell.indices[i+1],shell.indices[i+2]],[shell.indices[i+2],shell.indices[i]]]){const key=a<b?`${a},${b}`:`${b},${a}`;E.set(key,(E.get(key)||0)+1)}ok([...E.values()].every(n=>n===2),'mesh stanza realmente chiusa/manifold');
// Deep map: wall background at 2 m, central patch at 1 m = object in front.
k.deep={w:40,h:30,data:new Float32Array(1200).fill(2)};for(let y=10;y<20;y++)for(let x=16;x<24;x++)k.deep.data[y*40+x]=1;k.fit={mode:'direct',m:1,b:0,n:100,med:.01,p90:.02,cells:10,span:1};const cls=H.guidedFrameClassify(k,{meshStride:2,meshMaxVertices:6000});ok(cls.wall.length>20,'background Deep viene assegnato alla parete nota',`wall=${cls.wall.length}`);ok(cls.objects.length>5,'patch più vicina diventa oggetto/residuo',`obj=${cls.objects.length}`);ok(cls.wall.every(q=>Math.abs(q.p[2]+2)<.03),'parete Deep è proiettata sul piano confermato, nessun foglio ruotato');
// Same confirmed wall with a patch far behind: it is an optical/opening region, never structural geometry.
k.captureRole='wall';k.wallIndex=0;for(let y=8;y<14;y++)for(let x=15;x<25;x++)k.deep.data[y*40+x]=3.2;const cls2=H.guidedFrameClassify(k,{meshStride:2,meshMaxVertices:6000});ok(cls2.optical.length>0,'patch dietro la parete viene isolata come apertura/superficie ottica');ok(cls2.wall.every(q=>Math.abs(q.p[2]+2)<.03),'anche con anomalie ottiche la parete resta sul piano metrico');
// Texture masking uses the same confirmed wall ray: foreground is excluded, wall is accepted, behind-shell RGB may be preserved without geometry.
const wall0=walls[0],frontP=[0,1,-2],frontCls=H.wallTexturePixelClass(k,wall0,frontP,.5,.5,2);ok(['wall','object','optical','unknown'].includes(frontCls),'classificatore texture restituisce una classe valida');
const tk={...k,xrDepthGrid:{w:4,h:4,data:new Float32Array(16).fill(2)},deep:null,fit:null};ok(H.wallTexturePixelClass(tk,wall0,frontP,.5,.5,2)==='wall','texture: XR coerente conserva RGB parete');tk.xrDepthGrid.data.fill(1);ok(H.wallTexturePixelClass(tk,wall0,frontP,.5,.5,2)==='object','texture: foreground XR viene mascherato come oggetto');tk.xrDepthGrid.data.fill(3.2);ok(H.wallTexturePixelClass(tk,wall0,frontP,.5,.5,2)==='optical','texture: depth dietro shell è ottica/apertura, RGB preservabile ma geometria esclusa');
const results=[{wall:Array.from({length:80},(_,i)=>({p:[0,2.45+(i%10)*.015,-2],frameId:1})),high:Array.from({length:40},(_,i)=>({p:[0,2.62+(i%3)*.01,0],frameId:i%2+1})),objects:[],floor:[],rejected:[]},{wall:Array.from({length:80},(_,i)=>({p:[0,2.47+(i%10)*.014,2],frameId:2})),high:Array.from({length:40},(_,i)=>({p:[0,2.63+(i%3)*.01,0],frameId:i%2+2})),objects:[],floor:[],rejected:[]}];const ceil=H.estimateGuidedCeiling(results);ok(ceil.height>2.5&&ceil.height<2.75,'soffitto aggregato tra più foto',`${ceil.height.toFixed(2)}m ${Math.round(ceil.confidence*100)}%`);

// Persistent optical samples on two frames form a wall feature without changing room geometry.
const op=[];for(let f=1;f<=2;f++){const optical=[];for(let gy=0;gy<4;gy++)for(let gx=0;gx<5;gx++)optical.push({wallIndex:0,frameId:f,kind:'opening',p:[-1+gx*.08,.8+gy*.08,-2]});op.push({optical})}const feats=H.summarizeGuidedWallFeatures(op,2.65);ok(feats.length>=1&&feats[0].wallIndex===0,'anomalie persistenti diventano feature di parete, non nuova profondità');

// Concave polygon remains valid and watertight; self-crossing polygon is rejected before confirmation.
const L=[[0,0,0],[3,0,0],[3,0,1],[1,0,1],[1,0,3],[0,0,3]];H.state.guided.floorPoints=L.map((p,i)=>({id:`L${i}`,p}));H.state.guided.closed=H.state.guided.confirmed=true;ok(H.guidedPolygonValid().ok,'footprint concavo a L valido');const ls=H.buildGuidedRoomShell(2.5,false,true);const LE=new Map();for(let i=0;i<ls.indices.length;i+=3)for(const [a,b] of [[ls.indices[i],ls.indices[i+1]],[ls.indices[i+1],ls.indices[i+2]],[ls.indices[i+2],ls.indices[i]]]){const key=a<b?`${a},${b}`:`${b},${a}`;LE.set(key,(LE.get(key)||0)+1)}ok(close(ls.area,5,.01)&&[...LE.values()].every(n=>n===2),'stanza a L conserva concavità e chiusura');
H.state.guided.floorPoints=[[0,0,0],[2,0,2],[0,0,2],[2,0,0]].map((p,i)=>({id:`X${i}`,p}));ok(!H.guidedPolygonValid().ok,'perimetro auto-intersecante rifiutato');

// Non-structural object representation: rotated evidence must yield one compact OBB aligned with the object, not with world axes.
const theta=Math.PI/6,objCells=[];for(let iu=-8;iu<=8;iu++)for(let iv=-3;iv<=3;iv++)for(let iy=0;iy<=4;iy++){const u=iu*.07,vv=iv*.07,y=.25+iy*.10,x=.35+u*Math.cos(theta)-vv*Math.sin(theta),z=.2+u*Math.sin(theta)+vv*Math.cos(theta);objCells.push({key:`r${objCells.length}`,p:[x,y,z],color:[150,90,60],confidence:.82,frames:new Set([1,2]),xr:false,deep:true})}const obb=H.semanticOrientedBox(objCells,.14);ok(obb&&Math.abs(Math.cos(obb.yaw-theta))>.97&&obb.extent[0]>obb.extent[2]*1.8,'OBB PCA segue un oggetto ruotato nel piano XZ',obb?`yaw=${(obb.yaw*180/Math.PI).toFixed(1)} ext=${obb.extent.map(x=>x.toFixed(2)).join('x')}`:'none');
// Populate the actual object builder and verify that removal covers every voxel, not only the display sample.
H.state.guided.floorPoints=[[-2,0,-2],[2,0,-2],[2,0,2],[-2,0,2]].map((p,i)=>({id:`R${i}`,p}));H.state.guided.closed=H.state.guided.confirmed=true;H.buildGuidedRoomShell(2.6,false,true);H.state.structuralModel={footprint:[[-2,-2],[2,-2],[2,2],[-2,2]],floorY:0,ceilY:2.6};H.state.surfaces=[];H.state.nativeSurfels=new Map();H.state.deepResidualSurfels=new Map();let oi=0;for(let iu=-7;iu<=7;iu++)for(let iv=-2;iv<=2;iv++)for(let iy=0;iy<=3;iy++){const u=iu*.08,vv=iv*.08,y=.3+iy*.12,x=.2+u*Math.cos(theta)-vv*Math.sin(theta),z=.1+u*Math.sin(theta)+vv*Math.cos(theta),p3=[x,y,z];H.state.deepResidualSurfels.set(`d${oi++}`,{p:p3,color:[120,160,210],confidence:.85,frames:[1,2],evidence:['test residual']})}const built=H.buildPersistentObjects();ok(built.length===1&&built[0].obb&&built[0].representation==='RGB point cloud + OBB','residuo persistente diventa un oggetto selezionabile OBB + cloud',built[0]?`${built[0].cells} cells / ${built[0].points.length} display points`:'none');ok(built[0]&&built[0].points.length<=H.CFG.semanticObjectPointMax&&built[0].cellKeys.length===built[0].cells,'point cloud visuale limitata ma tutte le celle oggetto restano indicizzate');if(built[0]){H.state.objectOverrides.set(built[0].signature,'removed');const rb=H.buildPersistentObjects()[0];ok(rb.status==='removed'&&H.state.removedObjectCells.size===rb.cellKeys.length,'Rimuovi esclude tutte le celle dell oggetto dalla scena/export');}

// V12.2.3: persistent XR wall evidence must prefer the wide outer wall over a nearer parallel furniture face.
H.state.guided.floorPoints=[[-2,0,-2],[2,0,-2],[2,0,2],[-2,0,2]].map((p,i)=>({id:`R${i}`,p,createdAt:'x',frameId:null,revisions:0}));H.state.guided.closed=H.state.guided.confirmed=true;H.state.guided.xrRefineDone=false;H.state.guided.planRevision=20;H.state.nativeSurfels=new Map();H.state.wallCoverage=[];H.state.wallEvidence=null;
let si=0;const put=(p,n=[0,0,1],weight=7,conf=.94)=>H.state.nativeSurfels.set(`g${si++}`,{p,m2:[.001,.001,.001],observations:6,weight,confidence:conf,sources:{'WebXR depth':6},frames:[],evidence:['WebXR depth'],normal:n,normalWeight:weight,color:[160,180,190],colorSamples:2,colorSource:'WebXR raw camera'});
for(let x=-1.9;x<=1.9;x+=.18)for(let y=.25;y<=2.45;y+=.42)put([x,y,-2.24]); // true wall, broad support, offset -24 cm
for(let x=-.75;x<=.75;x+=.15)for(let y=.25;y<=1.85;y+=.38)put([x,y,-1.50]); // furniture face, +50 cm, narrower
const ev=H.analyzeWallEvidenceFromNative(true),e0=ev?.walls?.[0];ok(e0&&e0.offset<-.12&&e0.offset>-.36,'persistenza XR seleziona la parete esterna e non il mobile parallelo',e0?`offset=${(e0.offset*100).toFixed(1)}cm cov=${(e0.coverage*100).toFixed(0)}%`:'none');
const sug=H.computeGuidedRefineSuggestion();ok(sug&&sug.points[0][1]<-2.10&&sug.points[1][1]<-2.10,'intersezioni delle pareti correggono gli spigoli mantenendo il footprint chiuso',sug?`mean=${(sug.meanShift*100).toFixed(1)}cm`:'none');
const cov0=H.wallCoverageSummary(0);ok(cov0.xr>.08,'gaussian surfel persistenti popolano la coverage XR della parete',`XR=${Math.round(cov0.xr*100)}%`);
// Two partial Deep observations of the same wall must accumulate in the same 2-D wall coverage grid.
const ww=H.guidedWallDescriptors()[0],mk=(u,y,frameId)=>({p:[ww.a[0]+(ww.b[0]-ww.a[0])*u,y,ww.a[1]+(ww.b[1]-ww.a[1])*u],wallIndex:0,frameId});const ra={wall:[],optical:[]},rb={wall:[],optical:[]};for(let u=.03;u<.56;u+=.035)for(let y=.18;y<2.55;y+=.20)ra.wall.push(mk(u,y,101));for(let u=.44;u<.98;u+=.035)for(let y=.18;y<2.55;y+=.20)rb.wall.push(mk(u,y,102));H.rebuildWallDeepCoverage([ra,rb],2.7);const dc=H.wallCoverageSummary(0);ok(dc.deep>.55,'più foto parziali si uniscono nella coverage Deep della stessa parete',`Deep=${Math.round(dc.deep*100)}%`);
// Gaussian anchors should be projectable as metric evidence when a Deep frame sees the wall.
const gk={projection:P,worldFromView:W,worldToView:W,deep:{w:20,h:16,data:new Float32Array(320).fill(1)}};const ga=H.gaussianAnchorsForFrame(gk,0,100);ok(Array.isArray(ga),'anchor gaussiani interrogabili dal fit Deep',`n=${ga.length}`);

if(fail)process.exit(1);console.log('\nTutti i test runtime V12.2.3 sono passati.');
