import {pixelRay,projectPoint,qRotate} from '../slam/math.js';
import {normalizeFrame} from './view_puzzle.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const scale=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
const norm=a=>{const n=Math.hypot(...a)||1;return a.map(x=>x/n);};
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];

/**
 * V30.29 hybrid room solver.
 *
 * 1. Globally aligned relative depth becomes a set of uncertain camera rays.
 * 2. Large multi-view planar explanations are extracted first.
 * 3. Only residual observations are represented by a user-bounded particle set.
 * 4. Particles are refined with deterministic annealing / EM.  Updates are
 *    accepted against a fixed-temperature validation loss with backtracking,
 *    so the number shown to the user is directly comparable across iterations.
 */
export class HybridSceneSolver{
  constructor(graph,puzzle,depthScale,{particleBudget=3000,maxObservations=65000,maxPlanes=8,initial=null}={}){
    this.graph=graph?.format==='ROOMSCAN-PROB-GRAPH-1'?graph:(graph?.exportState?.()||graph||{});this.puzzle=puzzle;this.depthScale=depthScale;this.particleBudget=clamp(Math.round(particleBudget||3000),250,10000);this.maxObservations=maxObservations;this.maxPlanes=maxPlanes;this.frames=(this.graph.frames||[]).map(f=>({raw:f,photo:normalizeFrame(f),pose:f.poseEstimate||f.posePrior,K:f.K}));this.frameMap=new Map(this.frames.map((f,i)=>[String(f.raw.frameId),i]));this.deepMap=new Map((this.graph.deepFactors||[]).map(x=>[String(x.frameId),x]));this.observations=[];this.planes=[];this.residual=[];this.particles=[];this.iteration=0;this.stats={validationLoss:Infinity};this.cellSize=.05;this.rng=mulberry32(0x30_29_51);this.restored=!!initial;if(initial)this.restore(initial);
  }
  prepare(){
    this.observations=this.buildObservations();if(!this.observations.length)throw new Error('nessuna osservazione metrica utilizzabile: servono depth globalmente allineate o landmark multi-view');
    this.planes=detectPlanes(this.observations,{maxPlanes:this.maxPlanes,rng:this.rng});snapManhattan(this.planes,this.observations);const membership=assignPlanes(this.observations,this.planes),res=[];for(let i=0;i<this.observations.length;i++)if(membership[i]<.72)res.push(i);this.residual=res;
    if(!this.particles.length)this.particles=initializeParticles(this.observations,this.residual,this.particleBudget);this.cellSize=estimateParticleCell(this.particles);this.stats=this.computeStats({accepted:true,temperature:this.temperature()});return this.stats;
  }
  restore(s){if(!s)return this;if(Array.isArray(s.particles)&&s.particles.length){this.particles=s.particles.map(cloneParticle);this.particleBudget=s.particleBudget||this.particleBudget;this.iteration=s.iteration||0;}if(Array.isArray(s.planes))this.planes=s.planes.map(clonePlane);this.stats=s.stats||this.stats;}
  temperature(){return Math.max(.62,2.6*Math.exp(-this.iteration/28));}
  step(count=1){if(!this.observations.length)this.prepare();for(let k=0;k<count;k++)this.singleStep();return this.stats;}
  singleStep(){
    if(!this.particles.length){this.iteration++;this.stats=this.computeStats({accepted:true,temperature:this.temperature()});return;}
    const temp=this.temperature(),before=this.validationLoss(this.particles),old=this.particles.map(p=>p.p.slice()),candidate=this.emCandidate(temp),baseDamping=Math.max(.32,.72*Math.exp(-this.iteration/180));let damping=baseDamping,accepted=false,loss=before;
    for(let bt=0;bt<5;bt++){for(let i=0;i<this.particles.length;i++){const a=old[i],b=candidate[i]?.p||a;this.particles[i].p=[a[0]+(b[0]-a[0])*damping,a[1]+(b[1]-a[1])*damping,a[2]+(b[2]-a[2])*damping];}loss=this.validationLoss(this.particles);if(loss<=before*(1+2e-4)){accepted=true;break;}damping*=.5;}
    if(!accepted){for(let i=0;i<this.particles.length;i++)this.particles[i].p=old[i];loss=before;}else{for(let i=0;i<this.particles.length;i++){const c=candidate[i];if(!c)continue;this.particles[i].support=c.support;this.particles[i].confidence=c.confidence;this.particles[i].color=c.color;this.particles[i].sigma=c.sigma;}}
    this.iteration++;
    if(this.iteration%7===0)this.tryRebirth();
    this.stats=this.computeStats({accepted,temperature:temp,validationLoss:loss,damping});
  }
  emCandidate(temp){
    const n=this.particles.length,H=Array.from({length:n},()=>new Float64Array(6)),b=Array.from({length:n},()=>new Float64Array(3)),sw=new Float64Array(n),colors=Array.from({length:n},()=>new Float64Array(3)),support=new Uint16Array(n),lastFrame=new Array(n).fill(null),hash=buildParticleHash(this.particles,this.cellSize*Math.max(1,temp*.82)),gate=11.5*temp*temp;
    for(const oi of this.residual){const o=this.observations[oi],hit=nearestParticle(o,this.particles,hash,this.cellSize*Math.max(1,temp*.82),gate);if(!hit)continue;const i=hit.i,e=hit.energy,robust=1/Math.max(1,Math.sqrt(e/4)),w=o.weight*Math.exp(-.5*e/(temp*temp))*robust;if(w<1e-6)continue;accumulateRayInformation(H[i],b[i],o,w);sw[i]+=w;for(let c=0;c<3;c++)colors[i][c]+=w*o.color[c];if(lastFrame[i]!==o.frameId){support[i]++;lastFrame[i]=o.frameId;}}
    const out=new Array(n);for(let i=0;i<n;i++){const p=this.particles[i],prior=1/Math.max(1e-6,(p.sigma||this.cellSize)**2)*.035;H[i][0]+=prior;H[i][3]+=prior;H[i][5]+=prior;b[i][0]+=prior*p.p[0];b[i][1]+=prior*p.p[1];b[i][2]+=prior*p.p[2];const q=solveSym3(H[i],b[i])||p.p.slice(),maxStep=Math.max(.018,this.cellSize*temp*1.4),dv=sub(q,p.p),dn=Math.hypot(...dv),qq=dn>maxStep?add(p.p,scale(dv,maxStep/dn)):q,conf=clamp((sw[i]/(sw[i]+1.5))*(1-Math.exp(-support[i]/2)),.02,.995),sig=Math.max(.006,Math.min(this.cellSize*1.8,1/Math.sqrt(Math.max(1e-6,(H[i][0]+H[i][3]+H[i][5])/3))));out[i]={p:qq,support:Math.max(1,support[i]),confidence:conf,sigma:sig,color:sw[i]>0?Array.from(colors[i],x=>clamp(Math.round(x/sw[i]),0,255)):p.color.slice()};}return out;
  }
  tryRebirth(){
    if(this.particles.length<32)return;const hash=buildParticleHash(this.particles,this.cellSize),bad=[];for(let i=0;i<this.particles.length;i++)if((this.particles[i].support||0)<1||(this.particles[i].confidence||0)<.04)bad.push(i);if(!bad.length)return;const candidates=[];const stride=Math.max(1,Math.ceil(this.residual.length/9000));for(let k=0;k<this.residual.length;k+=stride){const oi=this.residual[k],o=this.observations[oi],h=nearestParticle(o,this.particles,hash,this.cellSize,9);if(!h)candidates.push({oi,score:o.weight});}candidates.sort((a,b)=>b.score-a.score);if(!candidates.length)return;const before=this.validationLoss(this.particles),backup=bad.map(i=>cloneParticle(this.particles[i]));let used=0;for(let bi=0;bi<bad.length&&used<candidates.length;bi++,used++){const o=this.observations[candidates[used].oi];this.particles[bad[bi]]={p:o.point.slice(),color:o.color.slice(),confidence:.12,support:1,sigma:Math.max(.012,o.sigmaLateral),source:'rebirth'};}const after=this.validationLoss(this.particles);if(after>before){for(let i=0;i<bad.length;i++)this.particles[bad[i]]=backup[i];}
  }
  validationLoss(particles=this.particles){
    if(!this.observations.length)return Infinity;const hash=buildParticleHash(particles,this.cellSize),stride=Math.max(1,Math.ceil(this.observations.length/14000));let sum=0,sw=0;for(let i=0;i<this.observations.length;i+=stride){const o=this.observations[i],pp=planeProbability(o,this.planes);let e;if(pp>.72){const pl=bestPlane(o,this.planes);e=pl?Math.min(9,(Math.abs(dot(pl.n,o.point)-pl.d)/Math.max(.018,o.sigmaDepth*.55))**2):9;}else{const hit=nearestParticle(o,particles,hash,this.cellSize,16);e=hit?Math.min(16,hit.energy):16;}const w=Math.max(.01,o.weight);sum+=w*e;sw+=w;}return sw?sum/sw:Infinity;
  }
  computeStats(extra={}){const planeExplained=this.observations.length?1-this.residual.length/this.observations.length:0,mesh=buildPlaneMesh(this.planes),loss=Number.isFinite(extra.validationLoss)?extra.validationLoss:this.validationLoss();return {iteration:this.iteration,validationLoss:loss,temperature:extra.temperature??this.temperature(),accepted:extra.accepted??true,damping:extra.damping??null,observations:this.observations.length,particles:this.particles.length,planes:this.planes.length,planeExplainedFraction:planeExplained,shoeboxConfidence:mesh.shoeboxConfidence||0,metricMode:this.depthScale?.metricModel?.mode||null,depthAlignmentError:this.depthScale?.stats?.meanEdgeResidual??Infinity,connectedFraction:this.puzzle?.stats?.connectedFraction??0};}
  preview(){return {gaussians:this.particles.map((p,i)=>({id:`particle-${i}`,position:p.p.slice(),color:p.color.slice(),opacity:clamp(.18+.78*p.confidence,.15,.95),scale:[p.sigma,p.sigma,p.sigma],covariance:[p.sigma*p.sigma,0,0,p.sigma*p.sigma,0,p.sigma*p.sigma],confidence:p.confidence,support:p.support,radius:p.sigma})),mesh:buildPlaneMesh(this.planes)};}
  exportState(){return {format:'ROOMSCAN-PUZZLE-HYBRID-1',iteration:this.iteration,particleBudget:this.particleBudget,particles:this.particles.map(cloneParticle),planes:this.planes.map(clonePlane),stats:this.stats,puzzle:this.puzzle?.exportState?.()||null,depthScale:this.depthScale?.exportState?.()||null};}
  buildObservations(){
    const out=[],largest=new Set(this.puzzle?.components?.[0]||this.frames.map((_,i)=>i)),allowedIds=new Set([...largest].map(i=>String(this.puzzle.frames[i]?.frameId||'')));
    // All ray distances below use EUCLIDEAN range along a normalized ray. Deep
    // and plane-sweep MVS report pinhole optical-Z; converting Z/rayCam.z here
    // avoids the off-axis bowing that otherwise bends planar walls.
    for(const l of this.graph.landmarkFactors||[]){if((l.probability||0)<.025)continue;for(const m of l.measurements||[]){const fi=this.frameMap.get(String(m.frameId));if(fi==null)continue;const f=this.frames[fi],q=projectPoint(f.pose,f.K,l.point);if(!q||q.z<=.15||q.z>15)continue;const ri=rayInfo(f,m.u,m.v),v=sub(l.point,f.pose.p),range=Math.max(.12,dot(v,ri.world)),sigma=Math.max(.008,Math.sqrt(Math.max(1e-6,traceCov(l.covariance||[])/3))),w=clamp((l.probability||.1)*(m.probability||.1)*1.7,.02,1.6);out.push(makeObs(f,ri.world,range,sigma,Math.max(.006,q.z/Math.max(f.K.fx,f.K.fy)*.9),w,colorAt(f,m.u,m.v),String(m.frameId),'track',l.point,q.z));}}
    // MVS is independent evidence. Its stored depth is camera optical-Z, not
    // Euclidean range, so it must be converted with the exact pixel ray.
    for(const mf of this.graph.mvsFactors||[]){if(out.length>=this.maxObservations*.42)break;const fi=this.frameMap.get(String(mf.frameId));if(fi==null)continue;const f=this.frames[fi],step=Math.max(1,Math.ceil((mf.count||mf.samples?.length||0)/600));let k=0;for(const s of iterateMvs(mf)){if((k++%step)!==0)continue;if(!(s.depth>.15&&s.depth<15))continue;const ri=rayInfo(f,s.u,s.v),range=s.depth/ri.rayZ,sigZ=Math.max(.012,s.sigmaDepth||s.depth*.07),sigRange=sigZ/ri.rayZ,w=clamp((s.probability||.1)*(s.priorEscaped?1.22:1),.02,.95),p=add(f.pose.p,scale(ri.world,range));out.push(makeObs(f,ri.world,range,sigRange,Math.max(.008,s.depth/Math.max(f.K.fx,f.K.fy)*1.4),w,s.color||colorAt(f,s.u,s.v),String(mf.frameId),'mvs',p,s.depth));if(out.length>=this.maxObservations*.42)break;}}
    // Dense relative depth only enters after photo-puzzle + sequence calibration.
    const deepFrames=[...this.deepMap.values()].filter(d=>allowedIds.has(String(d.frameId))&&this.depthScale?.transforms?.get(String(d.frameId))?.connected),remaining=Math.max(0,this.maxObservations-out.length),perFrame=Math.max(24,Math.floor(remaining/Math.max(1,deepFrames.length)));
    for(const d of deepFrames){const fi=this.frameMap.get(String(d.frameId));if(fi==null)continue;const f=this.frames[fi],trConf=this.depthScale.frameConfidence(String(d.frameId));if(trConf<.015)continue;const total=d.cols*d.rows,stride=Math.max(1,Math.ceil(Math.sqrt(total/perFrame)));for(let gy=0;gy<d.rows;gy+=stride)for(let gx=0;gx<d.cols;gx+=stride){if(out.length>=this.maxObservations)break;const raw=d.raw[gy*d.cols+gx],z=this.depthScale.metricDepth(String(d.frameId),raw);if(!(z>.18&&z<12))continue;const u=(gx+.5)/d.cols*(f.K.width||f.raw.width),v=(gy+.5)/d.rows*(f.K.height||f.raw.height),ri=rayInfo(f,u,v),range=z/ri.rayZ,rel=clamp((this.depthScale.metricModel?.error||.14)*1.35+(1-trConf)*.20,.055,.42),sd=Math.max(.025,z*rel)/ri.rayZ,sl=Math.max(.010,z/Math.max(f.K.fx,f.K.fy)*1.8),w=clamp(.34*trConf*Math.exp(-2.5*(this.depthScale.metricModel?.error||.2)),.012,.34),p=add(f.pose.p,scale(ri.world,range));out.push(makeObs(f,ri.world,range,sd,sl,w,colorAt(f,u,v),String(d.frameId),'deep',p,z));}}
    return out;
  }
}

function rayInfo(f,u,v){const cam=pixelRay(f.K,u,v),rayZ=Math.max(.08,cam[2]),world=norm(qRotate(f.pose.q,cam));return {cam,world,rayZ};}
function makeObs(f,dir,depth,sd,sl,w,color,frameId,source,point,zDepth=null){return {o:f.pose.p.slice(),d:dir,depth,zDepth:Number.isFinite(zDepth)?zDepth:null,sigmaDepth:sd,sigmaLateral:sl,weight:w,color,frameId,source,point:point?.slice?.()||add(f.pose.p,scale(dir,depth))};}
function traceCov(c){return (+c?.[0]||.0004)+(+c?.[3]||.0004)+(+c?.[5]||.0016);}
function colorAt(f,u,v){const p=f.photo;if(!p?.rgb?.length)return [175,195,210];const sw=f.K.width||f.raw.width||p.width,sh=f.K.height||f.raw.height||p.height,x=clamp(Math.floor(u/sw*p.width),0,p.width-1),y=clamp(Math.floor(v/sh*p.height),0,p.height-1),i=(y*p.width+x)*3;return [p.rgb[i],p.rgb[i+1],p.rgb[i+2]];}

export function detectPlanes(obs,{maxPlanes=8,minInliers=70,rng=mulberry32(1)}={}){
  const usable=[];for(let i=0;i<obs.length;i++){const o=obs[i];if(o.weight>.018&&o.point.every(Number.isFinite))usable.push(i);}const maxSample=6500,step=Math.max(1,Math.ceil(usable.length/maxSample)),active=usable.filter((_,i)=>i%step===0),planes=[];
  for(let pi=0;pi<maxPlanes&&active.length>=minInliers;pi++){
    let best=null;const hypotheses=Math.min(220,60+Math.floor(active.length/30));for(let h=0;h<hypotheses;h++){const ia=active[Math.floor(rng()*active.length)],ib=active[Math.floor(rng()*active.length)],ic=active[Math.floor(rng()*active.length)];if(ia===ib||ia===ic||ib===ic)continue;const p=plane3(obs[ia].point,obs[ib].point,obs[ic].point);if(!p)continue;let score=0,count=0;const frames=new Set();for(const oi of active){const o=obs[oi],thr=clamp(planeSigma(o,p.n)*1.75,.014,.15),r=Math.abs(dot(p.n,o.point)-p.d)/thr;if(r<1.35){const ww=o.weight*Math.exp(-.5*r*r);score+=ww;count++;if(r<1)frames.add(o.frameId);}}if(count>=minInliers&&frames.size>=3&&(!best||score>best.score))best={...p,score,count};}
    if(!best)break;let inliers=active.filter(oi=>{const o=obs[oi],thr=clamp(planeSigma(o,best.n)*1.75,.014,.15);return Math.abs(dot(best.n,o.point)-best.d)<1.45*thr;});if(inliers.length<minInliers)break;let plane=refinePlane(obs,inliers);if(!plane)break;inliers=active.filter(oi=>{const o=obs[oi],thr=clamp(planeSigma(o,plane.n)*1.55,.012,.13);return Math.abs(dot(plane.n,o.point)-plane.d)<1.25*thr;});const frames=new Set(inliers.map(i=>obs[i].frameId));if(inliers.length<minInliers||frames.size<3)break;plane=refinePlane(obs,inliers);const bounds=planeBounds(plane,obs,inliers),area=(bounds.maxU-bounds.minU)*(bounds.maxV-bounds.minV),confidence=clamp((1-plane.eigen[0]/Math.max(1e-9,plane.eigen[0]+plane.eigen[1]+plane.eigen[2]))*(1-Math.exp(-frames.size/3))*(1-Math.exp(-inliers.length/160))*Math.min(1,area/.8),.05,.995);if(area<.18||confidence<.18)break;plane={...plane,...bounds,area,confidence,supportFrames:frames.size,inlierCount:inliers.length,inliers};planes.push(plane);const remove=new Set(inliers.filter(i=>{const o=obs[i],thr=clamp(planeSigma(o,plane.n)*1.35,.010,.11);return Math.abs(dot(plane.n,o.point)-plane.d)<thr;}));const next=active.filter(i=>!remove.has(i));if(next.length>active.length*.92)break;active.splice(0,active.length,...next);
  }return planes;
}

export function snapManhattan(planes,obs,{angleDeg=9}={}){
  if(planes.length<2)return null;const sorted=planes.slice().sort((a,b)=>b.confidence*b.area-a.confidence*a.area),a0=norm(sorted[0].n);let second=sorted.find(p=>Math.abs(dot(a0,p.n))<.55),a1;if(second){const q=sub(second.n,scale(a0,dot(second.n,a0)));a1=norm(q);}else{const t=Math.abs(a0[1])<.8?[0,1,0]:[1,0,0];a1=norm(sub(t,scale(a0,dot(t,a0))));}const a2=norm(cross(a0,a1)),axes=[a0,a1,a2],cos=Math.cos(angleDeg*Math.PI/180);
  for(const p of planes){let best=0,bd=0,sign=1;for(let k=0;k<3;k++){const d=dot(p.n,axes[k]);if(Math.abs(d)>bd){bd=Math.abs(d);best=k;sign=d>=0?1:-1;}}if(bd<cos)continue;p.n=scale(axes[best],sign);p.d=weightedMedian(p.inliers.map(i=>dot(p.n,obs[i].point)),p.inliers.map(i=>obs[i].weight));p.axis=best;p.snapped=true;Object.assign(p,planeBounds(p,obs,p.inliers));p.area=(p.maxU-p.minU)*(p.maxV-p.minV);}
  return axes;
}

function planeSigma(o,n){const c=clamp(Math.abs(dot(o.d,n)),0,1),sd=Math.max(.004,o.sigmaDepth||.05),sl=Math.max(.003,o.sigmaLateral||sd*.35);return Math.sqrt(sl*sl+(sd*sd-sl*sl)*c*c);}
function assignPlanes(obs,planes){const out=new Float32Array(obs.length);for(let i=0;i<obs.length;i++)out[i]=planeProbability(obs[i],planes);return out;}
function planeProbability(o,planes){let best=0;for(const p of planes){const dist=Math.abs(dot(p.n,o.point)-p.d),thr=clamp(planeSigma(o,p.n)*1.55,.012,.13),r=dist/thr;if(r>2.4)continue;const uv=planeUv(p,o.point),margin=Math.max(.04,Math.sqrt(p.area)*.04);if(uv[0]<p.minU-margin||uv[0]>p.maxU+margin||uv[1]<p.minV-margin||uv[1]>p.maxV+margin)continue;best=Math.max(best,p.confidence*Math.exp(-.5*r*r));}return best;}
function bestPlane(o,planes){let best=null,bp=0;for(const p of planes){const pr=planeProbability(o,[p]);if(pr>bp){bp=pr;best=p;}}return best;}

export function initializeParticles(obs,residual,budget){if(!residual.length)return [];const pts=residual.map(i=>obs[i].point),box=bounds3(pts),vol=Math.max(1e-6,(box.max[0]-box.min[0])*(box.max[1]-box.min[1])*(box.max[2]-box.min[2])),target=Math.min(budget,residual.length);let cell=Math.cbrt(vol/Math.max(1,target))*.72,bins;for(let it=0;it<5;it++){bins=clusterObs(obs,residual,cell);if(bins.size>target*1.35)cell*=1.16;else if(bins.size<target*.72)cell*=.82;else break;}const items=[...bins.values()].sort((a,b)=>b.weight-a.weight).slice(0,target),out=items.map(x=>({p:x.sum.map(v=>v/x.weight),color:x.color.map(v=>clamp(Math.round(v/x.weight),0,255)),confidence:clamp(x.weight/(x.weight+1),.06,.7),support:Math.max(1,x.frames.size),sigma:Math.max(.008,cell*.45),source:'initial'}));return out;}
function clusterObs(obs,ids,cell){const m=new Map();for(const i of ids){const o=obs[i],k=hashKey(o.point,cell),x=m.get(k)||{sum:[0,0,0],color:[0,0,0],weight:0,frames:new Set()};const w=Math.max(.01,o.weight);for(let c=0;c<3;c++){x.sum[c]+=o.point[c]*w;x.color[c]+=o.color[c]*w;}x.weight+=w;x.frames.add(o.frameId);m.set(k,x);}return m;}
function estimateParticleCell(p){if(p.length<2)return .05;const box=bounds3(p.map(x=>x.p)),vol=Math.max(1e-6,(box.max[0]-box.min[0])*(box.max[1]-box.min[1])*(box.max[2]-box.min[2]));return clamp(Math.cbrt(vol/Math.max(1,p.length)),.015,.18);}

function buildParticleHash(particles,cell){const m=new Map();for(let i=0;i<particles.length;i++){const k=hashKey(particles[i].p,cell),a=m.get(k)||[];a.push(i);m.set(k,a);}return {map:m,cell};}
function nearestParticle(o,particles,hash,cell,gate){const q=o.point,cx=Math.floor(q[0]/cell),cy=Math.floor(q[1]/cell),cz=Math.floor(q[2]/cell);let best=null;for(let dz=-1;dz<=1;dz++)for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const a=hash.map.get(`${cx+dx},${cy+dy},${cz+dz}`)||[];for(const i of a){const p=particles[i].p,v=sub(p,o.o),t=dot(v,o.d),along=(t-o.depth)/Math.max(.008,o.sigmaDepth),perpVec=sub(v,scale(o.d,t)),perp=Math.hypot(...perpVec)/Math.max(.005,o.sigmaLateral),e=along*along+perp*perp;if(e<gate&&(!best||e<best.energy))best={i,energy:e};}}return best;}
function accumulateRayInformation(H,b,o,w){const d=o.d,il=1/Math.max(1e-8,o.sigmaLateral*o.sigmaLateral),ia=1/Math.max(1e-8,o.sigmaDepth*o.sigmaDepth),k=ia-il,P=[il+k*d[0]*d[0],k*d[0]*d[1],k*d[0]*d[2],il+k*d[1]*d[1],k*d[1]*d[2],il+k*d[2]*d[2]],x=o.point;for(let i=0;i<6;i++)H[i]+=w*P[i];b[0]+=w*(P[0]*x[0]+P[1]*x[1]+P[2]*x[2]);b[1]+=w*(P[1]*x[0]+P[3]*x[1]+P[4]*x[2]);b[2]+=w*(P[2]*x[0]+P[4]*x[1]+P[5]*x[2]);}
function solveSym3(H,b){const [a,d,e,c,f,g]=H,det=a*(c*g-f*f)-d*(d*g-e*f)+e*(d*f-e*c);if(Math.abs(det)<1e-12)return null;const i00=(c*g-f*f)/det,i01=(e*f-d*g)/det,i02=(d*f-e*c)/det,i11=(a*g-e*e)/det,i12=(d*e-a*f)/det,i22=(a*c-d*d)/det;return [i00*b[0]+i01*b[1]+i02*b[2],i01*b[0]+i11*b[1]+i12*b[2],i02*b[0]+i12*b[1]+i22*b[2]];}

export function buildPlaneMesh(planes){
  const strong=planes.filter(p=>p.confidence>.32&&p.area>.18),box=tryShoebox(strong);if(box)return box;const vertices=[],colors=[],faces=[];for(const p of strong){const c=planeCorners(p),base=vertices.length/3,col=planeColor(p);for(const x of c){vertices.push(...x);colors.push(...col);}faces.push(base,base+1,base+2,base,base+2,base+3);}return {vertices:new Float32Array(vertices),colors:new Uint8Array(colors),faces:new Uint32Array(faces),planes:strong.map(planePublic),shoebox:false,shoeboxConfidence:0,meanPlanarity:strong.length?strong.reduce((s,p)=>s+p.confidence,0)/strong.length:0};}
function tryShoebox(planes){const groups=[[],[],[]];for(const p of planes)if(Number.isInteger(p.axis)&&p.area>.65&&p.confidence>.48)groups[p.axis].push(p);if(groups.some(g=>g.length<2))return null;const axes=[];for(let a=0;a<3;a++){const ref=groups[a][0].n,axis=norm(ref),vals=groups[a].map(p=>({p,v:p.d/dot(p.n,axis)})).filter(x=>Number.isFinite(x.v)).sort((x,y)=>x.v-y.v);if(vals.length<2||vals.at(-1).v-vals[0].v<.55)return null;axes.push({axis,min:vals[0].v,max:vals.at(-1).v,conf:Math.min(vals[0].p.confidence,vals.at(-1).p.confidence)});}const ortho=Math.abs(dot(axes[0].axis,axes[1].axis))+Math.abs(dot(axes[0].axis,axes[2].axis))+Math.abs(dot(axes[1].axis,axes[2].axis));if(ortho>.18)return null;const corners=[];for(let z=0;z<2;z++)for(let y=0;y<2;y++)for(let x=0;x<2;x++){let p=[0,0,0];for(const [k,b] of [[0,x],[1,y],[2,z]])p=add(p,scale(axes[k].axis,b?axes[k].max:axes[k].min));corners.push(p);}const idx=[0,1,3,0,3,2,4,6,7,4,7,5,0,4,5,0,5,1,2,3,7,2,7,6,0,2,6,0,6,4,1,5,7,1,7,3],vertices=new Float32Array(corners.flat()),colors=new Uint8Array(corners.flatMap(()=>[188,205,214])),faces=new Uint32Array(idx),conf=clamp((axes[0].conf+axes[1].conf+axes[2].conf)/3*(1-ortho),0,1);return {vertices,colors,faces,planes:planes.map(planePublic),shoebox:true,shoeboxConfidence:conf,meanPlanarity:planes.reduce((s,p)=>s+p.confidence,0)/planes.length};}
function planeCorners(p){const {u,v}=planeBasis(p.n),o=scale(p.n,p.d);return [[p.minU,p.minV],[p.maxU,p.minV],[p.maxU,p.maxV],[p.minU,p.maxV]].map(([a,b])=>add(o,add(scale(u,a),scale(v,b))));}
function planeColor(p){const k=Number.isInteger(p.axis)?p.axis:3;return [[190,205,220],[210,195,178],[185,215,190],[200,200,205]][k];}
function planePublic(p){return {n:p.n.slice(),d:p.d,confidence:p.confidence,area:p.area,axis:p.axis??null,supportFrames:p.supportFrames,inlierCount:p.inlierCount,minU:p.minU,maxU:p.maxU,minV:p.minV,maxV:p.maxV};}

function plane3(a,b,c){const n=norm(cross(sub(b,a),sub(c,a)));if(Math.hypot(...n)<.9)return null;const area=Math.hypot(...cross(sub(b,a),sub(c,a)));if(area<1e-5)return null;return {n,d:dot(n,a)};}
function refinePlane(obs,ids){let sw=0,c=[0,0,0];for(const i of ids){const w=Math.max(.005,obs[i].weight);sw+=w;c=add(c,scale(obs[i].point,w));}if(!sw)return null;c=scale(c,1/sw);const C=new Float64Array(6);for(const i of ids){const o=obs[i],w=Math.max(.005,o.weight),x=sub(o.point,c);C[0]+=w*x[0]*x[0];C[1]+=w*x[0]*x[1];C[2]+=w*x[0]*x[2];C[3]+=w*x[1]*x[1];C[4]+=w*x[1]*x[2];C[5]+=w*x[2]*x[2];}for(let i=0;i<6;i++)C[i]/=sw;const eig=eigenSym3(C),n=eig.vectors[0];return {n,d:dot(n,c),centroid:c,eigen:eig.values};}
function planeBounds(p,obs,ids){const {u,v}=planeBasis(p.n),o=scale(p.n,p.d),us=[],vs=[];for(const i of ids){const x=sub(obs[i].point,o);us.push(dot(x,u));vs.push(dot(x,v));}return {basisU:u,basisV:v,minU:quantile(us,.03),maxU:quantile(us,.97),minV:quantile(vs,.03),maxV:quantile(vs,.97)};}
function planeBasis(n){const t=Math.abs(n[1])<.82?[0,1,0]:[1,0,0],u=norm(cross(t,n)),v=norm(cross(n,u));return {u,v};}function planeUv(p,x){const o=scale(p.n,p.d),q=sub(x,o),{u,v}=p.basisU?{u:p.basisU,v:p.basisV}:planeBasis(p.n);return [dot(q,u),dot(q,v)];}
function eigenSym3(c){let A=[[c[0],c[1],c[2]],[c[1],c[3],c[4]],[c[2],c[4],c[5]]],V=[[1,0,0],[0,1,0],[0,0,1]];for(let it=0;it<12;it++){let p=0,q=1,m=Math.abs(A[0][1]);for(const [i,j] of [[0,2],[1,2]])if(Math.abs(A[i][j])>m){m=Math.abs(A[i][j]);p=i;q=j;}if(m<1e-10)break;const phi=.5*Math.atan2(2*A[p][q],A[q][q]-A[p][p]),cs=Math.cos(phi),sn=Math.sin(phi);for(let k=0;k<3;k++){const apk=A[p][k],aqk=A[q][k];A[p][k]=cs*apk-sn*aqk;A[q][k]=sn*apk+cs*aqk;}for(let k=0;k<3;k++){const akp=A[k][p],akq=A[k][q];A[k][p]=cs*akp-sn*akq;A[k][q]=sn*akp+cs*akq;const vkp=V[k][p],vkq=V[k][q];V[k][p]=cs*vkp-sn*vkq;V[k][q]=sn*vkp+cs*vkq;}}const items=[0,1,2].map(i=>({value:A[i][i],vector:norm([V[0][i],V[1][i],V[2][i]])})).sort((a,b)=>a.value-b.value);return {values:items.map(x=>x.value),vectors:items.map(x=>x.vector)};}

function bounds3(pts){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const p of pts)for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[k]);max[k]=Math.max(max[k],p[k]);}return {min,max};}function hashKey(p,c){return `${Math.floor(p[0]/c)},${Math.floor(p[1]/c)},${Math.floor(p[2]/c)}`;}
function quantile(a,q){const b=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return 0;const x=(b.length-1)*q,i=Math.floor(x),t=x-i;return b[i]*(1-t)+b[Math.min(b.length-1,i+1)]*t;}function weightedMedian(v,w){const a=v.map((x,i)=>[x,Math.max(.001,w[i]||.001)]).filter(x=>Number.isFinite(x[0])).sort((a,b)=>a[0]-b[0]),s=a.reduce((n,x)=>n+x[1],0);let c=0;for(const x of a){c+=x[1];if(c>=s/2)return x[0];}return a.at(-1)?.[0]||0;}
function cloneParticle(p){return {p:p.p.slice(),color:p.color.slice(),confidence:+p.confidence,support:+p.support,sigma:+p.sigma,source:p.source||null};}function clonePlane(p){return {...p,n:p.n.slice(),centroid:p.centroid?.slice?.(),eigen:p.eigen?.slice?.(),basisU:p.basisU?.slice?.(),basisV:p.basisV?.slice?.(),inliers:Array.isArray(p.inliers)?p.inliers.slice():[]};}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function* iterateMvs(m){if(!m)return;if(!m.packed){yield*(m.samples||[]);return;}const n=m.count||Math.floor((m.data?.length||0)/8),a=m.data||[],nn=m.normal||[],cc=m.color||[],fl=m.flags||[];for(let i=0;i<n;i++){const o=i*8;yield {u:a[o],v:a[o+1],depth:a[o+2],probability:a[o+3],sigmaDepth:a[o+4],cost:a[o+5],distinctiveness:a[o+6],photoAgreement:a[o+7],priorEscaped:!!fl[i],sourceFrames:m.sourceFrames||[],normal:[nn[i*3],nn[i*3+1],nn[i*3+2]],color:[cc[i*3],cc[i*3+1],cc[i*3+2]]};}}
