/**
 * V30.52 diagnostic decision tree. It turns the large raw diagnostics stream
 * into a compact stage-by-stage explanation of the first weak link.
 */
const finite=(x,d=null)=>Number.isFinite(Number(x))?Number(x):d;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

export function buildPipelineTestSnapshot(input={}){
  const graph=input.graph||{},opt=input.optimizer||{},edge=opt.candidateStats?.edgeSwitches||opt.stats?.edgeSwitches||{},alva=opt.candidateStats?.alvaSwitches||opt.stats?.alvaSwitches||{},surface=input.surface||{},mvs=surface.mvsValidation||{},mesh=surface.meshQuality||{},policy=surface.geometryPolicy||{},depth=surface.depthGeometryPolicy||{},cons=surface.globalSurfaceConsensus||surface.surfaceConsensus||{},cleanup=surface.meshCleanup||{},archive=input.photoArchive||{},processing=input.processing||{},tracking=input.tracking||{},fast=input.fastLane||{},dense=input.dense||{};
  const stages=[];
  stages.push(stage('Acquisizione RGB/Alva',acquisitionStatus({archive,tracking,fast,graph}),{archived:finite(archive.accepted,0),backpressureDropped:finite(archive.backpressureDropped,0),persistentFeatures:finite(tracking.persistentFeatures,0),newFeatures:finite(tracking.newFeatures,0),quarantinedFrames:finite(tracking.quarantinedFrames,0),maxFastLaneGapMs:finite(fast.maxGapMs,0)}));
  stages.push(stage('Scaffold RGB',rgbStatus({graph,edge}),{frames:finite(graph.frames,0),photoEdges:finite(graph.photoEdges,0),importFraction:finite(graph.photoEdgeImportFraction,0),translationDirectionEdges:finite(edge.translationDirectionEdges,0),epipolarResidualDeg:finite(edge.meanEpipolarPlaneResidualDeg),lineInlierFraction:finite(edge.translationDirectionMeanInlierFraction),translationResidualDeg:finite(edge.meanTranslationDirectionResidualDeg),rgbActiveFraction:finite(opt.candidateStats?.rgbActiveFraction??opt.stats?.rgbActiveFraction),alvaTranslationMean:finite(alva.translationMean)}));
  stages.push(stage('Deep adattivo',deepStatus({processing,depth}),{rounds:finite(processing.deepRounds,0),deepAccepted:finite(processing.deepAccepted,0),uncertainty:finite(processing.uncertainty),medianRelativeResidual:finite(depth.medianRelativeResidual),p90RelativeResidual:finite(depth.p90RelativeResidual),meanDepthConfidence:finite(depth.meanDepthConfidence),commitAllowed:depth.commitAllowed===true}));
  stages.push(stage('MVS finale',mvsStatus(mvs),{input:finite(mvs.input,0),committed:finite(mvs.committed,0),commitFraction:finite(mvs.commitFraction,0),poseBoundFactors:finite(mvs.poseBoundFactors,0),legacyPoseBoundFactors:finite(mvs.legacyPoseBoundFactors,0),poseRejectedSamples:finite(mvs.poseRejectedSamples,0),meanParallaxDeg:finite(mvs.meanObservableParallaxDeg),meanDepthSensitivityPx:finite(mvs.meanDepthSensitivityPx),maxPoseDriftTranslation:finite(mvs.maxEstimateRelativePoseDriftTranslation)}));
  stages.push(stage('Consenso superficie',surfaceStatus({cons,surface}),{rawGaussians:finite(surface.rawGaussians??cons.input,0),clusters:finite(cons.clusters,0),authoritative:finite(cons.authoritative,finite(surface.committedGaussians,0)),medianConfidence:finite(cons.medianConfidence),occupiedCells:finite(cons.occupiedCells,0),visible:finite(surface.display?.visible),hidden:finite(surface.display?.hidden)}));
  stages.push(stage('Mesh / TSDF',meshStatus({mesh,policy,cleanup,surface}),{committed:surface.committed===true,reason:surface.withheldReason||policy.reason||null,faces:finite(mesh.faceCount,finite(surface.committedFaces,0)),components:finite(mesh.componentCount,0),largestComponentFraction:finite(mesh.largestComponentFraction,0),fragmentationScore:finite(mesh.fragmentationScore,1),scaleRatio:finite(policy.scaleRatio),discardedVertexFraction:finite(cleanup.discardedVertexFraction,0)}));
  const firstFailure=stages.find(s=>s.status==='fail')||stages.find(s=>s.status==='warn')||null,counts=summarizeEvents(input.events||[]),critical=(input.events||[]).filter(e=>e&&['warn','error'].includes(String(e.level||'').toLowerCase())).slice(-80).map(compactEvent);
  return {format:'ROOMSCAN-V30-PIPELINE-TEST-1',build:input.build||null,createdAt:Date.now(),stages,firstFailure:firstFailure?{name:firstFailure.name,status:firstFailure.status,reasons:firstFailure.reasons,actions:firstFailure.actions}:null,eventCounts:counts,criticalEvents:critical,raw:{graph,optimizer:compactOptimizer(opt),processing,tracking,photoArchive:archive,fastLane:fast,dense,surface}};
}

function acquisitionStatus({archive,tracking,fast,graph}){const reasons=[],actions=[];let status='ok';if((archive.accepted||0)<20&&(graph.frames||0)<20){status='fail';reasons.push('Poche fotografie nitide/pose valide archiviate.');actions.push('Muovere più lentamente e mantenere texture visibile.');}if((archive.backpressureDropped||0)>Math.max(8,(archive.accepted||0)*.10)){status=maxStatus(status,'warn');reasons.push('Backpressure elevata nella compressione foto.');actions.push('Ridurre carico durante Scan; Deep/MVS devono restare post-scan.');}if((fast.maxGapMs||0)>1400){status=maxStatus(status,'warn');reasons.push('Gap fast-lane > 1.4 s.');actions.push('Controllare CPU/main-thread e frequenza di lavoro sparso.');}if(tracking.recoveryRequired||(tracking.quarantinedFrames||0)>8){status=maxStatus(status,'warn');reasons.push('Tracking Alva ha richiesto recupero/quarantena.');actions.push('Ritornare verso una zona già riconosciuta prima di continuare.');}return {status,reasons,actions};}
function rgbStatus({graph,edge}){const reasons=[],actions=[];let status='ok',frames=graph.frames||0,dirs=edge.translationDirectionEdges||0;if(frames>=12&&dirs<Math.max(6,Math.ceil(frames*.08))){status='fail';reasons.push('Copertura delle linee di traslazione RGB insufficiente.');actions.push('Aumentare overlap/parallasse e verificare convenzione A/B dei photo-edge.');}if(Number.isFinite(edge.meanEpipolarPlaneResidualDeg)&&edge.meanEpipolarPlaneResidualDeg>5){status='fail';reasons.push('Residuo epipolare RGB alto.');actions.push('Isolare edge con corrispondenze errate o salti di posa.');}if(Number.isFinite(edge.translationDirectionMeanInlierFraction)&&edge.translationDirectionMeanInlierFraction<.55){status=maxStatus(status,'warn');reasons.push('Bassa frazione inlier nelle translation line.');actions.push('Rafforzare feature persistenti e geometria multi-view.');}return {status,reasons,actions};}
function deepStatus({processing,depth}){const reasons=[],actions=[];let status='ok';if((processing.deepAccepted||0)<8){status='warn';reasons.push('Poche depth informative disponibili.');actions.push('Continuare Deep adattivo nelle regioni ad alta uncertainty.');}if(Number.isFinite(depth.medianRelativeResidual)&&depth.medianRelativeResidual>.45){status='fail';reasons.push('Calibrazione Deep incompatibile con gli anchor metrici.');actions.push('Non fondere Deep; controllare posa/frame binding e anchor indipendenti.');}else if(Number.isFinite(depth.medianRelativeResidual)&&depth.medianRelativeResidual>.28){status=maxStatus(status,'warn');reasons.push('Calibrazione Deep ancora rumorosa.');actions.push('Selezionare nuove depth dove MVS/RGB osservano meglio la scala.');}if(Number.isFinite(processing.uncertainty)&&processing.uncertainty>.60){status=maxStatus(status,'warn');reasons.push('Uncertainty globale ancora alta.');actions.push('Richiedere una nuova tranche Deep mirata.');}return {status,reasons,actions};}
function mvsStatus(m){const reasons=[],actions=[];let status='ok',input=m.input||0,commit=m.committed||0;if(input>200&&commit/input<.08){status='fail';reasons.push('Quasi nessun MVS sopravvive alla verifica finale.');actions.push('Controllare pose finali, parallasse e distinctiveness del plane sweep.');}else if(input>200&&commit/input<.20){status='warn';reasons.push('Supporto MVS finale debole.');actions.push('Aumentare baseline utili, non il numero indiscriminato di job.');}if((m.poseBoundFactors||0)>0&&(m.legacyPoseBoundFactors||0)>=(m.poseBoundFactors||0)){status='fail';reasons.push('MVS esclusivamente legacy/non autoritativo.');actions.push('Rigenerare MVS sulle pose finali della scansione corrente.');}return {status,reasons,actions};}
function surfaceStatus({cons,surface}){const reasons=[],actions=[];let status='ok',n=cons.authoritative??surface.committedGaussians??0;if(n<80){status='fail';reasons.push('Troppi pochi surfel superano il consenso globale.');actions.push('Individuare se il deficit nasce da posa, MVS o calibrazione Deep.');}if(Number.isFinite(cons.medianConfidence)&&cons.medianConfidence<.34){status=maxStatus(status,'warn');reasons.push('Confidenza mediana dei surfel bassa.');actions.push('Non visualizzare/fondere le Gaussiane deboli; richiedere evidenza indipendente.');}return {status,reasons,actions};}
function meshStatus({mesh,policy,cleanup,surface}){const reasons=[],actions=[];let status='ok';if(surface.committed!==true){status='fail';reasons.push(`Geometria non committed${surface.withheldReason||policy.reason?`: ${surface.withheldReason||policy.reason}`:''}.`);actions.push('Usare il primo stadio TEST precedente che fallisce; non abbassare il gate mesh.');}if((mesh.componentCount||0)>16||(mesh.largestComponentFraction||0)<.55){status='fail';reasons.push('Mesh frammentata / senza componente dominante.');actions.push('Correggere consenso globale e pose prima del TSDF.');}if((cleanup.discardedVertexFraction||0)>.30){status='fail';reasons.push('Troppa geometria viene rimossa come isole durante cleanup.');actions.push('La superficie densa è incoerente a monte: non committare.');}return {status,reasons,actions};}
function stage(name,r,metrics){return {name,status:r.status,reasons:r.reasons,actions:r.actions,metrics};}function maxStatus(a,b){const n={ok:0,warn:1,fail:2};return n[b]>n[a]?b:a;}
function summarizeEvents(events){const out={};for(const e of events||[]){const k=String(e?.event||'unknown');out[k]=(out[k]||0)+1;}return out;}
function compactEvent(e){return {at:e.at,tMs:e.tMs,level:e.level,event:e.event,scope:e.scope,data:compactData(e.data)};}function compactData(d){if(!d||typeof d!=='object')return d;const allow=['reason','message','frameId','gapMs','round','processed','failed','totalDepth','uncertaintyDrop','beforeUncertainty','afterUncertainty','accepted','commitReady','componentCount','largestComponentFraction','fragmentationScore','poseRejectedSamples','translationDirectionEdges'];const out={};for(const k of allow)if(d[k]!=null)out[k]=d[k];return out;}
function compactOptimizer(o){return {stats:o.stats||null,candidateStats:o.candidateStats||null,gate:o.gate||null,accepted:o.accepted||0,rejected:o.rejected||0,stalled:!!o.stalled};}
