import {qConj,qRotate} from '../slam/math.js?v=30.42.0';
import {SparseDenseFusion,buildConsensusTsdfMeshFromSplats} from '../dense/fusion_core.js?v=30.42.0';
import {analyzeMeshQuality} from './mesh_quality.js?v=30.42.0';

/**
 * Small overlapping local maps.  Dense evidence is committed in one local
 * coordinate system only; loop/pose updates move the submap rigidly instead of
 * requiring a monolithic global TSDF to be de-integrated.
 */
export class SubmapFusionManager{
  constructor(frames,{size=8,overlap=2,fusionOptions={}}={}){this.frames=frames||[];this.size=Math.max(4,size|0);this.overlap=Math.max(1,Math.min(this.size-2,overlap|0));this.stride=this.size-this.overlap;this.submaps=[];this.frameMap=new Map(this.frames.map((f,i)=>[String(f.frameId),i]));this.primary=new Map();this.fusionOptions=fusionOptions;this.buildLayout();}
  buildLayout(){this.submaps=[];if(!this.frames.length)return;for(let start=0;start<this.frames.length;start+=this.stride){const end=Math.min(this.frames.length,start+this.size),ids=[];for(let i=start;i<end;i++)ids.push(String(this.frames[i].frameId));const anchorIndex=start,anchor=this.frames[anchorIndex],s={id:`S${this.submaps.length}`,start,end,anchorIndex,anchorFrameId:String(anchor.frameId),anchorPose:clonePose(anchor.poseEstimate||anchor.posePrior),frameIds:ids,fusion:new SparseDenseFusion(this.fusionOptions),integratedFrames:new Set()};this.submaps.push(s);if(end===this.frames.length)break;}for(let i=0;i<this.frames.length;i++){let best=0,bd=Infinity;for(let s=0;s<this.submaps.length;s++){const m=(this.submaps[s].start+this.submaps[s].end-1)/2,d=Math.abs(i-m);if(d<bd){bd=d;best=s;}}this.primary.set(String(this.frames[i].frameId),best);}}
  submapForFrame(frameId){const i=this.primary.get(String(frameId));return i==null?null:this.submaps[i];}
  integrate(frameId,rows,{origin=null,mode='submap'}={}){const s=this.submapForFrame(frameId);if(!s||!rows?.length)return 0;const localRows=[];for(const r of rows){if(!finite3(r?.p))continue;localRows.push(transformRowToLocal(r,s.anchorPose));}if(!localRows.length)return 0;const o=finite3(origin)?worldToLocal(origin,s.anchorPose):[0,0,0];s.fusion.integrate(localRows,{origin:o,frameId:String(frameId),mode});s.integratedFrames.add(String(frameId));return localRows.length;}
  finalize({maxSurfels=90000,maxTriangles=90000}={}){const gaussians=[],submaps=[];const per=Math.max(1000,Math.ceil(maxSurfels/Math.max(1,this.submaps.length)));for(const s of this.submaps){const gs=s.fusion.splats({max:per}).map(g=>splatToWorld(g,s.anchorPose,s.id));gaussians.push(...gs);submaps.push({id:s.id,anchorFrameId:s.anchorFrameId,anchorPose:clonePose(s.anchorPose),frameIds:s.frameIds.slice(),integratedFrames:[...s.integratedFrames],gaussians:gs.length});}const kept=gaussians.slice(0,maxSurfels),evidence={strong:0,confirmed:0,weak:0};for(const g of kept)evidence[g.evidenceClass] = (evidence[g.evidenceClass]||0)+1;const voxel=Math.max(.004,Number(this.fusionOptions?.voxel)||.035),mesh=buildConsensusTsdfMeshFromSplats(kept,{voxel,truncation:Number(this.fusionOptions?.truncation)||voxel*3,maxTsdf:Math.max(70000,Number(this.fusionOptions?.maxTsdf)||maxSurfels*3),maxTriangles}),meshQuality=analyzeMeshQuality(mesh);return {gaussians:kept,mesh,submaps,stats:{submaps:submaps.length,integratedFrames:new Set(submaps.flatMap(s=>s.integratedFrames)).size,gaussians:gaussians.length,faces:mesh?.faces?.length?mesh.faces.length/3:0,evidence,globalFinalTsdf:true,meshQuality,mesher:{inputSurfels:mesh?.inputSurfels??0,sourceSurfels:mesh?.sourceSurfels??0,droppedSurfels:mesh?.droppedSurfels??0,meshedSurfelFraction:mesh?.meshedSurfelFraction??0,surfaceLayers:mesh?.surfaceLayers??0,consensusMode:mesh?.consensusMode||null}}};}
}

function transformRowToLocal(r,pose){const out={...r,p:worldToLocal(r.p,pose)};if(finite3(r.normal))out.normal=qRotate(qConj(pose.q),r.normal);if(Array.isArray(r.covariance)&&r.covariance.length>=6)out.covariance=rotatePackedCov(r.covariance,qMat(qConj(pose.q)));if(Array.isArray(r.surfaceCovariance)&&r.surfaceCovariance.length>=6)out.surfaceCovariance=rotatePackedCov(r.surfaceCovariance,qMat(qConj(pose.q)));return out;}
function splatToWorld(g,pose,submapId){const position=localToWorld(g.position,pose),normal=qRotate(pose.q,g.normal),viewOrigin=finite3(g.viewOrigin)?localToWorld(g.viewOrigin,pose):null,covariance=Array.isArray(g.covariance)?rotatePackedCov(g.covariance,qMat(pose.q)):g.covariance,positionCovariance=Array.isArray(g.positionCovariance)?rotatePackedCov(g.positionCovariance,qMat(pose.q)):g.positionCovariance,basis=Array.isArray(g.basis)?g.basis.map(v=>qRotate(pose.q,v)):g.basis;return {...g,position,normal,viewOrigin,covariance,positionCovariance,basis,submapId};}
function meshToWorld(m,pose){if(!m?.vertices?.length)return m;const v=new Float32Array(m.vertices.length);for(let i=0;i<m.vertices.length;i+=3){const p=localToWorld([m.vertices[i],m.vertices[i+1],m.vertices[i+2]],pose);v[i]=p[0];v[i+1]=p[1];v[i+2]=p[2];}return {...m,vertices:v};}
function mergeMeshes(ms,maxTriangles){const vertices=[],colors=[],faces=[];let base=0,tri=0,voxelM=null;for(const m of ms){if(!m?.vertices?.length)continue;voxelM=voxelM??m.voxelM;const allowed=Math.min((m.faces?.length||0)/3,maxTriangles-tri);if(allowed<=0)break;for(let i=0;i<m.vertices.length;i++)vertices.push(m.vertices[i]);for(let i=0;i<(m.colors?.length||0);i++)colors.push(m.colors[i]);for(let i=0;i<allowed*3;i++)faces.push(base+m.faces[i]);tri+=allowed;base+=m.vertices.length/3;}return {voxelM,occupiedVoxels:ms.reduce((n,m)=>n+(m?.occupiedVoxels||0),0),vertices:new Float32Array(vertices),colors:new Uint8Array(colors),faces:new Uint32Array(faces),submapMesh:true};}
function worldToLocal(p,pose){const d=[p[0]-pose.p[0],p[1]-pose.p[1],p[2]-pose.p[2]];return qRotate(qConj(pose.q),d);}
function localToWorld(p,pose){const q=qRotate(pose.q,p);return [pose.p[0]+q[0],pose.p[1]+q[1],pose.p[2]+q[2]];}
function clonePose(p){return {p:p.p.slice(0,3).map(Number),q:p.q.slice(0,4).map(Number)};}
function finite3(p){return Array.isArray(p)&&p.length>=3&&p.slice(0,3).every(Number.isFinite);}
function qMat(q){const n=Math.hypot(...q)||1,x=q[0]/n,y=q[1]/n,z=q[2]/n,w=q[3]/n,xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;return [1-2*(yy+zz),2*(xy-wz),2*(xz+wy),2*(xy+wz),1-2*(xx+zz),2*(yz-wx),2*(xz-wy),2*(yz+wx),1-2*(xx+yy)];}
function rotatePackedCov(c,R){const C=[[c[0],c[1],c[2]],[c[1],c[3],c[4]],[c[2],c[4],c[5]]],A=[[0,0,0],[0,0,0],[0,0,0]];for(let i=0;i<3;i++)for(let j=0;j<3;j++)for(let k=0;k<3;k++)A[i][j]+=R[i*3+k]*C[k][j];const B=[[0,0,0],[0,0,0],[0,0,0]];for(let i=0;i<3;i++)for(let j=0;j<3;j++)for(let k=0;k<3;k++)B[i][j]+=A[i][k]*R[j*3+k];return [B[0][0],B[0][1],B[0][2],B[1][1],B[1][2],B[2][2]];}
