import test from 'node:test';import assert from 'node:assert/strict';
import {SwitchablePhotoEdgeModel} from '../js/probabilistic/switchable_edges.js';
import {SubmapPoseGraph} from '../js/probabilistic/submap_pose_graph.js';
const K={fx:300,fy:300,cx:160,cy:120,width:320,height:240},pose=(x=0,q=[0,0,0,1])=>({p:[x,0,0],q});
function meas(frame,p){const u=K.fx*(p[0]-frame.poseEstimate.p[0])/p[2]+K.cx,v=K.fy*p[1]/p[2]+K.cy;return {frameId:frame.frameId,u,v,probability:.98};}
test('good RGB edge grows instead of collapsing merely because support is finite',()=>{const A={frameId:'a',poseEstimate:pose(0),K},B={frameId:'b',poseEstimate:pose(.1),K},edge={aId:'a',bId:'b',visualConfidence:.22,rotationBToA:[1,0,0,0,1,0,0,0,1],matches:Array.from({length:18},()=>({}))},landmarks=[];for(let i=0;i<20;i++){const p=[(-.5+i*.05),.1*Math.sin(i),2.2];landmarks.push({point:p,measurements:[meas(A,p),meas(B,p)]});}const m=new SwitchablePhotoEdgeModel([edge]);for(let i=0;i<6;i++)m.update([A,B],landmarks);assert.ok(m.stats().mean>.55,m.stats());});

test('collapsed legacy RGB edge can recover during final RGB reconciliation when geometry agrees',()=>{const A={frameId:'a',poseEstimate:pose(0),K},B={frameId:'b',poseEstimate:pose(.1),K},edge={aId:'a',bId:'b',visualConfidence:.22,switch:.044,rotationBToA:[1,0,0,0,1,0,0,0,1],matches:Array.from({length:18},()=>({}))},landmarks=[];for(let i=0;i<24;i++){const p=[(-.55+i*.047),.08*Math.sin(i*.7),2.1+.04*Math.cos(i)];landmarks.push({point:p,measurements:[meas(A,p),meas(B,p)]});}const m=new SwitchablePhotoEdgeModel([edge]);for(let i=0;i<18;i++)m.update([A,B],landmarks,{bootstrap:true});for(let i=0;i<6;i++)m.update([A,B],landmarks);assert.ok(m.stats().active===1&&m.stats().mean>.55,m.stats());});
test('geometrically bad RGB edge still loses authority under independent evidence',()=>{const A={frameId:'a',poseEstimate:pose(0),K},B={frameId:'b',poseEstimate:pose(.1),K},edge={aId:'a',bId:'b',visualConfidence:.8,rotationBToA:[1,0,0,0,1,0,0,0,1],matches:Array.from({length:18},()=>({}))},landmarks=[];for(let i=0;i<20;i++){const p=[(-.5+i*.05),.1*Math.sin(i),2.2],bad=meas(B,p);bad.u+=80;bad.v-=45;landmarks.push({point:p,measurements:[meas(A,p),bad]});}const m=new SwitchablePhotoEdgeModel([edge]),start=m.stats().mean;for(let i=0;i<6;i++)m.update([A,B],landmarks);assert.ok(m.stats().mean<start*.75,{start,end:m.stats().mean,stats:m.stats()});});
test('rotation-only photo submap edge cannot fabricate or alter translation',()=>{const submaps=[{id:'s0',anchorPose:pose(0),frameIds:['a']},{id:'s1',anchorPose:pose(1),frameIds:['b']}],frames=[{frameId:'a'},{frameId:'b'}],photo=[{aId:'a',bId:'b',visualConfidence:.9,rotationBToA:[0,-1,0,1,0,0,0,0,1]}],edgeModel={pairWeight:()=>.9},g=new SubmapPoseGraph(submaps,frames,{photoEdges:photo,edgeModel});const before=g.nodes[1].pose.p.slice();g.optimize(10).apply();assert.ok(Math.hypot(...g.nodes[1].pose.p.map((x,i)=>x-before[i]))<1e-10,{before,after:g.nodes[1].pose.p});assert.equal(g.stats().photoTranslationFabricated,false);assert.ok(g.stats().rotationOnlyEdges>=1,g.stats());});
