/*
 * Offline Gaussian accumulation worker.
 * Protocol is intentionally permissive so both the original V30 host and the
 * compatibility app can feed either objects or packed position arrays.
 */
let cfg={voxel:.025,maxGaussians:240000,maxSnapshot:90000};
const voxels=new Map();
function key(p){const v=cfg.voxel||.025;return `${Math.round(p[0]/v)},${Math.round(p[1]/v)},${Math.round(p[2]/v)}`;}
function addOne(p,c=[180,210,240],opacity=.65,scale=null){if(!p||p.length<3||!p.every(Number.isFinite))return;const k=key(p),old=voxels.get(k);if(old){const n=old.n+1;old.position=old.position.map((v,i)=>(v*old.n+p[i])/n);old.color=old.color.map((v,i)=>Math.round((v*old.n+(c?.[i]??v))/n));old.opacity=Math.max(old.opacity,Number(opacity)||0);old.n=n;return;}if(voxels.size>=cfg.maxGaussians)return;voxels.set(k,{position:[+p[0],+p[1],+p[2]],color:[+(c?.[0]??180),+(c?.[1]??210),+(c?.[2]??240)],opacity:Number(opacity)||.65,scale:Array.isArray(scale)?scale:[cfg.voxel,cfg.voxel,cfg.voxel],n:1});}
function ingest(data){if(Array.isArray(data)){for(const g of data){const p=g?.position||g?.p||g?.mean||g?.xyz;addOne(p,g?.color||g?.rgb,g?.opacity??g?.alpha,g?.scale||g?.scales||g?.radius);}return;}const ps=data?.positions;if(ps&&(Array.isArray(ps)||ArrayBuffer.isView(ps))){const cs=data.colors||data.rgb,op=data.opacities||data.opacity,sc=data.scales||data.scale;for(let i=0;i+2<ps.length;i+=3){const j=i/3;addOne([+ps[i],+ps[i+1],+ps[i+2]],cs&&cs.length>=i+3?[cs[i],cs[i+1],cs[i+2]]:null,op?op[j]:.65,sc&&sc.length>=i+3?[sc[i],sc[i+1],sc[i+2]]:null);}}}
function snapshot(limit=cfg.maxSnapshot){const arr=[...voxels.values()],step=Math.max(1,Math.ceil(arr.length/Math.max(1,limit)));return arr.filter((_,i)=>i%step===0).slice(0,limit).map(({n,...g})=>g);}
self.onmessage=e=>{const d=e.data||{};try{if(d.type==='init'){cfg={...cfg,...(d.config||{})};postMessage({type:'ready',config:cfg});return;}if(d.type==='clear'){voxels.clear();postMessage({type:'cleared'});return;}if(d.type==='add'||d.type==='points'||d.type==='integrate'){ingest(d.gaussians||d.points||d.payload||d);const snap=snapshot();postMessage({type:'snapshot',count:voxels.size,gaussians:snap});return;}if(d.type==='snapshot'||d.type==='flush'){postMessage({type:'snapshot',count:voxels.size,gaussians:snapshot(d.maxSnapshot)});return;}postMessage({type:'status',count:voxels.size});}catch(err){postMessage({type:'error',message:err.message,stack:err.stack});}};
