/*
 * Room Scanner V30 - incremental 3D Gaussian map worker.
 *
 * Gaussians are not surface tiles. Each voxel stores the sufficient statistics
 * of many metric 3D observations: mean, covariance, RGB, normal and view count.
 * The raw keyframes/depth stay separate, so this map can be pruned aggressively
 * for mobile memory without destroying the source evidence.
 */
let cfg={voxel:0.028,maxGaussians:180000,maxSnapshot:65000,minDepth:.15,maxDepth:10};
let vox=new Map(),frameSeq=0,totalObs=0,cameraPath=[];
const key=(x,y,z)=>`${Math.floor(x/cfg.voxel)},${Math.floor(y/cfg.voxel)},${Math.floor(z/cfg.voxel)}`;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function qrot(q,v){const [x,y,z,w]=q,[vx,vy,vz]=v,tx=2*(y*vz-z*vy),ty=2*(z*vx-x*vz),tz=2*(x*vy-y*vx);return [vx+w*tx+(y*tz-z*ty),vy+w*ty+(z*tx-x*tz),vz+w*tz+(x*ty-y*tx)];}
function world(pose,pc){const r=qrot(pose.q,pc);return [r[0]+pose.p[0],r[1]+pose.p[1],r[2]+pose.p[2]];}
function metric(raw,cal){const x=cal.mode==='inverse'?1/Math.max(1e-6,raw):raw;return cal.a*x+(cal.b||0);}
function backproject(x,y,z,K){return [(x-K.cx)*z/K.fx,-(y-K.cy)*z/K.fy,z];}
function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
function norm(v){const n=Math.hypot(...v)||1;return v.map(x=>x/n);}
function addObs(p,n,c,frameId){const k=key(...p),old=vox.get(k);if(!old){vox.set(k,{n:1,m:[...p],M:[0,0,0,0,0,0],rgb:[c[0],c[1],c[2]],normal:[...n],views:1,lastFrame:frameId,lastSeen:frameSeq,firstSeen:frameSeq});return;}const count=old.n+1,dx=p[0]-old.m[0],dy=p[1]-old.m[1],dz=p[2]-old.m[2];old.m[0]+=dx/count;old.m[1]+=dy/count;old.m[2]+=dz/count;const ex=p[0]-old.m[0],ey=p[1]-old.m[1],ez=p[2]-old.m[2];old.M[0]+=dx*ex;old.M[1]+=dy*ey;old.M[2]+=dz*ez;old.M[3]+=dx*ey;old.M[4]+=dx*ez;old.M[5]+=dy*ez;old.rgb[0]+=(c[0]-old.rgb[0])/count;old.rgb[1]+=(c[1]-old.rgb[1])/count;old.rgb[2]+=(c[2]-old.rgb[2])/count;old.normal=norm([old.normal[0]*(count-1)+n[0],old.normal[1]*(count-1)+n[1],old.normal[2]*(count-1)+n[2]]);old.n=count;if(old.lastFrame!==frameId){old.views++;old.lastFrame=frameId;}old.lastSeen=frameSeq;}
function score(g){return g.views*5+Math.log1p(g.n)*2-Math.max(0,frameSeq-g.lastSeen)*.015;}
function prune(){if(vox.size<=cfg.maxGaussians)return 0;const arr=[...vox.entries()];arr.sort((a,b)=>score(b[1])-score(a[1]));const keep=Math.floor(cfg.maxGaussians*.92),next=new Map(arr.slice(0,keep));const removed=vox.size-next.size;vox=next;return removed;}
function snapshot(){const arr=[...vox.values()];arr.sort((a,b)=>score(b)-score(a));const n=Math.min(cfg.maxSnapshot,arr.length),stride=16,out=new Float32Array(n*stride);for(let i=0;i<n;i++){const g=arr[i],den=Math.max(1,g.n-1),vx=Math.max(1e-6,g.M[0]/den),vy=Math.max(1e-6,g.M[1]/den),vz=Math.max(1e-6,g.M[2]/den),base=i*stride;out[base]=g.m[0];out[base+1]=g.m[1];out[base+2]=g.m[2];out[base+3]=clamp(Math.sqrt(vx)*2+.009,.007,.07);out[base+4]=clamp(Math.sqrt(vy)*2+.009,.007,.07);out[base+5]=clamp(Math.sqrt(vz)*2+.009,.007,.07);out[base+6]=g.normal[0];out[base+7]=g.normal[1];out[base+8]=g.normal[2];out[base+9]=g.rgb[0]/255;out[base+10]=g.rgb[1]/255;out[base+11]=g.rgb[2]/255;out[base+12]=clamp(.15+Math.log1p(g.n)*.12+g.views*.08,.12,.98);out[base+13]=g.views;out[base+14]=g.n;out[base+15]=score(g);}return out;}
function integrate(m){const depth=new Float32Array(m.depth),rgb=new Uint8Array(m.rgb),W=m.width,H=m.height,K=m.K,pose=m.pose,cal=m.calibration,frameId=m.frameId;cameraPath.push([...pose.p]);if(cameraPath.length>2000)cameraPath.splice(0,400);frameSeq++;const target=m.targetPoints||7500,step=Math.max(1,Math.floor(Math.sqrt(W*H/target)));let accepted=0;for(let y=step;y<H-step;y+=step){for(let x=step;x<W-step;x+=step){const idx=y*W+x,raw=depth[idx],z=metric(raw,cal);if(!Number.isFinite(z)||z<cfg.minDepth||z>cfg.maxDepth)continue;const pc=backproject(x+.5,y+.5,z,K),pw=world(pose,pc);if(!pw.every(Number.isFinite))continue;const rawX=depth[idx+step],rawY=depth[idx+step*W],zx=metric(rawX,cal),zy=metric(rawY,cal);let nw=[0,0,-1];if(Number.isFinite(zx)&&Number.isFinite(zy)&&zx>cfg.minDepth&&zy>cfg.minDepth){const px=backproject(x+step+.5,y+.5,zx,K),py=backproject(x+.5,y+step+.5,zy,K),a=[px[0]-pc[0],px[1]-pc[1],px[2]-pc[2]],b=[py[0]-pc[0],py[1]-pc[1],py[2]-pc[2]],nc=norm(cross(a,b));nw=qrot(pose.q,nc);}const ci=idx*3,c=[rgb[ci]||128,rgb[ci+1]||128,rgb[ci+2]||128];addObs(pw,nw,c,frameId);accepted++;}}
 totalObs+=accepted;const removed=frameSeq%8===0?prune():0;const snap=snapshot();postMessage({type:'snapshot',frameId,count:vox.size,totalObs,accepted,removed,stride:16,data:snap.buffer},[snap.buffer]);}
self.onmessage=e=>{const m=e.data||{};try{if(m.type==='init'){cfg={...cfg,...m.config};postMessage({type:'ready',config:cfg});}else if(m.type==='integrate')integrate(m);else if(m.type==='snapshot'){const s=snapshot();postMessage({type:'snapshot',count:vox.size,totalObs,stride:16,data:s.buffer},[s.buffer]);}else if(m.type==='reset'){vox.clear();frameSeq=0;totalObs=0;cameraPath=[];postMessage({type:'reset-done'});}else if(m.type==='export'){const s=snapshotAll();postMessage({type:'export',stride:16,count:vox.size,totalObs,data:s.buffer,cameraPath},[s.buffer]);}}catch(err){postMessage({type:'error',message:err.message,stack:err.stack});}};
function snapshotAll(){const arr=[...vox.values()],stride=16,out=new Float32Array(arr.length*stride);for(let i=0;i<arr.length;i++){const g=arr[i],den=Math.max(1,g.n-1),base=i*stride;out[base]=g.m[0];out[base+1]=g.m[1];out[base+2]=g.m[2];out[base+3]=clamp(Math.sqrt(Math.max(1e-6,g.M[0]/den))*2+.009,.007,.07);out[base+4]=clamp(Math.sqrt(Math.max(1e-6,g.M[1]/den))*2+.009,.007,.07);out[base+5]=clamp(Math.sqrt(Math.max(1e-6,g.M[2]/den))*2+.009,.007,.07);out[base+6]=g.normal[0];out[base+7]=g.normal[1];out[base+8]=g.normal[2];out[base+9]=g.rgb[0]/255;out[base+10]=g.rgb[1]/255;out[base+11]=g.rgb[2]/255;out[base+12]=clamp(.15+Math.log1p(g.n)*.12+g.views*.08,.12,.98);out[base+13]=g.views;out[base+14]=g.n;out[base+15]=score(g);}return out;}
