import {ProbabilisticJointOptimizer} from '../js/probabilistic/joint_optimizer.js';
import {evaluateLiveCandidate} from '../js/probabilistic/live_optimization_gate.js';

let acceptedSnapshot=null,acceptedStats=null,workingSnapshot=null,busy=false,pending=null,generation=0,stopped=false;
const now=()=>globalThis.performance?.now?.()??Date.now();
self.onmessage=e=>{const d=e.data||{};try{
  if(d.type==='init'){acceptedSnapshot=d.initial||null;acceptedStats=d.initial?.stats||null;workingSnapshot=acceptedSnapshot;generation=0;stopped=false;self.postMessage({type:'live-opt-ready',accepted:!!acceptedSnapshot});return;}
  if(d.type==='stop'){stopped=true;pending=null;generation++;self.postMessage({type:'live-opt-stopped',acceptedStats});return;}
  if(d.type==='reset'){acceptedSnapshot=d.initial||null;acceptedStats=d.initial?.stats||null;workingSnapshot=acceptedSnapshot;pending=null;generation++;self.postMessage({type:'live-opt-reset'});return;}
  if(d.type==='sync'){stopped=false;pending=d;if(!busy)void drain();return;}
  if(d.type==='snapshot'){self.postMessage({type:'live-opt-snapshot',snapshot:acceptedSnapshot,stats:acceptedStats});return;}
}catch(err){self.postMessage({type:'live-opt-error',message:err?.message||String(err),stack:err?.stack||null});}};

async function drain(){if(busy||stopped)return;busy=true;try{while(pending&&!stopped){const job=pending;pending=null;await solve(job);await yieldNow();}}finally{busy=false;}}

async function solve(job){
  const gen=++generation,start=now(),graph=job.graph||{},summary=graph.summary||{frames:graph.frames?.length||0,landmarks:graph.landmarkFactors?.length||0,deepFrames:graph.deepFactors?.length||0,photoEdges:graph.edgeFactors?.length||0};
  if((summary.frames||0)<2||(summary.landmarks||0)<4){self.postMessage({type:'live-opt-deferred',generation:gen,reason:'insufficient-scaffold',trigger:job.reason,summary});return;}
  const baseOptions={...(job.options||{})},acceptedOpt=new ProbabilisticJointOptimizer(graph,{...baseOptions,initial:acceptedSnapshot||job.initial||null}),baselineStats=acceptedOpt.computeStats(),baselineSnapshot=acceptedOpt.snapshot(),opt=new ProbabilisticJointOptimizer(graph,{...baseOptions,initial:workingSnapshot||acceptedSnapshot||job.initial||null}),workingBaselineStats=opt.computeStats(),workingBaselineSnapshot=opt.snapshot(),budget=Math.max(8,Number(job.budgetMs)||36),maxIterations=Math.max(1,Math.min(5,Number(job.maxIterations)||2)),steps=[];
  self.postMessage({type:'live-opt-trace',generation:gen,event:'solve-start',data:{trigger:job.reason,budgetMs:budget,maxIterations,summary,windowDiagnostics:graph.windowDiagnostics||null,acceptedBaseline:compactStats(baselineStats),workingBaseline:compactStats(workingBaselineStats),workingSeeded:!!workingSnapshot}});
  let iterations=0;while(iterations<maxIterations&&!stopped){const t=now(),stats=opt.step(1),dt=now()-t;iterations++;steps.push({iteration:iterations,ms:dt,phase:stats.feedbackPhase,reprojectionRmse:stats.reprojectionRmse,deepRelativeError:stats.deepRelativeError,poseShiftMean:stats.poseShiftMean});if(now()-start>=budget)break;await yieldNow();}
  if(stopped)return;const candidateStats=opt.computeStats(),candidateSnapshot=opt.snapshot(),gate=evaluateLiveCandidate({baselineStats,candidateStats,baselineSnapshot,candidateSnapshot,options:job.gateOptions||{}}),elapsed=now()-start;
  if(gate.accepted){acceptedSnapshot=candidateSnapshot;acceptedStats=candidateStats;workingSnapshot=candidateSnapshot;let previewGaussians=null,previewStats=null,mapMs=0;if(job.previewMap&&String(candidateStats.feedbackPhase)==='depth-feedback'&&(summary.deepFrames||0)>0){const mt=now();try{const map=opt.rebuild({voxel:Number(job.previewVoxel)||.055,hashVoxel:Number(job.previewHashVoxel)||.04,maxSurfels:Math.max(700,Math.min(3500,Number(job.previewMaxSurfels)||2200)),maxTriangles:Math.max(300,Math.min(1800,Number(job.previewMaxTriangles)||900)),maxDeepSamples:Math.max(800,Math.min(6000,Number(job.previewMaxDeepSamples)||3200)),maxMvsSamples:Math.max(1000,Math.min(7000,Number(job.previewMaxMvsSamples)||3800)),submapSize:Math.max(4,Number(job.previewSubmapSize)||6),submapOverlap:2,deepFrameWeightBudget:10});previewGaussians=(map.gaussians||[]).slice(0,Number(job.previewMaxSurfels)||2200);previewStats=map.stats||null;}catch(err){self.postMessage({type:'live-opt-trace',generation:gen,event:'preview-map-error',data:{message:err?.message||String(err)}});}mapMs=now()-mt;}const anchors=opt.landmarkPreview(Math.max(40,Math.min(900,Number(job.maxPreviewLandmarks)||320))).filter(x=>(x.confidence||0)>.20).sort((a,b)=>(b.confidence||0)*(b.support||1)-(a.confidence||0)*(a.support||1)).slice(0,Math.max(40,Math.min(180,Number(job.maxPreviewAnchors)||90))).map(x=>({id:x.id,p:x.position,confidence:x.confidence,support:x.support}));self.postMessage({type:'live-opt-accepted',generation:gen,trigger:job.reason,elapsedMs:elapsed+mapMs,solveMs:elapsed,mapMs,iterations,steps,stats:candidateStats,gate,snapshot:acceptedSnapshot,anchors,previewGaussians,previewStats,summary});}
  else {const workingGate=evaluateLiveCandidate({baselineStats:workingBaselineStats,candidateStats,baselineSnapshot:workingBaselineSnapshot,candidateSnapshot,options:{maxReprojectionPx:8,maxReprojectionGrowth:1.8,maxCommonTranslationJump:.24,maxCommonRotationJumpRad:.16,maxMeanTranslationJump:.12,maxMeanRotationJumpRad:.08,maxDepthErrorGrowth:2.2,maxRejectedEdgeGrowth:8}}),workingRetained=workingGate.hardReasons.length===0;if(workingRetained)workingSnapshot=candidateSnapshot;else workingSnapshot=acceptedSnapshot;self.postMessage({type:'live-opt-rejected',generation:gen,trigger:job.reason,elapsedMs:elapsed,iterations,steps,stats:candidateStats,baselineStats,gate,workingGate,workingRetained,summary});}
}
function compactStats(s){return {iterations:s?.iterations,reprojectionRmse:s?.reprojectionRmse,poseShiftMean:s?.poseShiftMean,poseRotationShiftMeanRad:s?.poseRotationShiftMeanRad,deepRelativeError:s?.deepRelativeError,feedbackPhase:s?.feedbackPhase,observations:s?.observations,landmarks:s?.landmarks,edgeSwitches:s?.edgeSwitches,alvaSwitches:s?.alvaSwitches,reliability:s?.reliability};}
function yieldNow(){return new Promise(r=>setTimeout(r,0));}
