/* Incremental low-poly surface reconstruction.  It deliberately consumes only
 * tracked image features, not every depth pixel: this keeps the map readable
 * and makes its confidence meaningful on mobile hardware. */
let cfg={maxFeatures:180,minSpacingPx:15,maxEdgeL:.42,maxVertices:30000};
let positions=[],colors=[],confidence=[],faces=[],frames=0,sealed=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function qrot(q,v){const [x,y,z,w]=q,[vx,vy,vz]=v,tx=2*(y*vz-z*vy),ty=2*(z*vx-x*vz),tz=2*(x*vy-y*vx);return [vx+w*tx+(y*tz-z*ty),vy+w*ty+(z*tx-x*tz),vz+w*tz+(x*ty-y*tx)];}
function depth(raw,cal){const x=cal?.mode==='inverse'?1/Math.max(1e-6,raw):raw;return (cal?.a??1)*x+(cal?.b??0);}
function point(x,y,z,K,pose){const pc=[(x-K.cx)*z/K.fx,-(y-K.cy)*z/K.fy,z],r=qrot(pose.q,pc);return [r[0]+pose.p[0],r[1]+pose.p[1],r[2]+pose.p[2]];}
function sq(a,b){const x=a[0]-b[0],y=a[1]-b[1],z=a[2]-b[2];return x*x+y*y+z*z;}
function circum(a,b,c,p){const ax=a.x-p.x,ay=a.y-p.y,bx=b.x-p.x,by=b.y-p.y,cx=c.x-p.x,cy=c.y-p.y;const d=2*(ax*(by-cy)+bx*(cy-ay)+cx*(ay-by));if(Math.abs(d)<1e-9)return false;const aa=ax*ax+ay*ay,bb=bx*bx+by*by,cc=cx*cx+cy*cy,ux=(aa*(by-cy)+bb*(cy-ay)+cc*(ay-by))/d,uy=(aa*(cx-bx)+bb*(ax-cx)+cc*(bx-ay))/d;return ux*ux+uy*uy<=(ux-ax)*(ux-ax)+(uy-ay)*(uy-ay)+1e-7;}
/* Bowyer-Watson Delaunay in the image plane. Triangle validity is then tested
 * in 3D, so edges never bridge a depth discontinuity. */
function delaunay(input){if(input.length<3)return [];const pts=input.map((p,i)=>({...p,i})),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),d=Math.max(maxX-minX,maxY-minY)||1,mx=(minX+maxX)/2,my=(minY+maxY)/2,n=pts.length;pts.push({x:mx-20*d,y:my-10*d},{x:mx,y:my+20*d},{x:mx+20*d,y:my-10*d});let tri=[[n,n+1,n+2]];for(let i=0;i<n;i++){const bad=tri.filter(t=>circum(pts[t[0]],pts[t[1]],pts[t[2]],pts[i])),edges=[];for(const t of bad)for(const e of [[t[0],t[1]],[t[1],t[2]],[t[2],t[0]]]){const j=edges.findIndex(q=>q[0]===e[1]&&q[1]===e[0]);if(j>=0)edges.splice(j,1);else edges.push(e);}tri=tri.filter(t=>!bad.includes(t));for(const e of edges)tri.push([e[0],e[1],i]);}return tri.filter(t=>t.every(i=>i<n));}
function confidenceColor(c){const t=clamp(c,0,1);return t<.5?[1,.12+t*1.76,.08]:[1-(t-.5)*1.7,.95,.12+(t-.5)*.26];}
function snapshot(type='snapshot'){const p=new Float32Array(positions),c=new Float32Array(colors),q=new Float32Array(confidence),f=new Uint32Array(faces);postMessage({type,vertexCount:p.length/3,triangleCount:f.length/3,sealed,positions:p.buffer,colors:c.buffer,confidence:q.buffer,indices:f.buffer},[p.buffer,c.buffer,q.buffer,f.buffer]);}
function integrate(m){if(sealed)return;const raw=new Float32Array(m.depth),rgb=new Uint8Array(m.rgb),W=m.width,H=m.height,candidates=[];for(const f of m.features||[]){const x=Math.round(f.x),y=Math.round(f.y);if(x<2||y<2||x>=W-2||y>=H-2)continue;const z=depth(raw[y*W+x],m.calibration);if(!Number.isFinite(z)||z<.03||z>16)continue;let close=false;for(const q of candidates)if((q.x-x)**2+(q.y-y)**2<cfg.minSpacingPx**2){close=true;break;}if(close)continue;const zx=depth(raw[y*W+x+1],m.calibration),zy=depth(raw[(y+1)*W+x],m.calibration),smooth=Number.isFinite(zx)&&Number.isFinite(zy)?clamp(1-(Math.abs(z-zx)+Math.abs(z-zy))/Math.max(.025,z*.08),0,1):0,views=clamp((f.views||1)/5,0,1),conf=clamp(.12+.48*smooth+.40*views,0,1),i=(y*W+x)*3;candidates.push({x,y,z,p:point(x+.5,y+.5,z,m.K,m.pose),conf,rgb:[(rgb[i]||128)/255,(rgb[i+1]||128)/255,(rgb[i+2]||128)/255]});if(candidates.length>=cfg.maxFeatures)break;}
 const localFaces=delaunay(candidates),base=positions.length/3;for(const v of candidates){positions.push(...v.p);colors.push(...confidenceColor(v.conf));confidence.push(v.conf);}for(const t of localFaces){const a=candidates[t[0]],b=candidates[t[1]],c=candidates[t[2]],edge=Math.max(sq(a.p,b.p),sq(b.p,c.p),sq(c.p,a.p));if(edge<=cfg.maxEdgeL*cfg.maxEdgeL)faces.push(base+t[0],base+t[1],base+t[2]);}frames++;if(positions.length/3>cfg.maxVertices){/* retain the newest reliable patches rather than silently growing forever */positions=positions.slice(-cfg.maxVertices*3);colors=colors.slice(-cfg.maxVertices*3);confidence=confidence.slice(-cfg.maxVertices);faces=[];}if(frames%2===0)snapshot();}
function integrateVisual(m){if(sealed)return;const candidates=[];for(const v of m.points||[]){if(!Array.isArray(v.p)||v.p.length!==3||!v.p.every(Number.isFinite))continue;let close=false;for(const q of candidates)if((q.x-v.x)**2+(q.y-v.y)**2<cfg.minSpacingPx**2){close=true;break;}if(!close)candidates.push({x:v.x,y:v.y,p:v.p,conf:clamp(v.confidence||.2,0,1)});if(candidates.length>=cfg.maxFeatures)break;}const localFaces=delaunay(candidates),base=positions.length/3;for(const v of candidates){positions.push(...v.p);colors.push(...confidenceColor(v.conf));confidence.push(v.conf);}for(const t of localFaces){const a=candidates[t[0]],b=candidates[t[1]],c=candidates[t[2]],edge=Math.max(sq(a.p,b.p),sq(b.p,c.p),sq(c.p,a.p));if(edge<=cfg.maxEdgeL*cfg.maxEdgeL)faces.push(base+t[0],base+t[1],base+t[2]);}frames++;if(positions.length/3>cfg.maxVertices){positions=positions.slice(-cfg.maxVertices*3);colors=colors.slice(-cfg.maxVertices*3);confidence=confidence.slice(-cfg.maxVertices);faces=[];}snapshot();}
function seal(){if(sealed)return snapshot('sealed');sealed=true;if(positions.length>=9){let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<positions.length;i+=3)for(let k=0;k<3;k++){lo[k]=Math.min(lo[k],positions[i+k]);hi[k]=Math.max(hi[k],positions[i+k]);}const pad=Math.max(.08,Math.hypot(hi[0]-lo[0],hi[1]-lo[1],hi[2]-lo[2])*.025),b=[[lo[0]-pad,lo[1]-pad,lo[2]-pad],[hi[0]+pad,lo[1]-pad,lo[2]-pad],[hi[0]+pad,hi[1]+pad,lo[2]-pad],[lo[0]-pad,hi[1]+pad,lo[2]-pad],[lo[0]-pad,lo[1]-pad,hi[2]+pad],[hi[0]+pad,lo[1]-pad,hi[2]+pad],[hi[0]+pad,hi[1]+pad,hi[2]+pad],[lo[0]-pad,hi[1]+pad,hi[2]+pad]],base=positions.length/3;for(const p of b){positions.push(...p);colors.push(.9,.08,.08);confidence.push(.03);}for(const f of [[0,1,2],[0,2,3],[4,6,5],[4,7,6],[0,4,5],[0,5,1],[1,5,6],[1,6,2],[2,6,7],[2,7,3],[3,7,4],[3,4,0]])faces.push(base+f[0],base+f[1],base+f[2]);}snapshot('sealed');}
self.onmessage=e=>{const m=e.data||{};try{if(m.type==='init'){cfg={...cfg,...m.config};postMessage({type:'ready',config:cfg});}else if(m.type==='integrate')integrate(m);else if(m.type==='integrate-visual')integrateVisual(m);else if(m.type==='snapshot')snapshot();else if(m.type==='seal')seal();else if(m.type==='reset'){positions=[];colors=[];confidence=[];faces=[];frames=0;sealed=false;postMessage({type:'reset-done'});}}catch(err){postMessage({type:'error',message:err.message,stack:err.stack});}};
