import {projectPoint,pixelRay,qMul,qNormalize,qRotate,qConj} from '../slam/math.js';
import {SparseDenseFusion} from '../dense/fusion_core.js';
import {addPoseUncertaintyToPointCovariance} from './pose_uncertainty.js';

/**
 * Mobile-friendly alternating factor-graph optimiser.
 *
 * It is intentionally block-coordinate rather than a giant sparse normal
 * equation: landmark refinement -> small SE(3) pose correction with a strong
 * Alva prior -> sequence Deep calibration. This keeps memory bounded while
 * retaining the same measurements that a full bundle adjustment would use.
 */
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class ProbabilisticJointOptimizer{
  constructor(graph,{maxLandmarks=12000,maxObsPerFrame=280,posePriorScale=1,landmarkDamping=.7,poseDamping=.55,initial=null}={}){
    this.graph=normaliseGraph(graph);this.maxLandmarks=maxLandmarks;this.maxObsPerFrame=maxObsPerFrame;this.posePriorScale=posePriorScale;this.landmarkDamping=landmarkDamping;this.poseDamping=poseDamping;
    this.frames=this.graph.frames.map(f=>({...f,poseEstimate:clonePose(f.poseEstimate||f.posePrior),posePrior:clonePose(f.posePrior)}));this.frameMap=new Map(this.frames.map((f,i)=>[String(f.frameId),i]));
    this.landmarks=this.graph.landmarkFactors.slice(0,maxLandmarks).map(l=>({...l,point:l.point.slice(0,3).map(Number),priorPoint:l.point.slice(0,3).map(Number),covariance:(l.covariance||[.01,0,0,.01,0,.01]).slice(0,6),priorProbability:prob(l.probability)}));
    this.deepModel=null;this.iterations=0;this.lastStats={energy:Infinity,reprojectionRmse:Infinity,poseShiftMean:0,deepRelativeError:Infinity,landmarks:this.landmarks.length};if(initial)this.restore(initial);
  }
  restore(s){if(!s)return this;const fm=new Map((s.frames||[]).map(x=>[String(x.frameId),x]));for(const f of this.frames){const x=fm.get(String(f.frameId));if(x?.poseEstimate)f.poseEstimate=clonePose(x.poseEstimate);}const lm=new Map((s.landmarks||[]).map(x=>[String(x.id),x]));for(const l of this.landmarks){const x=lm.get(String(l.id));if(x?.point&&finite3(x.point))l.point=x.point.slice(0,3).map(Number);if(Number.isFinite(+x?.probability))l.probability=clamp(+x.probability,.002,.998);}this.deepModel=s.deepModel||this.deepModel;this.iterations=Math.max(0,Number(s.iterations)||0);this.lastStats=s.stats||this.computeStats();return this;}
  step(count=1){for(let k=0;k<count;k++){this.refineLandmarks();this.refinePoses();this.deepModel=this.fitDeepSequence();this.iterations++;}this.lastStats=this.computeStats();return this.lastStats;}
  refineLandmarks(){
    for(const l of this.landmarks){const obs=(l.measurements||[]).map(m=>({m,frame:this.frames[this.frameMap.get(String(m.frameId))]})).filter(x=>x.frame);if(obs.length<2)continue;let p=l.point.slice();
      for(let iter=0;iter<2;iter++){const H=new Float64Array(9),g=new Float64Array(3);let used=0;for(const {m,frame} of obs){const q=projectPoint(frame.poseEstimate,frame.K,p);if(!q)continue;const r=[q.u-m.u,q.v-m.v],e=Math.hypot(...r),w=prob(m.probability)*huber(e,2.0),J=numericPointJacobian(frame.poseEstimate,frame.K,p,q);if(!J)continue;accumulateJTJ(H,g,J,r,w);used++;}if(used<2)break;const prior=1/Math.max(1e-6,traceCov(l.covariance));for(let a=0;a<3;a++){H[a*3+a]+=prior*.08;g[a]+=prior*.08*(p[a]-l.priorPoint[a]);}const d=solveLinear(H,Array.from(g),3);if(!d)break;const dn=Math.hypot(...d),scale=dn>.12?.12/dn:1;for(let a=0;a<3;a++)p[a]-=d[a]*scale*this.landmarkDamping;if(dn<1e-5)break;}
      if(finite3(p))l.point=p;
      // Re-evaluate landmark existence continuously. A factor is never simply
      // "verified": poor multi-view reprojection can lower its posterior again
      // after neighbouring poses/landmarks move during later iterations.
      const errs=[];for(const {m,frame} of obs){const q=projectPoint(frame.poseEstimate,frame.K,l.point);if(q)errs.push(Math.hypot(q.u-m.u,q.v-m.v));}
      if(errs.length){const e=median(errs),prior=clamp(l.priorProbability??l.probability,.002,.998),odds=prior/(1-prior),lr=Math.exp(-.5*(e/1.6)**2)/.10,support=1+Math.log1p(Math.max(0,errs.length-2))*.18,post=odds*lr*support;l.probability=clamp(post/(1+post),.002,.998);l.posteriorReprojectionPx=e;}
    }
  }
  refinePoses(){
    const byFrame=new Map();for(const l of this.landmarks)for(const m of l.measurements||[]){const id=String(m.frameId);if(!this.frameMap.has(id))continue;let a=byFrame.get(id);if(!a)byFrame.set(id,a=[]);if(a.length<this.maxObsPerFrame)a.push({l,m});}
    for(let fi=1;fi<this.frames.length;fi++){const f=this.frames[fi],list=byFrame.get(String(f.frameId))||[];if(list.length<6)continue;const H=new Float64Array(36),g=new Float64Array(6);let used=0;
      for(const {l,m} of list){const q=projectPoint(f.poseEstimate,f.K,l.point);if(!q)continue;const r=[q.u-m.u,q.v-m.v],e=Math.hypot(...r),w=prob(m.probability)*prob(l.probability)*huber(e,2.2),J=numericPoseJacobian(f.poseEstimate,f.K,l.point,q);if(!J)continue;accumulateJTJ6(H,g,J,r,w);used++;}
      if(used<6)continue;const diag=f.poseCov?.diag||[4e-4,4e-4,4e-4,2e-4,2e-4,2e-4],deltaPrior=poseDelta6(f.posePrior,f.poseEstimate);for(let a=0;a<6;a++){const w=this.posePriorScale/Math.max(1e-9,+diag[a]||1e-4);H[a*6+a]+=w;g[a]+=w*deltaPrior[a];}
      const d=solveLinear(H,Array.from(g),6);if(!d)continue;const dt=Math.hypot(d[0],d[1],d[2]),dr=Math.hypot(d[3],d[4],d[5]),s=Math.min(1,.035/Math.max(.035,dt),.025/Math.max(.025,dr))*this.poseDamping;f.poseEstimate=perturbPose(f.poseEstimate,d.map(x=>-x*s));
    }
  }
  fitDeepSequence(){
    const deepMap=new Map(this.graph.deepFactors.map(d=>[String(d.frameId),d])),pairs=[];
    for(const l of this.landmarks){for(const m of l.measurements||[]){const f=this.frames[this.frameMap.get(String(m.frameId))],d=deepMap.get(String(m.frameId));if(!f||!d)continue;const q=projectPoint(f.poseEstimate,f.K,l.point);if(!q||q.z<=0)continue;const raw=sampleDeepGrid(d,m.u,m.v,f.K.width||f.width,f.K.height||f.height);if(!Number.isFinite(raw)||Math.abs(raw)<1e-8)continue;pairs.push({raw,depth:q.z,w:deepQualityWeight(d)*prob(m.probability)*prob(l.probability)/Math.max(.02,l.relativeDepthSigma||.1)});}}
    if(pairs.length<12)return this.deepModel;let best=null;for(const mode of ['direct','inverse-raw','inverse-depth']){const x=robustFit(pairs,mode);if(x&&(!best||x.error<best.error))best=x;}return best?{...best,pairs:pairs.length}:this.deepModel;
  }
  computeStats(){let ss=0,n=0,energy=0,shift=0,rotShift=0;for(const l of this.landmarks)for(const m of l.measurements||[]){const f=this.frames[this.frameMap.get(String(m.frameId))];if(!f)continue;const q=projectPoint(f.poseEstimate,f.K,l.point);if(!q)continue;const e=Math.hypot(q.u-m.u,q.v-m.v),w=prob(m.probability)*prob(l.probability);ss+=e*e;n++;energy+=w*Math.min(e*e,16);}for(const f of this.frames){shift+=Math.hypot(f.poseEstimate.p[0]-f.posePrior.p[0],f.poseEstimate.p[1]-f.posePrior.p[1],f.poseEstimate.p[2]-f.posePrior.p[2]);const d=poseDelta6(f.posePrior,f.poseEstimate);rotShift+=Math.hypot(d[3],d[4],d[5]);}return {iterations:this.iterations,energy,reprojectionRmse:n?Math.sqrt(ss/n):Infinity,poseShiftMean:this.frames.length?shift/this.frames.length:0,poseRotationShiftMeanRad:this.frames.length?rotShift/this.frames.length:0,deepRelativeError:this.deepModel?.error??Infinity,deepMode:this.deepModel?.mode||null,deepPairs:this.deepModel?.pairs||0,landmarks:this.landmarks.length,observations:n};}
  landmarkPreview(max=14000){const out=[];for(let i=0;i<this.landmarks.length&&out.length<max;i++){const l=this.landmarks[i],f=this.frames[this.frameMap.get(String(l.measurements?.[0]?.frameId||''))],depth=f?projectPoint(f.poseEstimate,f.K,l.point)?.z:2,scale=Math.max(.004,(depth||2)/(f?.K?.fx||300)*1.5),cov=l.covariance||[scale*scale,0,0,scale*scale,0,scale*scale*4];out.push({id:l.id,position:l.point.slice(),normal:f?norm(sub(f.poseEstimate.p,l.point)):[0,0,-1],color:[245,210,70],scale:[scale,scale,Math.max(.002,scale*.35)],covariance:cov,positionCovariance:cov,opacity:clamp(.25+.65*prob(l.probability),.2,.95),confidence:prob(l.probability),support:l.measurements?.length||1});}return out;}
  snapshot(){return {format:'ROOMSCAN-PROB-OPT-1',iterations:this.iterations,frames:this.frames.map(f=>({frameId:f.frameId,poseEstimate:f.poseEstimate})),landmarks:this.landmarks.map(l=>({id:l.id,point:l.point,probability:l.probability})),deepModel:this.deepModel,stats:this.lastStats};}

  /** Rebuild a dense Gaussian/mesh hypothesis from current graph variables. */
  rebuild({voxel=.035,hashVoxel=.02,maxSurfels=90000,maxTriangles=90000,maxDeepSamples=45000,maxMvsSamples=50000}={}){
    const fusion=new SparseDenseFusion({voxel,hashVoxel,minSupport:2,minConfirmBaseline:voxel*.65,maxSurfels,maxTsdf:Math.max(180000,maxSurfels*4),tsdfMinSupport:2,tsdfMaxSurfels:Math.min(70000,maxSurfels),observationReservoir:4});
    // Sparse metric skeleton: highest-information evidence.
    for(const l of this.landmarks){const frames=(l.measurements||[]).map(m=>String(m.frameId)),ref=this.frames[this.frameMap.get(frames[0])];if(!ref)continue;const cov=addPoseUncertaintyToPointCovariance(l.covariance,ref.poseCov,l.point,ref.poseEstimate.p),ray=sub(l.point,ref.poseEstimate.p),depth=Math.hypot(...ray);fusion.integrate([{p:l.point,depth,covariance:cov,sigmaDepth:Math.sqrt(Math.max(1e-10,quadCov(cov,norm(ray)))),normal:norm(ray).map(x=>-x),normalReliable:false,color:[235,210,90],confidence:clamp(l.probability,.02,.995),radius:Math.max(voxel*.20,depth/Math.max(ref.K.fx,ref.K.fy)*1.4),source:'track-probabilistic',trackId:l.id,evidenceFrames:frames,viewSupport:new Set(frames).size}],{origin:ref.poseEstimate.p,frameId:frames[0],mode:'track-probabilistic'});}
    // Independent photometric MVS observations, reprojected from corrected pose.
    let mvsCount=0;for(const mf of this.graph.mvsFactors){const f=this.frames[this.frameMap.get(String(mf.frameId))];if(!f)continue;const rows=[];for(const s of iterateMvsFactor(mf)){if(mvsCount>=maxMvsSamples)break;const p=unproject(f.poseEstimate,f.K,s.u,s.v,s.depth),ray=norm(sub(p,f.poseEstimate.p)),sl=Math.max(voxel*.08,s.depth/Math.max(f.K.fx,f.K.fy)*1.6),sd=Math.max(voxel*.12,+s.sigmaDepth||s.depth*.06),baseCov=rayCov(ray,sd,sl),cov=addPoseUncertaintyToPointCovariance(baseCov,f.poseCov,p,f.poseEstimate.p);rows.push({p,depth:s.depth,covariance:cov,sigmaDepth:sd,sigmaLateral:sl,normal:Array.isArray(s.normal)?s.normal:ray.map(x=>-x),normalReliable:!!s.normal,color:s.color||[165,190,215],confidence:clamp(s.probability,.015,.98),radius:sl*1.3,source:'mvs-probabilistic',evidenceFrames:[String(mf.frameId),...(s.sourceFrames||[])],viewSupport:1+(s.sourceFrames?.length||0)});mvsCount++;}if(rows.length)fusion.integrate(rows,{origin:f.poseEstimate.p,frameId:String(mf.frameId),mode:'mvs-probabilistic'});if(mvsCount>=maxMvsSamples)break;}
    // Monocular completion has deliberately broad uncertainty and can only be
    // confirmed by another camera frame. It never overrides sparse/MVS geometry.
    let deepCount=0;if(this.deepModel){for(const d of this.graph.deepFactors){const f=this.frames[this.frameMap.get(String(d.frameId))];if(!f)continue;const rows=[],sx=(f.K.width||f.width)/d.cols,sy=(f.K.height||f.height)/d.rows;for(let gy=0;gy<d.rows;gy+=2)for(let gx=0;gx<d.cols;gx+=2){if(deepCount>=maxDeepSamples)break;const raw=d.raw[gy*d.cols+gx],z=predictDeep(this.deepModel,raw);if(!(z>.2&&z<12))continue;const u=(gx+.5)*sx,v=(gy+.5)*sy,p=unproject(f.poseEstimate,f.K,u,v,z),ray=norm(sub(p,f.poseEstimate.p)),rel=clamp((this.deepModel.error||.15)*1.7,.06,.38),sd=z*rel,sl=Math.max(voxel*.15,z/Math.max(f.K.fx,f.K.fy)*Math.max(sx,sy)*.65),cov=addPoseUncertaintyToPointCovariance(rayCov(ray,sd,sl),f.poseCov,p,f.poseEstimate.p);rows.push({p,depth:z,covariance:cov,sigmaDepth:sd,sigmaLateral:sl,normal:ray.map(x=>-x),normalReliable:false,color:[130,165,205],confidence:clamp(.30*Math.exp(-3*(this.deepModel.error||.2)),.025,.35),radius:sl,source:'deep-sequence-probabilistic',evidenceFrames:[String(d.frameId)],viewSupport:1});deepCount++;}if(rows.length)fusion.integrate(rows,{origin:f.poseEstimate.p,frameId:String(d.frameId),mode:'deep-sequence-probabilistic'});if(deepCount>=maxDeepSamples)break;}}
    const gaussians=fusion.splats({max:maxSurfels}),mesh=fusion.mesh({maxTriangles,maxSurfels:Math.min(70000,maxSurfels)});return {gaussians,mesh,stats:{...fusion.exportPersistentState({maxSurfels:1}).stats,landmarkCount:this.landmarks.length,mvsCount,deepCount}};
  }
}

function normaliseGraph(g){return g?.format==='ROOMSCAN-PROB-GRAPH-1'?g:(g?.exportState?g.exportState():{frames:[],landmarkFactors:[],deepFactors:[],mvsFactors:[]});}
function clonePose(p){return {p:p.p.slice(0,3).map(Number),q:qNormalize(p.q.slice(0,4).map(Number))};}
function prob(p){return clamp(Number(p)||.01,.001,.999);}
function huber(e,k){return e<=k?1:k/Math.max(k,e);}
function finite3(p){return p?.length>=3&&p.slice(0,3).every(Number.isFinite);}
function traceCov(c){return (+c[0]||0)+(+c[3]||0)+(+c[5]||0);}
function numericPointJacobian(pose,K,p,q){const eps=Math.max(1e-5,q.z*2e-6),J=[new Float64Array(3),new Float64Array(3)];for(let k=0;k<3;k++){const x=p.slice();x[k]+=eps;const z=projectPoint(pose,K,x);if(!z)return null;J[0][k]=(z.u-q.u)/eps;J[1][k]=(z.v-q.v)/eps;}return J;}
function numericPoseJacobian(pose,K,p,q){const J=[new Float64Array(6),new Float64Array(6)];for(let k=0;k<6;k++){const eps=k<3?1e-5:5e-6,d=new Array(6).fill(0);d[k]=eps;const z=projectPoint(perturbPose(pose,d),K,p);if(!z)return null;J[0][k]=(z.u-q.u)/eps;J[1][k]=(z.v-q.v)/eps;}return J;}
function accumulateJTJ(H,g,J,r,w){for(let a=0;a<3;a++){g[a]+=w*(J[0][a]*r[0]+J[1][a]*r[1]);for(let b=0;b<3;b++)H[a*3+b]+=w*(J[0][a]*J[0][b]+J[1][a]*J[1][b]);}}
function accumulateJTJ6(H,g,J,r,w){for(let a=0;a<6;a++){g[a]+=w*(J[0][a]*r[0]+J[1][a]*r[1]);for(let b=0;b<6;b++)H[a*6+b]+=w*(J[0][a]*J[0][b]+J[1][a]*J[1][b]);}}
function solveLinear(A,b,n){A=Float64Array.from(A);b=Float64Array.from(b);for(let i=0;i<n;i++){let pivot=i,best=Math.abs(A[i*n+i]);for(let r=i+1;r<n;r++){const v=Math.abs(A[r*n+i]);if(v>best){best=v;pivot=r;}}if(best<1e-12)return null;if(pivot!==i){for(let c=i;c<n;c++){const t=A[i*n+c];A[i*n+c]=A[pivot*n+c];A[pivot*n+c]=t;}const t=b[i];b[i]=b[pivot];b[pivot]=t;}const d=A[i*n+i];for(let c=i;c<n;c++)A[i*n+c]/=d;b[i]/=d;for(let r=0;r<n;r++){if(r===i)continue;const f=A[r*n+i];if(!f)continue;for(let c=i;c<n;c++)A[r*n+c]-=f*A[i*n+c];b[r]-=f*b[i];}}return Array.from(b);}
function perturbPose(p,d){const t={p:[p.p[0]+d[0],p.p[1]+d[1],p.p[2]+d[2]],q:p.q},a=[d[3],d[4],d[5]],ang=Math.hypot(...a);if(ang>1e-12){const s=Math.sin(ang/2)/ang,dq=[a[0]*s,a[1]*s,a[2]*s,Math.cos(ang/2)];t.q=qNormalize(qMul(p.q,dq));}else t.q=p.q.slice();return t;}
function poseDelta6(prior,current){const dq=qNormalize(qMul(qConj(prior.q),current.q)),qq=dq[3]<0?dq.map(x=>-x):dq,sv=Math.hypot(qq[0],qq[1],qq[2]);let rv=[0,0,0];if(sv>1e-12){const ang=2*Math.atan2(sv,Math.max(1e-12,qq[3])),k=ang/sv;rv=[qq[0]*k,qq[1]*k,qq[2]*k];}return [current.p[0]-prior.p[0],current.p[1]-prior.p[1],current.p[2]-prior.p[2],...rv];}
function sampleDeepGrid(d,u,v,w,h){const x=clamp(u/Math.max(1,w)*d.cols-.5,0,d.cols-1),y=clamp(v/Math.max(1,h)*d.rows-.5,0,d.rows-1),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(d.cols-1,x0+1),y1=Math.min(d.rows-1,y0+1),tx=x-x0,ty=y-y0,a=d.raw;return (a[y0*d.cols+x0]*(1-tx)+a[y0*d.cols+x1]*tx)*(1-ty)+(a[y1*d.cols+x0]*(1-tx)+a[y1*d.cols+x1]*tx)*ty;}
function robustFit(pairs,mode){let active=pairs.slice(),fit=null;for(let it=0;it<4;it++){fit=wls(active,mode);if(!fit)return null;const errs=active.map(p=>Math.abs(predictDeep({...fit,mode},p.raw)-p.depth)/Math.max(.05,p.depth)),med=median(errs),mad=median(errs.map(x=>Math.abs(x-med))),gate=Math.max(.025,med+2.8*Math.max(.008,mad));const kept=active.filter((_,i)=>errs[i]<=gate);if(kept.length<8||kept.length===active.length)break;active=kept;}const errs=pairs.map(p=>Math.abs(predictDeep({...fit,mode},p.raw)-p.depth)/Math.max(.05,p.depth));return {...fit,mode,error:weightedMedian(errs,pairs.map(x=>x.w)),inlierRatio:active.length/pairs.length};}
function wls(a,mode){let sw=0,sx=0,sy=0,sxx=0,sxy=0;for(const p of a){let x,y;if(mode==='direct'){x=p.raw;y=p.depth;}else if(mode==='inverse-raw'){x=1/Math.max(1e-8,Math.abs(p.raw));y=p.depth;}else{x=p.raw;y=1/Math.max(1e-8,p.depth);}const w=Math.max(.001,p.w);sw+=w;sx+=w*x;sy+=w*y;sxx+=w*x*x;sxy+=w*x*y;}const den=sw*sxx-sx*sx;if(Math.abs(den)<1e-10)return null;const A=(sw*sxy-sx*sy)/den,B=(sy-A*sx)/sw;return Number.isFinite(A+B)?{a:A,b:B}:null;}
function predictDeep(m,r){if(!m||!Number.isFinite(r))return NaN;if(m.mode==='direct')return m.a*r+m.b;if(m.mode==='inverse-raw')return m.a/Math.max(1e-8,Math.abs(r))+m.b;const q=m.a*r+m.b;return q>1e-8?1/q:NaN;}
function weightedMedian(v,w){const a=v.map((x,i)=>[x,Math.max(.001,w[i]||.001)]).filter(x=>Number.isFinite(x[0])).sort((a,b)=>a[0]-b[0]),sum=a.reduce((s,x)=>s+x[1],0);let c=0;for(const x of a){c+=x[1];if(c>=sum*.5)return x[0];}return Infinity;}
function median(a){const b=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return Infinity;const m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])*.5;}
function unproject(pose,K,u,v,z){const d=pixelRay(K,u,v),cam=[d[0]/Math.max(1e-9,d[2])*z,d[1]/Math.max(1e-9,d[2])*z,z],w=qRotate(pose.q,cam);return [pose.p[0]+w[0],pose.p[1]+w[1],pose.p[2]+w[2]];}
function rayCov(r,sd,sl){const a=sl*sl,d=sd*sd-a;return [a+d*r[0]*r[0],d*r[0]*r[1],d*r[0]*r[2],a+d*r[1]*r[1],d*r[1]*r[2],a+d*r[2]*r[2]];}
function norm(v){const n=Math.hypot(...v)||1;return v.map(x=>x/n);}function sub(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]];}function quadCov(c,v){return v[0]*(c[0]*v[0]+c[1]*v[1]+c[2]*v[2])+v[1]*(c[1]*v[0]+c[3]*v[1]+c[4]*v[2])+v[2]*(c[2]*v[0]+c[4]*v[1]+c[5]*v[2]);}

function* iterateMvsFactor(m){if(!m)return;if(!m.packed){for(const s of m.samples||[])yield s;return;}const n=m.count||Math.floor((m.data?.length||0)/8),a=m.data||[],nn=m.normal||[],cc=m.color||[],fl=m.flags||[];for(let i=0;i<n;i++){const o=i*8;yield {u:a[o],v:a[o+1],depth:a[o+2],probability:a[o+3],sigmaDepth:a[o+4],cost:a[o+5],distinctiveness:a[o+6],photoAgreement:a[o+7],priorEscaped:!!fl[i],sourceFrames:m.sourceFrames||[],normal:[nn[i*3],nn[i*3+1],nn[i*3+2]],color:[cc[i*3],cc[i*3+1],cc[i*3+2]]};}}

function deepQualityWeight(d){const q=d?.quality||{};if(q.suspicious)return .05;const coherence=Number(q.coherenceRatio);let w=1;if(Number.isFinite(coherence)&&coherence<1.28)w*=.18;if(q.stripe?.suspicious)w*=.08;const explained=Number(q.stripe?.dominantExplained);if(Number.isFinite(explained)&&explained>.82)w*=.35;return clamp(w,.03,1);}
