import {DenseDepthConsistencyEvaluator} from './cross_depth_consistency.js?v=30.42.0';
import {predictMetricDepth} from './depth_calibration_hierarchy.js?v=30.42.0';
import {classifyResidualCauses} from './residual_cause_model.js?v=30.42.0';
import {projectPoint} from '../slam/math.js?v=30.42.0';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

/**
 * Multi-resolution E-step. Confidence is stored per frame and per region; pixel
 * confidence is derived on demand. The tested frame never validates itself:
 * DenseDepthConsistencyEvaluator only compares it with neighbouring views.
 */
export class HierarchicalReliabilityFeedback{
  constructor({frames=[],landmarks=[],deepFactors=[],calibration=null,photoEdges=[],edgeModel=null,alvaModel=null,regionCols=8,regionRows=8,maxNeighbors=4}={}){Object.assign(this,{frames,landmarks,deepFactors,calibration,photoEdges,edgeModel,alvaModel,regionCols,regionRows,maxNeighbors});this.frameMap=new Map(frames.map((f,i)=>[String(f.frameId),i]));this.deepMap=new Map(deepFactors.map(d=>[String(d.frameId),d]));this.frameConfidence=new Map();this.regionConfidence=new Map();this.causes=new Map();this.stats={frames:0,regions:0,meanDepthConfidence:0};}
  update(){if(!this.calibration)return this;const evaluator=new DenseDepthConsistencyEvaluator({frames:this.frames,deepFactors:this.deepFactors,calibration:this.calibration,photoEdges:this.photoEdges,edgeModel:this.edgeModel,maxNeighbors:this.maxNeighbors}),calMap=new Map((this.calibration.frames||[]).map(x=>[String(x.frameId),x]));let sum=0,n=0,regions=0;
    for(const f of this.frames){const id=String(f.frameId),d=this.deepMap.get(id),cal=calMap.get(id);if(!d?.raw?.length||!cal)continue;const cells=Array.from({length:this.regionCols*this.regionRows},()=>({samples:[],support:0,conflict:0,occluded:0,weight:0,count:0})),all=[],sx=(f.K.width||f.width)/d.cols,sy=(f.K.height||f.height)/d.rows;
      for(let gy=0;gy<d.rows;gy+=2)for(let gx=0;gx<d.cols;gx+=2){const raw=d.raw[gy*d.cols+gx],z=predictMetricDepth(cal,raw,this.calibration);if(!(z>.08&&z<30))continue;const u=(gx+.5)*sx,v=(gy+.5)*sy,ev=evaluator.evaluate(id,u,v,z),res=Number(ev.residualMedian);if(Number.isFinite(res))all.push({u,v,r:res,w:Math.max(.03,ev.weight)});const rx=clamp(Math.floor(u/Math.max(1,f.K.width||f.width)*this.regionCols),0,this.regionCols-1),ry=clamp(Math.floor(v/Math.max(1,f.K.height||f.height)*this.regionRows),0,this.regionRows-1),c=cells[ry*this.regionCols+rx];c.count++;c.support+=ev.support||0;c.conflict+=ev.conflicts||0;c.occluded+=ev.occluded||0;c.weight+=ev.weight||0;if(Number.isFinite(res))c.samples.push({u,v,r:res,w:ev.weight});}
      const reproj=this.frameReprojection(id),priorReproj=this.frameReprojection(id,true),improve=Number.isFinite(priorReproj)&&priorReproj>0?clamp((priorReproj-reproj)/Math.max(.5,priorReproj),0,1):0,cause=classifyResidualCauses(all,{width:f.K.width||f.width,height:f.K.height||f.height,rgbReprojectionPx:reproj,poseImprovement:improve});this.causes.set(id,cause);const rconf=new Float32Array(cells.length);for(let i=0;i<cells.length;i++){const c=cells[i],agreement=c.count?clamp((c.support+.25*c.occluded)/(c.support+c.conflict+c.occluded+1),0,1):.08,edgePenalty=1-.72*cause.depthLocal,posePenalty=1-.45*cause.poseError,base=c.count?c.weight/c.count:.08;rconf[i]=clamp((.12+.88*agreement)*(.25+.75*base)*edgePenalty*posePenalty,.015,1);regions++;}this.regionConfidence.set(id,rconf);const rgbQ=clamp(Number(f.photoQuality?.score??.65),.08,1),causePenalty=clamp(1-.55*cause.depthGlobal-.40*cause.wrongMatches-.35*cause.dynamic,.12,1),fc=clamp(mean(rconf)*(.25+.75*(cal.confidence||.05))*(.35+.65*rgbQ)*causePenalty,.01,1);this.frameConfidence.set(id,fc);sum+=fc;n++;}
    this.stats={frames:n,regions,meanDepthConfidence:n?sum/n:0};return this;}
  causeForFrame(frameId){return this.causes.get(String(frameId))||null;}
  frameDepthConfidence(frameId){return this.frameConfidence.get(String(frameId))??.02;}
  pixelConfidence(frameId,u,v,{structural=1,visibility=1}={}){const id=String(frameId),f=this.frames[this.frameMap.get(id)],r=this.regionConfidence.get(id),fc=this.frameConfidence.get(id)??.05;if(!f||!r)return .02;const x=clamp(Math.floor(u/Math.max(1,f.K.width||f.width)*this.regionCols),0,this.regionCols-1),y=clamp(Math.floor(v/Math.max(1,f.K.height||f.height)*this.regionRows),0,this.regionRows-1),rc=r[y*this.regionCols+x]||.03;return clamp(Math.sqrt(fc*rc)*clamp(structural,.02,1)*clamp(visibility,.02,1),.005,1);}
  frameReprojection(frameId,usePrior=false){const id=String(frameId),f=this.frames[this.frameMap.get(id)];if(!f)return Infinity;const e=[];for(const l of this.landmarks){for(const m of l.measurements||[])if(String(m.frameId)===id){const q=projectPoint(usePrior?f.posePrior:f.poseEstimate,f.K,l.point);if(q)e.push(Math.hypot(q.u-m.u,q.v-m.v));}}return median(e);}
  poseImprovementMap(){const m=new Map();for(const f of this.frames){const a=this.frameReprojection(f.frameId,true),b=this.frameReprojection(f.frameId,false);m.set(String(f.frameId),Number.isFinite(a+b)&&a>0?clamp((a-b)/Math.max(.5,a),0,1):0);}return m;}
  rgbSupportMap(){const m=new Map();for(const f of this.frames)m.set(String(f.frameId),this.edgeModel?.incidentWeight?.(f.frameId)??.5);return m;}
  summary(){const causes=[...this.causes.values()];return {...this.stats,poseSuspect:causes.filter(x=>x.poseError>.45).length,localDepthSuspect:causes.filter(x=>x.depthLocal>.45).length,globalDepthSuspect:causes.filter(x=>x.depthGlobal>.45).length};}
  serialize(){return {format:'ROOMSCAN-RELIABILITY-FEEDBACK-1',stats:this.summary(),frames:this.frames.map(f=>({frameId:String(f.frameId),confidence:this.frameConfidence.get(String(f.frameId))??.02,cause:this.causes.get(String(f.frameId))||null,regions:Array.from(this.regionConfidence.get(String(f.frameId))||[]),regionCols:this.regionCols,regionRows:this.regionRows}))};}
}
function mean(a){if(!a?.length)return 0;let s=0;for(const x of a)s+=x;return s/a.length;}function median(a){const b=(a||[]).filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return Infinity;const m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])*.5;}
