const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

/** Lightweight model selection over the spatial residual field. */
export function classifyResidualCauses(samples,{width=1,height=1,rgbReprojectionPx=null,poseImprovement=0}={}){
  const a=(samples||[]).filter(s=>Number.isFinite(s?.r));if(a.length<6)return base();const xs=[],ys=[],rs=[],ws=[];for(const s of a){xs.push((Number(s.u)||0)/Math.max(1,width)-.5);ys.push((Number(s.v)||0)/Math.max(1,height)-.5);rs.push(+s.r);ws.push(clamp(Number(s.w)||1,.01,10));}
  const fit=fitPlane(xs,ys,rs,ws),abs=rs.map(Math.abs),med=median(abs),signedMed=median(rs),mad=median(rs.map(x=>Math.abs(x-median(rs))))||1e-6,coverage=spatialCoverage(xs,ys),outlierFrac=abs.filter(x=>x>Math.max(3*mad,med*2.5,1e-3)).length/a.length,lowDim=clamp(fit.r2*coverage,0,1),gradient=Math.hypot(fit.b,fit.c),globalShift=clamp(Math.abs(signedMed)/(Math.abs(signedMed)+2.5*mad+1e-6),0,1),locality=clamp(outlierFrac*(1-lowDim)*2.2,0,1),rgbBad=Number.isFinite(rgbReprojectionPx)?clamp((rgbReprojectionPx-1.2)/4,0,1):0,improve=clamp(poseImprovement,0,1);
  let pose=.08+.48*lowDim+.24*rgbBad+.20*improve,depthGlobal=.08+.60*globalShift*(1-rgbBad*.5),depthLocal=.06+.78*locality,wrongMatch=.04+.68*rgbBad*(1-lowDim),occlusion=.05+.42*locality*(gradient>.02?1:.55),dynamic=.03+.30*locality*(rgbBad>.45?1:.35);const vals=[pose,depthGlobal,depthLocal,wrongMatch,occlusion,dynamic],sum=vals.reduce((s,x)=>s+x,0)||1;[pose,depthGlobal,depthLocal,wrongMatch,occlusion,dynamic]=vals.map(x=>x/sum);return {poseError:pose,depthGlobal,depthLocal,wrongMatches:wrongMatch,occlusion,dynamic,lowDimensionality:lowDim,globalShift,locality,gradient,r2:fit.r2,medianResidual:signedMed,mad,coverage,samples:a.length};
}
function fitPlane(x,y,r,w){let A=new Float64Array(9),b=new Float64Array(3),sw=0,mean=0;for(let i=0;i<r.length;i++){const v=[1,x[i],y[i]],q=w[i];sw+=q;mean+=q*r[i];for(let a=0;a<3;a++){b[a]+=q*v[a]*r[i];for(let c=0;c<3;c++)A[a*3+c]+=q*v[a]*v[c];}}const p=solve3(A,b)||[0,0,0];mean/=Math.max(1e-9,sw);let ss=0,se=0;for(let i=0;i<r.length;i++){const q=w[i],e=r[i]-(p[0]+p[1]*x[i]+p[2]*y[i]);se+=q*e*e;ss+=q*(r[i]-mean)*(r[i]-mean);}return {a:p[0],b:p[1],c:p[2],r2:ss>1e-12?clamp(1-se/ss,0,1):0};}
function solve3(A,b){A=Float64Array.from(A);b=Float64Array.from(b);for(let i=0;i<3;i++){let p=i,v=Math.abs(A[i*3+i]);for(let r=i+1;r<3;r++)if(Math.abs(A[r*3+i])>v){v=Math.abs(A[r*3+i]);p=r;}if(v<1e-12)return null;if(p!==i){for(let c=0;c<3;c++){const t=A[i*3+c];A[i*3+c]=A[p*3+c];A[p*3+c]=t;}const t=b[i];b[i]=b[p];b[p]=t;}const d=A[i*3+i];for(let c=i;c<3;c++)A[i*3+c]/=d;b[i]/=d;for(let r=0;r<3;r++)if(r!==i){const f=A[r*3+i];for(let c=i;c<3;c++)A[r*3+c]-=f*A[i*3+c];b[r]-=f*b[i];}}return Array.from(b);}
function spatialCoverage(x,y){const s=new Set();for(let i=0;i<x.length;i++){const gx=clamp(Math.floor((x[i]+.5)*4),0,3),gy=clamp(Math.floor((y[i]+.5)*4),0,3);s.add(`${gx},${gy}`);}return s.size/16;}
function median(a){const b=(a||[]).filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return 0;const m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])*.5;}
function base(){return {poseError:.1,depthGlobal:.15,depthLocal:.2,wrongMatches:.1,occlusion:.2,dynamic:.05,lowDimensionality:0,globalShift:0,locality:0,gradient:0,r2:0,medianResidual:0,mad:0,coverage:0,samples:0};}
