import {projectPoint,qRotate,qConj} from '../slam/math.js?v=30.52.0';
import {estimatePhotoTranslationDirection,translationLineAngle} from './rgb_translation_direction.js?v=30.52.0';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

/**
 * Switch variables for whole RGB edges.
 *
 * A few wrong feature matches inside a good pair are handled by robust losses.
 * A wrong pair of photographs is more dangerous, so every pair has a second
 * switch s_ij in [0,1].  It is driven by visual prior, rotation consistency and
 * shared-landmark reprojection support.  No edge is hard-deleted by RANSAC.
 */
export class SwitchablePhotoEdgeModel{
  constructor(photoEdges=[],{rotationSigmaRad=.055,reprojectionSigmaPx=2.2,minPrior=.03}={}){this.rotationSigmaRad=rotationSigmaRad;this.reprojectionSigmaPx=reprojectionSigmaPx;this.minPrior=minPrior;this.edges=(photoEdges||[]).map((e,k)=>({...e,_key:k,switch:clamp(Number(e.switch??e.visualConfidence??e.weight??.25),.01,.995)}));this.byPair=new Map();this.byFrame=new Map();this.reindex();}
  reindex(){this.byPair.clear();this.byFrame.clear();for(const e of this.edges){const a=String(e.aId??e.a),b=String(e.bId??e.b),k=pairKey(a,b);this.byPair.set(k,e);for(const id of [a,b]){const x=this.byFrame.get(id)||[];x.push(e);this.byFrame.set(id,x);}}}
  update(frames,landmarks,{bootstrap=false}={}){const fm=new Map((frames||[]).map((f,i)=>[String(f.frameId),{f,i}]));for(const e of this.edges){const aId=String(e.aId??e.a),bId=String(e.bId??e.b),A=fm.get(aId)?.f,B=fm.get(bId)?.f;if(!A||!B){e.switch=Math.min(e.switch,.08);continue;}const rotErr=rotationResidualRad(A.poseEstimate||A.posePrior,B.poseEstimate||B.posePrior,e.rotationBToA),shared=sharedLandmarkResidual(aId,bId,A,B,landmarks),prior=clamp(Number(e.visualConfidence??e.weight??.15),this.minPrior,.995),matchSupport=clamp(Math.log1p((e.matches?.length||e.inliers||0))/Math.log(30),.08,1),sharedStrength=clamp(shared.count/14,0,1),rotLike=Math.exp(-.5*(rotErr/this.rotationSigmaRad)**2),landLike=shared.count?Math.exp(-.5*(shared.median/this.reprojectionSigmaPx)**2):.62,dir=estimatePhotoTranslationDirection(e,A,B),predT=relativeTranslationA(A.poseEstimate||A.posePrior,B.poseEstimate||B.posePrior),predN=Math.hypot(...predT),dirErr=dir&&predN>1e-6?translationLineAngle(predT,dir.direction):null,dirLike=Number.isFinite(dirErr)?Math.exp(-.5*(dirErr/.14)**2):.62,dirStrength=dir?clamp(dir.confidence,0,1):0;
      // Direct photo matches contribute an epipolar translation-direction check.
      // This is scale-free, so it cannot fabricate metric translation, but it
      // prevents a rotation-perfect / translation-wrong Alva trajectory from
      // being declared visually consistent merely because landmark overlap is
      // sparse. Missing direction is absence of evidence, not a negative vote.
      const landWeight=.10+.60*sharedStrength,dirWeight=dir?clamp(.18+.37*dirStrength,.18,.55):0,rotWeight=Math.max(.12,1-landWeight-dirWeight),ws=rotWeight+landWeight+dirWeight,structural=clamp((rotWeight*rotLike+landWeight*landLike+dirWeight*dirLike)/ws,0,1),strength=clamp(.10+.30*matchSupport+.42*sharedStrength+.24*dirStrength,.10,1),logitPrior=Math.log(prior/Math.max(1e-9,1-prior)),directionEvidence=dir?clamp((dirLike-.5)*5,-2.8,2.8)*dirStrength:0,landmarkEvidence=shared.count?clamp((landLike-.5)*4,-2.2,2.2)*sharedStrength:0,evidence=clamp((structural-.48)*6+directionEvidence+landmarkEvidence,-4,4),post=1/(1+Math.exp(-(logitPrior+strength*evidence))),alpha=bootstrap?.18:.58,bootstrapFloor=bootstrap?clamp(prior*.72,.08,.32):clamp(prior*.05,.004,.05);e.switch=clamp((1-alpha)*e.switch+alpha*post,bootstrapFloor,.998);e.rotationResidualRad=rotErr;e.sharedLandmarks=shared.count;e.sharedReprojectionPx=shared.median;e.translationDirection=dir?.direction||null;e.translationDirectionConfidence=dir?.confidence||0;e.translationDirectionResidualRad=dirErr;e.translationDirectionMatches=dir?.matchesUsed||0;e.translationDirectionInlierFraction=dir?.inlierFraction??null;e.translationEpipolarResidualRad=dir?.medianEpipolarResidualRad??null;e.translationDirectionParallaxRad=dir?.medianParallaxRad??null;e.posterior=post;e.structuralLikelihood=structural;e.evidenceStrength=strength;e.bootstrapFloor=bootstrap?bootstrapFloor:null;}return this.stats();}
  pairWeight(a,b){return this.byPair.get(pairKey(String(a),String(b)))?.switch??.42;}
  incidentWeight(frameId){const a=this.byFrame.get(String(frameId))||[];if(!a.length)return .45;return clamp(a.reduce((s,e)=>s+e.switch,0)/a.length,.02,1);}
  // Switch-independent contradiction from direct RGB epipolar geometry. This is
  // intentionally available even when the whole-photo switch has already
  // collapsed, so Alva cannot silence the evidence that should falsify it.
  translationContradictionMap(){const acc=new Map();for(const e of this.edges){const a=String(e.aId??e.a),b=String(e.bId??e.b),ang=Number(e.translationDirectionResidualRad),conf=clamp(Number(e.translationDirectionConfidence)||0,0,1),n=Math.max(0,Number(e.translationDirectionMatches)||0),inliers=clamp(Number(e.translationDirectionInlierFraction??1),0,1);if(!Number.isFinite(ang)||conf<.08||n<8)continue;const onset=12*Math.PI/180,full=38*Math.PI/180,severity=clamp((ang-onset)/Math.max(1e-6,full-onset),0,1),support=clamp((n-6)/20,.15,1),v=severity*conf*support*inliers;for(const id of [a,b])acc.set(id,Math.max(acc.get(id)||0,v));}return acc;}
  measurementSupport(landmark,frameId){const others=(landmark?.measurements||[]).map(m=>String(m.frameId)).filter(x=>x!==String(frameId));if(!others.length)return .45;let best=.10;for(const j of others)best=Math.max(best,this.pairWeight(frameId,j));return clamp(best,.10,1);}
  factorsForFrame(frameId){const id=String(frameId),out=[];for(const e of this.byFrame.get(id)||[]){const a=String(e.aId??e.a),b=String(e.bId??e.b);out.push({edge:e,other:a===id?b:a,weight:e.switch});}return out;}
  serialize(){return {format:'ROOMSCAN-SWITCHABLE-RGB-EDGES-1',edges:this.edges.map(e=>({aId:String(e.aId??e.a),bId:String(e.bId??e.b),switch:e.switch,visualConfidence:e.visualConfidence??e.weight??null,rotationResidualRad:e.rotationResidualRad??null,sharedLandmarks:e.sharedLandmarks||0,sharedReprojectionPx:e.sharedReprojectionPx??null}))};}
  restore(state){const by=new Map((state?.edges||[]).map(e=>[pairKey(String(e.aId),String(e.bId)),e]));for(const e of this.edges){const x=by.get(pairKey(String(e.aId??e.a),String(e.bId??e.b)));if(!x)continue;e.switch=clamp(Number(x.switch??e.switch),.002,.998);if(Number.isFinite(+x.rotationResidualRad))e.rotationResidualRad=+x.rotationResidualRad;if(Number.isFinite(+x.sharedReprojectionPx))e.sharedReprojectionPx=+x.sharedReprojectionPx;if(Number.isFinite(+x.sharedLandmarks))e.sharedLandmarks=+x.sharedLandmarks;}return this;}
  stats(){const s=this.edges.map(e=>e.switch),dir=this.edges.filter(e=>Array.isArray(e.translationDirection)&&e.translationDirectionConfidence>.08),dr=dir.map(e=>Number(e.translationDirectionResidualRad)).filter(Number.isFinite),ir=dir.map(e=>Number(e.translationDirectionInlierFraction)).filter(Number.isFinite),er=dir.map(e=>Number(e.translationEpipolarResidualRad)).filter(Number.isFinite),pr=dir.map(e=>Number(e.translationDirectionParallaxRad)).filter(Number.isFinite);return {edges:s.length,active:s.filter(x=>x>.55).length,weak:s.filter(x=>x<=.55&&x>.15).length,rejected:s.filter(x=>x<=.15).length,mean:s.length?s.reduce((a,b)=>a+b,0)/s.length:0,translationDirectionEdges:dir.length,meanTranslationDirectionResidualDeg:dr.length?dr.reduce((a,b)=>a+b,0)/dr.length*180/Math.PI:null,translationDirectionMeanInlierFraction:ir.length?ir.reduce((a,b)=>a+b,0)/ir.length:null,meanEpipolarPlaneResidualDeg:er.length?er.reduce((a,b)=>a+b,0)/er.length*180/Math.PI:null,meanTranslationParallaxDeg:pr.length?pr.reduce((a,b)=>a+b,0)/pr.length*180/Math.PI:null};}
}

export function rotationResidualVector(poseA,poseB,Robs){if(!poseA?.q||!poseB?.q||!Array.isArray(Robs)||Robs.length!==9)return [0,0,0];const RA=qMat(poseA.q),RB=qMat(poseB.q),pred=mul3(transpose3(RA),RB),delta=mul3(transpose3(Robs),pred);return rotationLog(delta);}
export function rotationResidualRad(poseA,poseB,Robs){return Math.hypot(...rotationResidualVector(poseA,poseB,Robs));}

function sharedLandmarkResidual(aId,bId,A,B,landmarks){const errs=[];for(const l of landmarks||[]){let ma=null,mb=null;for(const m of l.measurements||[]){if(String(m.frameId)===aId)ma=m;else if(String(m.frameId)===bId)mb=m;}if(!ma||!mb)continue;const qa=projectPoint(A.poseEstimate||A.posePrior,A.K,l.point),qb=projectPoint(B.poseEstimate||B.posePrior,B.K,l.point);if(!qa||!qb)continue;const ea=Math.hypot(qa.u-ma.u,qa.v-ma.v),eb=Math.hypot(qb.u-mb.u,qb.v-mb.v);if(Number.isFinite(ea+eb))errs.push(.5*(ea+eb));}return {count:errs.length,median:errs.length?median(errs):Infinity};}
function qMat(q){const n=Math.hypot(...q)||1,x=q[0]/n,y=q[1]/n,z=q[2]/n,w=q[3]/n,xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;return [1-2*(yy+zz),2*(xy-wz),2*(xz+wy),2*(xy+wz),1-2*(xx+zz),2*(yz-wx),2*(xz-wy),2*(yz+wx),1-2*(xx+yy)];}
function transpose3(A){return [A[0],A[3],A[6],A[1],A[4],A[7],A[2],A[5],A[8]];}
function mul3(A,B){const C=new Array(9);for(let r=0;r<3;r++)for(let c=0;c<3;c++)C[r*3+c]=A[r*3]*B[c]+A[r*3+1]*B[3+c]+A[r*3+2]*B[6+c];return C;}
function rotationLog(R){const c=clamp((R[0]+R[4]+R[8]-1)/2,-1,1),a=Math.acos(c);if(a<1e-7)return [(R[7]-R[5])*.5,(R[2]-R[6])*.5,(R[3]-R[1])*.5];const s=2*Math.sin(a),k=a/Math.max(1e-9,s);return [(R[7]-R[5])*k,(R[2]-R[6])*k,(R[3]-R[1])*k];}
function relativeTranslationA(a,b){if(!a?.p||!b?.p||!a?.q)return [0,0,0];return qRotate(qConj(a.q),[b.p[0]-a.p[0],b.p[1]-a.p[1],b.p[2]-a.p[2]]);}
function dot3(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
function pairKey(a,b){return a<b?`${a}|${b}`:`${b}|${a}`;}
function median(a){const b=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return Infinity;const m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])*.5;}
