import {CaptureRepository} from '../js/db_v20_2_0.js';
import {makeESS} from '../js/audio_v20_2_0.js';
import {acousticMeasurementSchema,aggregateRelativeRIRs,analyzeRIRWindow} from '../js/acoustics_v20_2_0.js';

let cancelled=false;
self.onmessage=e=>{const m=e.data||{};if(m.type==='cancel'){cancelled=true;return;}if(m.type==='run'){cancelled=false;run(m).catch(error=>postMessage({type:'error',message:error.message,stack:error.stack}));}};
async function run({sessionId}){const repo=new CaptureRepository();await repo.open();const [records,blobs]=await Promise.all([repo.getRecords(sessionId),repo.getBlobs(sessionId,'audio-pcm')]),chirps=records.filter(r=>r.kind==='chirp').map(r=>r.value).sort((a,b)=>a.expectedMicFrame-b.expectedMicFrame),chunks=blobs.sort((a,b)=>(a.meta.sequence||0)-(b.meta.sequence||0));if(!chirps.length)throw new Error('Nessun chirp salvato');if(!chunks.length)throw new Error('Nessun PCM salvato');const sr=chunks[0].meta.sampleRate||48000,analyses=[];for(let i=0;i<chirps.length;i++){if(cancelled)throw new Error('Analisi RIR annullata');const c=chirps[i],pre=Math.round(.22*sr),post=Math.round((c.sweep.durationS+(c.tailDurationS||.62)+.35)*sr),start=Math.max(0,(c.expectedMicFrame||0)-pre),end=(c.expectedMicFrame||0)+post,window=await readPCMWindow(chunks,start,end),sweep=makeESS(sr,{durationS:c.sweep.durationS,startHz:c.sweep.startHz,endHz:c.sweep.endHz,level:c.sweep.level}).samples,analysis=analyzeRIRWindow(window,sweep,sr,{chirpId:c.id,pose:c.pose,motionQuality:Math.max(.08,c.captureQuality??1)}),schema=acousticMeasurementSchema(c,analysis),rirBlob=new Blob([analysis.rir.buffer],{type:'application/x-roomscan-rir-f32'});await repo.enqueueBlob(sessionId,'rir-f32',rirBlob,{chirpId:c.id,sampleRate:sr,directIndex:analysis.directIndex,absoluteDelayS:analysis.absoluteDelayS,absoluteDelayTrusted:false},`${sessionId}/rir/${String(i).padStart(6,'0')}-${c.id}.f32`);await repo.enqueueRecord(sessionId,'rir-analysis',schema,{key:`${sessionId}/rir-analysis/${String(i).padStart(6,'0')}`});analyses.push(analysis);postMessage({type:'progress',progress:100*(i+1)/chirps.length,detail:`RIR ${i+1}/${chirps.length}, SNR ${analysis.snrDb.toFixed(1)} dB`});}
  const aggregate=aggregateRelativeRIRs(analyses),model=await repo.getModel(sessionId);if(model){model.acoustics.status='relative-rir-estimated';model.acoustics.measurements=(await repo.getRecords(sessionId,'rir-analysis')).map(r=>r.value);model.acoustics.aggregate={count:aggregate?.count||0,totalWeight:aggregate?.totalWeight||0,absoluteDelayTrusted:false};await repo.putModel(sessionId,model);}if(aggregate)await repo.enqueueBlob(sessionId,'rir-aggregate-f32',new Blob([aggregate.rir.buffer]),{sampleRate:sr,count:aggregate.count,absoluteDelayTrusted:false},`${sessionId}/rir/aggregate.f32`);await repo.drain(2500);postMessage({type:'complete',count:analyses.length,valid:analyses.filter(a=>a.quality>.2).length});repo.close();}
async function readPCMWindow(chunks,start,end){const out=new Int16Array(Math.max(0,end-start));for(const chunk of chunks){const a=chunk.meta.startFrame??0,b=chunk.meta.endFrame??a+(chunk.meta.frames||0);if(b<=start||a>=end)continue;const pcm=new Int16Array(await chunk.blob.arrayBuffer()),from=Math.max(start,a),to=Math.min(end,b),srcOffset=from-a,dstOffset=from-start;out.set(pcm.subarray(srcOffset,srcOffset+(to-from)),dstOffset);}const f=new Float32Array(out.length);for(let i=0;i<out.length;i++)f[i]=out[i]/32768;return f;}
