/*
 * Sequential Depth Anything worker. It is loaded only from processing.html,
 * never during WebXR. Local assets are tried before network URLs.
 */
let ortReady=false,session=null,inputName=null,outputName=null,currentConfig=null;
self.onmessage=async e=>{const m=e.data||{};try{if(m.type==='init')await init(m);else if(m.type==='process')await processFrame(m);else if(m.type==='dispose')dispose();}catch(error){postMessage({type:'error',requestId:m.requestId||null,message:error.message||String(error),stack:error.stack||null});}};
async function init(m){if(session){postMessage({type:'ready',cached:true,modelUrl:currentConfig?.modelUrl});return;}currentConfig=m;postMessage({type:'status',stage:'runtime-loading'});const runtimeUrls=m.runtimeUrls||['../vendor/onnxruntime-web/ort.min.js','https://cdn.jsdelivr.net/npm/onnxruntime-web@1.23.2/dist/ort.min.js'];let runtimeError=null;for(const url of runtimeUrls){try{importScripts(url);if(self.ort){runtimeError=null;break;}}catch(e){runtimeError=e;}}if(!self.ort)throw runtimeError||new Error('ONNX Runtime Web non disponibile');ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;if(m.wasmPaths)ort.env.wasm.wasmPaths=new URL(m.wasmPaths,self.location.href).href;postMessage({type:'status',stage:'model-loading',wasmPaths:ort.env.wasm.wasmPaths});const modelUrls=m.modelUrls||['../models/depth_anything_v2_small_q4.onnx','../models/depth_anything_v2_small_q4f16.onnx','https://huggingface.co/onnx-community/depth-anything-v2-small/resolve/main/onnx/model_q4.onnx'];let last=null;for(const url of modelUrls){try{session=await ort.InferenceSession.create(url,{executionProviders:['wasm'],graphOptimizationLevel:'all',enableCpuMemArena:true});last=null;currentConfig.modelUrl=url;break;}catch(e){last=e;}}if(!session)throw last||new Error('Modello Depth Anything non disponibile');inputName=session.inputNames?.[0]||Object.keys(session.inputMetadata||{})[0];outputName=session.outputNames?.[0]||Object.keys(session.outputMetadata||{})[0];ortReady=true;postMessage({type:'ready',modelUrl:currentConfig.modelUrl,inputName,outputName,wasmPaths:ort.env.wasm.wasmPaths});}
async function processFrame(m){if(!ortReady)throw new Error('Depth worker non inizializzato');const size=m.inputSize||518,bitmap=await createImageBitmap(m.blob),canvas=new OffscreenCanvas(size,size),ctx=canvas.getContext('2d',{alpha:false,willReadFrequently:true});ctx.drawImage(bitmap,0,0,size,size);bitmap.close();const image=ctx.getImageData(0,0,size,size),rgba=image.data,input=new Float32Array(3*size*size),mean=[.485,.456,.406],std=[.229,.224,.225];for(let i=0,p=0;i<rgba.length;i+=4,p++){input[p]=(rgba[i]/255-mean[0])/std[0];input[size*size+p]=(rgba[i+1]/255-mean[1])/std[1];input[2*size*size+p]=(rgba[i+2]/255-mean[2])/std[2];}const feeds={};feeds[inputName]=new ort.Tensor('float32',input,[1,3,size,size]);const result=await session.run(feeds),tensor=result[outputName]||result[Object.keys(result)[0]],depth=tensor.data instanceof Float32Array?tensor.data:new Float32Array(tensor.data),dims=tensor.dims||[1,size,size],outH=dims.at(-2)||size,outW=dims.at(-1)||size,rgb=new Uint8Array(outW*outH*3);let finite=0,min=Infinity,max=-Infinity;for(const value of depth)if(Number.isFinite(value)){finite++;min=Math.min(min,value);max=Math.max(max,value);}if(finite<depth.length*.98||!Number.isFinite(min+max)||max-min<1e-5)throw new Error('Depth Anything ha prodotto una mappa priva di variazione utile');if(outW===size&&outH===size){for(let p=0,i=0;p<outW*outH;p++,i+=4){rgb[p*3]=rgba[i];rgb[p*3+1]=rgba[i+1];rgb[p*3+2]=rgba[i+2];}}else{const c2=new OffscreenCanvas(outW,outH),x2=c2.getContext('2d',{alpha:false,willReadFrequently:true});x2.drawImage(canvas,0,0,outW,outH);const d2=x2.getImageData(0,0,outW,outH).data;for(let p=0,i=0;p<outW*outH;p++,i+=4){rgb[p*3]=d2[i];rgb[p*3+1]=d2[i+1];rgb[p*3+2]=d2[i+2];}}postMessage({type:'result',requestId:m.requestId,frameId:m.frameId,width:outW,height:outH,depth:depth.buffer,rgb:rgb.buffer,modelUrl:currentConfig.modelUrl,depthStats:{finite,min,max,range:max-min}},[depth.buffer,rgb.buffer]);}
function dispose(){session=null;ortReady=false;postMessage({type:'disposed'});close();}
