/*
 * Adaptive map worker.
 * Input point layout (10 floats): x y z, nx ny nz, r g b, confidence.
 * The worker performs bounded surfel fusion and plane-aware decimation so the
 * XR thread only samples sensors and draws a compact grid snapshot.
 */
const CFG={voxel:.055,flatTile:0.22,objectTile:.075,unknownTile:.13,edgeTile:.065,maxFrameRefs:6,budget:42000};
let cells=new Map(),coarse=new Map(),sessionId=null,totalPoints=0,droppedPoints=0,batches=0,lastPrune=0;
self.onmessage=e=>{const m=e.data||{};try{if(m.type==='init')init(m);else if(m.type==='depthBatch')ingest(m);else if(m.type==='photoEvidence')photoEvidence(m);else if(m.type==='markpoint')markpoint(m);else if(m.type==='snapshot')snapshot(m);else if(m.type==='finalize')finalize(m);else if(m.type==='reset')reset();}catch(error){postMessage({type:'error',message:error.message,stack:error.stack});}};
function init(m){sessionId=m.sessionId;CFG.budget=m.budget||CFG.budget;cells=new Map();coarse=new Map();totalPoints=0;droppedPoints=0;batches=0;postMessage({type:'ready',sessionId});}
function key3(x,y,z,s=CFG.voxel){return `${Math.floor(x/s)},${Math.floor(y/s)},${Math.floor(z/s)}`;}
function ingest(m){
  const a=new Float32Array(m.buffer),origin=m.viewOrigin||[0,0,0],viewKey=m.viewKey||key3(...origin,.22),source=m.source||'xr-depth',frameId=m.frameId||null,time=m.time||Date.now();batches++;
  for(let i=0;i+9<a.length;i+=10){const x=a[i],y=a[i+1],z=a[i+2],nx=a[i+3],ny=a[i+4],nz=a[i+5],r=a[i+6],g=a[i+7],b=a[i+8],conf=a[i+9];if(!Number.isFinite(x+y+z)||conf<=0)continue;const key=key3(x,y,z);let c=cells.get(key);if(!c){c={key,count:0,w:0,pos:[0,0,0],pos2:[0,0,0],normal:[0,0,0],rgb:[0,0,0],views:new Map(),frameRefs:new Map(),xrDepth:0,deepDepth:0,hitTest:0,lastSeen:time,curvature:0,markpointId:null};cells.set(key,c);}const w=Math.max(.08,Math.min(1.5,conf));c.count++;c.w+=w;c.pos[0]+=x*w;c.pos[1]+=y*w;c.pos[2]+=z*w;c.pos2[0]+=x*x*w;c.pos2[1]+=y*y*w;c.pos2[2]+=z*z*w;c.normal[0]+=nx*w;c.normal[1]+=ny*w;c.normal[2]+=nz*w;c.rgb[0]+=r*w;c.rgb[1]+=g*w;c.rgb[2]+=b*w;c.lastSeen=time;if(source==='xr-depth')c.xrDepth++;else if(source==='deep')c.deepDepth++;else c.hitTest++;
    const prev=c.views.get(viewKey);if(!prev)c.views.set(viewKey,{origin,count:1});else prev.count++;
    if(frameId){const f=c.frameRefs.get(frameId)||{id:frameId,count:0,sharpness:m.sharpness||0,exposure:m.exposure||0,uv:m.uv||null};f.count++;c.frameRefs.set(frameId,f);trimMap(c.frameRefs,CFG.maxFrameRefs,(a,b)=>b[1].count-a[1].count);}
    totalPoints++;
  }
  if(cells.size>CFG.budget&&Date.now()-lastPrune>650){prune();lastPrune=Date.now();}
  if(batches%5===0)postMessage({type:'stats',cells:cells.size,totalPoints,droppedPoints,batches});
}
function photoEvidence(m){for(const hit of m.hits||[]){const c=cells.get(hit.key);if(!c)continue;const f=c.frameRefs.get(m.frameId)||{id:m.frameId,count:0,sharpness:m.sharpness||0,exposure:m.exposure||0,uv:hit.uv||null};f.count++;f.sharpness=Math.max(f.sharpness,m.sharpness||0);f.exposure=Math.max(f.exposure,m.exposure||0);c.frameRefs.set(m.frameId,f);trimMap(c.frameRefs,CFG.maxFrameRefs,(a,b)=>b[1].count-a[1].count);}}
function markpoint(m){const key=m.cellKey||key3(...m.position);let c=cells.get(key);if(!c){c={key,count:1,w:1,pos:[...m.position],pos2:m.position.map(v=>v*v),normal:[0,1,0],rgb:[255,0,255],views:new Map(),frameRefs:new Map(),xrDepth:0,deepDepth:0,hitTest:1,lastSeen:Date.now(),curvature:1,markpointId:m.markpointId};cells.set(key,c);}c.markpointId=m.markpointId;c.curvature=1;}
function cellSummary(c,now){
  const iw=1/Math.max(c.w,1e-6),p=c.pos.map(v=>v*iw),n=normalize(c.normal),rgb=c.rgb.map(v=>Math.max(0,Math.min(255,Math.round(v*iw))));const variance=c.pos2.map((v,i)=>Math.max(0,v*iw-p[i]*p[i]));const std=Math.sqrt((variance[0]+variance[1]+variance[2])/3);const resultant=Math.hypot(...c.normal)/Math.max(c.w,1e-6);const origins=[...c.views.values()].map(v=>v.origin);let baseline=0,parallax=0;for(let i=0;i<origins.length;i++)for(let j=i+1;j<origins.length;j++){baseline=Math.max(baseline,dist(origins[i],origins[j]));const a=normalize(sub(origins[i],p)),b=normalize(sub(origins[j],p));parallax=Math.max(parallax,Math.acos(Math.max(-1,Math.min(1,dot(a,b))))*180/Math.PI);}
  const ny=n[1],curvature=Math.max(c.curvature,Math.min(1,std/.055));let surfaceType=Math.abs(ny)>.78?(ny>0?'floor':'ceiling'):Math.abs(ny)<.32?(curvature>.19?'edge':'wall'):(curvature>.15?'object':'unknown');if(c.markpointId)surfaceType='edge';
  const depthSupport=c.xrDepth+.55*c.deepDepth+.30*c.hitTest,support=1-Math.exp(-depthSupport/5.2),viewScore=Math.max(0,Math.min(1,(origins.length-1)/2.4)),baseScore=Math.max(0,Math.min(1,(baseline-.22)/.26)),normalScore=Math.max(0,Math.min(1,(resultant-.45)/.5)),varScore=Math.max(0,Math.min(1,1-std/.095));const geometry=.30*support+.19*viewScore+.16*baseScore+.20*normalScore+.15*varScore;
  const frames=[...c.frameRefs.values()],photoViews=frames.length,sharp=frames.length?frames.reduce((s,f)=>s+f.sharpness,0)/frames.length:0,expo=frames.length?frames.reduce((s,f)=>s+f.exposure,0)/frames.length:0,photo=(1-Math.exp(-photoViews/1.3))*(.58+.24*sharp+.18*expo),parallaxScore=Math.max(0,Math.min(1,(parallax-7)/8));const objectLike=surfaceType==='object'||surfaceType==='edge',requiredPhoto=objectLike ? .72 : .48,requiredParallax=objectLike ? .55 : .25;let status='red';if(geometry>=.72&&photo>=requiredPhoto&&parallaxScore>=requiredParallax)status='green';else if(geometry>=.34||photo>.20)status='yellow';const needDeep=(status!=='green'&&photo<requiredPhoto)||(geometry<.56&&photoViews>0&&now-c.lastSeen>4500);const overall=Math.max(0,Math.min(1,.58*geometry+.27*photo+.15*parallaxScore));const size=(c.markpointId||surfaceType==='edge') ? .065 : (surfaceType==='object' ? .075 : (['wall','floor','ceiling'].includes(surfaceType)&&resultant>.82&&geometry>.62 ? .24 : .13));
  return {id:c.key,key:c.key,center:p,normal:n,rgb,size,surfaceType,status,needDeep,overall,geometry,photoScore:photo,maxParallaxDeg:parallax,maxBaselineM:baseline,viewCount:origins.length,frameRefs:frames,markpointId:c.markpointId,lastSeen:c.lastSeen,count:c.count,positionStdM:std,curvature};
}
function snapshot(m){const now=Date.now(),center=m.cameraPosition||[0,1.5,0],radius=m.radius||9,max=m.maxCells||2400;let real=[];for(const c of cells.values()){const s=cellSummary(c,now),d=dist(s.center,center);if(d<=radius)real.push({...s,_d:d,_p:priority(s,d)});}const predicted=propagateTargets(real,center,Math.min(1100,Math.floor(max*.55)));let arr=real.concat(predicted);arr.sort((a,b)=>b._p-a._p);arr=arr.slice(0,max).map(({_d,_p,...s})=>s);postMessage({type:'snapshot',requestId:m.requestId||null,tiles:arr,stats:{cells:cells.size,predictedTargets:predicted.length,totalPoints,droppedPoints,batches}});}
function propagateTargets(real,camera,maxPredicted){const out=[],seen=new Set(real.map(s=>`${s.surfaceType}:${key3(...s.center,Math.max(.045,s.size*.72))}`));const seeds=real.filter(s=>s.geometry>.30&&s.surfaceType!=='unknown').sort((a,b)=>b.geometry-a.geometry).slice(0,520);for(const seed of seeds){if(out.length>=maxPredicted)break;const n=normalize(seed.normal),structural=seed.surfaceType==='wall'||seed.surfaceType==='floor'||seed.surfaceType==='ceiling',ring=structural?2:1,size=(seed.surfaceType==='object'||seed.surfaceType==='edge') ? .075 : Math.max(.11,Math.min(.22,seed.size||.13));let u,v;if(Math.abs(n[1])>.82){u=[1,0,0];v=[0,0,1];}else{u=normalize([-n[2],0,n[0]]);v=normalize([n[1]*u[2]-n[2]*u[1],n[2]*u[0]-n[0]*u[2],n[0]*u[1]-n[1]*u[0]]);}for(let a=-ring;a<=ring;a++)for(let b=-ring;b<=ring;b++){if(!a&&!b)continue;if(structural&&Math.abs(a)+Math.abs(b)>ring+1)continue;const p=[seed.center[0]+u[0]*a*size+v[0]*b*size,seed.center[1]+u[1]*a*size+v[1]*b*size,seed.center[2]+u[2]*a*size+v[2]*b*size];if(dist(p,camera)>9)continue;const key=`${seed.surfaceType}:${key3(...p,Math.max(.045,size*.72))}`;if(seen.has(key))continue;seen.add(key);const d=dist(p,camera),target={id:`target:${key}`,key:`target:${key}`,center:p,normal:n,rgb:seed.rgb,size,surfaceType:seed.surfaceType,status:'red',needDeep:true,overall:0,geometry:0,photoScore:0,maxParallaxDeg:0,maxBaselineM:0,viewCount:0,frameRefs:[],markpointId:null,lastSeen:seed.lastSeen,count:0,positionStdM:null,curvature:seed.curvature,predicted:true,parentId:seed.id,_d:d};target._p=priority(target,d)-.18;out.push(target);if(out.length>=maxPredicted)break;} }return out;}
function finalize(m){const now=Date.now(),tiles=[];for(const c of cells.values())tiles.push(cellSummary(c,now));postMessage({type:'final',requestId:m.requestId||null,tiles,stats:{cells:cells.size,totalPoints,droppedPoints,batches}},m.transfer||[]);}
function prune(){
  // Stable flat cells are represented at a coarser scale. Markpoints, edges,
  // object-like cells and cells with useful photo links are explicitly kept.
  const candidates=[];for(const [key,c] of cells){const s=cellSummary(c,Date.now());const preserve=!!c.markpointId||s.surfaceType==='object'||s.surfaceType==='edge'||s.frameRefs.length>1||s.status!=='green';if(!preserve)candidates.push([key,c,s]);}
  const target=Math.max(0,cells.size-Math.floor(CFG.budget*.86));if(!target)return;candidates.sort((a,b)=>a[2].overall-b[2].overall||a[1].lastSeen-b[1].lastSeen);const coarseSeen=new Set();let removed=0;
  for(const [key,c,s] of candidates){if(removed>=target)break;const ck=key3(...s.center,CFG.flatTile);if(!coarseSeen.has(ck)){coarseSeen.add(ck);continue;}cells.delete(key);removed++;droppedPoints+=c.count;}
  if(cells.size>CFG.budget){const rest=[...cells.entries()].filter(([,c])=>!c.markpointId).sort((a,b)=>importance(a[1])-importance(b[1]));for(const [key,c] of rest){if(cells.size<=CFG.budget*.94)break;cells.delete(key);droppedPoints+=c.count;}}
}
function priority(s,d){return (s.status==='red'?3:s.status==='yellow'?1.7:.1)+(s.needDeep?1.3:0)+((s.surfaceType==='object'||s.surfaceType==='edge') ? .8 : 0)+1/(.4+d);}
function importance(c){return (c.markpointId?100:0)+Math.min(10,c.count)*.1+c.frameRefs.size*.7+c.views.size*.5+c.curvature*2+(Date.now()-c.lastSeen<8000?1:0);}
function trimMap(map,max,sorter){if(map.size<=max)return;const a=[...map.entries()].sort(sorter);map.clear();for(const [k,v] of a.slice(0,max))map.set(k,v);}
function reset(){cells.clear();coarse.clear();totalPoints=0;droppedPoints=0;batches=0;}
function normalize(a){const n=Math.hypot(...a)||1;return a.map(v=>v/n);}function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]];}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function dist(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);}
