import {CaptureRepository} from '../js/db_v20_2_0.js';
import {decodePointBatch} from '../js/xr_capture_v20_2_0.js';
import {buildAcousticReadyModel,clusterResidualObjects,decimateSurfels,fitStructuralPlanes} from '../js/reconstruction_v20_2_0.js';
import {clamp,dist3,hashCell,invert4,norm3,projectWorldPoint,transformDirection4,transformPoint4,uid} from '../js/math_v20_2_0.js';
import {applySegmentTransformToPacked,estimateSegmentTransforms,transformPoseMatrix} from '../js/registration_v20_2_0.js';

let cancelled=false,activeDeep=null;
self.onmessage=e=>{const m=e.data||{};if(m.type==='cancel'){cancelled=true;activeDeep?.terminate();post('cancelled',0,'Interruzione richiesta');return;}if(m.type==='run'){cancelled=false;run(m).catch(error=>postMessage({type:'error',message:error.message,stack:error.stack}));}};

async function run({sessionId,mode='safe',memoryBudgetMB=320}){
  const repo=new CaptureRepository();await repo.open();stage(2,'Apro la sessione persistita');const session=await repo.getSession(sessionId);if(!session)throw new Error('Sessione non trovata');const [records,blobRecords,events]=await Promise.all([repo.getRecords(sessionId),repo.getBlobs(sessionId),repo.getEvents(sessionId)]);check();
  const byKind=groupRecords(records),depthBlobs=blobRecords.filter(b=>b.kind==='depth-points'),frameBlobs=blobRecords.filter(b=>b.kind==='frame-jpeg'),maxSurfels=Math.max(18000,Math.floor(memoryBudgetMB*150));
  const rawMarkpoints=(byKind.get('markpoint')||[]).map(r=>r.value),registration=estimateSegmentTransforms(session.segments||[],rawMarkpoints),referenceSegment=registration.referenceSegmentId;let skippedUnregisteredBatches=0;stage(6,`Caricati ${depthBlobs.length} batch metrici, ${frameBlobs.length} fotografie; frame di riferimento ${referenceSegment}`);
  const accumulator=new IncrementalAccumulator({maxCells:maxSurfels,voxel:.075});for(let i=0;i<depthBlobs.length;i++){check();const b=depthBlobs[i],origin=b.meta?.origin||[0,0,0],segmentId=b.meta?.segmentId||referenceSegment,reg=registration.transforms[segmentId];if(segmentId!==referenceSegment&&!reg?.registered){skippedUnregisteredBatches++;continue;}try{let packed=decodePointBatch(await b.blob.arrayBuffer(),origin);if(reg?.matrix)packed=applySegmentTransformToPacked(packed,reg.matrix);accumulator.addPacked(packed,{source:'xr-depth',frameId:null,segmentId});}catch(error){post('warning',6+24*(i+1)/Math.max(1,depthBlobs.length),`Batch ${i} ignorato: ${error.message}`);}if(i%4===0)stage(6+24*(i+1)/Math.max(1,depthBlobs.length),`Fusione metrica ${i+1}/${depthBlobs.length}`);}
  for(const record of byKind.get('hit-test-chunk')||[]){const segmentId=record.value.segmentId||referenceSegment,reg=registration.transforms[segmentId];if(segmentId!==referenceSegment&&!reg?.registered)continue;for(const h of record.value.hits||[]){let p=h.position,n=h.normal;if(reg?.matrix){p=transformPoint4(reg.matrix,p);n=transformDirection4(reg.matrix,n);}accumulator.add({position:p,normal:n,rgb:[145,145,145],quality:.32,source:'hit-test',surfaceType:'unknown'});}}
  const snapshots=byKind.get('grid-snapshot')||[],latestSnapshot=[...snapshots].reverse().find(r=>{const sid=r.value.segmentId||referenceSegment;return sid===referenceSegment||registration.transforms[sid]?.registered;})?.value;if(latestSnapshot){const reg=registration.transforms[latestSnapshot.segmentId||referenceSegment];for(const t of latestSnapshot.tiles||[]){const tile={...t};if(reg?.matrix){tile.center=transformPoint4(reg.matrix,t.center);tile.normal=transformDirection4(reg.matrix,t.normal);}accumulator.addTile(tile);}}let points=accumulator.toSurfels();stage(31,`${points.length} surfel metrici dopo la fusione incrementale`);await saveCheckpoint(repo,sessionId,'metric-fusion',{surfelCount:points.length,sourceBatches:depthBlobs.length,registration,skippedUnregisteredBatches});
  if(mode==='deep'&&frameBlobs.length){try{points=await mergeDeepFrames({points,frameBlobs,frameRecords:byKind.get('frame-meta')||[],accumulator,registration,referenceSegment,progressBase:32,progressSpan:30});stage(63,`Deep completato: ${points.length} surfel fusi`);}catch(error){post('warning',63,`Depth Anything non disponibile; continuo con dati metrici: ${error.message}`);}}
  check();stage(68,'Decimazione adattativa plane-aware');points=decimateSurfels(points,{maxPoints:Math.min(maxSurfels,70000)});await saveCheckpoint(repo,sessionId,'decimation',{surfelCount:points.length});check();
  stage(75,'RANSAC vincolato, pavimento, soffitto e pareti');const fit=fitStructuralPlanes(points);await saveCheckpoint(repo,sessionId,'structural-fit',{stats:fit.stats,planes:fit.planes});check();
  stage(86,'Raggruppo i residui in oggetti RGB');const objects=clusterResidualObjects(fit.residual,{maxPoints:Math.min(20000,Math.floor(memoryBudgetMB*55))});check();
  const markpoints=rawMarkpoints.map(m=>transformEntityPoint(m,registration,referenceSegment)),frames=(byKind.get('frame-meta')||[]).map(r=>transformFrameMeta(r.value,registration,referenceSegment)).filter(Boolean),chirps=(byKind.get('chirp')||[]).map(r=>transformChirp(r.value,registration,referenceSegment)).filter(Boolean),audio=blobRecords.filter(b=>b.kind==='audio-pcm').map(b=>({key:b.key,size:b.size,meta:b.meta}));stage(93,'Creo superfici acusticamente indirizzabili');const model=buildAcousticReadyModel({session,points,fit,objects,markpoints,frames,chirps,audio,registration,diagnostics:events});await repo.putModel(sessionId,model);await repo.patchSession(sessionId,{status:'processed',flags:{processingStarted:true},processing:{finishedAt:Date.now(),mode,surfelCount:points.length,planeCount:fit.planes.length,objectCount:objects.length}});await repo.drain(2500);stage(100,'Modello salvato');postMessage({type:'complete',model,summary:{surfels:points.length,planes:fit.planes.length,objects:objects.length,frames:frames.length,chirps:chirps.length}});repo.close();
}

class IncrementalAccumulator {
  constructor({maxCells,voxel}){this.maxCells=maxCells;this.voxel=voxel;this.map=new Map();this.seen=0;}
  addPacked(a,{source='xr-depth',frameId=null}={}){for(let i=0;i+9<a.length;i+=10)this.add({position:[a[i],a[i+1],a[i+2]],normal:[a[i+3],a[i+4],a[i+5]],rgb:[a[i+6],a[i+7],a[i+8]],quality:a[i+9],source,frameId});}
  addTile(t){this.add({position:t.center,normal:t.normal,rgb:t.rgb,quality:t.overall??.5,source:'grid',frameId:t.frameRefs?.[0]?.id||null,surfaceType:t.surfaceType,status:t.status,curvature:t.curvature,frameRefs:t.frameRefs,markpointId:t.markpointId});}
  add(p){if(!p.position?.every(Number.isFinite))return;this.seen++;const important=p.markpointId||p.surfaceType==='object'||p.surfaceType==='edge'||p.status!=='green',size=important?this.voxel*.72:this.voxel,key=hashCell(p.position,size);let c=this.map.get(key);if(!c){c={w:0,p:[0,0,0],n:[0,0,0],rgb:[0,0,0],q:0,count:0,frameRefs:new Set(),surfaceVotes:new Map(),markpointId:null,status:'green',curvature:0,last:this.seen};this.map.set(key,c);}const w=.1+clamp(p.quality??.5,0,1);c.w+=w;c.count++;for(let k=0;k<3;k++){c.p[k]+=p.position[k]*w;c.n[k]+=(p.normal?.[k]||0)*w;c.rgb[k]+=(p.rgb?.[k]??145)*w;}c.q+=(p.quality??.5)*w;c.last=this.seen;c.curvature=Math.max(c.curvature,p.curvature||0);for(const f of p.frameRefs||[])c.frameRefs.add(typeof f==='string'?f:f.id);if(p.frameId)c.frameRefs.add(p.frameId);if(p.surfaceType)c.surfaceVotes.set(p.surfaceType,(c.surfaceVotes.get(p.surfaceType)||0)+w);if(p.status&&p.status!=='green')c.status=p.status;c.markpointId||=p.markpointId||null;if(this.map.size>this.maxCells*1.08)this.prune();}
  prune(){const arr=[...this.map.entries()];arr.sort((a,b)=>cellImportance(a[1])-cellImportance(b[1]));const remove=Math.ceil(this.map.size-this.maxCells*.92);for(let i=0;i<remove;i++)this.map.delete(arr[i][0]);}
  toSurfels(){const out=[];for(const [key,c] of this.map){const iw=1/c.w,surfaceType=[...c.surfaceVotes].sort((a,b)=>b[1]-a[1])[0]?.[0]||'unknown';out.push({id:key,position:c.p.map(v=>v*iw),normal:norm3(c.n),rgb:c.rgb.map(v=>Math.round(v*iw)),quality:c.q*iw,curvature:c.curvature,frameRefs:[...c.frameRefs].slice(0,8),surfaceType,status:c.status,markpointId:c.markpointId});}return out;}
}
function cellImportance(c){return (c.markpointId?100:0)+c.frameRefs.size*2+c.curvature*3+Math.min(4,c.count*.2)+(c.status!=='green'?1.5:0)+(c.last/1e8);}

async function mergeDeepFrames({points,frameBlobs,frameRecords,accumulator,registration,referenceSegment,progressBase,progressSpan}){
  const metaById=new Map(frameRecords.map(r=>[r.value.id,r.value])),worker=new Worker(new URL('./depth_ai_worker_v20_2_0.js',import.meta.url));activeDeep=worker;await workerRequest(worker,{type:'init',runtimeUrls:['../vendor/onnxruntime-web/ort.min.js','https://cdn.jsdelivr.net/npm/onnxruntime-web@1.23.2/dist/ort.min.js'],modelUrls:['../models/depth_anything_v2_vits_q4.onnx','https://huggingface.co/onnx-community/depth-anything-v2-small/resolve/main/onnx/model_q4.onnx'],wasmPaths:'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.23.2/dist/'},'ready',120000);
  for(let i=0;i<frameBlobs.length;i++){check();const b=frameBlobs[i],frameId=b.meta?.id||extractFrameId(b.key),rawMeta=metaById.get(frameId)||b.meta,meta=transformFrameMeta(rawMeta,registration,referenceSegment);if(!meta?.pose?.matrix||!meta?.pose?.projectionMatrix)continue;const result=await workerRequest(worker,{type:'process',requestId:`deep-${i}`,frameId,blob:b.blob,inputSize:518},'result',120000);const depth=new Float32Array(result.depth),rgb=new Uint8Array(result.rgb),cal=calibrateDepth(depth,result.width,result.height,meta,points);if(cal.valid){const deepPoints=reprojectDeep(depth,rgb,result.width,result.height,meta,cal,frameId);accumulator.addPacked(deepPoints,{source:'deep',frameId});points=accumulator.toSurfels();post('progress',progressBase+progressSpan*(i+1)/frameBlobs.length,`Deep ${i+1}/${frameBlobs.length}, residuo ${cal.residualM.toFixed(3)} m`);}else post('warning',progressBase+progressSpan*(i+1)/frameBlobs.length,`Foto ${i+1}: ancore metriche insufficienti`);}
  worker.terminate();activeDeep=null;return accumulator.toSurfels();
}
function calibrateDepth(depth,w,h,meta,points){const worldFromCamera=meta.pose.matrix,view=invert4(worldFromCamera),proj=meta.pose.projectionMatrix;if(!view)return {valid:false};const pairs=[];for(let i=0;i<points.length;i+=Math.max(1,Math.floor(points.length/1800))){const p=points[i],screen=projectWorldPoint(p.position,view,proj,w,h);if(!screen?.inside)continue;const cam=transformPoint4(view,p.position),z=-cam[2];if(z<.15||z>10)continue;const x=clamp(Math.round(screen.x),0,w-1),y=clamp(Math.round(screen.y),0,h-1),d=depth[y*w+x];if(Number.isFinite(d)&&Math.abs(d)>1e-6)pairs.push([d,z]);}if(pairs.length<8)return {valid:false,anchors:pairs.length};const direct=robustAffine(pairs,false),inverse=robustAffine(pairs,true),best=direct.residual<=inverse.residual?direct:inverse;return {valid:best.residual<.42&&Number.isFinite(best.a+best.b),mode:best.mode,a:best.a,b:best.b,residualM:best.residual,anchors:pairs.length};}
function robustAffine(pairs,inverse){let data=pairs.map(([x,y])=>[inverse?1/(Math.abs(x)<1e-6?1e-6:x):x,y]);let fit=linear(data);for(let k=0;k<3;k++){const residuals=data.map(([x,y])=>Math.abs(y-(fit.a*x+fit.b))),med=medianLocal(residuals),mad=medianLocal(residuals.map(r=>Math.abs(r-med)))||.02;data=data.filter(([x,y])=>Math.abs(y-(fit.a*x+fit.b))<=med+2.8*mad);if(data.length<6)break;fit=linear(data);}const residual=medianLocal(data.map(([x,y])=>Math.abs(y-(fit.a*x+fit.b))));return {...fit,residual,mode:inverse?'inverse':'direct'};}
function linear(data){const n=data.length,mx=data.reduce((s,p)=>s+p[0],0)/n,my=data.reduce((s,p)=>s+p[1],0)/n;let xx=0,xy=0;for(const [x,y] of data){xx+=(x-mx)**2;xy+=(x-mx)*(y-my);}const a=xy/(xx||1e-9),b=my-a*mx;return {a,b};}
function reprojectDeep(depth,rgb,w,h,meta,cal,frameId){const invProj=invert4(meta.pose.projectionMatrix),world=meta.pose.matrix;if(!invProj)return new Float32Array(0);const stride=13,out=[];for(let y=stride/2|0;y<h;y+=stride)for(let x=stride/2|0;x<w;x+=stride){const d=depth[y*w+x],z=cal.mode==='inverse'?cal.a/(Math.abs(d)<1e-6?1e-6:d)+cal.b:cal.a*d+cal.b;if(!Number.isFinite(z)||z<.15||z>10)continue;const far=transformPoint4(invProj,[x/(w-1)*2-1,1-y/(h-1)*2,1]),ray=norm3(far);if(ray[2]>=-.01)continue;const cam=[ray[0]*z/(-ray[2]),ray[1]*z/(-ray[2]),ray[2]*z/(-ray[2])],p=transformPoint4(world,cam);const n=[0,0,1],idx=(y*w+x)*3,conf=clamp(1-cal.residualM/.5,.15,.78);out.push(p[0],p[1],p[2],n[0],n[1],n[2],rgb[idx],rgb[idx+1],rgb[idx+2],conf);}return new Float32Array(out);}
function workerRequest(worker,message,expected,timeoutMs){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>cleanup(new Error(`Timeout ${expected}`)),timeoutMs);const onMessage=e=>{const m=e.data||{};if(m.type==='error'&&(m.requestId==null||m.requestId===message.requestId))cleanup(new Error(m.message));else if(m.type===expected&&(message.requestId==null||m.requestId===message.requestId))cleanup(null,m);};const onError=e=>cleanup(e.error||new Error(e.message));function cleanup(error,value){clearTimeout(timer);worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError);error?reject(error):resolve(value);}worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage(message);});}
function transformFrameMeta(meta,registration,referenceSegment){if(!meta)return null;const sid=meta.segmentId||referenceSegment,reg=registration.transforms[sid];if(sid!==referenceSegment&&!reg?.registered)return null;if(!reg?.matrix)return meta;const pose={...meta.pose,matrix:Array.from(transformPoseMatrix(meta.pose.matrix,reg.matrix)),position:transformPoint4(reg.matrix,meta.pose.position)};return {...meta,pose,registeredFromSegment:sid};}
function transformEntityPoint(entity,registration,referenceSegment){const sid=entity.segmentId||referenceSegment,reg=registration.transforms[sid];if(!reg?.matrix)return {...entity,registered: sid===referenceSegment||!!reg?.registered};return {...entity,position:transformPoint4(reg.matrix,entity.position),registered:true,registeredFromSegment:sid};}
function transformChirp(chirp,registration,referenceSegment){const sid=chirp.segmentId||referenceSegment,reg=registration.transforms[sid];if(sid!==referenceSegment&&!reg?.registered)return null;if(!reg?.matrix)return chirp;const pose=chirp.pose?{...chirp.pose,position:transformPoint4(reg.matrix,chirp.pose.position),matrix:chirp.pose.matrix?Array.from(transformPoseMatrix(chirp.pose.matrix,reg.matrix)):chirp.pose.matrix}:chirp.pose;return {...chirp,pose,registeredFromSegment:sid};}
async function saveCheckpoint(repo,sessionId,name,value){await repo.enqueueRecord(sessionId,'processing-checkpoint',{name,time:Date.now(),value},{key:`${sessionId}/processing/${name}`});}
function groupRecords(records){const m=new Map();for(const r of records){if(!m.has(r.kind))m.set(r.kind,[]);m.get(r.kind).push(r);}return m;}
function stage(progress,detail){post('progress',progress,detail);}function post(type,progress,detail){postMessage({type,progress,detail,time:Date.now()});}function check(){if(cancelled)throw new Error('Processing annullato');}function extractFrameId(key){const m=key.match(/(frame-[0-9a-f-]+)/i);return m?.[1]||key;}function medianLocal(a){if(!a.length)return Infinity;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2;}
