import {clamp,median,mad} from './math_v20_2_0.js';

/**
 * Lightweight offline DSP for the append-only chirp stream.
 * Absolute device latency is never interpreted as distance. Each RIR is aligned
 * on its measured direct path and only relative echo delays are exported.
 */
export function nextPow2(n){let p=1;while(p<n)p<<=1;return p;}
export function fft(real,imag,inverse=false){const n=real.length;if(n!==imag.length||(n&(n-1)))throw new Error('FFT length must be a power of two');for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[real[i],real[j]]=[real[j],real[i]];[imag[i],imag[j]]=[imag[j],imag[i]];}}for(let len=2;len<=n;len<<=1){const ang=(inverse?2:-2)*Math.PI/len,wlenR=Math.cos(ang),wlenI=Math.sin(ang);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const uR=real[i+j],uI=imag[i+j],vR=real[i+j+len/2]*wr-imag[i+j+len/2]*wi,vI=real[i+j+len/2]*wi+imag[i+j+len/2]*wr;real[i+j]=uR+vR;imag[i+j]=uI+vI;real[i+j+len/2]=uR-vR;imag[i+j+len/2]=uI-vI;const nr=wr*wlenR-wi*wlenI;wi=wr*wlenI+wi*wlenR;wr=nr;}}}if(inverse)for(let i=0;i<n;i++){real[i]/=n;imag[i]/=n;}return {real,imag};}

export function correlateESS(signal,sweep){const n=nextPow2(signal.length+sweep.length-1),ar=new Float64Array(n),ai=new Float64Array(n),br=new Float64Array(n),bi=new Float64Array(n);ar.set(signal);for(let i=0;i<sweep.length;i++)br[i]=sweep[sweep.length-1-i];fft(ar,ai);fft(br,bi);for(let i=0;i<n;i++){const r=ar[i]*br[i]-ai[i]*bi[i],im=ar[i]*bi[i]+ai[i]*br[i];ar[i]=r;ai[i]=im;}fft(ar,ai,true);return ar.subarray(0,signal.length+sweep.length-1);}

export function deconvolveESS(signal,sweep,{regularization=1e-5,maxRirSamples=null}={}){const n=nextPow2(signal.length+sweep.length-1),yr=new Float64Array(n),yi=new Float64Array(n),xr=new Float64Array(n),xi=new Float64Array(n);yr.set(signal);xr.set(sweep);fft(yr,yi);fft(xr,xi);let maxPower=0;for(let i=0;i<n;i++)maxPower=Math.max(maxPower,xr[i]*xr[i]+xi[i]*xi[i]);const lambda=Math.max(1e-14,maxPower*regularization);for(let i=0;i<n;i++){const den=xr[i]*xr[i]+xi[i]*xi[i]+lambda,r=(yr[i]*xr[i]+yi[i]*xi[i])/den,im=(yi[i]*xr[i]-yr[i]*xi[i])/den;yr[i]=r;yi[i]=im;}fft(yr,yi,true);const outLength=Math.min(maxRirSamples||n,n),out=new Float32Array(outLength);for(let i=0;i<outLength;i++)out[i]=yr[i];return out;}

export function findDirectPath(rir,sampleRate,{searchStartS=0,searchEndS=.18}={}){const a=Math.max(0,Math.floor(searchStartS*sampleRate)),b=Math.min(rir.length,Math.ceil(searchEndS*sampleRate)),abs=[];for(let i=a;i<b;i++)abs.push(Math.abs(rir[i]));const noise=median(abs.slice(0,Math.max(8,Math.floor(abs.length*.08))))||1e-8,threshold=Math.max(noise*7,(Math.max(...abs)||0)*.15);let candidate=-1;for(let i=a+2;i<b-2;i++){const e=Math.abs(rir[i]);if(e>=threshold&&e>=Math.abs(rir[i-1])&&e>=Math.abs(rir[i+1])){candidate=i;break;}}if(candidate<0){let best=0;for(let i=a;i<b;i++)if(Math.abs(rir[i])>Math.abs(rir[best]))best=i;candidate=best;}return {index:candidate,timeS:candidate/sampleRate,amplitude:rir[candidate],noiseFloor:noise,threshold};}

export function alignRelativeRIR(rir,sampleRate,options={}){const direct=findDirectPath(rir,sampleRate,options),pre=Math.round((options.preDirectS??.004)*sampleRate),start=Math.max(0,direct.index-pre),aligned=new Float32Array(rir.length-start);aligned.set(rir.subarray(start));return {aligned,directIndex:pre,directOriginalIndex:direct.index,absoluteDelayS:direct.timeS,relativeTimeOriginS:pre/sampleRate,direct};}

export function extractEarlyPeaks(aligned,sampleRate,{directIndex=0,endS=.12,minGapS=.00065,thresholdDb=-28}={}){const end=Math.min(aligned.length,directIndex+Math.round(endS*sampleRate)),directAmp=Math.max(1e-9,Math.abs(aligned[directIndex])),threshold=directAmp*Math.pow(10,thresholdDb/20),gap=Math.max(1,Math.round(minGapS*sampleRate)),peaks=[];for(let i=directIndex+gap;i<end-1;i++){const e=Math.abs(aligned[i]);if(e<threshold||e<Math.abs(aligned[i-1])||e<Math.abs(aligned[i+1]))continue;if(peaks.length&&i-peaks.at(-1).index<gap){if(e>peaks.at(-1).amplitude)peaks[peaks.length-1]={index:i,delayS:(i-directIndex)/sampleRate,amplitude:e,relativeDb:20*Math.log10(e/directAmp)};}else peaks.push({index:i,delayS:(i-directIndex)/sampleRate,amplitude:e,relativeDb:20*Math.log10(e/directAmp)});}return peaks;}

export function analyzeRIRWindow(window,sweep,sampleRate,metadata={}){const rir=deconvolveESS(window,sweep,{maxRirSamples:Math.round(sampleRate*1.0)}),aligned=alignRelativeRIR(rir,sampleRate),peaks=extractEarlyPeaks(aligned.aligned,sampleRate,{directIndex:aligned.directIndex});const snrDb=20*Math.log10(Math.max(1e-9,Math.abs(aligned.aligned[aligned.directIndex]))/Math.max(1e-9,aligned.direct.noiseFloor));return {chirpId:metadata.chirpId||null,pose:metadata.pose||null,sampleRate,absoluteDelayS:aligned.absoluteDelayS,absoluteDelayTrusted:false,directIndex:aligned.directIndex,snrDb,quality:clamp((snrDb-8)/28,0,1)*(metadata.motionQuality??1),peaks,rir:aligned.aligned};}

export function aggregateRelativeRIRs(analyses,{maxLength=null}={}){const valid=analyses.filter(a=>a?.rir?.length&&a.quality>0),length=Math.min(maxLength||Infinity,...valid.map(a=>a.rir.length));if(!valid.length||!Number.isFinite(length))return null;const out=new Float32Array(length),weightSum=new Float32Array(length);for(const a of valid){const w=Math.max(.04,a.quality);for(let i=0;i<length;i++){const robust=clamp(a.rir[i],-2,2);out[i]+=robust*w;weightSum[i]+=w;}}for(let i=0;i<length;i++)out[i]/=weightSum[i]||1;return {rir:out,count:valid.length,totalWeight:valid.reduce((s,a)=>s+a.quality,0),absoluteDelayTrusted:false};}

export function acousticMeasurementSchema(chirp,analysis){return {id:chirp.id,segmentId:chirp.segmentId,pose:chirp.pose,sweep:chirp.sweep,expectedMicFrame:chirp.expectedMicFrame,absoluteDelayS:analysis?.absoluteDelayS??null,absoluteDelayTrusted:false,relativePeaks:analysis?.peaks||[],snrDb:analysis?.snrDb??null,quality:analysis?.quality??0,surfacePosteriors:[],notes:'Echo delays are relative to the measured direct path; hardware latency is retained only as diagnostics.'};}
