import {BUILD,profileFor} from './config_v20_2_0.js';
import {CaptureRepository} from './db_v20_2_0.js';
import {Diagnostics} from './diagnostics_v20_2_0.js';
import {AppendOnlyAudioCapture,RapidChirpScheduler} from './audio_v20_2_0.js';
import {XRCaptureController} from './xr_capture_v20_2_0.js';
import {computePatchDescriptor,MarkpointManager} from './markpoints_v20_2_0.js';
import {buildDiagnosticsBundle,buildRawBundle,downloadBlob} from './raw_export_v20_2_0.js';
import {uid} from './math_v20_2_0.js';

const $=s=>document.querySelector(s),repo=new CaptureRepository();let diag=new Diagnostics(repo),currentSession=null,currentSegmentId=null,controller=null,audioCapture=null,chirpScheduler=null,markpoints=null,pendingMarkpoint=null,latestCompatibility=null;

async function init(){
  await repo.open();diag.bindGlobalHandlers();latestCompatibility=await XRCaptureController.compatibility();renderCompatibility(latestCompatibility);bindUI();await restoreLatest();registerServiceWorker();setState('Pronto','neutral');
}
function bindUI(){
  $('#btn-start').addEventListener('click',()=>startCapture({resume:false}));$('#btn-resume').addEventListener('click',()=>startCapture({resume:true}));$('#btn-resume-review').addEventListener('click',()=>startCapture({resume:true}));
  $('#btn-safe-exit').addEventListener('click',()=>safeExit('user-button'));$('#btn-force-photo').addEventListener('click',()=>{controller?.requestPhoto('manual-deep');toast('Fotografia richiesta: mantieni l’inquadratura per un istante.');});$('#btn-markpoint').addEventListener('click',()=>{controller?.requestMarkpoint();toast('Centra un oggetto fisso e molto riconoscibile.');});
  $('#btn-confirm-markpoint').addEventListener('click',async e=>{e.preventDefault();if(!pendingMarkpoint)return;try{const point=await markpoints.accept(pendingMarkpoint.candidate,pendingMarkpoint.validation);toast(point.status==='weak'?'Riferimento salvato come debole.':'Riferimento salvato; riprendilo da un’altra posizione.');$('#markpoint-dialog').close();pendingMarkpoint=null;}catch(error){diag.error('markpoint-save-failed',error);toast(`Errore markpoint: ${error.message}`);}});
  for(const id of ['btn-export-raw-home','btn-export-raw-review'])$(id).addEventListener('click',()=>exportRaw());for(const id of ['btn-export-diag-home','btn-export-diag-review'])$(id).addEventListener('click',()=>exportDiagnostics());
  $('#btn-open-review-home').addEventListener('click',()=>openReview());$('#btn-process-safe').addEventListener('click',()=>{if(currentSession)location.href=`processing.html?session=${encodeURIComponent(currentSession.id)}`;});$('#btn-delete-session').addEventListener('click',deleteCurrentSession);
  addEventListener('popstate',()=>{if(controller&&!controller.ended)safeExit('browser-back');});
}
async function restoreLatest(){currentSession=await repo.latestSession();if(!currentSession)return;diag.setSession(currentSession.id);const recoverable=['created','capturing','xr-ending','captured','interrupted','processed','error'].includes(currentSession.status);$('#recovery-card').hidden=!recoverable;$('#btn-resume').hidden=!recoverable;$('#recovery-summary').textContent=`${currentSession.id} · ${new Date(currentSession.updatedAt).toLocaleString()} · stato ${currentSession.status}. I chunk RAW già scritti sono recuperabili.`;if(new URLSearchParams(location.search).get('review')==='1')await openReview();}
async function startCapture({resume}){
  if(controller&&!controller.ended)return;const profileName=$('#capture-profile').value,profile=profileFor(profileName),audioMode=$('#audio-mode').value;setState('Richiesta permessi','warn');$('#btn-start').disabled=true;$('#btn-resume').disabled=true;
  // requestSession is invoked before the first await in this click handler. This
  // avoids losing the transient activation required by immersive-ar.
  let xrPromise;try{xrPromise=XRCaptureController.requestImmersiveSession(document.body);}catch(error){captureStartFailed(error);return;}
  try{
    if(!resume||!currentSession){currentSession=await repo.createSession({profile:profileName,audioMode,compatibility:latestCompatibility});}else currentSession=await repo.getSession(currentSession.id);
    currentSegmentId=uid('segment');const segments=[...(currentSession.segments||[]),{id:currentSegmentId,createdAt:Date.now(),status:'starting',coordinateFrame:'independent-WebXR-local-floor',registration:'pending-if-resumed'}];currentSession=await repo.patchSession(currentSession.id,{profile:profileName,audioMode,currentSegmentId,segments,status:'starting'});diag.setSession(currentSession.id);diag.state='BOOT';await diag.log('capture-start-requested',{resume,segmentId:currentSegmentId,profileName,audioMode});
    audioCapture=null;let audioPromise=Promise.resolve(null);if(audioMode==='rapid'){audioCapture=new AppendOnlyAudioCapture({repository:repo,diagnostics:diag,sessionId:currentSession.id,profile});audioPromise=audioCapture.start().then(()=>audioCapture).catch(async error=>{await diag.error('audio-start-failed',error);audioCapture=null;toast('Audio non disponibile: la scansione 3D continua senza chirp.');return null;});}
    const [xrSession]=await Promise.all([xrPromise,audioPromise]);const existingMarkRecords=await repo.getRecords(currentSession.id,'markpoint');markpoints=new MarkpointManager({repository:repo,diagnostics:diag,mapWorker:null,sessionId:currentSession.id,segmentId:currentSegmentId});markpoints.load(existingMarkRecords.map(r=>r.value));chirpScheduler=audioCapture?new RapidChirpScheduler({audioCapture,repository:repo,diagnostics:diag,sessionId:currentSession.id,segmentId:currentSegmentId,onChirp:()=>{}}):null;
    controller=new XRCaptureController({canvas:$('#xr-canvas'),overlayCanvas:$('#grid-overlay'),repository:repo,diagnostics:diag,session:currentSession,segmentId:currentSegmentId,profile,audioCapture,chirpScheduler,markpointManager:markpoints,callbacks:{onCoverage:updateCoverage,onGuidance:updateGuidance,onTelemetry:updateTelemetry,onPhoto:m=>toast(`Foto ${m.sequence+1} salvata (${Math.round(m.image.size/1024)} kB).`),onMarkpointCandidate:showMarkpointCandidate,onEnded:handleCaptureEnded}});await controller.start({xrSession});markpoints.worker=controller.mapWorker;document.body.classList.add('xr-active');showScreen('capture');setState('WebXR attivo','good');history.pushState({roomscanXR:true},'',location.href);await repo.patchSession(currentSession.id,{segments:currentSession.segments.map(s=>s.id===currentSegmentId?{...s,status:'capturing',startedAt:Date.now()}:s)});
  }catch(error){try{(await xrPromise)?.end?.();}catch{}try{await audioCapture?.stop?.();}catch{}await diag.error('capture-start-failed',error);captureStartFailed(error);}
}
function captureStartFailed(error){setState('Avvio fallito','bad');$('#btn-start').disabled=false;$('#btn-resume').disabled=false;toast(error.message||String(error));showScreen('home');}
async function safeExit(reason){if(!controller||controller.ended)return;setState('Salvataggio e uscita','warn');$('#btn-safe-exit').disabled=true;toast('Interrompo nuovi dati e chiudo XR senza avviare processing.');try{await controller.requestSafeExit(reason);}catch(error){await diag.error('safe-exit-failed',error);toast(`Uscita incompleta: ${error.message}. I chunk già scritti restano recuperabili.`);}}
async function handleCaptureEnded(info){document.body.classList.remove('xr-active');$('#btn-safe-exit').disabled=false;currentSession=await repo.getSession(info.sessionId);setState(info.reason==='requested'?'Acquisizione salvata':'Acquisizione recuperabile',info.reason==='requested'?'good':'warn');showScreen('review');await renderReview();controller=null;audioCapture=null;chirpScheduler=null;}
function updateCoverage(c){$('#count-red').textContent=c.red;$('#count-yellow').textContent=c.yellow;$('#count-green').textContent=c.green;$('#count-deep').textContent=c.deep;}
function updateGuidance(g){$('#guidance-arrow').style.transform=`rotate(${g.angleRad}rad)`;$('#guidance-title').textContent=g.title;$('#guidance-detail').textContent=g.detail;}
function updateTelemetry(t){$('#telemetry-points').textContent=`${t.points.toLocaleString()} punti`;
  $('#telemetry-frames').textContent=`${t.frames} foto`;$('#telemetry-chirps').textContent=`${t.chirps} chirp`;$('#telemetry-writes').textContent=`coda ${t.pendingWrites}`;}
function showMarkpointCandidate(candidate){
  const descriptor=computePatchDescriptor(candidate.rgba,candidate.width,candidate.height,candidate.cx,candidate.cy),compact={frameId:candidate.frameId,position:candidate.position,normal:candidate.normal,depthSamples:candidate.depthSamples,descriptor,pose:candidate.pose,referenceCameraPosition:candidate.pose?.position},validation=markpoints.evaluate(compact);pendingMarkpoint={candidate:compact,validation};const match=validation.bestMatch?` Corrisponde probabilmente al riferimento ${validation.bestMatch.point.logicalId} (${validation.bestMatch.distance.toFixed(2)}).`:'';$('#markpoint-feedback').textContent=(validation.valid?'Riferimento valido.':'Riferimento debole: '+(validation.reasons.join(', ')||'riprova da più vicino')+'.')+match;$('#markpoint-quality').innerHTML=Object.entries(validation.scores).map(([k,v])=>`<div class="quality-row"><span>${escapeHtml(k)}</span><meter min="0" max="1" value="${v}"></meter><b>${Math.round(v*100)}%</b></div>`).join('');$('#btn-confirm-markpoint').textContent=validation.valid?'Usa questo punto':'Salva comunque come debole';$('#markpoint-dialog').showModal();
}
async function openReview(){if(!currentSession)return;showScreen('review');await renderReview();}
async function renderReview(){currentSession=await repo.getSession(currentSession.id);const [records,blobs,events]=await Promise.all([repo.getRecords(currentSession.id),repo.getBlobs(currentSession.id),repo.getEvents(currentSession.id)]),bytes=blobs.reduce((s,b)=>s+b.size,0),kinds=countKinds(blobs);$('#review-summary').textContent=`Sessione ${currentSession.id}. ${records.length} record e ${blobs.length} artefatti binari sono indipendenti dal processing.`;const metrics=[['Stato',currentSession.status],['Pose',currentSession.counts?.poses||records.filter(r=>r.kind==='pose-chunk').reduce((s,r)=>s+(r.value.poses?.length||0),0)],['Foto',kinds['frame-jpeg']?.count||0],['Depth batch',kinds['depth-points']?.count||0],['Audio',formatBytes(kinds['audio-pcm']?.bytes||0)],['RAW totali',formatBytes(bytes)],['Chirp',records.filter(r=>r.kind==='chirp').length],['Markpoint',records.filter(r=>r.kind==='markpoint').length]];$('#session-metrics').innerHTML=metrics.map(([l,v])=>`<div class="metric"><strong>${escapeHtml(String(v))}</strong><span>${escapeHtml(l)}</span></div>`).join('');$('#diagnostic-tail').textContent=events.slice(-45).map(e=>`${new Date(e.time).toISOString()} ${String(e.level||'info').toUpperCase()} ${e.type} ${JSON.stringify(e.data||{})}`).join('\n');$('#recovery-card').hidden=false;$('#btn-resume').hidden=false;}
async function exportRaw(){if(!currentSession)return;setState('Creo pacchetto RAW','warn');try{const out=await buildRawBundle(repo,currentSession.id,{onProgress:p=>setState(`RAW ${p.done}/${p.total}`,'warn')});downloadBlob(out.blob,out.filename);await repo.patchSession(currentSession.id,{flags:{rawExported:true},lastRawExportAt:Date.now()});setState(`RAW pronto · ${formatBytes(out.blob.size)}`,'good');}catch(error){await diag.error('raw-export-failed',error);setState('Export RAW fallito','bad');toast(error.message);}}
async function exportDiagnostics(){if(!currentSession)return;try{const out=await buildDiagnosticsBundle(repo,currentSession.id);downloadBlob(out.blob,out.filename);toast('Diagnostica esportata.');}catch(error){diag.error('diagnostics-export-failed',error);toast(error.message);}}
async function deleteCurrentSession(){if(!currentSession||!confirm('Eliminare definitivamente questa sessione e tutti i RAW locali?'))return;await repo.deleteSession(currentSession.id);currentSession=null;$('#recovery-card').hidden=true;$('#btn-resume').hidden=true;showScreen('home');toast('Sessione eliminata.');}
function renderCompatibility(c){$('#compatibility-report').textContent=Object.entries(c).map(([k,v])=>`${k.padEnd(18)} ${typeof v==='object'?JSON.stringify(v):v}`).join('\n');$('#btn-start').disabled=!(c.secureContext&&c.indexedDB&&c.webXR&&c.immersiveAR);}
function showScreen(name){for(const s of document.querySelectorAll('.screen'))s.classList.toggle('active',s.id===`screen-${name}`);}
function setState(text,tone){const p=$('#state-pill');p.textContent=text;p.className=`pill ${tone}`;}
function toast(text){const t=$('#capture-toast');t.textContent=text;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,3800);}
function countKinds(items){const o={};for(const x of items){o[x.kind]??={count:0,bytes:0};o[x.kind].count++;o[x.kind].bytes+=x.size||0;}return o;}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} kB`;return`${(n/1048576).toFixed(1)} MB`;}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw_v20_2_0.js',{updateViaCache:'none'}).catch(e=>diag.error('service-worker-register-failed',e));}
init().catch(error=>{console.error(error);setState('Errore iniziale','bad');$('#compatibility-report').textContent=error.stack||error.message;});
