import {BUILD,profileFor} from './config_v20_2_0.js';
import {CaptureRepository} from './db_v20_2_0.js';
import {Diagnostics} from './diagnostics_v20_2_0.js';
import {AppendOnlyAudioCapture,RapidChirpScheduler} from './audio_v20_2_0.js';
import {XRCaptureController} from './xr_capture_v20_2_0.js';
import {computePatchDescriptor,MarkpointManager} from './markpoints_v20_2_0.js';
import {buildDiagnosticsBundle,buildRawBundle,downloadBlob} from './raw_export_v20_2_0.js';
import {uid} from './math_v20_2_0.js';

const $=s=>document.querySelector(s),repo=new CaptureRepository();let diag=new Diagnostics(repo),currentSession=null,currentSegmentId=null,controller=null,audioCapture=null,chirpScheduler=null,markpoints=null,pendingMarkpoint=null,pendingDownload=null,latestCompatibility=null;

async function init(){
  await repo.open();diag.bindGlobalHandlers();if(recoverMismatchedShell())return;latestCompatibility=await XRCaptureController.compatibility();renderCompatibility(latestCompatibility);bindUI();await restoreLatest();registerServiceWorker();setState('Pronto','neutral');
}
function bindUI(){
  on('btn-start',()=>startCapture({resume:false}));on('btn-resume',()=>startCapture({resume:true}));on('btn-resume-review',()=>startCapture({resume:true}));
  on('btn-safe-exit',()=>safeExit('user-button'));on('btn-force-photo',()=>{controller?.requestPhoto('manual-deep');toast('Fotografia richiesta: mantieni l’inquadratura per un istante.');});on('btn-markpoint',pinAtReticle);
  on('btn-confirm-markpoint',async e=>{e.preventDefault();if(!pendingMarkpoint)return;try{const {mode,id}=pendingMarkpoint.action||{mode:'new'};const point=mode==='new'?await markpoints.accept(pendingMarkpoint.candidate,pendingMarkpoint.validation):await markpoints.pin(id,pendingMarkpoint.candidate,{move:mode==='move'});renderMarkpointActions();toast(mode==='move'?'Posizione del riferimento aggiornata.':mode==='pin'?'Nuova vista fissata al riferimento.':point.status==='weak'?'Riferimento salvato come debole.':'Riferimento salvato; riprendilo da un’altra posizione.');$('#markpoint-dialog')?.close();pendingMarkpoint=null;}catch(error){await diag.error('markpoint-save-failed',error);toast(`Errore riferimento: ${error.message}`);}});
  for(const id of ['btn-export-raw-home','btn-export-raw-review'])on(id,()=>exportRaw());for(const id of ['btn-export-diag-home','btn-export-diag-review'])on(id,()=>exportDiagnostics());
  on('btn-open-review-home',()=>openReview());on('btn-process-safe',()=>openProcessing());on('btn-delete-session',deleteCurrentSession);on('btn-download-ready',downloadPreparedFile);
  addEventListener('popstate',()=>{if(controller&&!controller.ended)safeExit('browser-back');});
}
async function restoreLatest(){const query=new URLSearchParams(location.search),requestedId=query.get('session');currentSession=requestedId?await repo.getSession(requestedId):await repo.latestSession();if(!currentSession)return;diag.setSession(currentSession.id);const recoverable=['created','starting','capturing','xr-ending','captured','interrupted','processed','error'].includes(currentSession.status);$('#recovery-card').hidden=!recoverable;$('#btn-resume').hidden=!recoverable;$('#recovery-summary').textContent=`${currentSession.id} · ${new Date(currentSession.updatedAt).toLocaleString()} · stato ${currentSession.status}. I chunk RAW già scritti sono recuperabili.`;if(query.get('review')==='1')await openReview();}
async function startCapture({resume}){
  if(controller&&!controller.ended)return;const profileName=$('#capture-profile').value,profile=profileFor(profileName),audioMode=$('#audio-mode').value;setState('Richiesta permessi','warn');$('#btn-start').disabled=true;$('#btn-resume').disabled=true;
  // requestSession is invoked before the first await in this click handler. This
  // avoids losing the transient activation required by immersive-ar.
  let xrPromise;try{xrPromise=XRCaptureController.requestImmersiveSession(document.body);}catch(error){captureStartFailed(error);return;}
  try{
    if(!resume||!currentSession){currentSession=await repo.createSession({profile:profileName,audioMode,compatibility:latestCompatibility});}else currentSession=await repo.getSession(currentSession.id);
    currentSegmentId=uid('segment');const segments=[...(currentSession.segments||[]),{id:currentSegmentId,createdAt:Date.now(),status:'starting',coordinateFrame:'independent-WebXR-local-floor',registration:'pending-if-resumed'}];currentSession=await repo.patchSession(currentSession.id,{profile:profileName,audioMode,currentSegmentId,segments,status:'starting'});diag.setSession(currentSession.id);diag.state='BOOT';await diag.log('capture-start-requested',{resume,segmentId:currentSegmentId,profileName,audioMode});
    audioCapture=null;let audioPromise=Promise.resolve(null);if(audioMode==='rapid'){const capture=new AppendOnlyAudioCapture({repository:repo,diagnostics:diag,sessionId:currentSession.id,profile});audioCapture=capture;audioPromise=capture.start().then(()=>capture).catch(async error=>{await diag.error('audio-start-failed',error);if(audioCapture===capture)audioCapture=null;toast('Audio non disponibile: la scansione 3D continua senza chirp.');return null;});}
    const xrSession=await xrPromise;
    // Microphone permission is optional and may stay pending behind Android's
    // AR permission sheet. It must never make the primary capture button look
    // dead or delay the camera/tracking view indefinitely.
    const audioReady=await Promise.race([audioPromise,new Promise(resolve=>setTimeout(()=>resolve('timeout'),2400))]);
    if(audioReady==='timeout'){audioCapture=null;audioPromise.then(c=>c?.stop?.()).catch(error=>diag.error('late-audio-stop-failed',error));await diag.log('audio-start-timeout',{timeoutMs:2400},'warn');toast('Audio non pronto: avvio la scansione 3D senza chirp.');}else audioCapture=audioReady;
    const existingMarkRecords=await repo.getRecords(currentSession.id,'markpoint');markpoints=new MarkpointManager({repository:repo,diagnostics:diag,mapWorker:null,sessionId:currentSession.id,segmentId:currentSegmentId});markpoints.load(existingMarkRecords.map(r=>r.value));renderMarkpointActions();chirpScheduler=audioCapture?new RapidChirpScheduler({audioCapture,repository:repo,diagnostics:diag,sessionId:currentSession.id,segmentId:currentSegmentId,onChirp:()=>{}}):null;
    controller=new XRCaptureController({canvas:freshXRCanvas(),overlayCanvas:$('#grid-overlay'),repository:repo,diagnostics:diag,session:currentSession,segmentId:currentSegmentId,profile,audioCapture,chirpScheduler,markpointManager:markpoints,callbacks:{onCoverage:updateCoverage,onGuidance:updateGuidance,onTelemetry:updateTelemetry,onPhoto:m=>toast(`Foto ${m.sequence+1} salvata (${Math.round(m.image.size/1024)} kB).`),onMarkpointCandidate:showMarkpointCandidate,onEnded:handleCaptureEnded}});
    // The immersive compositor is live as soon as requestSession resolves.
    // Reveal the transparent XR canvas and compact HUD before WebGL/reference
    // space initialization, otherwise Android shows the ordinary dark page
    // during AR startup and can keep that stale layer above the passthrough.
    document.documentElement.classList.add('xr-active');document.body.classList.add('xr-active');showScreen('capture');setState('Avvio vista WebXR','warn');
    await controller.start({xrSession});markpoints.worker=controller.mapWorker;setState('WebXR attivo','good');history.pushState({roomscanXR:true},'',location.href);await repo.patchSession(currentSession.id,{segments:currentSession.segments.map(s=>s.id===currentSegmentId?{...s,status:'capturing',startedAt:Date.now()}:s)});
  }catch(error){try{(await xrPromise)?.end?.();}catch{}try{await audioCapture?.stop?.();}catch{}await diag.error('capture-start-failed',error);captureStartFailed(error);}
}
function captureStartFailed(error){document.documentElement.classList.remove('xr-active');document.body.classList.remove('xr-active');setState('Avvio fallito','bad');$('#btn-start').disabled=false;$('#btn-resume').disabled=false;toast(error.message||String(error));showScreen('home');}
async function safeExit(reason){if(!controller||controller.ended)return;setState('Salvataggio e uscita','warn');$('#btn-safe-exit').disabled=true;toast('Interrompo nuovi dati e chiudo XR senza avviare processing.');try{await controller.requestSafeExit(reason);}catch(error){await diag.error('safe-exit-failed',error);$('#btn-safe-exit').disabled=false;setState('Uscita da XR incompleta','bad');toast(`Uscita incompleta: ${error.message}. I chunk già scritti restano recuperabili.`);}}
async function handleCaptureEnded(info){document.documentElement.classList.remove('xr-active');document.body.classList.remove('xr-active');$('#btn-safe-exit').disabled=false;setState(info.reason==='requested'?'Acquisizione salvata':'Acquisizione recuperabile',info.reason==='requested'?'good':'warn');showScreen('review');try{currentSession=await repo.getSession(info.sessionId);if(!currentSession)throw new Error('Sessione non trovata dopo la chiusura XR');await renderReview();}catch(error){await diag.error('capture-review-failed',error,{sessionId:info.sessionId});$('#review-summary').textContent='XR è chiuso e i dati già salvati restano recuperabili. Riapri la pagina per caricare il riepilogo o esporta la diagnostica.';$('#diagnostic-tail').textContent=`Errore nel riepilogo: ${error.message}`;toast('XR chiuso; il riepilogo non è stato caricato completamente.');}finally{controller=null;audioCapture=null;chirpScheduler=null;}}
function updateCoverage(c){$('#count-red').textContent=c.red;$('#count-yellow').textContent=c.yellow;$('#count-green').textContent=c.green;$('#count-deep').textContent=c.deep;}
function updateGuidance(g){$('#guidance-arrow').style.transform=`rotate(${g.angleRad}rad)`;$('#guidance-title').textContent=g.title;$('#guidance-detail').textContent=g.detail;}
function updateTelemetry(t){$('#telemetry-points').textContent=`${t.points.toLocaleString()} punti`;
  $('#telemetry-frames').textContent=`${t.frames} foto`;$('#telemetry-chirps').textContent=`${t.chirps} chirp`;$('#telemetry-writes').textContent=`coda ${t.pendingWrites}`;}
async function pinAtReticle(){try{const action=parseMarkpointAction($('#markpoint-action')?.value||'new');if(action.mode==='new'&&markpoints?.points.length>=10){toast('Hai già raggiunto 10 riferimenti. Selezionane uno per aggiungere una vista o spostarlo.');return;}const candidate=controller?.getReticleCandidate();if(!candidate){toast('Attendi il reticolo su una superficie, poi riprova.');return;}const point=action.mode==='new'?await markpoints.place(candidate):await markpoints.pin(action.id,candidate,{move:action.mode==='move'});controller?.setMarkpoints(markpoints.points);renderMarkpointActions();controller?.requestMarkpoint({pointId:point.id});toast(action.mode==='move'?`Riferimento spostato e lasciato visibile.`:action.mode==='pin'?`Nuova vista fissata al riferimento.`:`Riferimento R${markpoints.points.indexOf(point)+1} fissato: resta visibile nella scena.`);}catch(error){await diag.error('markpoint-spatial-place-failed',error);toast(`Impossibile fissare il riferimento: ${error.message}`);}}
async function showMarkpointCandidate(candidate){
  const descriptor=computePatchDescriptor(candidate.rgba,candidate.width,candidate.height,candidate.cx,candidate.cy),compact={frameId:candidate.frameId,position:candidate.position,normal:candidate.normal,depthSamples:candidate.depthSamples,descriptor,pose:candidate.pose,referenceCameraPosition:candidate.referenceCameraPosition||candidate.pose?.position};if(candidate.targetMarkpointId){const validation=markpoints.evaluate(compact,{excludeId:candidate.targetMarkpointId}),point=await markpoints.refine(candidate.targetMarkpointId,compact,validation);controller?.setMarkpoints(markpoints.points);renderMarkpointActions();toast(validation.valid?`Foto utile: riferimento R${markpoints.points.indexOf(point)+1} raffinato.`:'Riferimento fissato; la foto non è ancora sufficiente per confermarlo.');return;}const validation=markpoints.evaluate(compact),action=parseMarkpointAction($('#markpoint-action')?.value||'new');pendingMarkpoint={candidate:compact,validation,action};const match=validation.bestMatch?` Corrisponde probabilmente al riferimento ${validation.bestMatch.point.logicalId} (${validation.bestMatch.distance.toFixed(2)}).`:'';const intent=action.mode==='move'?'Aggiornerai la posizione del riferimento selezionato.':action.mode==='pin'?'Aggiungerai una vista al riferimento selezionato.':validation.valid?'Riferimento valido.':'Riferimento debole: ';$('#markpoint-feedback').textContent=intent+(action.mode==='new'&&!validation.valid?(validation.reasons.join(', ')||'riprova da più vicino')+'.':'')+match;$('#markpoint-quality').innerHTML=Object.entries(validation.scores).map(([k,v])=>`<div class="quality-row"><span>${escapeHtml(k)}</span><meter min="0" max="1" value="${v}"></meter><b>${Math.round(v*100)}%</b></div>`).join('');$('#btn-confirm-markpoint').textContent=action.mode==='move'?'Sposta qui':action.mode==='pin'?'Pinna questa vista':validation.valid?'Usa questo punto':'Salva comunque come debole';$('#markpoint-dialog')?.showModal();
}
async function openReview(){if(!currentSession){toast('Nessuna sessione locale da mostrare.');return;}showScreen('review');try{await renderReview();}catch(error){await diag.error('open-review-failed',error,{sessionId:currentSession.id});setState('Riepilogo non disponibile','bad');toast(`Impossibile aprire il riepilogo: ${error.message}`);showScreen('home');}}
async function openProcessing(){try{if(!currentSession)currentSession=await repo.latestSession();if(!currentSession){setState('Nessuna sessione','bad');toast('Nessuna sessione locale da elaborare.');return;}setState('Apro processing','warn');location.assign(`processing.html?session=${encodeURIComponent(currentSession.id)}`);}catch(error){await diag.error('processing-open-failed',error);setState('Processing non disponibile','bad');toast(`Impossibile aprire processing: ${error.message}`);}}
async function renderReview(){currentSession=await repo.getSession(currentSession.id);const [records,blobs,events]=await Promise.all([repo.getRecords(currentSession.id),repo.getBlobs(currentSession.id),repo.getEvents(currentSession.id)]),bytes=blobs.reduce((s,b)=>s+b.size,0),kinds=countKinds(blobs);$('#review-summary').textContent=`Sessione ${currentSession.id}. ${records.length} record e ${blobs.length} artefatti binari sono indipendenti dal processing.`;const metrics=[['Stato',currentSession.status],['Pose',currentSession.counts?.poses||records.filter(r=>r.kind==='pose-chunk').reduce((s,r)=>s+(r.value.poses?.length||0),0)],['Foto',kinds['frame-jpeg']?.count||0],['Depth batch',kinds['depth-points']?.count||0],['Audio',formatBytes(kinds['audio-pcm']?.bytes||0)],['RAW totali',formatBytes(bytes)],['Chirp',records.filter(r=>r.kind==='chirp').length],['Markpoint',records.filter(r=>r.kind==='markpoint').length]];$('#session-metrics').innerHTML=metrics.map(([l,v])=>`<div class="metric"><strong>${escapeHtml(String(v))}</strong><span>${escapeHtml(l)}</span></div>`).join('');$('#diagnostic-tail').textContent=events.slice(-45).map(e=>`${new Date(e.time).toISOString()} ${String(e.level||'info').toUpperCase()} ${e.type} ${JSON.stringify(e.data||{})}`).join('\n');$('#recovery-card').hidden=false;$('#btn-resume').hidden=false;}
async function exportRaw(){if(!currentSession)return;setState('Creo pacchetto RAW','warn');try{const out=await buildRawBundle(repo,currentSession.id,{onProgress:p=>setState(`RAW ${p.done}/${p.total}`,'warn')});await repo.patchSession(currentSession.id,{flags:{rawExported:true},lastRawExportAt:Date.now()});prepareDownload(out,'Pacchetto RAW pronto');setState(`RAW pronto · ${formatBytes(out.blob.size)}`,'good');}catch(error){await diag.error('raw-export-failed',error);setState('Export RAW fallito','bad');toast(error.message);}}
async function exportDiagnostics(){if(!currentSession)return;setState('Creo diagnostica','warn');try{const out=await buildDiagnosticsBundle(repo,currentSession.id);prepareDownload(out,'Diagnostica pronta');setState('Diagnostica pronta','good');}catch(error){await diag.error('diagnostics-export-failed',error);setState('Export diagnostica fallito','bad');toast(error.message);}}
async function deleteCurrentSession(){if(!currentSession||!confirm('Eliminare definitivamente questa sessione e tutti i RAW locali?'))return;await repo.deleteSession(currentSession.id);currentSession=null;$('#recovery-card').hidden=true;$('#btn-resume').hidden=true;showScreen('home');toast('Sessione eliminata.');}
function renderCompatibility(c){const report=$('#compatibility-report'),start=$('#btn-start');if(report)report.textContent=Object.entries(c).map(([k,v])=>`${k.padEnd(18)} ${typeof v==='object'?JSON.stringify(v):v}`).join('\n');if(start)start.disabled=!(c.secureContext&&c.indexedDB&&c.webXR&&c.immersiveAR);}
function showScreen(name){for(const s of document.querySelectorAll('.screen'))s.classList.toggle('active',s.id===`screen-${name}`);}
function setState(text,tone){const p=$('#state-pill');if(!p)return;p.textContent=text;p.className=`pill ${tone}`;}
function toast(text){const t=$('#capture-toast');if(!t){setState(text,'warn');return;}t.textContent=text;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,3800);}
function renderMarkpointActions(){const select=$('#markpoint-action'),count=$('#markpoint-count');if(!select)return;const previous=select.value,allPoints=markpoints?.points||[],points=allPoints.filter(point=>point.segmentId===markpoints?.segmentId);select.replaceChildren();if(allPoints.length<10)select.add(new Option('Nuovo riferimento al reticolo','new'));points.forEach((point,index)=>{const label=`R${index+1} · ${point.confirmations?.length||0} viste`;select.add(new Option(`Pinna vista · ${label}`,`pin:${point.id}`));select.add(new Option(`Sposta qui · ${label}`,`move:${point.id}`));});select.value=[...select.options].some(o=>o.value===previous)?previous:'new';if(count)count.textContent=`${allPoints.length}/10 riferimenti`;}
function parseMarkpointAction(value){const [mode='new',id=null]=String(value||'new').split(':');return {mode,id};}
function on(id,handler){const element=$(`#${id}`);if(!element){diag.log('ui-control-missing',{id,build:BUILD.id},'warn');return false;}element.addEventListener('click',handler);return true;}
function recoverMismatchedShell(){const missing=['btn-start','btn-safe-exit','btn-download-ready','screen-review'].filter(id=>!$(`#${id}`));if(!missing.length)return false;const url=new URL(location.href);if(url.searchParams.get('roomscan-build')!==BUILD.id){url.searchParams.set('roomscan-build',BUILD.id);location.replace(url);return true;}setState('Aggiorna la pagina','warn');return false;}
function freshXRCanvas(){const old=$('#xr-canvas'),canvas=old.cloneNode(false);old.replaceWith(canvas);return canvas;}
function prepareDownload(out,title){pendingDownload=out;const heading=$('#download-title'),detail=$('#download-detail'),dialog=$('#download-dialog');if(heading)heading.textContent=title;if(detail)detail.textContent=`${out.filename} · ${formatBytes(out.blob.size)}. Il download viene avviato ora; se il browser lo blocca, tocca “Scarica di nuovo”.`;downloadPreparedFile({close:false});if(dialog?.showModal&&!dialog.open)dialog.showModal();}
function downloadPreparedFile({close=true}={}){if(!pendingDownload)return;downloadBlob(pendingDownload.blob,pendingDownload.filename);setState('Download avviato','good');if(close)$('#download-dialog')?.close();}
function countKinds(items){const o={};for(const x of items){o[x.kind]??={count:0,bytes:0};o[x.kind].count++;o[x.kind].bytes+=x.size||0;}return o;}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} kB`;return`${(n/1048576).toFixed(1)} MB`;}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function registerServiceWorker(){if(!('serviceWorker'in navigator))return;try{const registration=await navigator.serviceWorker.register(`./sw_v20_2_0.js?build=${encodeURIComponent(BUILD.id)}`,{updateViaCache:'none'});await registration.update();}catch(error){diag.error('service-worker-register-failed',error);}}
init().catch(error=>{console.error(error);setState('Errore iniziale','bad');const report=$('#compatibility-report');if(report)report.textContent=error.stack||error.message;});
