/** Lightweight, dependency-free orbit preview for processed metric models. */
export class InteractiveModelPreview {
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.model=null;this.yaw=-.72;this.pitch=.42;this.zoom=1.65;this.pan=[0,0];this.drag=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);this.drag={x:e.clientX,y:e.clientY,pan:e.shiftKey};});canvas.addEventListener('pointermove',e=>this._move(e));canvas.addEventListener('pointerup',()=>this.drag=null);canvas.addEventListener('pointercancel',()=>this.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=clamp(this.zoom*Math.exp(-e.deltaY*.0012),.45,3.2);this.draw();},{passive:false});canvas.addEventListener('keydown',e=>{if(e.key==='r'||e.key==='R'){this.yaw=-.72;this.pitch=.42;this.zoom=1.65;this.pan=[0,0];this.draw();}});if(globalThis.ResizeObserver){this.resizeObserver=new ResizeObserver(()=>this.draw());this.resizeObserver.observe(canvas);}else globalThis.addEventListener?.('resize',()=>this.draw());}
  setModel(model){this.model=model;this.draw();}
  _move(e){if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.x=e.clientX;this.drag.y=e.clientY;if(this.drag.pan){this.pan[0]+=dx;this.pan[1]+=dy;}else{this.yaw+=dx*.009;this.pitch=clamp(this.pitch+dy*.008,-1.35,1.35);}this.draw();}
  draw(){const canvas=this.canvas,ctx=this.ctx,dpr=Math.min(2,globalThis.devicePixelRatio||1),w=canvas.clientWidth||800,h=canvas.clientHeight||420;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#050d10';ctx.fillRect(0,0,w,h);const points=this.model?.geometry?.surfels||[];if(!points.length){ctx.fillStyle='#9bb0b5';ctx.font='14px system-ui';ctx.fillText('Nessun punto disponibile',18,30);return;}const bounds=extent(points),rendered=[];for(let i=0,step=Math.max(1,Math.ceil(points.length/16000));i<points.length;i+=step){const p=points[i],q=this._project(p.position,bounds,w,h);if(q)rendered.push({q,p});}rendered.sort((a,b)=>a.q.depth-b.q.depth);for(const {q,p} of rendered){const rgb=p.rgb||[145,155,160],alpha=p.surfaceType==='wall'||p.surfaceType==='floor'||p.surfaceType==='ceiling'?.68:.84;ctx.fillStyle=`rgba(${rgb[0]},${rgb[1]},${rgb[2]},${alpha})`;const size=Math.max(.9,2.35-q.depth*.45);ctx.fillRect(q.x-size/2,q.y-size/2,size,size);}this._surfaces(bounds,w,h);this._marks(bounds,w,h);ctx.fillStyle='rgba(5,13,16,.78)';ctx.fillRect(10,h-34,250,24);ctx.fillStyle='#d6e7e8';ctx.font='12px system-ui';ctx.fillText('Trascina: ruota · Shift+trascina: sposta · rotella: zoom · R: reset',16,h-18);}
  _surfaces(bounds,w,h){const ctx=this.ctx;for(const surface of this.model?.geometry?.structuralSurfaces||[]){const poly=surface.geometry?.bounds?.polygon||[],projected=poly.map(p=>this._project(p,bounds,w,h)).filter(Boolean);if(projected.length<3)continue;const color=surface.kind==='floor'?'#52e0b6':surface.kind==='ceiling'?'#64b5f6':'#ffd166';ctx.beginPath();ctx.moveTo(projected[0].x,projected[0].y);for(const p of projected.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=2.2;ctx.stroke();}}
  _marks(bounds,w,h){const ctx=this.ctx;for(const mark of this.model?.markpoints||[]){const p=this._project(mark.position,bounds,w,h);if(!p)continue;ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fillStyle='#ff72ce';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1.3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 10px system-ui';ctx.fillText('R',p.x+8,p.y-7);}}
  _project(position,bounds,w,h){if(!position?.every(Number.isFinite))return null;let x=(position[0]-bounds.center[0])/bounds.scale,y=(position[1]-bounds.center[1])/bounds.scale,z=(position[2]-bounds.center[2])/bounds.scale;const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),x1=cy*x-sy*z,z1=sy*x+cy*z,cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),y1=cp*y-sp*z1,z2=sp*y+cp*z1+3.1/this.zoom;if(z2<=.2)return null;const focal=Math.min(w,h)*.94,px=w/2+this.pan[0]+x1/z2*focal,py=h/2+this.pan[1]-y1/z2*focal;return {x:px,y:py,depth:z2};}
}
function extent(points){const xs=points.map(p=>p.position?.[0]).filter(Number.isFinite),ys=points.map(p=>p.position?.[1]).filter(Number.isFinite),zs=points.map(p=>p.position?.[2]).filter(Number.isFinite),min=[Math.min(...xs),Math.min(...ys),Math.min(...zs)],max=[Math.max(...xs),Math.max(...ys),Math.max(...zs)],center=min.map((v,i)=>(v+max[i])/2),scale=Math.max(.25,...max.map((v,i)=>v-min[i]));return {center,scale};}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
