/** Dependency-free, touch-friendly orbit viewer for the processed metric model. */
export class InteractiveModelPreview {
  constructor(canvas){
    this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.model=null;this.yaw=-.72;this.pitch=.42;this.zoom=1.65;this.pan=[0,0];this.mode='mesh';this.drag=null;this.pointers=new Map();this.pinch=null;
    canvas.addEventListener('pointerdown',e=>this._pointerDown(e));canvas.addEventListener('pointermove',e=>this._pointerMove(e));canvas.addEventListener('pointerup',e=>this._pointerUp(e));canvas.addEventListener('pointercancel',e=>this._pointerUp(e));
    canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoomBy(Math.exp(-e.deltaY*.0012));},{passive:false});canvas.addEventListener('keydown',e=>{if(e.key==='r'||e.key==='R')this.resetView();if(e.key==='+'||e.key==='=')this.zoomBy(1.14);if(e.key==='-')this.zoomBy(.88);});
    if(globalThis.ResizeObserver){this.resizeObserver=new ResizeObserver(()=>this.draw());this.resizeObserver.observe(canvas);}else globalThis.addEventListener?.('resize',()=>this.draw());
  }
  setModel(model){this.model=model;this.draw();}
  setMode(mode){this.mode=mode==='points'?'points':'mesh';this.draw();}
  zoomBy(factor){this.zoom=clamp(this.zoom*factor,.42,4.2);this.draw();}
  resetView(){this.yaw=-.72;this.pitch=.42;this.zoom=1.65;this.pan=[0,0];this.draw();}
  _pointerDown(e){this.canvas.setPointerCapture?.(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===1)this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,pan:e.shiftKey};else this.pinch=this._pinchState();}
  _pointerMove(e){if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size>=2){const next=this._pinchState(),prev=this.pinch;if(prev&&next){this.zoom=clamp(this.zoom*(next.distance/Math.max(1,prev.distance)),.42,4.2);this.pan[0]+=next.x-prev.x;this.pan[1]+=next.y-prev.y;this.draw();}this.pinch=next;return;}if(!this.drag||this.drag.id!==e.pointerId)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.x=e.clientX;this.drag.y=e.clientY;if(this.drag.pan){this.pan[0]+=dx;this.pan[1]+=dy;}else{this.yaw+=dx*.009;this.pitch=clamp(this.pitch+dy*.008,-1.35,1.35);}this.draw();}
  _pointerUp(e){this.pointers.delete(e.pointerId);this.drag=null;this.pinch=this.pointers.size>=2?this._pinchState():null;}
  _pinchState(){const [a,b]=[...this.pointers.values()];return a&&b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2,distance:Math.hypot(a.x-b.x,a.y-b.y)}:null;}
  draw(){
    const canvas=this.canvas,ctx=this.ctx,dpr=Math.min(2,globalThis.devicePixelRatio||1),w=canvas.clientWidth||800,h=canvas.clientHeight||420;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#050d10';ctx.fillRect(0,0,w,h);
    const points=this.model?.geometry?.surfels||[],mesh=this.model?.geometry?.structuralMesh,bounds=extent([...points,...(mesh?.vertices||[]),...(this.model?.markpoints||[])]);if(!bounds){this._empty(w,h);return;}
    const hasMesh=!!(mesh?.vertices?.length&&mesh?.triangles?.length);if(this.mode==='mesh'&&hasMesh)this._drawMesh(mesh,bounds,w,h);else this._drawPoints(points,bounds,w,h);this._surfaces(bounds,w,h);this._marks(bounds,w,h);this._legend(w,h,hasMesh,mesh?.patchCount||0);
  }
  _empty(w,h){this.ctx.fillStyle='#9bb0b5';this.ctx.font='14px system-ui';this.ctx.fillText('Nessuna geometria metrica disponibile',18,30);}
  _drawMesh(mesh,bounds,w,h){const tris=[];for(const tri of mesh.triangles||[]){const vertices=tri.slice(0,3).map(i=>mesh.vertices[i]).filter(Boolean),projected=vertices.map(v=>this._project(v.position,bounds,w,h));if(projected.length!==3||projected.some(p=>!p))continue;const rgb=averageRgb(vertices.map(v=>v.rgb));tris.push({projected,rgb,depth:projected.reduce((s,p)=>s+p.depth,0)/3});}tris.sort((a,b)=>b.depth-a.depth);const ctx=this.ctx;for(const t of tris){ctx.beginPath();ctx.moveTo(t.projected[0].x,t.projected[0].y);ctx.lineTo(t.projected[1].x,t.projected[1].y);ctx.lineTo(t.projected[2].x,t.projected[2].y);ctx.closePath();ctx.fillStyle=`rgba(${t.rgb[0]},${t.rgb[1]},${t.rgb[2]},.58)`;ctx.fill();ctx.strokeStyle=`rgba(${t.rgb[0]},${t.rgb[1]},${t.rgb[2]},.30)`;ctx.lineWidth=.55;ctx.stroke();}}
  _drawPoints(points,bounds,w,h){const rendered=[];for(let i=0,step=Math.max(1,Math.ceil(points.length/14000));i<points.length;i+=step){const p=points[i],q=this._project(p.position,bounds,w,h);if(q)rendered.push({q,p});}rendered.sort((a,b)=>b.q.depth-a.q.depth);for(const {q,p} of rendered){const rgb=p.rgb||[145,155,160],size=Math.max(.9,2.35-q.depth*.45);this.ctx.fillStyle=`rgba(${rgb[0]},${rgb[1]},${rgb[2]},.82)`;this.ctx.fillRect(q.x-size/2,q.y-size/2,size,size);}}
  _surfaces(bounds,w,h){const ctx=this.ctx;for(const surface of this.model?.geometry?.structuralSurfaces||[]){const poly=surface.geometry?.bounds?.polygon||[],projected=poly.map(p=>this._project(p,bounds,w,h)).filter(Boolean);if(projected.length<3)continue;const color=surface.kind==='floor'?'#52e0b6':surface.kind==='ceiling'?'#64b5f6':'#ffd166';ctx.beginPath();ctx.moveTo(projected[0].x,projected[0].y);for(const p of projected.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=2.1;ctx.stroke();}}
  _marks(bounds,w,h){const ctx=this.ctx;for(const mark of this.model?.markpoints||[]){const p=this._project(mark.position,bounds,w,h);if(!p)continue;ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fillStyle='#ff72ce';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1.3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 10px system-ui';ctx.fillText('R',p.x+8,p.y-7);}}
  _legend(w,h,hasMesh,patches){const ctx=this.ctx;ctx.fillStyle='rgba(5,13,16,.82)';ctx.fillRect(10,h-38,Math.min(w-20,455),28);ctx.fillStyle='#d6e7e8';ctx.font='12px system-ui';const source=this.mode==='mesh'&&hasMesh?`Mesh WebXR: ${patches} patch osservate`:'Punti metrici';ctx.fillText(`${source} · 1 dito: ruota · 2 dita: sposta/zoom · + − reset`,16,h-20);}
  _project(position,bounds,w,h){if(!position?.every(Number.isFinite))return null;let x=(position[0]-bounds.center[0])/bounds.scale,y=(position[1]-bounds.center[1])/bounds.scale,z=(position[2]-bounds.center[2])/bounds.scale;const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),x1=cy*x-sy*z,z1=sy*x+cy*z,cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),y1=cp*y-sp*z1,z2=sp*y+cp*z1+3.1/this.zoom;if(z2<=.2)return null;const focal=Math.min(w,h)*.94,px=w/2+this.pan[0]+x1/z2*focal,py=h/2+this.pan[1]-y1/z2*focal;return {x:px,y:py,depth:z2};}
}
function extent(items){const positions=items.map(p=>p.position).filter(p=>p?.every(Number.isFinite));if(!positions.length)return null;const axis=i=>positions.map(p=>p[i]),min=[Math.min(...axis(0)),Math.min(...axis(1)),Math.min(...axis(2))],max=[Math.max(...axis(0)),Math.max(...axis(1)),Math.max(...axis(2))],center=min.map((v,i)=>(v+max[i])/2),scale=Math.max(.25,...max.map((v,i)=>v-min[i]));return {center,scale};}
function averageRgb(colors){const out=[0,0,0];for(const rgb of colors)for(let i=0;i<3;i++)out[i]+=rgb?.[i]??145;return out.map(v=>Math.round(v/colors.length));}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
