import {BUILD} from './config_v20_2_0.js';

/**
 * Uncompressed ZIP builder. Stored entries avoid CPU-heavy deflate and preserve
 * already compressed JPEGs. Data is read one entry at a time for CRC32; the
 * final Blob is assembled from references instead of a second base64 copy.
 */
export class StoredZipBuilder {
  constructor(){this.entries=[];this.parts=[];this.central=[];this.offset=0;}
  async add(name,data,{mtime=new Date()}={}){
    const safeName=name.replace(/^\/+|\.\.(?:\/|\\)/g,'').replace(/\\/g,'/'),nameBytes=new TextEncoder().encode(safeName),blob=data instanceof Blob?data:new Blob([typeof data==='string'?new TextEncoder().encode(data):data]);if(blob.size>0xffffffff)throw new Error(`Entry troppo grande per ZIP32: ${safeName}`);const bytes=new Uint8Array(await blob.arrayBuffer()),crc=crc32(bytes),{date,time}=dosDateTime(mtime);const local=new ArrayBuffer(30+nameBytes.length),dv=new DataView(local);dv.setUint32(0,0x04034b50,true);dv.setUint16(4,20,true);dv.setUint16(6,0x0800,true);dv.setUint16(8,0,true);dv.setUint16(10,time,true);dv.setUint16(12,date,true);dv.setUint32(14,crc,true);dv.setUint32(18,blob.size,true);dv.setUint32(22,blob.size,true);dv.setUint16(26,nameBytes.length,true);dv.setUint16(28,0,true);new Uint8Array(local,30).set(nameBytes);const localOffset=this.offset;this.parts.push(local,blob);this.offset+=local.byteLength+blob.size;
    this.central.push({nameBytes,crc,size:blob.size,date,time,offset:localOffset});this.entries.push({name:safeName,size:blob.size,crc32:crc.toString(16).padStart(8,'0')});return this;
  }
  finish(){const centralStart=this.offset;for(const e of this.central){const b=new ArrayBuffer(46+e.nameBytes.length),dv=new DataView(b);dv.setUint32(0,0x02014b50,true);dv.setUint16(4,20,true);dv.setUint16(6,20,true);dv.setUint16(8,0x0800,true);dv.setUint16(10,0,true);dv.setUint16(12,e.time,true);dv.setUint16(14,e.date,true);dv.setUint32(16,e.crc,true);dv.setUint32(20,e.size,true);dv.setUint32(24,e.size,true);dv.setUint16(28,e.nameBytes.length,true);dv.setUint16(30,0,true);dv.setUint16(32,0,true);dv.setUint16(34,0,true);dv.setUint16(36,0,true);dv.setUint32(38,0,true);dv.setUint32(42,e.offset,true);new Uint8Array(b,46).set(e.nameBytes);this.parts.push(b);this.offset+=b.byteLength;}const centralSize=this.offset-centralStart,end=new ArrayBuffer(22),dv=new DataView(end);dv.setUint32(0,0x06054b50,true);dv.setUint16(4,0,true);dv.setUint16(6,0,true);dv.setUint16(8,this.central.length,true);dv.setUint16(10,this.central.length,true);dv.setUint32(12,centralSize,true);dv.setUint32(16,centralStart,true);dv.setUint16(20,0,true);this.parts.push(end);return new Blob(this.parts,{type:'application/zip'});}
}

export async function buildRawBundle(repository,sessionId,{onProgress=()=>{}}={}){
  const session=await repository.getSession(sessionId);if(!session)throw new Error('Sessione non trovata');const [records,blobs,events,model]=await Promise.all([repository.getRecords(sessionId),repository.getBlobs(sessionId),repository.getEvents(sessionId),repository.getModel(sessionId)]);const zip=new StoredZipBuilder(),createdAt=new Date();let done=0,total=5+blobs.length;
  const step=(label)=>onProgress({done:++done,total,label,ratio:done/total});
  await zip.add('manifest.json',JSON.stringify({format:BUILD.rawFormat,createdAt:createdAt.toISOString(),build:BUILD,sessionId,session,counts:{records:records.length,blobs:blobs.length,events:events.length},entries:blobs.map(b=>({key:b.key,kind:b.kind,size:b.size,type:b.type,meta:b.meta}))},null,2));step('manifest');
  await zip.add('diagnostics/events.ndjson',events.map(e=>JSON.stringify(e)).join('\n')+'\n');step('diagnostica');
  const byKind=new Map();for(const r of records){if(!byKind.has(r.kind))byKind.set(r.kind,[]);byKind.get(r.kind).push({key:r.key,time:r.time,value:r.value});}for(const [kind,list] of byKind)await zip.add(`records/${sanitize(kind)}.ndjson`,list.map(v=>JSON.stringify(v)).join('\n')+'\n');step('metadati');
  if(model)await zip.add('model/model.json',JSON.stringify(model,null,2));step('modello');
  await zip.add('README.txt',rawReadme(session));step('istruzioni');
  for(const b of blobs){const name=blobPath(b);await zip.add(name,b.blob,{mtime:new Date(b.time)});step(name);}
  const bundle=zip.finish();return {blob:bundle,filename:`roomscan-${shortId(sessionId)}-${new Date().toISOString().replace(/[:.]/g,'-')}.rscan.zip`,entries:zip.entries};
}

export async function buildDiagnosticsBundle(repository,sessionId){const session=await repository.getSession(sessionId),events=await repository.getEvents(sessionId),records=await repository.getRecords(sessionId),blobs=await repository.getBlobs(sessionId);const payload={format:'ROOMSCAN-DIAGNOSTICS-1',exportedAt:new Date().toISOString(),session,storage:{records:records.length,blobs:blobs.length,blobBytes:blobs.reduce((s,b)=>s+b.size,0),byKind:groupCounts(blobs)},events,recordIndex:records.map(r=>({key:r.key,kind:r.kind,time:r.time,summary:summarizeRecord(r.value)})),userAgent:navigator.userAgent,platform:navigator.platform??null};return {blob:new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),filename:`roomscan-${shortId(sessionId)}-diagnostics.json`};}
export function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}

function blobPath(b){const leaf=b.key.split('/').pop();if(b.kind==='frame-jpeg')return `frames/${leaf}`;if(b.kind==='depth-points'||b.kind==='depth-rays')return `depth/${leaf}`;if(b.kind==='audio-pcm')return `audio/${leaf}`;return `binary/${sanitize(b.kind)}/${leaf}`;}
function sanitize(s){return String(s).replace(/[^a-zA-Z0-9._-]+/g,'_');}function shortId(id){return id.split('-').slice(-1)[0].slice(0,10);}function groupCounts(items){const o={};for(const x of items){o[x.kind]??={count:0,bytes:0};o[x.kind].count++;o[x.kind].bytes+=x.size||0;}return o;}function summarizeRecord(v){if(v==null||typeof v!=='object')return v;const o={};for(const k of Object.keys(v).slice(0,18)){const x=v[k];o[k]=Array.isArray(x)?`Array(${x.length})`:ArrayBuffer.isView(x)?`${x.constructor.name}(${x.length})`:typeof x==='object'?'Object':x;}return o;}
function rawReadme(session){return `ROOM SCANNER RAW DATA\n\nFormat: ${BUILD.rawFormat}\nBuild: ${BUILD.id}\nSession: ${session.id}\n\nThis archive is intentionally uncompressed for reliable, low-CPU export on a phone.\n- manifest.json: session and binary index\n- records/*.ndjson: poses, frame metadata, chirps, grid snapshots and markpoints\n- frames/*.jpg: raw-camera keyframes\n- depth/*.rsry: dense raw view rays (UV + metric Z depth + normal + RGB/confidence, RSRY v1)
- depth/*.rspt: legacy compact metric point batches (RSPT v1)\n- audio/*.pcm16: mono signed 16-bit little-endian PCM chunks\n- diagnostics/events.ndjson: persisted state transitions and failures\n\nUse tools/process_rscan.py from the source package to validate and extract trajectory, WAV, dense PLY and diagnostics. RSRY preserves the ray geometry needed for future Gaussian/occupancy processing.\nNo absolute acoustic delay is assumed: chirp records preserve browser/audio clocks and WebXR poses.\n`;}
function dosDateTime(d){const year=Math.max(1980,d.getFullYear());return {date:((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate(),time:(d.getHours()<<11)|(d.getMinutes()<<5)|Math.floor(d.getSeconds()/2)};}
let CRC_TABLE=null;function crc32(bytes){if(!CRC_TABLE){CRC_TABLE=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;CRC_TABLE[n]=c>>>0;}}let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
