import {PROCESSING} from './config_v20_2_0.js';
import {angle3,clamp,cross3,dist3,dot3,hashCell,len3,median,norm3,quantile,scale3,sub3,uid} from './math_v20_2_0.js';

/** Plane-aware bounded decimation that preserves edges, objects and anchors. */
export function decimateSurfels(points,{maxPoints=50000}={}){
  const buckets=new Map();for(const p of points){const important=p.markpointId||p.surfaceType==='edge'||p.surfaceType==='object'||(p.curvature||0)>.18||p.status!=='green';const size=important ? .06 : (['wall','floor','ceiling'].includes(p.surfaceType)&&p.quality>.65 ? .18 : .10),key=hashCell(p.position,size);let b=buckets.get(key);if(!b){b={weight:0,position:[0,0,0],normal:[0,0,0],rgb:[0,0,0],quality:0,curvature:0,frameRefs:new Set(),surfaceVotes:new Map(),markpointId:null,status:'green'};buckets.set(key,b);}const w=.2+clamp(p.quality??.5,0,1);b.weight+=w;for(let i=0;i<3;i++){b.position[i]+=p.position[i]*w;b.normal[i]+=(p.normal?.[i]||0)*w;b.rgb[i]+=(p.rgb?.[i]??145)*w;}b.quality+=w*(p.quality??.5);b.curvature=Math.max(b.curvature,p.curvature||0);for(const f of p.frameRefs||[])b.frameRefs.add(typeof f==='string'?f:f.id);b.surfaceVotes.set(p.surfaceType,(b.surfaceVotes.get(p.surfaceType)||0)+w);b.markpointId||=p.markpointId||null;if(p.status!=='green')b.status=p.status;}
  let out=[];for(const b of buckets.values()){const iw=1/b.weight,surfaceType=[...b.surfaceVotes].sort((a,b)=>b[1]-a[1])[0]?.[0]||'unknown';out.push({id:uid('surfel'),position:b.position.map(v=>v*iw),normal:norm3(b.normal),rgb:b.rgb.map(v=>Math.round(v*iw)),quality:b.quality*iw,curvature:b.curvature,frameRefs:[...b.frameRefs].slice(0,8),surfaceType,markpointId:b.markpointId,status:b.status});}
  if(out.length>maxPoints){out.sort((a,b)=>importance(b)-importance(a));out=out.slice(0,maxPoints);}return out;
}
function importance(p){return (p.markpointId?100:0)+(p.surfaceType==='object'||p.surfaceType==='edge'?5:0)+(p.status!=='green'?2:0)+(p.frameRefs?.length||0)*.5+(p.quality||0);}

export function fitStructuralPlanes(points,options={}){
  const cfg={...PROCESSING,...options};const horizontal=points.filter(p=>Math.abs(p.normal?.[1]||0)>=cfg.floorNormalY);const vertical=points.filter(p=>Math.abs(p.normal?.[1]||0)<=cfg.wallNormalYMax);const floors=fitHorizontalClusters(horizontal,points,'floor');const ceilings=fitHorizontalClusters(horizontal,points,'ceiling');let remaining=vertical.slice(),walls=[];
  const rng=mulberry32(0x20_02_00);for(let planeIndex=0;planeIndex<cfg.maxPlanes&&remaining.length>=cfg.minPlaneSupport;planeIndex++){let best=null;for(let it=0;it<cfg.planeIterations;it++){const seed=remaining[Math.floor(rng()*remaining.length)],n=canonicalHorizontalNormal(seed.normal);if(len3(n)<.8)continue;const d=-dot3(n,seed.position),inliers=[];let score=0;for(let i=0;i<remaining.length;i++){const p=remaining[i],dist=Math.abs(dot3(n,p.position)+d),align=Math.abs(dot3(n,norm3(p.normal)));if(dist<=cfg.planeDistanceM&&align>=Math.cos(cfg.planeNormalDeg*Math.PI/180)){inliers.push(i);score+=(p.quality||.5)*(1-dist/cfg.planeDistanceM)*(.5+.5*align);}}if(!best||score>best.score)best={n,d,inliers,score};}if(!best||best.inliers.length<cfg.minPlaneSupport)break;const inlierPoints=best.inliers.map(i=>remaining[i]),plane=refineVerticalPlane(best.n,inlierPoints);plane.id=uid('wall');plane.kind='wall';plane.support=inlierPoints.length;plane.confidence=clamp(inlierPoints.reduce((s,p)=>s+(p.quality||.5),0)/inlierPoints.length,0,1);plane.frameRefs=uniqueFrames(inlierPoints);plane.bounds=planeBounds(plane,inlierPoints);walls.push(plane);const remove=new Set(best.inliers);remaining=remaining.filter((_,i)=>!remove.has(i));}
  walls=mergeCoplanarWalls(walls);const all=[...floors,...ceilings,...walls];const structuralInliers=new Set();for(const plane of all)for(const p of points)if(pointFitsPlane(p,plane,cfg))structuralInliers.add(p.id);return {planes:all,floors,ceilings,walls,residual:points.filter(p=>!structuralInliers.has(p.id)),stats:{input:points.length,horizontal:horizontal.length,vertical:vertical.length,planes:all.length,residual:points.length-structuralInliers.size}};
}

function fitHorizontalClusters(horizontal,all,kind){
  if(!horizontal.length)return kind==='floor'?[inferredHorizontal(all,kind)]:[inferredHorizontal(all,kind)];const bins=new Map();for(const p of horizontal){const y=p.position[1],key=Math.round(y/.08);if(!bins.has(key))bins.set(key,[]);bins.get(key).push(p);}const clusters=[...bins.values()].filter(c=>c.length>=Math.max(8,horizontal.length*.015)).sort((a,b)=>b.length-a.length);const ys=all.map(p=>p.position[1]),low=quantile(ys,.04),high=quantile(ys,.96);let chosen=null;if(kind==='floor')chosen=clusters.filter(c=>median(c.map(p=>p.position[1]))<=low+.35).sort((a,b)=>b.length-a.length)[0];else chosen=clusters.filter(c=>median(c.map(p=>p.position[1]))>=high-.45).sort((a,b)=>b.length-a.length)[0];if(!chosen)return [inferredHorizontal(all,kind)];const y=median(chosen.map(p=>p.position[1])),normal=kind==='floor'?[0,1,0]:[0,-1,0],d=-dot3(normal,[0,y,0]),plane={id:uid(kind),kind,normal,d,support:chosen.length,confidence:clamp(chosen.length/Math.max(25,horizontal.length*.25),.25,.96),source:'observed-horizontal',frameRefs:uniqueFrames(chosen)};plane.bounds=horizontalBounds(y,all,kind);return [plane];
}
function inferredHorizontal(all,kind){const ys=all.map(p=>p.position[1]).filter(Number.isFinite);const y=kind==='floor'?(ys.length?quantile(ys,.02):0):(ys.length?Math.max(2.15,quantile(ys,.98)):2.7),normal=kind==='floor'?[0,1,0]:[0,-1,0];return {id:uid(kind),kind,normal,d:-dot3(normal,[0,y,0]),support:0,confidence:.12,source:'inferred-from-extent',frameRefs:[],bounds:horizontalBounds(y,all,kind)};}
function horizontalBounds(y,all,kind){const xz=all.map(p=>[p.position[0],p.position[2]]);const hull=convexHull2D(xz);return {polygon:hull.map(([x,z])=>[x,y,z]),area:polygonArea(hull),height:y,kind};}
function canonicalHorizontalNormal(n){let v=norm3([n?.[0]||0,0,n?.[2]||0]);if(v[0]<0||(Math.abs(v[0])<1e-8&&v[2]<0))v=scale3(v,-1);return v;}
function refineVerticalPlane(initial,points){let nx=0,nz=0;for(const p of points){let n=canonicalHorizontalNormal(p.normal);if(dot3(n,initial)<0)n=scale3(n,-1);const w=p.quality||.5;nx+=n[0]*w;nz+=n[2]*w;}const normal=norm3([nx,0,nz]),d=-median(points.map(p=>dot3(normal,p.position)));return {normal,d,source:'ransac-regularized'};}
function planeBounds(plane,points){const up=[0,1,0],u=norm3(cross3(up,plane.normal)),vals=points.map(p=>({u:dot3(u,p.position),v:p.position[1]})),us=vals.map(v=>v.u),vs=vals.map(v=>v.v),umin=quantile(us,.015),umax=quantile(us,.985),vmin=quantile(vs,.015),vmax=quantile(vs,.985),origin=scale3(plane.normal,-plane.d);const corner=(a,b)=>[origin[0]+u[0]*a, b, origin[2]+u[2]*a];return {u,up,rangeU:[umin,umax],rangeV:[vmin,vmax],polygon:[corner(umin,vmin),corner(umax,vmin),corner(umax,vmax),corner(umin,vmax)],area:Math.max(0,umax-umin)*Math.max(0,vmax-vmin)};}
function mergeCoplanarWalls(walls){const used=new Set(),out=[];for(let i=0;i<walls.length;i++){if(used.has(i))continue;const group=[walls[i]];used.add(i);for(let j=i+1;j<walls.length;j++){if(used.has(j))continue;let n=walls[j].normal,d=walls[j].d;if(dot3(n,walls[i].normal)<0){n=scale3(n,-1);d=-d;}if(angle3(n,walls[i].normal)<8*Math.PI/180&&Math.abs(d-walls[i].d)<.13){group.push({...walls[j],normal:n,d});used.add(j);}}if(group.length===1){out.push(group[0]);continue;}const support=group.reduce((s,p)=>s+p.support,0),normal=norm3(group.reduce((a,p)=>[a[0]+p.normal[0]*p.support,0,a[2]+p.normal[2]*p.support],[0,0,0])),d=group.reduce((s,p)=>s+p.d*p.support,0)/support,points=group.flatMap(p=>p.bounds.polygon.map(position=>({position,normal,quality:p.confidence,frameRefs:p.frameRefs})));out.push({id:uid('wall'),kind:'wall',normal,d,support,confidence:group.reduce((s,p)=>s+p.confidence*p.support,0)/support,source:'merged-coplanar',frameRefs:[...new Set(group.flatMap(p=>p.frameRefs))].slice(0,12),bounds:planeBounds({normal,d},points)});}return out;}
function pointFitsPlane(p,plane,cfg){const dist=Math.abs(dot3(plane.normal,p.position)+plane.d),align=Math.abs(dot3(plane.normal,norm3(p.normal)));return dist<=cfg.planeDistanceM*1.35&&align>=Math.cos((cfg.planeNormalDeg+8)*Math.PI/180);}

export function clusterResidualObjects(points,{radius=PROCESSING.objectClusterRadiusM,minPoints=PROCESSING.minObjectPoints,maxPoints=PROCESSING.maxObjectPoints}={}){
  const size=radius,map=new Map();for(let i=0;i<points.length;i++){const k=hashCell(points[i].position,size);if(!map.has(k))map.set(k,[]);map.get(k).push(i);}const visited=new Uint8Array(points.length),objects=[];for(let seed=0;seed<points.length;seed++){if(visited[seed])continue;const queue=[seed],indices=[];visited[seed]=1;while(queue.length&&indices.length<maxPoints){const i=queue.pop();indices.push(i);const p=points[i].position,ix=Math.floor(p[0]/size),iy=Math.floor(p[1]/size),iz=Math.floor(p[2]/size);for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++)for(let dz=-1;dz<=1;dz++){const list=map.get(`${ix+dx},${iy+dy},${iz+dz}`)||[];for(const j of list)if(!visited[j]&&dist3(p,points[j].position)<=radius*1.65){visited[j]=1;queue.push(j);}}}if(indices.length<minPoints)continue;const pts=indices.map(i=>points[i]),obb=fitOBB(pts),volume=obb.size[0]*obb.size[1]*obb.size[2];if(volume<.001||volume>80)continue;objects.push({id:uid('object'),label:'Oggetto rilevato',confidence:clamp(pts.reduce((s,p)=>s+(p.quality||.5),0)/pts.length,0,1),points:pts.slice(0,6000).map(p=>({position:p.position,rgb:p.rgb,normal:p.normal,frameRefs:p.frameRefs})),obb,mesh:boxMesh(obb,averageColor(pts)),frameRefs:uniqueFrames(pts),acousticSurfaces:objectAcousticSurfaces()});}return objects;}
function fitOBB(points){let cx=0,cz=0;for(const p of points){cx+=p.position[0];cz+=p.position[2];}cx/=points.length;cz/=points.length;let xx=0,xz=0,zz=0;for(const p of points){const x=p.position[0]-cx,z=p.position[2]-cz;xx+=x*x;xz+=x*z;zz+=z*z;}const angle=.5*Math.atan2(2*xz,xx-zz),u=[Math.cos(angle),0,Math.sin(angle)],v=[-Math.sin(angle),0,Math.cos(angle)],us=points.map(p=>dot3(u,p.position)),vs=points.map(p=>dot3(v,p.position)),ys=points.map(p=>p.position[1]),umin=quantile(us,.01),umax=quantile(us,.99),vmin=quantile(vs,.01),vmax=quantile(vs,.99),ymin=quantile(ys,.01),ymax=quantile(ys,.99),center=[u[0]*(umin+umax)/2+v[0]*(vmin+vmax)/2,(ymin+ymax)/2,u[2]*(umin+umax)/2+v[2]*(vmin+vmax)/2];return {center,axes:[u,[0,1,0],v],size:[Math.max(.03,umax-umin),Math.max(.03,ymax-ymin),Math.max(.03,vmax-vmin)],angleY:angle};}
function boxMesh(obb,rgb){const [u,y,v]=obb.axes,[sx,sy,sz]=obb.size.map(s=>s/2),verts=[];for(const a of [-1,1])for(const b of [-1,1])for(const c of [-1,1])verts.push([obb.center[0]+u[0]*sx*a+y[0]*sy*b+v[0]*sz*c,obb.center[1]+u[1]*sx*a+y[1]*sy*b+v[1]*sz*c,obb.center[2]+u[2]*sx*a+y[2]*sy*b+v[2]*sz*c]);const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]],labels=['left','right','bottom','top','front','back'];return {vertices:verts.map(position=>({position,rgb})),triangles:faces.flatMap((f,i)=>[[f[0],f[1],f[2],labels[i]],[f[0],f[2],f[3],labels[i]]])};}
function averageColor(points){const s=[0,0,0];for(const p of points)for(let i=0;i<3;i++)s[i]+=p.rgb?.[i]??145;return s.map(v=>Math.round(v/points.length));}
function objectAcousticSurfaces(){return ['left','right','bottom','top','front','back'].map(key=>acousticSurface(`object-${key}`,key));}

export function buildAcousticReadyModel({session,points,fit,objects,markpoints,frames,chirps,audio,registration=null,diagnostics=[]}){
  const surfaces=fit.planes.map(p=>({id:p.id,kind:p.kind,geometry:{plane:{normal:p.normal,d:p.d},bounds:p.bounds},confidence:p.confidence,source:p.source,frameRefs:p.frameRefs,acoustic:acousticSurface(p.id,p.kind)}));return {format:'ROOMSCAN-MODEL-20.2',build:session.build,sessionId:session.id,createdAt:new Date().toISOString(),metricFrame:{type:'WebXR-local-floor',scaleMetersPerUnit:1,authority:'WebXR/XR-depth',globalRescaleAllowed:false,segmentRegistration:registration},captureSummary:{sessionStatus:session.status,counts:session.counts,frames:frames.length,chirps:chirps.length,markpoints:markpoints.length},geometry:{surfelCount:points.length,surfels:points,structuralSurfaces:surfaces,objects,floorSurfaceIds:surfaces.filter(s=>s.kind==='floor').map(s=>s.id),ceilingSurfaceIds:surfaces.filter(s=>s.kind==='ceiling').map(s=>s.id),wallSurfaceIds:surfaces.filter(s=>s.kind==='wall').map(s=>s.id)},markpoints,photos:frames.map(f=>({id:f.id,pose:f.pose,quality:f.quality,linkedTiles:f.linkedTiles,image:f.image})),acoustics:{status:'captured-not-yet-associated',bandsHz:[125,250,500,1000,2000,4000,8000],measurements:chirps,pcmManifest:audio,policy:{chirpStrategy:'rapid-many-positions',absoluteDelayKnown:false,alignment:'relative-to-direct-path',aggregation:'quality-weighted-robust'},surfaceCount:surfaces.length+objects.reduce((s,o)=>s+o.acousticSurfaces.length,0)},diagnostics:{fit:fit.stats,eventCount:diagnostics.length}};}
function acousticSurface(id,kind){return {id:`acoustic-${id}`,geometryRef:id,kind,status:'unestimated',bandsHz:[125,250,500,1000,2000,4000,8000],absorption:[null,null,null,null,null,null,null],confidence:[0,0,0,0,0,0,0],scattering:null,rirAssociations:[],manualOverride:false};}
function uniqueFrames(points){return [...new Set(points.flatMap(p=>(p.frameRefs||[]).map(f=>typeof f==='string'?f:f.id)))].slice(0,PROCESSING.maxFrameLinksPerSurface);}
function convexHull2D(points){const unique=[...new Map(points.filter(p=>p.every(Number.isFinite)).map(p=>[`${p[0].toFixed(4)},${p[1].toFixed(4)}`,p])).values()].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(unique.length<3){if(!unique.length)return [[-1,-1],[1,-1],[1,1],[-1,1]];const xs=unique.map(p=>p[0]),ys=unique.map(p=>p[1]),pad=.2;return [[Math.min(...xs)-pad,Math.min(...ys)-pad],[Math.max(...xs)+pad,Math.min(...ys)-pad],[Math.max(...xs)+pad,Math.max(...ys)+pad],[Math.min(...xs)-pad,Math.max(...ys)+pad]];}const cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]),lo=[],up=[];for(const p of unique){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),p)<=0)lo.pop();lo.push(p);}for(let i=unique.length-1;i>=0;i--){const p=unique[i];while(up.length>=2&&cross(up.at(-2),up.at(-1),p)<=0)up.pop();up.push(p);}lo.pop();up.pop();return lo.concat(up);}
function polygonArea(poly){let a=0;for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length];a+=p[0]*q[1]-q[0]*p[1];}return Math.abs(a)/2;}
function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
