import {BUILD,GRID} from './config_v20_2_0.js';
import {add3,angle3,cameraPositionFromMatrix,clamp,cross3,dist3,finiteArray,forwardFromMatrix,invert4,len3,norm3,projectWorldPoint,quantizedViewKey,scale3,sub3,transformDirection4,transformPoint4,uid} from './math_v20_2_0.js';
import {AdaptiveGridOverlay,summarizeCoverage} from './grid_v20_2_0.js';
import {computePatchDescriptor} from './markpoints_v20_2_0.js';

/** Compact append-only point format: 14 bytes per surfel, relative to camera. */
export function encodePointBatch(points,origin){
  const count=Math.floor(points.length/10),header=20,recordBytes=14,buffer=new ArrayBuffer(header+count*recordBytes),dv=new DataView(buffer);dv.setUint32(0,0x52535054,true);dv.setUint16(4,1,true);dv.setUint16(6,recordBytes,true);dv.setUint32(8,count,true);dv.setFloat32(12,GRID.sourceVoxelM,true);dv.setUint32(16,0,true);let o=header;
  for(let i=0;i<count;i++){const p=i*10;for(let k=0;k<3;k++)dv.setInt16(o+k*2,clamp(Math.round((points[p+k]-origin[k])*1000),-32767,32767),true);dv.setInt8(o+6,clamp(Math.round(points[p+3]*127),-127,127));dv.setInt8(o+7,clamp(Math.round(points[p+4]*127),-127,127));dv.setInt8(o+8,clamp(Math.round(points[p+5]*127),-127,127));dv.setUint8(o+9,clamp(Math.round(points[p+6]),0,255));dv.setUint8(o+10,clamp(Math.round(points[p+7]),0,255));dv.setUint8(o+11,clamp(Math.round(points[p+8]),0,255));dv.setUint8(o+12,clamp(Math.round(points[p+9]*255),0,255));dv.setUint8(o+13,0);o+=recordBytes;}return buffer;
}
export function decodePointBatch(buffer,origin){const dv=new DataView(buffer),magic=dv.getUint32(0,true);if(magic!==0x52535054)throw new Error('Point batch non valido');const count=dv.getUint32(8,true),stride=dv.getUint16(6,true),out=new Float32Array(count*10);let o=20;for(let i=0;i<count;i++,o+=stride){const p=i*10;out[p]=origin[0]+dv.getInt16(o,true)/1000;out[p+1]=origin[1]+dv.getInt16(o+2,true)/1000;out[p+2]=origin[2]+dv.getInt16(o+4,true)/1000;out[p+3]=dv.getInt8(o+6)/127;out[p+4]=dv.getInt8(o+7)/127;out[p+5]=dv.getInt8(o+8)/127;out[p+6]=dv.getUint8(o+9);out[p+7]=dv.getUint8(o+10);out[p+8]=dv.getUint8(o+11);out[p+9]=dv.getUint8(o+12)/255;}return out;}

class PoseMotionTracker {
  constructor(){this.last=null;this.linearSpeed=0;this.angularSpeed=0;this.stability=0;}
  update(matrix,orientation,timeMs){const pos=cameraPositionFromMatrix(matrix);if(this.last){const dt=Math.max(.001,(timeMs-this.last.time)/1000);const v=dist3(pos,this.last.pos)/dt;const dot=Math.abs((orientation?.x||0)*(this.last.q?.x||0)+(orientation?.y||0)*(this.last.q?.y||0)+(orientation?.z||0)*(this.last.q?.z||0)+(orientation?.w??1)*(this.last.q?.w??1));const angle=2*Math.acos(clamp(dot,-1,1));this.linearSpeed=.72*this.linearSpeed+.28*v;this.angularSpeed=.72*this.angularSpeed+.28*(angle/dt);}this.stability=clamp(1-this.linearSpeed/1.0-this.angularSpeed/2.3,0,1);this.last={pos,q:orientation?{x:orientation.x,y:orientation.y,z:orientation.z,w:orientation.w}:null,time:timeMs};return {position:pos,linearSpeed:this.linearSpeed,angularSpeed:this.angularSpeed,stability:this.stability};}
}

class RawCameraReader {
  constructor(gl,binding,{targetWidth=416,diagnostics}){this.gl=gl;this.binding=binding;this.targetWidth=targetWidth;this.diag=diagnostics;this.program=null;this.fbo=null;this.outputTexture=null;this.width=0;this.height=0;this.disabled=false;}
  _compile(type,source){const gl=this.gl,s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'Shader camera non compilato');return s;}
  _init(width,height){const gl=this.gl;if(!(gl instanceof WebGL2RenderingContext))throw new Error('Raw camera readback richiede WebGL2');const vs=this._compile(gl.VERTEX_SHADER,'#version 300 es\nin vec2 a_position;out vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}');const fs=this._compile(gl.FRAGMENT_SHADER,'#version 300 es\nprecision mediump float;uniform sampler2D u_camera;in vec2 v_uv;out vec4 outColor;void main(){outColor=texture(u_camera,v_uv);}');const p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Programma camera non collegato');gl.deleteShader(vs);gl.deleteShader(fs);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);this.program={p,b,a:gl.getAttribLocation(p,'a_position'),u:gl.getUniformLocation(p,'u_camera')};this.fbo=gl.createFramebuffer();this.outputTexture=gl.createTexture();this._resize(width,height);}
  _resize(width,height){const gl=this.gl;this.width=width;this.height=height;gl.bindTexture(gl.TEXTURE_2D,this.outputTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.outputTexture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('Framebuffer camera incompleto');gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
  async read(view){
    if(this.disabled||!view.camera)return null;const gl=this.gl;try{const texture=this.binding.getCameraImage(view.camera);if(!texture)return null;const aspect=view.camera.width/view.camera.height,width=Math.max(160,Math.min(this.targetWidth,view.camera.width)),height=Math.max(120,Math.round(width/aspect));if(!this.program)this._init(width,height);else if(width!==this.width||height!==this.height)this._resize(width,height);const prevFbo=gl.getParameter(gl.FRAMEBUFFER_BINDING),prevViewport=gl.getParameter(gl.VIEWPORT),prevProgram=gl.getParameter(gl.CURRENT_PROGRAM);gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.viewport(0,0,width,height);gl.useProgram(this.program.p);gl.bindBuffer(gl.ARRAY_BUFFER,this.program.b);gl.enableVertexAttribArray(this.program.a);gl.vertexAttribPointer(this.program.a,2,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(this.program.u,0);gl.drawArrays(gl.TRIANGLES,0,6);const pixels=new Uint8Array(width*height*4);gl.readPixels(0,0,width,height,gl.RGBA,gl.UNSIGNED_BYTE,pixels);gl.bindFramebuffer(gl.FRAMEBUFFER,prevFbo);gl.viewport(prevViewport[0],prevViewport[1],prevViewport[2],prevViewport[3]);gl.useProgram(prevProgram);const flipped=flipRows(pixels,width,height);return {rgba:flipped,width,height,cameraWidth:view.camera.width,cameraHeight:view.camera.height};}catch(error){this.disabled=true;this.diag?.error('raw-camera-disabled',error);return null;}
  }
  dispose(){const gl=this.gl;try{if(this.program){gl.deleteBuffer(this.program.b);gl.deleteProgram(this.program.p);}if(this.outputTexture)gl.deleteTexture(this.outputTexture);if(this.fbo)gl.deleteFramebuffer(this.fbo);}catch{}this.program=this.outputTexture=this.fbo=null;}
}

export class XRCaptureController {
  constructor({canvas,overlayCanvas,repository,diagnostics,session,segmentId,profile,audioCapture,chirpScheduler,markpointManager,callbacks={}}){this.canvas=canvas;this.overlay=new AdaptiveGridOverlay(overlayCanvas,{maxVisibleTiles:profile.maxVisibleTiles});this.repo=repository;this.diag=diagnostics;this.sessionRecord=session;this.sessionId=session.id;this.segmentId=segmentId||session.currentSegmentId||'segment-0';this.profile=profile;this.audio=audioCapture;this.chirps=chirpScheduler;this.markpoints=markpointManager;this.cb=callbacks;this.xrSession=null;this.refSpace=null;this.viewerSpace=null;this.hitTestSource=null;this.gl=null;this.binding=null;this.cameraReader=null;this.mapWorker=null;this.motion=new PoseMotionTracker();this.frameSeq=0;this.depthSeq=0;this.poseChunk=[];this.hitChunk=[];this.activeTasks=new Set();this.lastPoseWrite=0;this.lastDepthSample=0;this.lastPlaneSample=0;this.lastPhoto=0;this.lastSnapshot=0;this.lastGridPersist=0;this.gridTiles=[];this.gridStats={};this.coverage={red:0,yellow:0,green:0,deep:0,total:0,score:0};this.closing=false;this.ended=false;this.forcePhoto=false;this.markpointRequest=null;this.latestFrameContext=null;this.lastDepthCandidate=null;this.reticle=null;this.autoPhotoCount=0;this.autoPhotoByTarget=new Map();this.plannedAutoTargetId=null;this._snapshotRequest=0;this._endPromise=null;this.depthMode='none';this.depthDataFormat=null;this.depthReadDisabled=false;this._depthModeLogged=false;}
  static async compatibility(){const out={secureContext:globalThis.isSecureContext,indexedDB:!!globalThis.indexedDB,mediaDevices:!!navigator.mediaDevices?.getUserMedia,webXR:!!navigator.xr,immersiveAR:false,rawCamera:'optional',depthSensing:'optional',audioWorklet:!!globalThis.AudioWorkletNode,offscreenCanvas:!!globalThis.OffscreenCanvas,compressionStream:!!globalThis.CompressionStream};if(navigator.xr)try{out.immersiveAR=await navigator.xr.isSessionSupported('immersive-ar');}catch(e){out.xrError=e.message;}return out;}
  static requestImmersiveSession(domRoot=document.body){
    if(!navigator.xr)throw new Error('WebXR non disponibile');
    const options={requiredFeatures:['local-floor'],optionalFeatures:['depth-sensing','camera-access','hit-test','anchors','plane-detection','dom-overlay'],depthSensing:{usagePreference:['cpu-optimized','gpu-optimized'],dataFormatPreference:['float32','luminance-alpha']},domOverlay:{root:domRoot}};
    // This function contains no await before requestSession. Call it directly
    // from the user click handler to preserve transient user activation.
    return navigator.xr.requestSession('immersive-ar',options);
  }
  async start({xrSession=null}={}){
    if(!navigator.xr)throw new Error('WebXR non disponibile');this.mapWorker=new Worker(new URL('../workers/map_worker_v20_2_0.js',import.meta.url));this.mapWorker.onmessage=e=>this._onMapMessage(e.data);this.mapWorker.onerror=e=>this.diag.error('map-worker-error',e.error||new Error(e.message));this.mapWorker.postMessage({type:'init',sessionId:this.sessionId,budget:this.profile.mapBudgetCells});
    await this.diag.transition('XR_REQUESTING',{preRequested:!!xrSession});this.xrSession=xrSession||await XRCaptureController.requestImmersiveSession(document.body);this.xrSession.addEventListener('end',()=>this._onSessionEnd(),{once:true});
    this.gl=this.canvas.getContext('webgl2',{xrCompatible:true,alpha:true,antialias:false,depth:false,stencil:false,preserveDrawingBuffer:false,desynchronized:true});if(!this.gl)throw new Error('WebGL2 non disponibile');await this.gl.makeXRCompatible?.();const baseLayer=new XRWebGLLayer(this.xrSession,this.gl,{alpha:true,antialias:false,depth:false,stencil:false,framebufferScaleFactor:.72});this.xrSession.updateRenderState({baseLayer,depthNear:.08,depthFar:12});this.binding=new XRWebGLBinding(this.xrSession,this.gl);try{this.depthMode=this.xrSession.depthUsage||'none';this.depthDataFormat=this.xrSession.depthDataFormat||null;}catch{this.depthMode='none';this.depthDataFormat=null;}this.cameraReader=new RawCameraReader(this.gl,this.binding,{targetWidth:this.profile.cameraWidth,diagnostics:this.diag});this.refSpace=await this.xrSession.requestReferenceSpace('local-floor');
    try{this.viewerSpace=await this.xrSession.requestReferenceSpace('viewer');this.hitTestSource=await this.xrSession.requestHitTestSource({space:this.viewerSpace});}catch(e){await this.diag.error('hit-test-unavailable',e);}
    await this.repo.patchSession(this.sessionId,{status:'capturing',xr:{startedAt:Date.now(),enabledFeatures:Array.from(this.xrSession.enabledFeatures||[]),depthUsage:this.depthMode,depthDataFormat:this.depthDataFormat,environmentBlendMode:this.xrSession.environmentBlendMode||null}});await this.diag.transition('XR_CAPTURING',{enabledFeatures:Array.from(this.xrSession.enabledFeatures||[])});this.xrSession.requestAnimationFrame((t,f)=>this._onXRFrame(t,f));return this;
  }
  _trackTask(promise,label='task'){const p=Promise.resolve(promise).catch(e=>this.diag.error(`${label}-failed`,e)).finally(()=>this.activeTasks.delete(p));this.activeTasks.add(p);return p;}
  requestPhoto(reason='user'){this.forcePhoto=true;this.photoReason=reason;}
  requestMarkpoint({pointId=null}={}){this.markpointRequest={pointId};this.forcePhoto=true;this.photoReason='markpoint';}
  getReticleCandidate(){if(!this.reticle?.position)return null;return {position:Array.from(this.reticle.position),normal:Array.from(this.reticle.normal||[0,1,0]),depthSamples:Number.isFinite(this.reticle.depthM)?[this.reticle.depthM]:[],confidence:this.reticle.confidence??.45,referenceCameraPosition:Array.from(this.reticle.referenceCameraPosition||this.motion.last?.pos||[0,0,0])};}
  setMarkpoints(points){this.overlay.setMarkpoints(points);}
  async requestSafeExit(reason='user'){
    if(this.closing||this.ended)return this._endPromise;this.closing=true;this._endPromise=new Promise(resolve=>this._resolveEnd=resolve);await this.diag.transition('XR_EXIT_REQUESTED',{reason,pendingWrites:this.repo.pendingCount()});this.chirps?.stop();
    // Flush only the small worklet tail. Existing PCM/JPEG/depth chunks are
    // already committed, so this path cannot create a full-session copy.
    if(this.activeTasks.size){const before=this.activeTasks.size;await Promise.race([Promise.allSettled([...this.activeTasks]),new Promise(r=>setTimeout(r,420))]);if(this.activeTasks.size)await this.diag.log('capture-tasks-left-running',{before,remaining:this.activeTasks.size},'warn');}
    try{await Promise.race([this.audio?.flush?.(),new Promise(r=>setTimeout(r,180))]);}catch(e){await this.diag.error('pre-exit-audio-flush-failed',e);}
    try{await Promise.all([this._flushPoseChunk(),this._flushHitChunk()]);}catch(e){await this.diag.error('pre-exit-small-record-flush-failed',e);}
    try{await this.repo.patchSession(this.sessionId,{status:'xr-ending',lastExitReason:reason});}catch(e){await this.diag.error('pre-exit-session-patch-failed',e);}
    try{
      await this.xrSession?.end();
      // A few Android WebXR stacks resolve end() before dispatching `end` and
      // occasionally never dispatch it after a renderer interruption. Never
      // leave the user on an inert capture HUD in that case.
      if(!this.ended){const ended=await Promise.race([this._endPromise.then(()=>true),new Promise(resolve=>setTimeout(()=>resolve(false),1200))]);if(!ended&&!this.ended){await this.diag.log('xr-end-event-timeout',{timeoutMs:1200},'warn');await this._onSessionEnd();}}
    }catch(e){await this.diag.error('xr-end-call-failed',e);await this._onSessionEnd();}return this._endPromise;
  }
  _onXRFrame(time,frame){
    if(this.ended)return;const session=frame.session;if(!this.closing)session.requestAnimationFrame((t,f)=>this._onXRFrame(t,f));try{const pose=frame.getViewerPose(this.refSpace);if(!pose?.views?.length)return;const view=pose.views[0];this._prepareXRFramebuffer(view);const matrix=finiteArray(view.transform.matrix),viewMatrix=finiteArray(view.transform.inverse.matrix),projection=finiteArray(view.projectionMatrix),motion=this.motion.update(matrix,view.transform.orientation,time),cameraPosition=motion.position;this.latestFrameContext={time,frame,view,pose,matrix,viewMatrix,projection,cameraPosition,motion};
      this._recordPose(time,view,motion);if(!this.closing&&time-this.lastPlaneSample>900)this._samplePlanes(frame,time,motion);if(!this.closing&&time-this.lastDepthSample>230)this._sampleDepth(frame,view,time,motion);if(!this.closing)this._sampleHitTest(frame,time,motion);
      if(!this.closing&&time-this.lastSnapshot>720){this.lastSnapshot=time;this.mapWorker?.postMessage({type:'snapshot',requestId:++this._snapshotRequest,cameraPosition,maxCells:2600,radius:9});}
      this.overlay.setReticle(this.reticle);this.overlay.setMarkpoints((this.markpoints?.points||[]).filter(point=>point.segmentId===this.segmentId));const guidance=this.overlay.render({viewMatrix,projectionMatrix:projection,cameraPosition});if(guidance)this.cb.onGuidance?.(guidance);this.cb.onMotion?.(motion);
      if(!this.closing&&this._shouldTakePhoto(time,guidance))this._trackTask(this._capturePhotoInFrame(view,time,motion,guidance),'photo-capture');
      if(!this.closing)this.chirps?.maybeSchedule({pose:this._compactPose(view,time),linearSpeed:motion.linearSpeed,angularSpeed:motion.angularSpeed,quality:motion.stability}).catch(e=>this.diag.error('chirp-schedule-failed',e));
      this.cb.onTelemetry?.({points:this.gridStats.totalPoints||0,planeCells:this.gridStats.planeCells||0,planes:this.planeCount||0,depthBatches:this.sessionRecord.counts.depthBatches||0,depthState:this.depthReadDisabled?'fallback-plane':this.depthMode==='cpu-optimized'?'active':'unavailable',frames:this.frameSeq,chirps:this.chirps?.sequence||0,pendingWrites:this.repo.pendingCount(),coverage:this.coverage});
    }catch(error){this.diag.error('xr-frame-error',error);}
  }
  _prepareXRFramebuffer(view){
    // Immersive AR relies on transparent pixels in the XR projection layer to
    // reveal the device passthrough. Some runtimes leave a freshly-created
    // framebuffer opaque/black until the page explicitly clears it. Always
    // initialize the current eye viewport with alpha=0 before drawing any XR
    // content; the DOM overlay remains separate and is composited by WebXR.
    const gl=this.gl,layer=this.xrSession?.renderState?.baseLayer;if(!gl||!layer)return;
    try{
      gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);
      const vp=layer.getViewport(view);if(vp)gl.viewport(vp.x,vp.y,vp.width,vp.height);
      gl.disable(gl.SCISSOR_TEST);gl.colorMask(true,true,true,true);
      gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);
    }catch(error){if(!this._xrFramebufferErrorLogged){this._xrFramebufferErrorLogged=true;this.diag.error('xr-framebuffer-prepare-failed',error);}}
  }
  _recordPose(time,view,motion){if(time-this.lastPoseWrite<90)return;this.lastPoseWrite=time;const rec=this._compactPose(view,time,motion);this.poseChunk.push(rec);if(this.poseChunk.length>=20)this._flushPoseChunk().catch(e=>this.diag.error('pose-write-failed',e));}
  _compactPose(view,time,motion=null){return {seq:this.poseChunk.length,segmentId:this.segmentId,timeXR:time,timeEpoch:Date.now(),position:cameraPositionFromMatrix(view.transform.matrix),orientation:{x:view.transform.orientation.x,y:view.transform.orientation.y,z:view.transform.orientation.z,w:view.transform.orientation.w},matrix:finiteArray(view.transform.matrix),projectionMatrix:finiteArray(view.projectionMatrix),linearSpeed:motion?.linearSpeed??this.motion.linearSpeed,angularSpeed:motion?.angularSpeed??this.motion.angularSpeed};}
  async _flushPoseChunk(){if(!this.poseChunk.length)return;const chunk=this.poseChunk.splice(0);const key=`${this.sessionId}/poses/${String(chunk[0].seq??Date.now()).padStart(8,'0')}-${Date.now()}`;await this.repo.enqueueRecord(this.sessionId,'pose-chunk',{poses:chunk},{key});this.sessionRecord.counts.poses+=chunk.length;}
  async _flushHitChunk(){if(!this.hitChunk.length)return;const chunk=this.hitChunk.splice(0);await this.repo.enqueueRecord(this.sessionId,'hit-test-chunk',{segmentId:this.segmentId,hits:chunk},{key:`${this.sessionId}/hit-tests/${Date.now()}`});}
  _sampleDepth(frame,view,time,motion){
    this.lastDepthSample=time;if(this.depthReadDisabled)return;
    // Depth Sensing has two different access APIs. XRFrame.getDepthInformation
    // is valid only for cpu-optimized sessions; XRWebGLBinding.getDepthInformation
    // is valid only for gpu-optimized sessions. V20.2.0 always called the latter
    // and then expected CPU methods, which produced InvalidStateError on phones
    // that negotiated GPU depth. We only build CPU surfels when true CPU depth
    // is available. GPU depth remains a valid capability but is not synchronously
    // read back on the capture thread; hit-test + RGB/Deep keep acquisition alive.
    let info=null;
    try{
      if(this.depthMode==='cpu-optimized'&&typeof frame.getDepthInformation==='function')info=frame.getDepthInformation(view);
      else if(this.depthMode==='gpu-optimized'){
        if(!this._depthModeLogged){this._depthModeLogged=true;this.diag.log('xr-depth-gpu-fallback',{depthUsage:this.depthMode,dataFormat:this.depthDataFormat,action:'skip-gpu-readback-use-hit-test-and-deep'},'warn');}
        return;
      }else return;
    }catch(error){
      // A depth failure must never abort the XR frame loop. Disable only this
      // optional source after the first contract/runtime error and continue AR.
      this.depthReadDisabled=true;this.diag.error('xr-depth-read-disabled',error,{depthUsage:this.depthMode,dataFormat:this.depthDataFormat});return;
    }
    if(!info?.getDepthInMeters)return;
    // Some Android runtimes advertise CPU depth but throw RangeError around a
    // cropped buffer edge. Isolate this optional source so it cannot take down
    // every XR frame or silently leave the user with an empty metric map.
    const points=sampleCPUDepth(info,view,this.profile.depthStride,this.profile.maxPointBatch,motion.position),depthStats=points.depthStats||{};
    if(!points.length){
      if(depthStats.readErrors){this.depthReadDisabled=true;this.depthFailure=depthStats;this.diag.log('xr-depth-sampling-disabled',{depthUsage:this.depthMode,depthDataFormat:this.depthDataFormat,...depthStats,action:'continue-with-plane-hit-test-mesh'},'warn');}
      return;
    }
    if(depthStats.readErrors&&!this._depthEdgeWarningLogged){this._depthEdgeWarningLogged=true;this.diag.log('xr-depth-edge-samples-skipped',depthStats,'warn');}
    const origin=motion.position,seq=this.depthSeq++,frameId=null,meta={sequence:seq,timeXR:time,timeEpoch:Date.now(),origin,viewKey:quantizedViewKey(origin),count:points.length/10,source:'xr-depth-cpu',projectionMatrix:finiteArray(view.projectionMatrix),cameraMatrix:finiteArray(view.transform.matrix),depthWidth:info.width,depthHeight:info.height,rawValueToMeters:info.rawValueToMeters??null,depthUsage:this.depthMode,depthDataFormat:this.depthDataFormat,depthStats};const compact=encodePointBatch(points,origin);this.repo.enqueueBlob(this.sessionId,'depth-points',new Blob([compact],{type:'application/x-roomscan-points'}),meta,`${this.sessionId}/depth/points-${String(seq).padStart(7,'0')}.rspt`).catch(e=>this.diag.error('depth-batch-write-failed',e,{seq}));this.repo.enqueueRecord(this.sessionId,'depth-meta',meta,{key:`${this.sessionId}/depth-meta/${String(seq).padStart(7,'0')}`}).catch(e=>this.diag.error('depth-meta-write-failed',e,{seq}));this.lastDepthCandidate=extractCenterDepthCandidate(points,motion.position);if(!this.reticle&&this.lastDepthCandidate)this.reticle={...this.lastDepthCandidate,referenceCameraPosition:motion.position};this.mapWorker?.postMessage({type:'depthBatch',buffer:points.buffer,viewOrigin:origin,viewKey:meta.viewKey,source:'xr-depth',time:Date.now(),frameId},[points.buffer]);this.sessionRecord.counts.depthBatches++;
  }
  _sampleHitTest(frame,time,motion){if(!this.hitTestSource||time-(this.lastHitTime||0)<420)return;this.lastHitTime=time;try{const hit=frame.getHitTestResults(this.hitTestSource)?.[0];const pose=hit?.getPose(this.refSpace);if(!pose)return;const m=pose.transform.matrix,p=[m[12],m[13],m[14]],n=norm3([m[4],m[5],m[6]]),toCam=sub3(motion.position,p),nn=(n[0]*toCam[0]+n[1]*toCam[1]+n[2]*toCam[2])<0?scale3(n,-1):n;this.reticle={position:p,normal:nn,depthM:dist3(p,motion.position),confidence:.72,referenceCameraPosition:motion.position};const a=new Float32Array([p[0],p[1],p[2],nn[0],nn[1],nn[2],145,145,145,.36]);this.hitChunk.push({segmentId:this.segmentId,timeXR:time,timeEpoch:Date.now(),position:p,normal:nn,cameraPosition:motion.position});if(this.hitChunk.length>=24)this._flushHitChunk().catch(e=>this.diag.error('hit-test-write-failed',e));this.mapWorker?.postMessage({type:'depthBatch',buffer:a.buffer,viewOrigin:motion.position,viewKey:quantizedViewKey(motion.position),source:'hit-test',time:Date.now()},[a.buffer]);}catch(e){if(!this._hitErrorLogged){this._hitErrorLogged=true;this.diag.error('hit-test-frame-failed',e);}}
  }
  _samplePlanes(frame,time,motion){
    this.lastPlaneSample=time;const detected=frame.detectedPlanes;if(!detected?.size)return;const planes=[];
    try{for(const plane of detected){const pose=frame.getPose(plane.planeSpace,this.refSpace),vertices=Array.from(plane.polygon||[]);if(!pose||vertices.length<3)continue;const matrix=pose.transform.matrix,polygon=vertices.map(p=>transformPoint4(matrix,[p.x,p.y,p.z]));if(!polygon.every(p=>p.every(Number.isFinite)))continue;let normal=norm3(transformDirection4(matrix,[0,1,0]));const center=polygon.reduce((sum,p)=>add3(sum,p),[0,0,0]).map(v=>v/polygon.length);if(dot(normal,sub3(motion.position,center))<0)normal=scale3(normal,-1);const label=plane.semanticLabel||plane.orientation||'surface',id=`${label}:${quantizedViewKey(center,.45)}:${normal.map(v=>Math.round(v*4)).join(',')}`;planes.push({id,label,polygon,normal,center,lastChangedTime:plane.lastChangedTime??null});}
      this.planeCount=planes.length;if(planes.length)this.mapWorker?.postMessage({type:'planeEstimates',planes,time:Date.now()});
    }catch(error){if(!this._planeErrorLogged){this._planeErrorLogged=true;this.diag.error('plane-estimation-unavailable',error);}}
  }
  _shouldTakePhoto(time,guidance){
    if(this.repo.pendingCount()>=this.profile.maxPendingWrites)return false;
    if(this.forcePhoto)return time-this.lastPhoto>480;
    const target=guidance&&this.gridTiles.find(t=>t.id===guidance.tileId);if(!target?.needDeep||this.motion.stability<.35)return false;
    if(this.autoPhotoCount>=this.profile.maxAutoPhotos){if(!this._autoPhotoLimitLogged){this._autoPhotoLimitLogged=true;this.diag.log('auto-photo-budget-reached',{max:this.profile.maxAutoPhotos},'info');}return false;}
    const history=this.autoPhotoByTarget.get(target.id),minInterval=Math.max(this.profile.minPhotoIntervalMs,this.profile.autoPhotoMinIntervalMs||0),baseline=history?dist3(this.motion.last?.pos||[0,0,0],history.position):Infinity;
    if(time-this.lastPhoto<minInterval||history&&(history.count>=this.profile.maxAutoPhotosPerTarget||time-history.time<minInterval&&baseline<.38))return false;
    this.plannedAutoTargetId=target.id;return true;
  }
  async _capturePhotoInFrame(view,time,motion,guidance){
    this.lastPhoto=time;const reason=this.photoReason||((guidance&&'grid-deep')||'auto'),autoTargetId=reason==='grid-deep'?this.plannedAutoTargetId:null,markpointRequest=this.markpointRequest;this.forcePhoto=false;this.photoReason=null;this.plannedAutoTargetId=null;const capture=await this.cameraReader.read(view);if(!capture){await this.diag.log('photo-skipped',{reason,cause:'raw-camera-unavailable'},'warn');return;}const quality=imageQuality(capture.rgba,capture.width,capture.height);if(reason==='grid-deep'&&(quality.sharpness<.12||quality.exposureScore<.28)){await this.diag.log('photo-discarded-low-utility',{reason,quality,autoTargetId},'info');return;}const frameId=uid('frame'),seq=this.frameSeq++;const blob=await rgbaToJpegBlob(capture.rgba,capture.width,capture.height,.78);const linkedTiles=this._visibleTileLinks(view.transform.inverse.matrix,view.projectionMatrix,capture.width,capture.height);const meta={id:frameId,sequence:seq,sessionId:this.sessionId,segmentId:this.segmentId,timeXR:time,timeEpoch:Date.now(),reason,pose:this._compactPose(view,time,motion),image:{width:capture.width,height:capture.height,cameraWidth:capture.cameraWidth,cameraHeight:capture.cameraHeight,mime:'image/jpeg',size:blob.size},quality,linkedTiles,metricAnchors:this.reticle?[this.reticle]:this.lastDepthCandidate?[this.lastDepthCandidate]:[],markpointCandidate:false};
    await this.repo.enqueueBlob(this.sessionId,'frame-jpeg',blob,meta,`${this.sessionId}/frames/${String(seq).padStart(7,'0')}-${frameId}.jpg`);await this.repo.enqueueRecord(this.sessionId,'frame-meta',meta,{key:`${this.sessionId}/frame-meta/${String(seq).padStart(7,'0')}`});this.mapWorker?.postMessage({type:'photoEvidence',frameId,cameraPosition:motion.position,sharpness:quality.sharpness,exposure:quality.exposureScore,hits:linkedTiles.map(t=>({key:t.tileId,uv:t.uv}))});this.sessionRecord.counts.frames++;
    if(reason==='grid-deep'&&autoTargetId){const old=this.autoPhotoByTarget.get(autoTargetId);this.autoPhotoByTarget.set(autoTargetId,{time,position:motion.position,count:(old?.count||0)+1});this.autoPhotoCount++;}
    if(reason==='markpoint'||markpointRequest){this.markpointRequest=null;const candidate={...buildMarkpointCandidate(capture,this.reticle||this.lastDepthCandidate,meta),targetMarkpointId:markpointRequest?.pointId||null};Promise.resolve(this.cb.onMarkpointCandidate?.(candidate)).catch(error=>this.diag.error('markpoint-photo-candidate-failed',error));}
    // Re-observe accepted markpoints in ordinary keyframes. This creates real
    // multi-view evidence instead of trusting a single user tap.
    if(this.markpoints?.points?.length){const observations=[];for(const point of this.markpoints.points){if(point.segmentId!==this.segmentId)continue;const screen=projectWorldPoint(point.position,view.transform.inverse.matrix,view.projectionMatrix,capture.width,capture.height);if(!screen?.inside||screen.x<12||screen.y<12||screen.x>capture.width-12||screen.y>capture.height-12)continue;observations.push({markpointId:point.id,descriptor:computePatchDescriptor(capture.rgba,capture.width,capture.height,screen.x,screen.y,10),referenceCameraPosition:point.referenceCameraPosition});}if(observations.length)this.markpoints.observeFrame({frameId,cameraPosition:motion.position,projectedPatches:observations}).then(updates=>{if(updates.some(p=>p.status==='valid'))this.cb.onMarkpointValidated?.(updates);}).catch(e=>this.diag.error('markpoint-observation-failed',e));}
    this.cb.onPhoto?.(meta);await this.diag.log('frame-saved',{frameId,seq,size:blob.size,reason,quality,linkedTiles:linkedTiles.length});
    // Release the large RGBA array at the end of this task; only Blob and small
    // descriptors survive. This is essential on memory-constrained phones.
  }
  _visibleTileLinks(viewMatrix,projection,width,height){const links=[];for(const t of this.gridTiles){const p=projectWorldPoint(t.center,viewMatrix,projection,width,height);if(p?.inside)links.push({tileId:t.id,uv:[p.x/width,p.y/height],status:t.status,needDeep:t.needDeep});if(links.length>=180)break;}return links;}
  _onMapMessage(m){if(m.type==='snapshot'){if(m.requestId&&m.requestId<this._lastSnapshotAccepted)return;this._lastSnapshotAccepted=m.requestId||0;this.gridTiles=m.tiles||[];this.gridStats=m.stats||{};this.coverage=summarizeCoverage(this.gridTiles);this.overlay.setTiles(this.gridTiles);this.cb.onCoverage?.(this.coverage,this.gridTiles);const now=performance.now();if(now-this.lastGridPersist>this.profile.gridSnapshotIntervalMs){this.lastGridPersist=now;const compact={time:Date.now(),segmentId:this.segmentId,stats:this.gridStats,coverage:this.coverage,tiles:this.gridTiles};this.repo.enqueueRecord(this.sessionId,'grid-snapshot',compact,{key:`${this.sessionId}/grid-snapshot/${Date.now()}`}).catch(e=>this.diag.error('grid-snapshot-write-failed',e));this.sessionRecord.counts.gridSnapshots++;}}else if(m.type==='stats'){this.gridStats=m;}else if(m.type==='error')this.diag.error('map-worker-message-error',new Error(m.message),{stack:m.stack});}
  async _onSessionEnd(){
    if(this.ended)return;this.ended=true;const reason=this.closing?'requested':'unexpected';await this.diag.transition('XR_ENDED',{reason,pendingWrites:this.repo.pendingCount()});
    // The order below is deliberately small and deterministic. No worker for
    // Deep, plane fitting, ZIP creation or model reconstruction is started.
    try{this.hitTestSource?.cancel?.();}catch{}this.hitTestSource=null;try{this.cameraReader?.dispose();}catch{}this.cameraReader=null;try{this.gl?.getExtension('WEBGL_lose_context')?.loseContext();}catch{}this.canvas.width=this.canvas.height=1;this.overlay.clear();try{this.mapWorker?.terminate();}catch{}this.mapWorker=null;
    try{await this.audio?.stop?.({timeoutMs:520});}catch(e){await this.diag.error('audio-stop-after-xr-failed',e);}const drain=await this.repo.drain(1700);try{await this.repo.patchSession(this.sessionId,{status:reason==='requested'?'captured':'interrupted',flags:{xrEnded:true},xr:{endedAt:Date.now(),endReason:reason},counts:this.sessionRecord.counts,writeDrain:drain});}catch(e){await this.diag.error('final-session-patch-failed',e);}
    await this.diag.memory('after-xr-release');await this.diag.transition('CAPTURE_SAVED',{drain});
    try{await this.cb.onEnded?.({reason,drain,sessionId:this.sessionId});}catch(error){await this.diag.error('capture-ended-ui-failed',error);}
    this._resolveEnd?.({reason,drain});
  }
}

export function sampleCPUDepth(info,view,stride,maxPoints,cameraPosition){
  const w=Math.floor(info.width||0),h=Math.floor(info.height||0),invProj=invert4(view.projectionMatrix);if(w<8||h<8||!invProj)return new Float32Array(0);const world=view.transform.matrix,depthToView=info.normDepthBufferFromNormView?.inverse?.matrix||null,records=[],stats={attempted:0,readErrors:0,invalid:0,accepted:0};const step=Math.max(4,Math.floor(stride)),margin=Math.max(step+3,8),offset=Math.max(2,Math.floor(step*.55));let sampled=0;
  const readDepth=(x,y)=>{x=Math.floor(x);y=Math.floor(y);if(x<margin||y<margin||x>=w-margin||y>=h-margin){stats.invalid++;return null;}stats.attempted++;try{const value=info.getDepthInMeters(x,y);if(!Number.isFinite(value)||value<.12||value>10){stats.invalid++;return null;}return value;}catch{stats.readErrors++;return null;}};
  const worldPoint=(x,y)=>{const depth=readDepth(x,y);if(depth==null)return null;let u=(x+.5)/w,v=(y+.5)/h;if(depthToView){const p=transformPoint4(depthToView,[u,v,0]);u=p[0];v=p[1];}const ndc=[u*2-1,1-v*2,1],far=transformPoint4(invProj,ndc),ray=norm3(far);if(ray[2]>=-.01)return null;const camera=scale3(ray,depth/(-ray[2]));return transformPoint4(world,camera);};
  for(let y=margin;y<h-margin-offset&&sampled<maxPoints;y+=step)for(let x=margin;x<w-margin-offset&&sampled<maxPoints;x+=step){const p=worldPoint(x,y),px=worldPoint(x+offset,y),py=worldPoint(x,y+offset);if(!p||!px||!py)continue;let n=norm3(cross3(sub3(px,p),sub3(py,p)));if(len3(n)<.5)continue;if(dot(n,sub3(cameraPosition,p))<0)n=scale3(n,-1);const depth=dist3(p,cameraPosition),confidence=clamp(1-depth/12,0.18,1);records.push(p[0],p[1],p[2],n[0],n[1],n[2],145,145,145,confidence);sampled++;stats.accepted++;}
  const out=new Float32Array(records);Object.defineProperty(out,'depthStats',{value:stats});return out;
}
function extractCenterDepthCandidate(points,camera){if(!points.length)return null;let best=null,bestAngle=Infinity;const forward=[0,0,-1];for(let i=0;i<points.length;i+=10){const p=[points[i],points[i+1],points[i+2]],dir=norm3(sub3(p,camera)),a=Math.acos(clamp(-dir[2],-1,1));if(a<bestAngle){bestAngle=a;best={position:p,normal:[points[i+3],points[i+4],points[i+5]],depthM:dist3(p,camera),confidence:points[i+9]};}}return best;}
function buildMarkpointCandidate(capture,depthCandidate,meta){const cx=Math.floor(capture.width/2),cy=Math.floor(capture.height/2),depthSamples=depthCandidate?[depthCandidate.depthM]:[];return {frameId:meta.id,position:depthCandidate?.position||meta.pose.position.map((v,i)=>v+(i===2?-1:0)),normal:depthCandidate?.normal||[0,0,1],depthSamples,rgba:capture.rgba,width:capture.width,height:capture.height,cx,cy,pose:meta.pose,referenceCameraPosition:depthCandidate?.referenceCameraPosition||meta.pose.position};}
function imageQuality(rgba,w,h){let sum=0,sum2=0,clip=0,edges=0,n=0;for(let y=2;y<h-2;y+=4)for(let x=2;x<w-2;x+=4){const i=(y*w+x)*4,l=(.2126*rgba[i]+.7152*rgba[i+1]+.0722*rgba[i+2])/255;sum+=l;sum2+=l*l;if(l<.03||l>.97)clip++;const ir=(y*w+x+2)*4,id=((y+2)*w+x)*4,lr=(.2126*rgba[ir]+.7152*rgba[ir+1]+.0722*rgba[ir+2])/255,ld=(.2126*rgba[id]+.7152*rgba[id+1]+.0722*rgba[id+2])/255;edges+=Math.abs(lr-l)+Math.abs(ld-l);n++;}const mean=sum/Math.max(1,n),std=Math.sqrt(Math.max(0,sum2/Math.max(1,n)-mean*mean));return {meanLuma:mean,contrast:std,clippedFraction:clip/Math.max(1,n),sharpness:clamp(edges/Math.max(1,n)/.18,0,1),exposureScore:clamp(1-Math.abs(mean-.5)*1.7-clip/Math.max(1,n)*2,0,1)};}
async function rgbaToJpegBlob(rgba,w,h,quality){const canvas=globalThis.OffscreenCanvas?new OffscreenCanvas(w,h):document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.putImageData(new ImageData(new Uint8ClampedArray(rgba.buffer,rgba.byteOffset,rgba.byteLength),w,h),0,0);if(canvas.convertToBlob)return canvas.convertToBlob({type:'image/jpeg',quality});return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('JPEG encoding fallito')),'image/jpeg',quality));}
function flipRows(src,w,h){const out=new Uint8Array(src.length),row=w*4;for(let y=0;y<h;y++)out.set(src.subarray((h-1-y)*row,(h-y)*row),y*row);return out;}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
