/**
 * Dependency-free diagnostic Gaussian renderer.
 * It renders 3-D Gaussian centers as depth-sorted screen splats and supports a
 * simple orbit/pan camera. This is intentionally lightweight for offline use.
 */
export class GaussianRenderer{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.items=[];this.yaw=0;this.pitch=0;this.distance=4;this.center=[0,0,0];this.splat=1;this._drag=null;this._bind();this.resize();}
  setData(items){this.items=normalize(items);this.fit();this.draw();}
  setSplatSize(v){this.splat=Number(v)||1;this.draw();}
  fit(){if(!this.items.length){this.center=[0,0,0];this.distance=4;return}const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const g of this.items)for(let k=0;k<3;k++){min[k]=Math.min(min[k],g.p[k]);max[k]=Math.max(max[k],g.p[k]);}this.center=min.map((v,k)=>(v+max[k])/2);this.distance=Math.max(1,Math.hypot(max[0]-min[0],max[1]-min[1],max[2]-min[2])*1.8);}
  resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);this.canvas.width=Math.max(1,Math.round(r.width*dpr));this.canvas.height=Math.max(1,Math.round(r.height*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);this.draw();}
  draw(){const r=this.canvas.getBoundingClientRect(),w=r.width,h=r.height,g=this.ctx;g.clearRect(0,0,w,h);g.fillStyle='#05080c';g.fillRect(0,0,w,h);const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),pts=[];for(const s of this.items){let x=s.p[0]-this.center[0],y=s.p[1]-this.center[1],z=s.p[2]-this.center[2];const x1=cy*x-sy*z,z1=sy*x+cy*z,y1=cp*y-sp*z1,z2=sp*y+cp*z1+this.distance;if(z2<=.05)continue;const f=Math.min(w,h)*.8,px=w/2+f*x1/z2,py=h/2-f*y1/z2,rad=Math.max(.6,Math.min(12,(s.r||.02)*f/z2*20*this.splat));pts.push({px,py,z:z2,rad,c:s.c,a:s.a});}pts.sort((a,b)=>b.z-a.z);for(const p of pts){g.globalAlpha=Math.max(.08,Math.min(1,p.a));g.fillStyle=`rgb(${p.c[0]},${p.c[1]},${p.c[2]})`;g.beginPath();g.arc(p.px,p.py,p.rad,0,Math.PI*2);g.fill();}g.globalAlpha=1;}
  _bind(){this.canvas.addEventListener('pointerdown',e=>{this._drag={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture?.(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!this._drag)return;this.yaw+=(e.clientX-this._drag.x)*.008;this.pitch=Math.max(-1.4,Math.min(1.4,this.pitch+(e.clientY-this._drag.y)*.008));this._drag={x:e.clientX,y:e.clientY};this.draw()});this.canvas.addEventListener('pointerup',()=>this._drag=null);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.distance=Math.max(.15,this.distance*Math.exp(e.deltaY*.001));this.draw()},{passive:false});addEventListener('resize',()=>this.resize());}
}
function normalize(items){if(!Array.isArray(items))return [];return items.map(g=>{const p=g.position||g.p||g.mean||g.xyz||[0,0,0],c=g.color||g.rgb||[180,210,240],scale=g.scale||g.scales||g.radius||.02,r=Array.isArray(scale)?Math.max(...scale.map(Number)):Number(scale);return {p:p.map(Number),c:c.map(v=>Math.max(0,Math.min(255,Number(v)||0))),r:Number.isFinite(r)?r:.02,a:Number(g.opacity??g.alpha??1)}}).filter(g=>g.p.every(Number.isFinite));}
